- docs/overview/architecture.md
fix docs/overview/architecture.md bug
> fix doc show bug

- src/backend/project/boot-project/build.gradle
> change project compile

- src/backend/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/Container.kt
> fix elements

- src/backend/artifactory/biz-artifactory-sample/src/main/kotlin/com/tencent/devops/artifactory/service/impl/EeArchiveAtomToLocalServiceImpl.kt
- src/backend/store/api-store/src/main/kotlin/com/tencent/devops/store/api/atom/ServiceMarketAtomArchiveResource.kt
- src/backend/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/atom/AtomEnvRequest.kt
- src/backend/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/atom/GetAtomConfigResult.kt
- src/backend/store/biz-store-sample/src/main/kotlin/com/tencent/devops/store/service/atom/impl/EeMarketAtomServiceImpl.kt
- src/backend/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/atom/ServiceMarketAtomArchiveResourceImpl.kt
- src/backend/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/MarketAtomArchiveService.kt
- src/backend/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/MarketAtomCommonService.kt
- src/backend/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomArchiveServiceImpl.kt
- src/backend/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomCommonServiceImpl.kt
- src/backend/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomServiceImpl.kt
> refactor the store structure

- src/backend/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildDao.kt
- src/backend/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/store/api-store/src/main/kotlin/com/tencent/devops/store/api/atom/ServiceMarketAtomResource.kt
- src/backend/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/atom/ServiceMarketAtomArchiveResourceImpl.kt
- src/backend/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/atom/ServiceMarketAtomResourceImpl.kt
- src/backend/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/atom/UserAtomResourceImpl.kt
- src/backend/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/AtomService.kt
- src/backend/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomServiceImpl.kt
- src/backend/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomArchiveServiceImpl.kt
- src/backend/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomServiceImpl.kt
- src/backend/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/container/impl/ContainerAppServiceImpl.kt
执行历史页面分支名、别名过滤需要忽略大小写 resolve #18
> 执行历史页面分支名、别名过滤需要忽略大小写 resolve #18

- src/backend/worker/worker-agent/src/main/kotlin/com/tencent/devops/agent/utils/KillBuildProcessTree.kt
部分第三方构建机上出现worker-agent.jar进程延迟退出的问题  fixed #16
> 部分第三方构建机上出现worker-agent.jar进程延迟退出的问题  fixed #16

- src/backend/build.gradle
- src/backend/common/common-archive/src/main/kotlin/com/tencent/devops/common/archive/ArchiveElementSubTypeFetcher.kt
- src/backend/common/common-archive/src/main/resources/META-INF/services/com.tencent.devops.common.pipeline.ElementSubTypeFetcher
- src/backend/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/AutoConfiguration.kt
- src/backend/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/ElementSubTypeFetcher.kt
- src/backend/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/ElementSubTypeRegisterLoader.kt
- src/backend/common/common-pipeline/src/main/resources/META-INF/spring.factories
- src/backend/settings.gradle
- src/backend/worker/worker-agent/src/main/kotlin/com/tencent/devops/agent/runner/WorkRunner.kt
- src/backend/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/AbstractBuildResourceApi.kt
- src/backend/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/TaskFactory.kt
>  1.采用SPI机制识别Element的扩展子类并注册到JsonSubType中。

- src/backend/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineInfoDao.kt
- src/backend/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/listener/run/monitor/PipelineBuildHeartbeatListener.kt
- src/backend/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
> 支持无projectId 获取流水线

- src/frontend/devops-atomstore/src/views/atom_list.vue
- src/frontend/devops-codelib/src/views/Index.vue
> 新增gitlab时赋值authType

- src/pipeline-plugin/bksdk/src/main/java/com/tencent/bk/devops/atom/api/Header.java
- src/pipeline-plugin/bksdk/src/main/java/com/tencent/bk/devops/atom/api/SdkEnv.java
> 1.remove deprecated fields

- src/backend/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/MarketAtomDao.kt
- src/backend/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomServiceImpl.kt
> 查询插件信息bug修复

- support-files/templates/#etc#bkci#application-assembly.yml
- support-files/templates/assembly#assembly.sh
[Assembly]增加单进程配置文件和启动脚本 resloves #68
> [Assembly]增加单进程配置文件和启动脚本 resloves #68

- scripts/bkenv.properties
- src/agent/src/pkg/collector/collector.go
- src/agent/src/pkg/config/config.go
- support-files/agent-package/config/.agent.properties
> 增加agent中构建机状态采集的开关配置

- src/backend/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/client/InfluxdbClient.kt
- src/backend/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/resources/thirdPartyAgent/OpThirdPartyAgentResourceImpl.kt
> [BE] 构建机详情采集未开启情况下返回的默认值 

- src/backend/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdPartyAgent/DownloadAgentInstallService.kt
> [BE] 增加agent中构建机状态采集的开关配置

- src/backend/artifactory/api-artifactory-store/src/main/kotlin/com/tencent/devops/artifactory/constant/ArtifactoryConstants.kt
- src/backend/artifactory/biz-artifactory-store/src/main/kotlin/com/tencent/devops/artifactory/service/impl/ArchiveAtomToLocalServiceImpl.kt
- src/backend/environment/api-environment-blueking/build.gradle
- src/backend/environment/api-environment-blueking/src/main/kotlin/com/tencent/devops/environment/api/ServiceNodeBluekingResource.kt
- src/backend/environment/biz-environment-blueking/src/main/kotlin/com/tencent/devops/environment/resources/ServiceNodeBlueKingResourceImpl.kt
- src/backend/environment/biz-environment-blueking/src/main/kotlin/com/tencent/devops/environment/service/NodeBluekingService.kt
- src/backend/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/dao/NodeDao.kt
- src/backend/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/NodeService.kt
- src/backend/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdPartyAgent/ThirdPartyAgentService.kt
- src/backend/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdPartyAgent/UpgradeService.kt
- src/backend/settings.gradle
- src/backend/worker/worker-agent/src/main/kotlin/com/tencent/devops/agent/AgentVersion.kt
- src/backend/worker/worker-agent/src/main/kotlin/com/tencent/devops/agent/Application.kt
- src/backend/worker/worker-agent/src/main/kotlin/com/tencent/devops/agent/runner/WorkRunner.kt
- src/backend/worker/worker-api-sdk/src/main/kotlin/com/tencent/devops/worker/common/api/atom/AtomArchiveResourceApi.kt
- src/backend/worker/worker-common/build.gradle
- src/backend/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Runner.kt
- src/backend/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/WorkspaceInterface.kt
- src/backend/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/AbstractBuildResourceApi.kt
- src/backend/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/archive/ArchiveSDKApi.kt
- src/backend/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/env/AgentEnv.kt
- src/backend/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/env/DockerEnv.kt
- src/backend/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/heartbeat/Heartbeat.kt
- src/backend/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
- src/backend/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/Constants.kt
- src/backend/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/ExceptionUtils.kt
- src/backend/worker/worker-plugin-scm/src/main/kotlin/com/tencent/devops/plugin/worker/task/scm/SCM.kt
- src/backend/worker/worker-plugin-scm/src/main/kotlin/com/tencent/devops/plugin/worker/task/scm/git/GitUpdateTask.kt
[BE] [Agent] MarketAtomTask对有报告类的输出作报告归档 fix #96 
[BE] [环境管理] 修改环境管理中的节点别名，更新时间没有变化 fix #97
> [BE] [环境管理] 问题修改

- src/frontend/devops-nav/src/index.html
- src/frontend/devops-pipeline/index.html
- src/frontend/devops-pipeline/src/components/atomFormField/VuexInput/index.vue
- src/frontend/devops-pipeline/src/components/atomFormField/VuexTextarea/index.vue
- src/frontend/devops-pipeline/src/components/pipelineSetting/BaseInfo.vue
1、去掉qq.com
2、去掉徽章功能
3、fixfix插件框异常标红bug
> 去掉qq.com的引用、fix插件框异常标红bug

- src/pipeline-plugin/bksdk/src/main/java/com/tencent/bk/devops/atom/api/SdkEnv.java
- src/pipeline-plugin/bksdk/src/main/java/com/tencent/bk/devops/atom/utils/http/SdkUtils.java
- src/pipeline-plugin/bksdk/src/test/java/com/tencent/bk/devops/atom/utils/http/SdkUtilsTest.java
> [BE][PipelinePlugin] 插件SdkEnv.genUrl适配带http开头的gateway

- src/pipeline-plugin/demo/src/main/java/com/tencent/bk/devops/atom/task/DemoAtom.java
- src/pipeline-plugin/demo/task.json
> [BE][PipelinePlugin] 流水线插件启动的java变量替换为$bk_java_path

- src/backend/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/CodeGitWebHookTriggerElement.kt
- src/backend/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/CodeGithubWebHookTriggerElement.kt
- src/backend/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/CodeGitlabWebHookTriggerElement.kt
- src/backend/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/CodeSVNWebHookTriggerElement.kt
- src/backend/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildDao.kt
- src/backend/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
> [BE] [Pipeline] 74837817 webhook触发的构建在运行中在执行历史页面展示的是远程触发

- src/backend/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/task/SubPipelineCallAtom.kt
> 调用子流水线插件支持父流水线的停止指令

- src/backend/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/client/InfluxdbClient.kt
> fix #151 fluxdb数据异常导致构建机详情接口异常

- src/backend/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/AutoConfiguration.kt
- src/backend/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/VMBuildContainer.kt
- src/backend/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/BuildContainerType.kt
- src/backend/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/type/BuildType.kt
- src/backend/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/type/DispatchRouteKeySuffix.kt
- src/backend/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/type/DispatchType.kt
- src/backend/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/type/agent/AgentType.kt
- src/backend/process/api-process/src/main/kotlin/com/tencent/devops/process/api/op/OpPipelineContainerMonitorResource.kt
- src/backend/process/api-process/src/main/kotlin/com/tencent/devops/process/api/template/UserPTemplateResource.kt
- src/backend/process/api-process/src/main/kotlin/com/tencent/devops/process/api/template/UserTemplateInstanceResource.kt
- src/backend/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/PipelineContainerMonitor.kt
- src/backend/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/PipelineCopy.kt
- src/backend/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/PipelineModelTask.kt
- src/backend/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/pipeline/PipelineResource.kt
- src/backend/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/template/TemplateCompareModel.kt
- src/backend/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/template/TemplateCompareModelResult.kt
- src/backend/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/template/TemplateId.kt
- src/backend/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/template/TemplateInstanceCreate.kt
- src/backend/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/template/TemplateInstanceParams.kt
- src/backend/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/template/TemplateInstanceUpdate.kt
- src/backend/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/template/TemplateInstances.kt
- src/backend/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/template/TemplateModelDetail.kt
- src/backend/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/template/TemplateOperationMessage.kt
- src/backend/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/template/TemplatePipeline.kt
- src/backend/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/template/TemplateType.kt
- src/backend/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/template/TemplateVersion.kt
- src/backend/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/Constants.kt
> fix some code

- src/backend/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/enums/SvnDepth.kt
> fix svnDepth typo

- README.md
Update url to allow everyone to access
> Update docker image link to allow anonymous access

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceBuildPermissionResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceBuildPermissionResourceImpl.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/AppRepositoryResource.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/AppRepositoryResourceImpl.kt
> --task=6924783 拉取代码记录App接口

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/init/AtomConfig.kt
人工审核通知需要加上通知功能， 但功能需要对接通知模块才可使用
fix #216
> --bug=76235681 插件-人工审核没有通知提醒

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/init/AtomConfig.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/service/OPPServiceVO.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/service/ServiceCreateInfo.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/service/ServiceVO.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/ServiceDao.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsUserProjectServiceServiceImpl.kt
- support-files/sql/0002_ci_project_20190806-0431_mysql.sql
- support-files/sql/0004_ci_project-update-table_20191111-1336_mysql.sql
--story=856658901 iframe类嵌入的服务支持灰度
close #218
> --story=856658901 iframe类嵌入的服务支持灰度

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/OkhttpUtils.kt
- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/dispatch/AbstractBuildResourceApi.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/AbstractBuildResourceApi.kt
- src/pipeline-plugin/bksdk/src/main/java/com/tencent/bk/devops/atom/utils/http/OkHttpUtils.java
- support-files/agent-package/script/docker_init.sh
- support-files/agent-package/script/init.sh
改动范围：
1. pipeline plugin java sdk
2. 通用http组件
3. docker构建机启动脚本
close #220
> --story=856668315 涉及到HTTP请求的支持https

- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/ProjectVO.kt
- src/backend/ci/core/project/api-project/src/test/kotlin/com/tencent/devops/project/pojo/ProjectVOTest.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/util/ProjectUtils.kt
> 兼容旧有project项目下划线项目逻辑

- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/ServiceRepositoryResource.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/dao/RepositoryDao.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/ServiceRepositoryResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepositoryService.kt
> --story=856670035 增加代码库匹配查询接口

- support-files/sql/0002_ci_store_20190806-0432_mysql.sql
- support-files/sql/0004_ci_store-update-table_20191111-1356_mysql.sql
> 研发商店镜像市场sql变更补充

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/exception/ErrorCodeException.kt
- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/script/BatScriptUtil.kt
- src/backend/ci/core/common/common-archive/src/main/kotlin/com/tencent/devops/common/archive/pojo/CheckSums.kt~HEAD
- src/backend/ci/core/common/common-archive/src/main/kotlin/com/tencent/devops/common/archive/pojo/CheckSums.kt~story_856580249
- src/backend/ci/core/common/common-archive/src/main/kotlin/com/tencent/devops/common/archive/pojo/JFrogFileInfo.kt~HEAD
- src/backend/ci/core/common/common-archive/src/main/kotlin/com/tencent/devops/common/archive/pojo/JFrogFileInfo.kt~story_856580249
- src/backend/ci/core/common/common-client/src/main/kotlin/com/tencent/devops/common/client/Client.kt
- src/backend/ci/core/common/common-redis/src/main/kotlin/com/tencent/devops/common/redis/RedisKeys.kt
- src/backend/ci/core/common/common-redis/src/main/kotlin/com/tencent/devops/common/redis/RedisOperation.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/svn/api/SVNWebHook.kt
- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/gray/RepoGray.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/template/UserTemplateInstanceResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/mq/PipelineBuildContainerEvent.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/template/TemplateInstancePage.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/template/UserTemplateInstanceResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/BuildMonitorControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/ContainerControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/template/TemplatePipelineDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/listener/run/monitor/PipelineBuildHeartbeatListener.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineVMBuildService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/template/TemplateService.kt
- src/backend/ci/core/process/plugin-trigger/src/main/kotlin/com/tencent/devops/process/plugin/trigger/service/PipelineTimerService.kt
- src/backend/ci/core/store/api-store-image/src/main/kotlin/com/tencent/devops/store/api/image/service/ServiceStoreImageResource.kt~HEAD
- src/backend/ci/core/store/api-store-image/src/main/kotlin/com/tencent/devops/store/api/image/service/ServiceStoreImageResource.kt~story_856580249
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/common/enums/BusinessFeatureEnum.kt~HEAD
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/common/enums/BusinessFeatureEnum.kt~story_856580249
- src/backend/ci/core/store/biz-store-sample/src/main/kotlin/com/tencent/devops/store/service/common/impl/SampleStoreLogoServiceImpl.kt~HEAD
- src/backend/ci/core/store/biz-store-sample/src/main/kotlin/com/tencent/devops/store/service/common/impl/SampleStoreLogoServiceImpl.kt~story_856580249
> --story=856580249 【流水线插件执行】异常终止执行插件时，将终止原因打印到插件日志里，供用户查看

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/EnvUtils.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/archive/AtomBuildArchiveTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Runner.kt
> 插件发布未做参数检查，worker获取的堆栈信息无法加载 #250

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/CheckImageInitPipelineService.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/dao/image/MarketImageDao.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageReleaseService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/image/MarketCheckImageTask.kt
> 研发商店：修复私有镜像库的镜像上架流程不能重新验证的问题

- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/DockerHostBuildService.kt
> --task=6951511 查询镜像tag接口过滤掉latest名字的tag

- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageService.kt
> --bug=76525491 【镜像商店】镜像大小解析报错

- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/DockerHostBuildService.kt
> 镜像市场上架镜像时验证镜像合法性优化

- src/backend/ci/core/store/api-store-image/src/main/kotlin/com/tencent/devops/store/pojo/image/response/ImageDetail.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/constant/StoreMessageCode.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/dao/image/ImageDao.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/resources/image/user/UserImageResourceImpl.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageProjectService.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageService.kt
--bug=76555071 【容器镜像商店】OP编辑镜像功能修复
详情接口增加权重
> --bug=76555071 【容器镜像商店】OP编辑镜像功能修复

- support-files/sql/0004_ci_store-update-table_20191212-1127_mysql.sql
> --story=856722827 【容器镜像】蓝盾提供的公共镜像拉取策略优化

- src/backend/ci/core/plugin/codecc-plugin/common-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/CodeccApi.kt
- src/backend/ci/core/quality/api-quality/src/main/kotlin/com/tencent/devops/quality/constant/CodeccConstants.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleCheckService.kt
> bugfix: quality codec link to v2

- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/dao/image/ImageFeatureDao.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageLabelService.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageReleaseService.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/MarketImageService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/common/StoreMemberDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomMemberServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/StoreMemberService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/impl/StoreMemberServiceImpl.kt
> feature:增加部分开放方法

- src/backend/ci/core/plugin/codecc-plugin/common-codecc/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/agent/LinuxCodeCCScriptElement.kt
- src/backend/ci/core/plugin/codecc-plugin/common-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/CodeccApi.kt
> bugfix: fix ccn type

- src/agent/src/pkg/config/version.go
> bugfix:解决worker版本兼容问题

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/constant/ProcessMessageCode.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/modelcheck/DispatchTypeBizPlugin.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/extend/DefaultModelCheckPlugin.kt
- src/backend/ci/core/process/plugin-load/src/main/kotlin/com/tencent/devops/process/plugin/load/ContainerBizPluginLoader.kt
- src/backend/ci/core/process/plugin-load/src/main/kotlin/com/tencent/devops/process/plugin/load/ContainerBizRegistrar.kt
- src/backend/ci/core/process/plugin-sdk/src/main/kotlin/com/tencent/devops/process/plugin/ContainerBizPlugin.kt
- src/backend/ci/core/process/plugin-sdk/src/main/kotlin/com/tencent/devops/process/plugin/annotation/ContainerBiz.kt
- src/backend/ci/core/store/api-store-image/src/main/kotlin/com/tencent/devops/store/pojo/image/response/MyImage.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/dao/image/ImageDao.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageCommonService.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageProjectService.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageService.kt
> bugfix:修复容器镜像商店若干问题

- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/LogService.kt
- src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/log/model/pojo/QueryLogs.kt
- src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/log/utils/LogUtils.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/dao/v2/LogStatusDaoV2.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/resources/UserLogResourceImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/LogServiceDispatcher.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/v2/LogServiceV2.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/util/Constants.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/TaskAtomService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchBuildLessDockerShutdownTaskAtom.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchBuildLessDockerStartupTaskAtom.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchVMShutdownTaskAtom.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchVMStartupTaskAtom.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/BuildEndControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/BuildMonitorControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/ContainerControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/MutexControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildTaskDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineVMBuildService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Runner.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/AbstractBuildResourceApi.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/logger/LoggerService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/ProcessService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/TaskFactory.kt
> feature: 日志组件部分优化 issue #304

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineSettingService.kt
> saveAll 重复处理lable逻辑去除

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildTaskDao.kt
- src/backend/ci/core/quality/biz-quality/build.gradle
> add container hash id & gradle complie

- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/LogService.kt
- src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/log/model/pojo/QueryLogs.kt
- src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/log/utils/LogUtils.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/dao/v2/LogStatusDaoV2.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/resources/UserLogResourceImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/LogServiceDispatcher.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/v2/LogServiceV2.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/util/Constants.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/TaskAtomService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchBuildLessDockerShutdownTaskAtom.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchBuildLessDockerStartupTaskAtom.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchVMShutdownTaskAtom.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchVMStartupTaskAtom.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/BuildEndControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/BuildMonitorControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/ContainerControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/MutexControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildTaskDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineVMBuildService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Runner.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/AbstractBuildResourceApi.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/logger/LoggerService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/ProcessService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/TaskFactory.kt
> bugfix: 修复缺少行 #311

- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/scm/ServiceGitResource.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/scm/ServiceGitResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/GitOauthService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/GitService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/IGitOauthService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/IGitService.kt
支持获取用户名下的GIT代码库/分支/tag列表接口 - 用户态 #378
> 支持获取用户名下的GIT代码库/分支/tag列表接口 - 用户态

- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/gray/RepoGray.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/ProjectInfoResponseRepoGray.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/ProjectDao.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/OpProjectService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsOpProjectServiceImpl.kt
> feature: 支持仓库灰度设置

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/constant/ProcessMessageCode.kt
feature: 新增callback回调相关的2个错误类型 issue #432
> feature: 新增callback回调相关的2个错误类型 issue #432

- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/user/UserProjectResource.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/UserProjectResourceImpl.kt
> refactor: 统一user/project

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
bugfix: 有构建环境下的agent转换插件输入参数格式不对 issue #440 
fix #440
> bugfix: 有构建环境下的agent转换插件输入参数格式不对 issue #440

- src/backend/ci/core/store/biz-store-sample/src/main/kotlin/com/tencent/devops/store/SampleServiceConfig.kt
bugfix: 删除模板可见范围无用代码 issue #446
fix #446
> bugfix: 删除模板可见范围无用代码 issue #446

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/task/SubPipelineCallAtom.kt
> bugfix: 主流水线终止时，调用的子流水线未被一并终止 issue #459

- src/backend/ci/core/store/api-store-image/src/main/kotlin/com/tencent/devops/store/api/image/service/ServiceStoreImageResource.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/dao/image/ImageDao.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/resources/image/service/ServiceImageResourceImpl.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageService.kt
feature:增加获取所有的自研公共镜像Service接口
> feature:增加获取所有的自研公共镜像Service接口

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/task/SubPipelineCallAtom.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/BuildEndControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/StageControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildService.kt
> bugfix: 在取消构建结束逻辑统一取消子流水线构建 issue #459

- src/backend/ci/core/dispatch/api-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/api/BuildDockerHostResource.kt
- src/backend/ci/core/dispatch/api-dispatch/build.gradle
- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/controller/BuildDockerHostResourceImpl.kt
- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/service/DockerHostBuildService.kt
- src/backend/ci/core/dispatch/biz-dispatch/build.gradle
- src/backend/ci/core/dockerhost/biz-dockerhost/build.gradle
- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/dispatch/DockerHostBuildResourceApi.kt
- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/init/BuildClusterCronConfiguration.kt
- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/DockerHostBuildService.kt
> 公共镜像不做本地清理

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/BuildNo.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserBuildResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/BuildManualStartupInfo.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserBuildResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildService.kt
> fix: 推荐版本号执行可见功能缺失 #472

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/AtomDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/template/impl/MarketTemplateServiceImpl.kt
bugfix: 安装模板时自动安装模板下的插件校验逻辑应排除处于审核中或测试中版本的插件 issue #466
fix #466
> bugfix: 安装模板时自动安装模板下的插件校验逻辑应排除处于审核中或测试中版本的插件 issue #466

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/env/AgentEnv.kt
Feature: 修改MACOS构建类型获取运行参数的方式 issue #503
> Feature: 修改MACOS构建类型获取运行参数的方式 issue #503

- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/service/DockerHostBuildService.kt
> feature:增加dispatch关键日志打印

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/template/impl/MarketTemplateServiceImpl.kt
bugfix: 安装模板到项目要支持批量安装该模板下用户有权限的插件 issue #511
fix #511
> bugfix: 安装模板到项目要支持批量安装该模板下用户有权限的插件 issue #511

- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/service/DockerHostBuildService.kt
> Fix credential GitHub

- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/service/DockerHostDebugService.kt
> bugfix:修复历史镜像登录调试失败的问题

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
> feature: : 日志组件部分功能改进 issue #401

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
> bugfix: 构建日志重试超过3次无法查看 #553

- src/frontend/devops-atomstore/src/components/detailInfo.vue
- src/frontend/devops-atomstore/src/views/imageDetail/detail.vue
> bugfix: #462 修复商店展示镜像宽度撑出

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/template/TemplateOperationMessage.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/template/TemplateService.kt
feature:模板实例化结果返回成功的流水线Id #584
> feature:模板实例化结果返回成功的流水线Id #584

- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/cron/Runner.kt
- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/DockerHostBuildService.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageReleaseService.kt
bugfix:修复镜像缓存安全问题 #582
bugfix:仅针对流水线构建镜像进行agentType不为空校验 #565
>  bugfix:修复镜像缓存安全问题 #582

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildVarResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildVarResourceImpl.kt
> feature:支持获取构建参数

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/MutexControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/listener/run/finish/PipelineBuildCancelListener.kt
流水线日志中增加更详细的互斥组信息 issue #580
bugfix: job互斥组为变量的时候出现没有替换的情况 issue #578
> 流水线日志中增加更详细的互斥组信息 issue #580 & bugfix: job互斥组为变量的时候出现没有替换的情况 issue#578

- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/index.vue
> bugfix: 镜像区分历史数据和列表数据 #571

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/BuildMonitorControl.kt
> bugfix: Job的执行超时监控触发人 issue #590

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/compatibility/BuildPropertyCompatibilityTools.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineService.kt
> bugfix: 只兼容推荐版本号的旧变量替换 issue #631

- src/backend/ci/core/plugin/codecc-plugin/common-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/CodeccApi.kt
> change codecc update api param #646

- src/backend/ci/core/plugin/codecc-plugin/common-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/CodeccApi.kt
> feature: change codecc update api param

- src/backend/ci/core/common/common-api/src/main/java/com/tencent/devops/common/api/util/ObjectReplaceEnvVarUtil.java
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineVMBuildService.kt
> story:变量替换参数逻辑问题 issue #431

- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/ServiceAutoConfiguration.kt
- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/gray/MacOSGray.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/ProjectInfoResponseMacOSGray.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/ProjectDao.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/OpProjectService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsOpProjectServiceImpl.kt
feature: 支持新的macos公共构建机的项目灰度功能 issue #638
> feature: 支持新的macos公共构建机的项目灰度功能

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildService.kt
> bugfix: 构建机正常结束不下发终止命令 issue #673

- src/backend/ci/core/plugin/codecc-plugin/api-codecc/src/main/kotlin/com/tencent/devops/plugin/api/UserCodeccResource.kt
- src/backend/ci/core/plugin/codecc-plugin/biz-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/resources/UserCodeccResourceImpl.kt
- src/backend/ci/core/plugin/codecc-plugin/common-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/CodeccApi.kt
> Codecc增加v2版的获取规则集接口 #675

- docs/specification/REST_interface_specification.md
- docs/specification/field_naming_specification.md
- docs/specification/log_specification.md
- docs/wiki/collaborative_development_guidelines.md
- docs/wiki/store_development_guidelines.md
docs: 增加蓝盾研发商店开发指引 issue Tencent#683
fix#683
> docs: 增加蓝盾研发商店开发指引 issue Tencent#683

- src/frontend/devops-pipeline/src/views/subpages/exec_detail.vue
> bugfix: 兼容偶现组件未加载的情况

- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/BuildParams.vue
- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/VersionConfig.vue
- src/frontend/devops-pipeline/src/components/PipelineVersionsForm.vue
- src/frontend/devops-pipeline/src/utils/customRules.js
- src/frontend/devops-pipeline/src/utils/pipelineConst.js
- src/frontend/devops-pipeline/src/utils/util.js
- src/frontend/devops-pipeline/src/utils/validDictionary.js
- src/frontend/devops-pipeline/src/views/subpages/preview.vue
- src/frontend/devops-pipeline/src/views/template/instance_create.vue
> pipeline version update

- src/backend/ci/core/plugin/codecc-plugin/api-codecc/src/main/kotlin/com/tencent/devops/plugin/api/BuildCodeccResource.kt
- src/backend/ci/core/plugin/codecc-plugin/biz-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/resources/BuildCodeccResourceImpl.kt
- src/backend/ci/core/plugin/codecc-plugin/biz-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/service/CodeccService.kt
- src/backend/ci/core/plugin/codecc-plugin/common-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/CodeccUtils.kt
- src/backend/ci/core/plugin/codecc-plugin/common-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/config/CodeccScriptConfig.kt
- src/backend/ci/core/plugin/codecc-plugin/worker-plugin-codecc/src/main/kotlin/com/tencent/devops/plugin/worker/task/codecc/util/CodeccScriptUtils.kt
- src/backend/ci/core/plugin/codecc-plugin/worker-plugin-codecc/src/main/kotlin/com/tencent/devops/plugin/worker/task/codecc/util/CodeccUtils.kt
- src/backend/ci/core/plugin/codecc-plugin/worker-plugin-codecc/src/main/kotlin/com/tencent/devops/worker/common/api/codecc/PluginCodeccResourceApi.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityIndicatorService.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityPipelineService.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleCheckService.kt
> add codecc download script logic #688

- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/atom/AtomVersion.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomServiceImpl.kt
feature:【研发商店】插件构建灰度问题fix issue #703
fix #703
> feature:【研发商店】插件构建灰度问题fix issue #703

- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/index.vue
> 修改获取macos接口数据的时机

- src/frontend/devops-atomstore/src/store/atom.js
- src/frontend/devops-atomstore/src/views/edit_atom.vue
> 研发商店升级插件接口，携带初始化项目数据

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/enums/EnumLoader.kt
- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/enums/EnumModifier.kt
- src/backend/ci/core/common/common-api/src/main/resources/META-INF/services/com.tencent.devops.common.api.enums.EnumModifier
- src/backend/ci/core/worker/worker-agent/src/main/kotlin/com/tencent/devops/agent/Application.kt
> refactor: BuildType枚举类支持动态变化 issue #710

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/TaskAtomService.kt
> refactor: 部分core代码内外不一致修正 issue #719

- src/backend/ci/core/plugin/codecc-plugin/common-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/CodeccUtils.kt
- src/backend/ci/core/plugin/codecc-plugin/common-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/element/LinuxPaasCodeCCScriptElementBizPlugin.kt
- src/backend/ci/core/quality/api-quality/src/main/kotlin/com/tencent/devops/quality/api/v2/pojo/request/BuildCheckParams.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityIndicatorService.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityPipelineService.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleCheckService.kt
- src/backend/ci/core/quality/common-quality/src/main/kotlin/com/tencent/devops/plugin/quality/task/QualityGateInTaskAtom.kt
- src/backend/ci/core/quality/common-quality/src/main/kotlin/com/tencent/devops/plugin/quality/task/QualityGateOutTaskAtom.kt
> bugfix: Codecc V2体验问题 #718

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/code/ScmWebhookMatcher.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/code/GitWebHookMatcher.kt
> feature:tag触发支持tag名称匹配 #727

- src/backend/ci/core/plugin/codecc-plugin/worker-plugin-codecc/src/main/kotlin/com/tencent/devops/plugin/worker/task/codecc/util/CodeccEnvHelper.kt
- src/backend/ci/core/plugin/codecc-plugin/worker-plugin-codecc/src/main/kotlin/com/tencent/devops/plugin/worker/task/codecc/util/CodeccInstaller.kt
- src/backend/ci/core/plugin/codecc-plugin/worker-plugin-codecc/src/main/kotlin/com/tencent/devops/plugin/worker/task/codecc/util/CodeccUtils.kt
> feature:Codecc v2 支持MacOs公共机/MacOs第三方机 #731

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/constant/ProcessMessageCode.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/utils/PipelineUtils.kt
> feature: 流水线变量命名规范 #624

- src/frontend/devops-log/src/index.vue
- src/frontend/devops-log/src/virtualScroll.vue
- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/index.vue
> bugfix: 修复日志空格正确展示

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleCheckService.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/ExternalCodeccRepoResource.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/ExternalCodeccRepoResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepoFileService.kt
> feature:增加获取文件内容接口v2 #761

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/PipelineEngineConfiguration.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/extend/DefaultModelCheckPlugin.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/utils/PipelineUtils.kt
重构：将检查放到CheckPlugin中处理, 方便内部版本进行扩展处理
> refactor: 流水线变量命名规范 issue #624

- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/service/ServiceProjectResource.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/ProjectDao.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/ServiceProjectResourceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsOpProjectServiceImpl.kt
> bugfix: 项目名为空查项目列表接口意外返回全部数据 issue #765

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/script/CommandLineExecutor.kt
- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/script/ShellUtil.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/CommandLineExecutor.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/ExecutorUtil.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/ShellUtil.kt
> refactor: Codecc执行异常调整 #769

- src/backend/ci/core/worker/worker-api-sdk/src/main/kotlin/com/tencent/devops/worker/common/api/process/BuildResourceApi.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/AbstractBuildResourceApi.kt
> feature: 缩短Agent的BuildSDKApi的HTTP请求的超时时间 issue #789

- src/gateway/core/lua/util/url_util.lua
bugfix: 网关解析url的query参数失败 issue #746
> bugfix: 网关解析url的query参数失败 issue #746

- support-files/templates/gateway#core#devops.server.conf
bugfix:多域名的时候nginx解析失败 issue #807
> bugfix:多域名的时候nginx解析失败 issue #807

- CONTRIBUTING.md
> docs: 增加issue的分类规范 issue #868

- src/backend/ci/core/store/api-store-image/src/main/kotlin/com/tencent/devops/store/pojo/image/request/ImageBaseInfoUpdateRequest.kt
- src/backend/ci/core/store/api-store-image/src/main/kotlin/com/tencent/devops/store/pojo/image/request/ImageUpdateRequest.kt
- src/backend/ci/core/store/api-store-image/src/main/kotlin/com/tencent/devops/store/pojo/image/request/MarketImageUpdateRequest.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/dao/image/MarketImageDao.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageReleaseService.kt
feature: 镜像上架/编辑时，Dockerfile改为非必填 #853
feature: 研发商店镜像上架时，tag支持latest #854
> feature: 镜像上架/编辑时，Dockerfile改为非必填，tag支持latest   #853 #854

- src/frontend/devops-pipeline/src/components/pipelineParamsForm.vue
bugfix: 前端流水线点击执行重新请求页面并重置store数据 issue #891
> bugfix: 前端流水线点击执行重新请求页面并重置store数据 issue #891

- src/backend/ci/core/dispatch/api-dispatch/src/main/kotlin/com/tencent/devops/dispatch/api/OpPrivateVMResource.kt
- src/backend/ci/core/dispatch/api-dispatch/src/main/kotlin/com/tencent/devops/dispatch/api/OpVMResource.kt
- src/backend/ci/core/dispatch/api-dispatch/src/main/kotlin/com/tencent/devops/dispatch/pojo/PipelineBuild.kt
- src/backend/ci/core/dispatch/api-dispatch/src/main/kotlin/com/tencent/devops/dispatch/pojo/PipelineBuildCreate.kt
- src/backend/ci/core/dispatch/api-dispatch/src/main/kotlin/com/tencent/devops/dispatch/pojo/VM.kt
- src/backend/ci/core/dispatch/api-dispatch/src/main/kotlin/com/tencent/devops/dispatch/pojo/VMCreate.kt
- src/backend/ci/core/dispatch/api-dispatch/src/main/kotlin/com/tencent/devops/dispatch/pojo/VMWithPrivateProject.kt
- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/dao/PipelineDockerDebugDao.kt
- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/dao/PipelineDockerTaskDao.kt
- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/controller/OpPrivateVMResourceImpl.kt
- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/controller/OpVMResourceImpl.kt
- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/controller/ServiceVMResourceImpl.kt
- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/dao/DispatchPipelineBuildDao.kt
- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/dao/PrivateVMDao.kt
- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/dao/ThirdPartyAgentBuildDao.kt
- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/dao/VMDao.kt
- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/pojo/ThirdPartyAgentPreBuildAgents.kt
- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/PrivateVMService.kt
- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/VMService.kt
- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/vm/PowerOffVM.kt
- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/vm/PowerOnVM.kt
- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/vm/VMCache.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/template/TemplateService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/template/dao/PipelineTemplateDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/template/service/PipelineTemplateService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/scm/git/GitUpdateTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/scm/svn/SvnUpdateTask.kt
#885 
额外包括小改动：
1）模板更新时，model带上templateId
2）源材料newCommitId字段为null时处理
> feature: 数据库主键修改为bigint #885

- src/frontend/devops-atomstore/src/views/edit_image.vue
- src/frontend/devops-atomstore/src/views/imageDetail/edit.vue
feature: 研发商店镜像dockerfile允许为空 issue #853
> feature: 研发商店镜像dockerfile允许为空 issue #853

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/enums/BuildStatus.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/ElementAdditionalOptions.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/Constants.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/ControlUtils.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/TaskControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineVMBuildService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineTaskService.kt
- src/backend/ci/core/process/biz-process/src/test/kotlin/com/tencent/devops/process/engine/control/ControlUtilsTest.kt
fix #548
resolve#588
close#548
> store:插件增加高级流程控制选项-自动重试 #528

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/TaskControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineTaskService.kt
fix #548
resolve#588
close#548
> feature: 插件增加高级流程控制选项-自动重试 #548

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildRepositoryResourceImpl.kt
> bugfix: 相关插件插入物料信息时删除不必要的逻辑 #898

- src/backend/ci/core/common/common-api/src/main/java/com/tencent/devops/common/api/util/ObjectReplaceEnvVarUtil.java
- src/backend/ci/core/common/common-api/src/test/java/com/tencent/devops/common/api/util/ObjectReplaceEnvVarUtilTest.java
插件参数支持包含特殊字符的变量嵌套替换 #873
fix #873
> 插件参数支持包含特殊字符的变量嵌套替换 #873

- src/backend/ci/core/common/common-archive/src/main/kotlin/com/tencent/devops/common/archive/constant/ArchiveConstants.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/ElementAdditionalOptions.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/utils/ModelUtils.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/app/AppPipelineBuildResource.kt
- src/backend/ci/core/process/biz-process/build.gradle
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/app/AppPipelineBuildResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/ContainerControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/ControlUtils.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineVMBuildService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/app/AppBuildService.kt
- src/backend/ci/core/process/biz-process/src/test/kotlin/com/tencent/devops/process/engine/control/ControlUtilsTest.kt
> feature: 构建历史app接口 #637

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/enums/BuildStatus.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/BuildEndControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/BuildMonitorControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildStageDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildDetailService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineService.kt
> feature: 流水线支持Stage issue #115

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildSubPipelineResourceImpl.kt
> refactor: 迁移子流水线的接口 #926

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/ContainerControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
> bug: 流水线job设置满足条件才执行在后面失败插件重试之后意外执行 #958

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildQualityService.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleCheckService.kt
- src/backend/ci/core/quality/common-quality/src/main/kotlin/com/tencent/devops/plugin/quality/task/QualityUtils.kt
> feature: Codecc增加语言类型&红线通知组、轮询等待修改 #932

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/task/SubPipelineCallAtom.kt
>  refactor: 迁移子流水线的接口 #926

- src/backend/ci/core/quality/api-quality/src/main/kotlin/com/tencent/devops/quality/api/v2/ServiceQualityRuleResource.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/resources/v2/ServiceQualityRuleResourceImpl.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleCheckService.kt
- src/backend/ci/core/quality/common-quality/src/main/kotlin/com/tencent/devops/plugin/quality/task/Constants.kt
- src/backend/ci/core/quality/common-quality/src/main/kotlin/com/tencent/devops/plugin/quality/task/QualityGateInTaskAtom.kt
- src/backend/ci/core/quality/common-quality/src/main/kotlin/com/tencent/devops/plugin/quality/task/QualityGateOutTaskAtom.kt
- src/backend/ci/core/quality/common-quality/src/main/kotlin/com/tencent/devops/plugin/quality/task/QualityUtils.kt
> feature: Codecc红线轮询修改 #988

- src/frontend/devops-pipeline/src/components/Stages/Stage.vue
- src/frontend/devops-pipeline/src/components/Stages/StatusIcon.vue
- src/frontend/devops-pipeline/src/views/index.vue
- src/frontend/devops-pipeline/src/views/subpages/index.vue
- src/frontend/locale/pipeline/zh-CN.json
> 流水线stage bugfix

- src/backend/ci/core/quality/api-quality/src/main/kotlin/com/tencent/devops/quality/api/v2/ServiceQualityRuleResource.kt
> bugfix: Codecc红线轮询修改 #995

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildSummaryDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/template/TemplateService.kt
> bugfix: 模板实例构建号更新被覆盖问题 issue #915

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/type/DispatchType.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/type/agent/ThirdPartyAgentEnvDispatchType.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/type/agent/ThirdPartyAgentIDDispatchType.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/type/agent/ThirdPartyDevCloudDispatchType.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/type/codecc/CodeCCDispatchType.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/type/docker/DockerDispatchType.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/type/exsi/ESXiDispatchType.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/type/tstack/TStackDispatchType.kt
- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/service/DockerHostBuildService.kt
- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/service/DockerHostDebugService.kt
- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/utils/CommonUtils.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/modelcheck/DispatchTypeBizPlugin.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/dao/image/MarketImageDao.kt
> bugfix:镜像地址空格过滤 #1005

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/ContainerControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/ControlUtils.kt
bugfix: 流水线job中包含状态为SKIP的插件，job执行完后总时间显示的是SKIP插件前面的所有插件执行时间之和 #948
fix #948
> bugfix: 流水线job中包含状态为SKIP的插件，job执行完后总时间显示的是SKIP插件前面的所有插件执行时间之和 #948

- src/backend/ci/core/artifactory/biz-artifactory-store/src/main/kotlin/com/tencent/devops/artifactory/service/impl/ArchiveAtomToLocalServiceImpl.kt
feature: 读取上传插件包的配置文件时允许用户不传quality.json #1008
fix #1008
> feature: 读取上传插件包的配置文件时允许用户不传quality.json #1008

- src/frontend/devops-pipeline/src/store/modules/atom/actions.js
bugfix: 安装完插件需要更新一下列表 issue #1015
> bugfix: 安装完插件需要更新一下列表 issue #1015

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/BuildStartControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
> refactor: 流水线支持Stage issue #115

- src/frontend/devops-pipeline/src/components/AtomFormComponent/SelectInput/index.vue
- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/index.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
feature: 凭证支持可输入变量,selectInput支持跳转链接 issue #952
> feature: 凭证支持可输入变量,selectInput支持跳转链接 issue #952

- src/gateway/core/backend.conf
- src/gateway/core/lua/cors_filter_apigw.lua
- src/gateway/core/nginx.conf
feature: openapi的apigw类接口支持跨域请求 issue #998
不对GET请求做跨域处理。
feature: 网关日志新增更多的内容 issue #1039
新增日志
service:$service agent:$http_user_agent up_stream:$upstream_addr upstream_response_time:$upstream_response_time refer:$http_referer http_x_forwarded_for:$http_x_forwarded_for
> feature: issue #998 ;issue #1039

- src/backend/ci/core/process/plugin-trigger/src/main/kotlin/com/tencent/devops/process/plugin/trigger/timer/quartz/PipelineQuartzService.kt
> bug: 定时逻辑与灰度策略的影响修正 #1044

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Constants.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/AtomTargetHandleService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/impl/CommonAtomTargetHandleServiceImpl.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/impl/JavaAtomTargetHandleServiceImpl.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/impl/NodeJsAtomTargetHandleServiceImpl.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/AtomTargetFactory.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
bugfix: Node插件会自动修改用户的PATH变量 #1031
fix #1031
> Node插件会自动修改用户的PATH变量 bug

- src/frontend/devops-pipeline/src/components/atomFormField/CronTimer/week.vue
bugfix: 修复safari兼容性问题，cron定时触发触发时间输入框值变更无效bug issue #1071
> bugfix: 修复safari兼容性问题，cron定时触发触发时间输入框值变更无效bug issue #1071

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/EnvUtils.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/PipelineEngineConfiguration.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/interceptor/TimerTriggerScmChangeInterceptor.kt
> feature:新插件支持“源代码未更新时不触发”功能 #1070

- src/gateway/core/backend.conf
指定external和app类接口，返回的时候增加X-Content-Type-Options:nosniff头部。
> feature:网关特定接口支持”X-Content-Type-Options“ issue #1096

- support-files/templates/gateway#core#devops.server.conf
> bug:网关代码启动失败 issue #1116

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/external/ExternalScmResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/external/ExternalPipelineResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/external/ExternalScmResourceImpl.kt
> feature: Gitlab webhook触发流水线的api issue #984

- support-files/templates/#etc#ci#application-assembly.yml
- support-files/templates/#etc#ci#application-log.yml
- support-files/templates/#etc#ci#application-store.yml
- support-files/templates/#etc#ci#common.yml
> chore: 补充缺少的配置 #1109

- src/backend/ci/core/project/api-project-sample/src/main/kotlin/com/tencent/devops/project/api/op/OpMessageCodeResource.kt
- src/backend/ci/core/project/biz-project-sample/src/main/kotlin/com/tencent/devops/project/dao/MessageCodeDetailDao.kt
- src/backend/ci/core/project/biz-project-sample/src/main/kotlin/com/tencent/devops/project/resources/op/OpMessageCodeResourceImpl.kt
- src/backend/ci/core/project/biz-project-sample/src/main/kotlin/com/tencent/devops/project/service/MessageCodeDetailService.kt
> fix: 补充开源后缺少的国际化代码 #1133

- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/ProjectCreateInfo.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/ProjectUpdateInfo.kt
> fix: 项目管理组织架构字段默认值 #1135

- README.md
> chore: 支持GitHub Actions Tencent #1136

- .github/workflows/release.yml
test data here:
- Actions: https://github.com/zanyzhao/bk-ci/actions/runs/83972296
- Release: https://github.com/zanyzhao/bk-ci/releases
```bash
├── agent-package
│   ├── config
│   ├── jar
│   ├── jre
│   │   ├── linux
│   │   ├── macos
│   │   └── windows
│   ├── script
│   │   ├── linux
│   │   ├── macos
│   │   └── windows
│   └── upgrade
│       ├── devopsAgent_linux
│       ├── devopsAgent_macos
│       ├── devopsDaemon_linux
│       ├── devopsDaemon_macos
│       ├── upgrader_linux
│       └── upgrader_macos
├── artifactory
├── assembly
├── dispatch
├── dockerhost
├── environment
├── frontend
│   ├── artifactory
│   ├── codelib
│   ├── common-lib
│   │   └── log
│   ├── console
│   │   └── static
│   ├── environment
│   ├── pipeline
│   ├── quality
│   ├── store
│   ├── svg-sprites …
```
> chore: change directory of release file

- src/frontend/devops-pipeline/src/components/MiniMap/index.vue
- src/frontend/devops-pipeline/src/views/subpages/edit.vue
- src/frontend/devops-pipeline/src/views/subpages/exec_detail.vue
- src/frontend/devops-pipeline/src/views/template/edit.vue
> feature: 流水线添加小地图 issue #848

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/type/BuildType.kt
将ESXi和MACOS构建类型的依赖编译环境配置，改成false
> feature: macOS公共构建机去掉“依赖编译环境” issue #1171

- docs/install/frontend.md
- docs/overview/source_compile.md
- src/frontend/devops-nav/src/utils/bsWebSocket.js
feature: websocket 读取cookie用户信息未兼容信息为空的情况，导致报错 issue #1207
> feature: websocket 读取cookie用户信息未兼容信息为空的情况，导致报错

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildService.kt
> bugfix: 插件重试导致无关变量写入启动参数 #1164

- src/gateway/core/lua/router_srv.lua
- support-files/templates/gateway#core#lua#init.lua
> feature: 网关服务发现支持服务后缀 issue #1203

- render_gateway.sh
- scripts/bkenv.properties
- support-files/templates/#etc#ci#application-misc.yml
- support-files/templates/gateway#core#lua#init.lua
> chore: 整理部署规范 #1199

- .github/workflows/release.yml
> chore: 支持GitHub Actions #1136

- src/frontend/devops-pipeline/src/components/MiniMap/index.vue
feature: 修改执行详情页面小地图状态颜色 issue #848
> feature: 修改执行详情页面小地图状态颜色 issue #848

- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/user/UserProjectResource.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/ProjectDao.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
> bug: 对已经存在的项目进行编辑报错 #1196

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleCheckService.kt
> feature: 调整红线提示 #1224

- src/frontend/devops-log/src/index.vue
- src/frontend/devops-log/src/job.vue
- src/frontend/devops-log/src/logContainer.vue
- src/frontend/devops-log/src/status.vue
- src/frontend/devops-log/src/worker.js
- src/frontend/devops-pipeline/src/components/ExecDetail/log/jobLog.vue
- src/frontend/devops-pipeline/src/components/ExecDetail/log/pluginLog.vue
- src/frontend/devops-pipeline/src/components/ExecDetail/log/worker.js
- src/frontend/devops-pipeline/src/components/ExecDetail/status.vue
- src/frontend/devops-pipeline/src/components/ExecDetail/tools/search.vue
feature: 日志搜索支持特殊符号，忽略大小写，支持折叠搜索 issue #1083
> feature: 日志搜索支持特殊符号，忽略大小写，支持折叠搜索 issue #1083

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/listener/pipeline/MQPipelineCreateListener.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineService.kt
bugfix:创建流水线时，不能异步初始化T_PIPELINE_BUILD_SUMMARY的记录 #1218
fix #1218
> bugfix:创建流水线时，不能异步初始化T_PIPELINE_BUILD_SUMMARY的记录 #1218

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/index.vue
- src/frontend/devops-pipeline/src/components/ExecDetail/detailContainer.vue
> feature: 执行详情页面，支持展示job和插件的配置和日志 #1083

- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/op/OPProjectServiceResource.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/OPProjectServiceResourceImpl.kt
feature:project模块暴露蓝盾服务op相关接口 #1256
fix #1256
> feature:project模块暴露蓝盾服务op相关接口 #1256

- src/backend/ci/core/ticket/api-ticket/src/main/kotlin/com/tencent/devops/ticket/constant/TicketMessageCode.kt
- src/backend/ci/core/ticket/biz-ticket/src/main/kotlin/com/tencent/devops/ticket/resources/UserCertResourceImpl.kt
> --bug=813  修复证书名字过长报错

- docs/install/gateway.md
安装命令中关于gateway部署的部分未更新gateway/core @freyzheng
> docs:修改网关部署文档 issue #1272

- src/backend/ci/core/project/biz-project-sample/src/main/kotlin/com/tencent/devops/project/service/impl/BluekingProjectPermissionServiceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/GrayTestServiceImpl.kt
refactor: GrayTestService 添加实现类 #1285
> refactor: GrayTestService 添加实现类

- src/backend/ci/boot-assembly/build.gradle
- src/backend/ci/core/environment/boot-environment/build.gradle
解决biz-environment-sample模块删除后，environment没有接口实现的问题。
> bug:解决环境管理environment编译问题 issue #1304

- support-files/templates/#etc#ci#application-assembly.yml
- support-files/templates/#etc#ci#application-log.yml
默认注释掉，仅需要时开启，ES配置支持xpack认证和searchguard证书认证
> Chore: 梳理部署规范 #1199

- src/frontend/devops-log/src/worker.js
- src/frontend/devops-pipeline/src/components/ExecDetail/log/worker.js
不支持OffscreenCanvas的浏览器，分析字符结合CSS来计算宽度
> feature: 兼容不支持OffscreenCanvas的浏览器 issue #1292

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleService.kt
删除应该是"删除"权限
~~userGetRule 没有校验 AuthPermission.VIEW 权限~~
~~listRuleDataSummary 没有校验 AuthPermission.LIST 权限~~
> bugfix: 补充 quality 中部分权限控制 issue #1190

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
bugfix:开源版插件上传插件包shaContent内容未入库 #1330
fix #1330
> bugfix:开源版插件上传插件包shaContent内容未入库 #1330

- src/frontend/devops-log/src/dataWorker.js
- src/frontend/devops-log/src/virtualScroll.vue
- src/frontend/devops-log/src/worker.js
- src/frontend/devops-pipeline/src/components/ExecDetail/log/dataWorker.js
- src/frontend/devops-pipeline/src/components/ExecDetail/log/virtualScroll.vue
- src/frontend/devops-pipeline/src/components/ExecDetail/log/worker.js
- src/frontend/devops-pipeline/src/views/subpages/exec_detail.vue
> feature: 日志数据预处理部分采用单独worker处理 issue #1326

- src/frontend/devops-pipeline/src/views/subpages/exec_detail.vue
feature: 详情页面只在流水线页面展示小地图 issue #848
> feature: 详情页面只在流水线页面展示小地图 issue #848

- src/frontend/devops-atomstore/src/components/common/comment/commentDialog.vue
> bugfix: 评论字数大于500 issue #1242

- src/backend/ci/core/environment/biz-environment-sample/src/main/kotlin/com/tencent/devops/environment/permission/config/EnvironmentPermConfiguration.kt
- src/backend/ci/core/environment/biz-environment-sample/src/main/kotlin/com/tencent/devops/environment/permission/service/impl/BluekingEnvironmentPermissionService.kt
- src/backend/ci/core/environment/biz-environment-sample/src/main/kotlin/com/tencent/devops/environment/permission/service/impl/MockEnvironmentPermissionService.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/permission/AbstractEnvironmentPermissionService.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdPartyAgent/UpgradeService.kt
- support-files/agent-package/packages/linux/README.md
- support-files/agent-package/packages/macos/README.md
- support-files/agent-package/packages/windows/README.md
> bug: 导入第三方构建机异常 #1361

- src/gateway/core/docs.conf
- src/gateway/core/frontend.conf
> gateway启用https后跳转到http地址 issue #1341

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/utils/code/svn/SvnUtils.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/utils/code/svn/TmatesoftBasicAuthenticationManager2.kt
> perf: 调整SVN超时时间 #1332

- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/client/DockerHostClient.kt
- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/config/DefaultImageConfig.kt
- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/service/DockerHostBuildService.kt
- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/service/DockerHostDebugService.kt
feature:Dispatch默认公共镜像可配置 #1325
> feature:Dispatch默认公共镜像可配置 #1325

- src/frontend/devops-nav/package.json
- src/frontend/devops-nav/src/index.html
- src/frontend/devops-nav/webpack.config.js
- src/frontend/devops-pipeline/src/components/BuildHistoryTable/index.vue
feature: 流水线执行历史去掉“rebuild”按钮 issue #1162
> feature: 流水线执行历史去掉“rebuild”按钮 issue #1162

- src/frontend/devops-nav/package.json
- src/frontend/devops-nav/src/index.html
- src/frontend/devops-nav/webpack.config.js
- src/frontend/devops-pipeline/src/components/BuildHistoryTable/index.vue
> Revert "feature: 流水线执行历史去掉“rebuild”按钮 issue #1162"

- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/ContainerContent.vue
> feature: 流水线选择镜像，不需要调用transfer接口 issue #1369

- src/frontend/devops-pipeline/src/components/ExecDetail/log/jobLog.vue
- src/frontend/devops-pipeline/src/components/ExecDetail/log/pluginLog.vue
- src/frontend/devops-pipeline/src/components/ExecDetail/log/virtualScroll.vue
> feature: 预处理部分采用单独worker issue #1326

- support-files/sql/0002_ci_store_ddl_mysql.sql
- support-files/sql/0004_ci_store-update_v2.1.0_mysql.sql
bugfix:开源版T_ATOM_VERSION_LOG表的ATOM_ID字段应该加上唯一索引 #1374
fix #1374
> bugfix:开源版T_ATOM_VERSION_LOG表的ATOM_ID字段应该加上唯一索引 #1374

- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/util/Constants.kt
> feat: 日志采用单独worker处理会耗时的地方 #1326

- src/frontend/devops-atomstore/src/components/common/card/empty.vue
- src/frontend/devops-atomstore/src/components/common/workList/atom.vue
- src/frontend/devops-atomstore/src/components/common/workList/image.vue
- src/frontend/devops-atomstore/src/components/common/workList/template.vue
- src/frontend/devops-atomstore/src/router/index.js
- src/frontend/devops-atomstore/src/views/atomDetail/index.vue
- src/frontend/devops-atomstore/src/views/atom_list.vue
- src/frontend/devops-atomstore/src/views/edit_atom.vue
- src/frontend/devops-atomstore/src/views/edit_image.vue
- src/frontend/devops-atomstore/src/views/edit_template.vue
- src/frontend/devops-atomstore/src/views/imageDetail/index.vue
- src/frontend/devops-atomstore/src/views/imageProgress.vue
- src/frontend/devops-atomstore/src/views/install.vue
- src/frontend/devops-atomstore/src/views/market/index.vue
- src/frontend/devops-atomstore/src/views/release_progress.vue
- src/frontend/devops-atomstore/src/views/templateDetail/index.vue
- src/frontend/devops-atomstore/src/views/upgrade_template.vue
-根据releaseFlag判断插件是否可删除
-线上没有可用版本就可以删除
> bugfix: 研发商店修改下架插件逻辑 issue #1243

- src/frontend/devops-atomstore/src/views/release_progress.vue
feature: 修改重新上传包的交互 issue #1386
> feature: 修改重新上传包的交互 issue #1386

- src/frontend/devops-nav/src/assets/static/devops-utils.js
bugfix: 导航同步url,准确定位到iframe issue #1383
> bugfix: 导航同步url issue #1383

- src/frontend/devops-artifactory/src/views/index.vue
- src/frontend/devops-codelib/src/views/App.vue
- src/frontend/devops-environment/src/views/index.vue
- src/frontend/devops-nav/src/components/Header/index.vue
- src/frontend/devops-pipeline/src/components/pipelineList/listCreateHeader.vue
- src/frontend/devops-pipeline/src/views/list/newlist.vue
- src/frontend/devops-ticket/src/views/index.vue
feature: 蓝鲸社区版对接：去掉中英文切换功能 issue #1275
> feature: 蓝鲸社区版对接：去掉中英文切换功能 issue #1275

- src/gateway/core/vhosts/devops.apigw.conf
> feature:蓝盾网关支持apigw的请求代理 issue #1347

- src/backend/ci/core/common/common-websocket/src/main/kotlin/com/tencent/devops/common/websocket/utils/RedisUtlis.kt
- src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/configuration/WebsocketConfiguration.kt
- src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/cron/ClearTimeoutCron.kt
- src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/listener/WebSocketListener.kt
- src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/servcie/WebsocketService.kt
1.websocket消费者数量配置化。
2.cache数量配置化。
3.loginOut处理同源页面。
4.添加自动清理大session页面逻辑 #1046
> websocket添加配置项

- scripts/bkenv.properties
- src/frontend/devops-nav/src/index.html
- src/frontend/devops-nav/src/typings/index.d.ts
- src/frontend/devops-nav/src/utils/iframeUtil.ts
> remove ptloginjs

- src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/cron/ClearTimeoutCron.kt
- src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/servcie/WebsocketService.kt
1.调整loginOut 删除cache逻辑
2.添加自动删除大page页面session逻辑 #1046
> refactor: websocket 消费配置化

- src/backend/ci/core/artifactory/biz-artifactory-store/src/main/kotlin/com/tencent/devops/artifactory/service/impl/ArchiveAtomServiceImpl.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/atom/ServiceMarketAtomArchiveResource.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/atom/AtomPkgInfoUpdateRequest.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/atom/ServiceMarketAtomArchiveResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/MarketAtomArchiveService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomArchiveServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomCommonServiceImpl.kt
- support-files/sql/0003_ci_store-init_dml_mysql.sql
bugfix:开源版插件上架进度条页面重新上传包后前端改动不生效修复 #1392
fix #1392
> bugfix:开源版插件上架进度条页面重新上传包后前端改动不生效修复 #1392

- src/frontend/devops-log/src/dataWorker.js
- src/frontend/devops-pipeline/src/components/ExecDetail/log/dataWorker.js
> feature: 修改空日志的逻辑 issue #1417

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwBuildResourceV3.kt
- src/backend/ci/core/openapi/boot-openapi/src/main/resources/application.yml
> feature: 新增openapi模块 issue #1173

- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/client/DockerHostClient.kt
- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/controller/UserDockerHostResourceImpl.kt
- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/dao/PipelineDockerTaskSimpleDao.kt
- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/service/DispatchDockerService.kt
- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/service/dispatcher/docker/DockerDispatcher.kt
- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/utils/DockerHostUtils.kt
> feat: 已录入构建机被移除时，清空与之关联的构建关系 #1441

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildService.kt
> bugfix: rebuild和重试时保持原启动类型 #1455

- src/backend/ci/core/environment/api-environment/src/main/kotlin/com/tencent/devops/environment/api/BuildNodeResource.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/dao/NodeDao.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/resources/BuildNodeResourceImpl.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/NodeService.kt
> feat: 支持根据节点名称获取节点信息 #1283

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/MarketAtomFeatureDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
feature:新增插件时默认将插件设置成推荐 #1470
fix #1470
> feature:新增插件时默认将插件设置成推荐 #1470

- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/schedule/VmStatusScheduler.kt
- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/service/DockerHostDebugService.kt
- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/utils/DockerHostUtils.kt
- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/DockerHostBuildLessService.kt
- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/DockerHostBuildService.kt
> feat: 优化dispatch调度 #1469

- src/frontend/devops-pipeline/src/store/modules/atom/atomUtil.js
- src/frontend/devops-pipeline/src/store/modules/atom/mutations.js
> feature: 插件切换版本，保留之前填的值 issue #1038

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/engine/pojo/BuildInfo.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/task/SubPipelineCallAtom.kt
> bug: 内置子流水线插件在子流水线状态为QUEUE时会卡住 #1508

- scripts/bkenv.properties
- src/backend/ci/core/process/boot-process/src/main/resources/application.yml
- support-files/templates/#etc#ci#application-process.yml
fix #1515 
queueConcurrency:
buildStart: __PROCESS_EVENT_CONCURRENT__    # 构建启动消息并发处理数量
stage: __PROCESS_EVENT_CONCURRENT__         # 步骤消息并发处理数量
container: __PROCESS_EVENT_CONCURRENT__     # Job消息并发处理数量
task: __PROCESS_EVENT_CONCURRENT__          # Task消息并发处理数量
buildFinish: __PROCESS_EVENT_CONCURRENT__   # 构建结束消息并发处理数量
> chore: application-process.yml配置模板文件增加引擎相关配置 #1515

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/event/CallBackData.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/CallBackControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/init/PipelineExtendConfiguration.kt
> feature: 流水线webhook新增项目ID、触发方式字段 #1188

- README.md
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/TimerTriggerElement.kt
fix #1487 
前端自定义crontab表达式增加格式提示：cron为unix格式:minutes hours dayOfMonth month dayOfWeek，前端可以增加cron校验。例如：[https://tool.lu/crontab/](https://tool.lu/crontab/)  的功能
> perf: 优化定时触发器cron #1487

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/init/PipelineExtendConfiguration.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/webhook/WebhookMQConfiguration.kt
> fix: 补充缺少的MQ Exchange #1561

- src/frontend/devops-pipeline/src/components/AtomFormComponent/DynamicParameter/index.vue
- src/frontend/devops-pipeline/src/components/AtomFormComponent/DynamicParameter/parameterInput.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/NormalAtomV2.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/PreviewAtom.vue
feature: 插件添加动态参数组件 issue #1538
> feature: 插件添加动态参数组件 issue #1538

- src/frontend/devops-nav/src/utils/bsWebSocket.js
feature: websocket重连优化 issue #1496
> feature: websocket重连优化 issue #1496

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/op/OpPipelineQuotaResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/op/OpPipelineQuotaResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/ContainerControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineQuotaService.kt
> feature: 增加流水线job执行次数配额控制 #1529

- src/backend/ci/core/quality/api-quality/src/main/kotlin/com/tencent/devops/quality/api/v2/OPQualityMetadataResource.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/resources/v2/OPQualityMetadataResourceImpl.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityMetadataService.kt
> feature: 增加红线元数据导入接口 #1586

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
bugfix:T_PIPELINE_RESOURCE默认保存50个编排,从T_PIPELINE_RESOURCE表中获取最近50个编排之前的流水线model逻辑需优化 #1592
fix #1592
> bugfix:T_PIPELINE_RESOURCE默认保存50个编排,从T_PIPELINE_RESOURCE表中获取最近50个编排之前的流水线model逻辑需优化 #1592

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/parser/DispatchTypeParser.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/parser/DispatchTypeParserImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchVMStartupTaskAtom.kt
> perf: 修改部分包名 #1604

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwRepositoryCommitResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwRepositoryCommitResourceV3Impl.kt
> feature:[api需求] api获取流水线构建的commit信息 issue #982

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/task/ManualReviewTaskAtom.kt
> bug: 人工审核插件通知未做变量替换 #1634

- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/ProjectDao.kt
> feature: project新增相关项目相关dao

- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/op/OPActivityResource.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/op/OPProjectResource.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/ActivityInfo.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/OPActivityUpdate.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/ActivityDao.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/OPActivityResourceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/OPProjectResourceImpl.kt
>  feature: 添加op公告相关接口

- src/frontend/devops-pipeline/src/components/pipelineParamsForm.vue
> Revert "bugfix: 修复流水线变量使用js关键字报错 issue #1588"

- src/frontend/devops-pipeline/src/components/template/templateTable.vue
bugfix: 修复模板到研发商店链接 issue #1626
> bugfix: 修复模板到研发商店链接 issue #1626

- src/frontend/devops-log/src/dataWorker.js
- src/frontend/devops-pipeline/src/components/ExecDetail/log/dataWorker.js
feature: 优化数据预处理过程 issue #1649
> feature: 优化数据预处理过程 issue #1649

- src/frontend/devops-pipeline/src/components/pipelineParamsForm.vue
> bugfix: 流水线变量支持js关键字 issue #1588

- src/frontend/devops-pipeline/src/components/pipelineList/taskCard/index.vue
feature：流水线列表支持“在新标签页中打开链接”功能。 issue #872
> feature：流水线列表支持“在新标签页中打开链接”功能。 issue #872

- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
> feature: 修改流程控制文案 issue #1528

- src/frontend/devops-atomstore/src/components/common/detail-info/atom.vue
- src/frontend/devops-atomstore/src/components/common/detail-info/image.vue
- src/frontend/devops-atomstore/src/components/common/detail-info/template.vue
> bugfix: 添加简介最大宽度 issue #1614

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/ContainerControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/ControlUtils.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineVMBuildService.kt
- src/backend/ci/core/process/biz-process/src/test/kotlin/com/tencent/devops/process/engine/control/ContainerControlTest.kt
- src/backend/ci/core/process/biz-process/src/test/kotlin/com/tencent/devops/process/engine/control/ControlUtilsTest.kt
> feat: Task插件按条件执行的变量值支持变量 #1593

- src/backend/codecc/task/api-task/src/main/kotlin/com/tencent/bk/codecc/task/enums/ProjectLanguage.kt
- src/backend/codecc/task/api-task/src/main/kotlin/com/tencent/bk/codecc/task/jackson/ForkProjDeserializer.kt
- src/backend/codecc/task/api-task/src/main/kotlin/com/tencent/bk/codecc/task/pojo/ActiveProjModel.kt
- src/backend/codecc/task/api-task/src/main/kotlin/com/tencent/bk/codecc/task/pojo/ActiveProjParseModel.kt
- src/backend/codecc/task/api-task/src/main/kotlin/com/tencent/bk/codecc/task/pojo/BranchCommitModel.kt
- src/backend/codecc/task/api-task/src/main/kotlin/com/tencent/bk/codecc/task/pojo/ConfigStorageInfo.kt
- src/backend/codecc/task/api-task/src/main/kotlin/com/tencent/bk/codecc/task/pojo/ForkProjModel.kt
- src/backend/codecc/task/api-task/src/main/kotlin/com/tencent/bk/codecc/task/pojo/GongfengBranchModel.kt
- src/backend/codecc/task/api-task/src/main/kotlin/com/tencent/bk/codecc/task/pojo/GongfengProjPageModel.kt
- src/backend/codecc/task/api-task/src/main/kotlin/com/tencent/bk/codecc/task/pojo/GongfengPublicProjModel.kt
- src/backend/codecc/task/api-task/src/main/kotlin/com/tencent/bk/codecc/task/pojo/GongfengStatPageModel.kt
- src/backend/codecc/task/api-task/src/main/kotlin/com/tencent/bk/codecc/task/pojo/NameSpaceInfo.kt
- src/backend/codecc/task/api-task/src/main/kotlin/com/tencent/bk/codecc/task/pojo/OwnerInfo.kt
- src/backend/codecc/task/api-task/src/main/kotlin/com/tencent/bk/codecc/task/pojo/ProjectCommitInfo.kt
- src/backend/codecc/task/api-task/src/main/kotlin/com/tencent/bk/codecc/task/pojo/StatisticsInfo.kt
- src/backend/codecc/task/api-task/src/main/kotlin/com/tencent/bk/codecc/task/pojo/TriggerPipelineModel.kt
- src/backend/codecc/task/api-task/src/main/kotlin/com/tencent/bk/codecc/task/pojo/TriggerPipelineReq.kt
- src/backend/codecc/task/api-task/src/main/kotlin/com/tencent/bk/codecc/task/pojo/TriggerPipelineRsp.kt
> feat: 同步api-Task模块 #1691

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityIndicatorService.kt
> bug: 质量红线工具排序sortMap问题 #1655

- support-files/sql/0003_ci_demo-init_dml_mysql.sql
> Issue 1706

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/app/AppPipelineBuildResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/external/ExternalPipelineResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBadgeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
通过提供
latest
latestSucceeded
latestFailed
latestFinished
来查询对应buildId的app端流水线详情信息。
>  feature: 蓝盾App可以通过scheme拉起最新构建 issue #1408

- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/dao/image/ImageDao.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageService.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/util/ImageUtil.kt
- src/backend/ci/core/store/biz-store-image/src/test/kotlin/com/tencent/devops/store/util/ImageUtilTest.kt
fix:容器镜像使用大版本.latest方式使用镜像时，最新版本获取有bug #1541
> fix:容器镜像使用大版本.latest方式使用镜像时，最新版本获取有bug #1541

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineInfoDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineService.kt
> feature:流水线增加回收站功能 #542

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/ContainerControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildQualityService.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleCheckService.kt
> bug: 配额扣减逻辑+红线拦截耗时调整 #1724

- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/handler/BadRequestExceptionMapper.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/handler/DependNotFoundExceptionMapper.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/handler/ErrorCodeExceptionMapper.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/handler/IllegalArgumentExceptionMapper.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/handler/NotFoundExceptionMapper.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/handler/OperationExceptionMapper.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/handler/ParamBlankExceptionMapper.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/handler/ParamExceptionMapper.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/handler/PipelineAlreadyExistExceptionMapper.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/handler/UnauthorizedExceptionMapper.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/task/ManualReviewTaskAtom.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/CallBackControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/listener/pipeline/MQPipelineUpdateListener.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildQualityService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildWebhookService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineVMBuildService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineWebhookService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/utils/QualityUtils.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/CodeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/scm/GitScmService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/scm/ScmProxyService.kt
- src/backend/ci/core/process/plugin-trigger/src/main/kotlin/com/tencent/devops/process/plugin/trigger/timer/listener/PipelineTimerBuildListener.kt
>  process 日志级别整理

- src/frontend/devops-nav/package.json
- src/frontend/devops-pipeline/package.json
- src/frontend/devops-pipeline/src/components/BuildHistoryTab/index.vue
- src/frontend/devops-pipeline/src/mixins/pipeline-operate-mixin.js
bugfix: 启动流水线preview界面时偶现Cannot read property 'xx' of null/undefined #824
> 启动流水线preview界面时偶现Cannot read property 'xx' of null/undefined

- src/frontend/devops-pipeline/src/components/MiniMap/index.vue
- src/frontend/devops-pipeline/src/store/modules/atom/atomUtil.js
- src/frontend/devops-pipeline/src/store/modules/atom/mutations.js
> fix: 修复切换老插件报错 issue #1733

- src/backend/ci/core/notify/biz-notify/src/main/kotlin/com/tencent/devops/notify/service/NotifyMessageTemplateServiceImpl.kt
> fix: 修复通知模板发送的部分逻辑 #1692

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildContainerDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildStageDao.kt
- src/backend/ci/core/process/boot-process/src/test/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildContainerDaoTest.kt
- src/backend/ci/core/process/boot-process/src/test/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildStageDaoTest.kt
fix #1659 
单元测试写在boot-process工程下，因为启动的时候需要读配置
> bugfix: 耗时COST统计SQL问题修正 #1659

- src/frontend/devops-pipeline/src/components/AtomFormComponent/SelectInput/index.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/ReferenceVariable.vue
bugfix：变量引用浮层和git插件内下拉浮层 zindex样式问题 issue #1601
bugfix： select-input组件的跳转链接url字段不能解析变量 issue #1676
> bugfix: select-input组件的跳转链接url字段不能解析变量 issue #1676 && issue #1601

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildVarDao.kt
> perf: process调优 #1779

- src/frontend/devops-pipeline/src/components/atomFormField/EnumInput/index.vue
feature: enum支持配置一行展示个数 issue #1763
> feature: enum支持配置一行展示个数 issue #1763

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomOption.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/NormalAtom.vue
- src/frontend/devops-pipeline/src/components/atomFormField/RouteTips/index.vue
- src/frontend/devops-pipeline/src/components/atomFormField/VuexInput/index.vue
- src/frontend/devops-pipeline/src/components/atomFormField/VuexTextarea/index.vue
- src/frontend/devops-pipeline/src/components/atomFormField/atomFieldMixin.js
- 修改tip组件的宽度
- 执行详情页面，输入框鼠标悬停展示title
> feature: 执行详情可以展示所有的输入信息 issue #913

- src/backend/ci/core/dispatch/api-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/api/op/OPDispatchDockerResource.kt
- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/controller/OPDispatchDockerResourceImpl.kt
- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/controller/UserDockerHostResourceImpl.kt
- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/dao/PipelineDockerTaskSimpleDao.kt
- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/service/DispatchDockerService.kt
- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/service/DockerHostDebugService.kt
- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/utils/DockerHostUtils.kt
- src/backend/ci/core/dockerhost/api-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/api/ServiceDockerHostResource.kt
- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/resources/ServiceDockerHostResourceImpl.kt
- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/DockerHostBuildService.kt
- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/DockerService.kt
- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/utils/RandomUtil.kt
将磁盘IO作为一个漂移阈值判断项
新增移除构建绑定关系接口
去除删除构建机时清空构建关联的逻辑
> bugfix: 流水线异常退出时，debug异常 #1794

- src/backend/ci/core/artifactory/biz-artifactory-store/src/main/kotlin/com/tencent/devops/artifactory/service/impl/ArchiveAtomServiceImpl.kt
- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/service/impl/ArchiveFileServiceImpl.kt
- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/ShaUtils.kt
- src/backend/ci/core/common/common-api/src/test/kotlin/com/tencent/devops/common/api/util/ShaUtilsTest.kt
- src/backend/ci/core/worker/worker-api-sdk/src/main/kotlin/com/tencent/devops/worker/common/api/atom/AtomArchiveResourceApi.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
> bug: ShaUtils内存占用问题 #1788

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwBuildResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwBuildResourceV3Impl.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceBuildResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServiceBuildResourceImpl.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageReleaseService.kt
> fix: 手动启动构建的openapi接口支持传入buildNo参数 #1803

- src/backend/ci/core/plugin/codecc-plugin/biz-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/init/CodeCCMQConfiguration.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/init/PipelineExtendConfiguration.kt
https://github.com/Tencent/bk-ci/issues/1815#issue-638752082
> fix: PipelineModelAnalysisEvent事件监听报错 issue #1815

- src/frontend/devops-pipeline/src/components/Stages/AtomList.vue
fix: 流水线点击可拖拽区域偶现放大 issue #1868
> fix: 流水线点击可拖拽区域偶现放大 issue #1868

- src/frontend/devops-pipeline/src/components/AtomFormComponent/DynamicParameter/parameterInput.vue
> task: 优化动态参数组件交互 issue #1743

- src/frontend/devops-pipeline/src/components/pipelineList/PipelineTemplatePopup/index.vue
- src/frontend/devops-pipeline/src/store/modules/soda/pipeline.js
> feature: 模板选择界面优化 issue #1385

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/EmojiUtil.kt
- src/backend/ci/core/common/common-api/src/test/kotlin/com/tencent/devops/common/api/util/EmojiUtilTest.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildWebhookService.kt
fix #652 
webhook中的commit msg去掉emoji
> bugfix: 变量支持emoji值 #652

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/ContainerControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/MutexControl.kt
> fix: Job 互斥失败或等待等日志，需加到Job日志里 #1883

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/BuildEndControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/BuildMonitorControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/interceptor/QueueInterceptor.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeExtService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
> perf: 优化获取T_PIPELINE_BUILD_HISTORY排队命中STATUS_KEY索引 #1901

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/StageControl.kt
> bugfix: Stage事件未做状态确认的保护 #1913

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildWebhookService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/BuildVariableService.kt
> bugfix: build variable变量移除emoji字符 #652

- src/backend/ci/build.gradle
- src/backend/ci/core/common/common-db/src/main/kotlin/com/tencent/devops/common/db/DBAutoConfiguration.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildSummaryDao.kt
- src/backend/ci/task_gen_jooq.gradle
> perf: jooq升级到3.12.3 #1904

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/BuildTask.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineVMBuildService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
feature:【插件工作空间】无编译环境插件可在编译环境下运行时，获取到的工作空间优化 #1817
fix #1817
> feature:【插件工作空间】无编译环境插件可在编译环境下运行时，获取到的工作空间优化 #1817

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwArtifactoryResourceV3.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwAtomResourceV3.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwBuildResourceV3.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwCallBackResourceV3.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwLogResourceV3.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwPipelineResourceV3.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwProjectResourceV3.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwRepositoryCommitResourceV3.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwTemplateInstanceResourceV3.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwTemplateResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwPipelineResourceV3Impl.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwProjectResourceV3Impl.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/service/ServiceProjectResource.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/ServiceProjectResourceImpl.kt
1、将resource定义的Path具体到资源，解决path冲突时出现的404问题。
2、project接口改成ServiceProjectResource,解决feign在解析文件上传接口时的异常问题。
> bugfix: openapi接口路径定义冲突 issue #1880

- src/frontend/devops-nav/src/components/AnnouncementDialog/index.vue
- src/frontend/devops-nav/src/components/Header/NavMenu.vue
- src/frontend/devops-nav/src/store/actions.ts
- src/frontend/devops-nav/src/store/constants.ts
- src/frontend/devops-nav/src/store/getters.ts
- src/frontend/devops-nav/src/store/index.ts
- src/frontend/devops-nav/src/store/mutations.ts
- src/frontend/devops-nav/src/typings/vuex.d.ts
- src/frontend/devops-nav/src/views/App.vue
- src/frontend/devops-nav/src/views/IFrame.vue
- src/frontend/devops-nav/src/views/Index.vue
> feature: 支持以跑马灯的方式展示全局公告 issue #834

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/StageControl.kt
> bugfix: Stage事件未做状态确认的保护(回退) #1913

- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/CommitService.kt
> bug: 插件使用变量拉取之后，“代码变更记录”里面，就变成unknown repo #1936

- src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/log/api/BuildLogResource.kt
- src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/log/utils/LogUtils.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/resources/BuildLogResourceImpl.kt
> feat: 构建日志上报接口支持红色和黄色高亮 #1931

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/BuildStartControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/scm/ScmProxyService.kt
> perf: 构建启动优化 #1930

- src/frontend/devops-pipeline/src/components/AtomFormComponent/DevopsSelect/index.vue
- src/frontend/devops-pipeline/src/components/AtomFormComponent/SelectInput/index.vue
- src/frontend/devops-pipeline/src/components/AtomFormComponent/Selector/index.vue
- src/frontend/devops-pipeline/src/components/AtomFormComponent/selectorMixins.js
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/FormField.vue
bugfix: 详情页插件框不可编辑时，相应tips没有正常展示 issue #1943
fix: 多个selector组件公共特性提取放到mixin issue #1924
> fix: 多个selector组件公共特性提取放到mixin issue #1924 && bugfix: 详情页插件框不可编辑时，相应tips没有正常展示 issue #1943

- src/frontend/devops-pipeline/src/components/Stages/Stage.vue
feature: stage重试功能接口 issue #1565
> feature: stage重试功能接口 issue #1565

- src/frontend/devops-nav/src/utils/bsWebSocket.js
feature: websocket重连打散时间改为1分钟 issue #1974
> feature: websocket重连打散时间改为1分钟 issue #1974

- src/frontend/devops-pipeline/src/store/modules/pipelines/pipelinesTemplate.js
- src/frontend/devops-pipeline/src/views/template/instance_create.vue
feature: 更新实例增加设置同步选项 issue #1854
> feature: 更新实例增加设置同步选项 issue #1854

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/StageControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
> feat: Stage准入 #1790

- src/frontend/devops-pipeline/src/components/atomFormField/EnumInput/index.vue
bugfix: enum-input插件组件tooltips重叠 issue #1997
> bugfix: enum-input插件组件tooltips重叠 issue #1997

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwTemplateInstanceResourceV3.kt
> bugfix: 解决openapi的V3实例更新接口的路径冲突 #1992

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/exception/TaskExecuteException.kt
> perf: TaskExecuteException异常由Throwable改为RuntimeException #1988

- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/service/PipelineHistoryDataClearService.kt
feature:定期清理流水线构建历史记录 #1848
fix #1848
> feature:定期清理流水线构建历史记录 #1848

- src/backend/ci/build.gradle
> chore: 版本号升级 v1.0.2 #2011

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/ContainerControl.kt
> perf: 当Job运行失败时，Set up job的状态不对 #1336

- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/dao/image/ImageDao.kt
> fix:镜像工作台列表数量异常 #2019

- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/JerseyConfig.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/handler/JsonMappingExceptionMapper.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/handler/JsonParseExceptionMapper.kt
fix #2042
resolve #2042
close #2042
> feature: 对 JsonParseException 进行拦截处理 

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchBuildLessDockerShutdownTaskAtom.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchBuildLessDockerStartupTaskAtom.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchVMShutdownTaskAtom.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchVMStartupTaskAtom.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/StageControl.kt
- src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/configuration/WebSocketConfig.kt
- src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/cron/ClearTimeoutCron.kt
- src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/listener/WebSocketListener.kt
1.调整websocket limitcache
2.日志调整
> bug:websocket挤压处理 #2039

- src/backend/ci/core/plugin/codecc-plugin/common-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/CodeccUtils.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceVarResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceVarResourceImpl.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityPipelineService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/SvnService.kt
> bug: 红线v3插件配置页面提示缺少插件问题 #2033

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/CodeGitWebHookTriggerElement.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/code/ScmWebhookMatcher.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildWebhookService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/code/GitWebHookMatcher.kt
> Feature 368

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildService.kt
> bug: BK_CI_BUILD_NO在rebuild后构建参数中丢失 #2026

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/type/DispatchType.kt
新增MACOS的dispatchTypem，用于macos公共构建机的dispatcher-macos。
> feature: DispatchType新增MACOS类型 #2025

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceVarResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceVarResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/SvnService.kt
> bug: 流水线增加获取构建变量的service接口 #1999

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/AtomBaseInfo.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/AtomMarketInitPipelineReq.kt
- src/backend/ci/core/plugin/codecc-plugin/api-codecc/src/main/kotlin/com/tencent/devops/plugin/api/ServiceCodeccResource.kt
- src/backend/ci/core/plugin/codecc-plugin/biz-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/resources/ServiceCodeccResourceImpl.kt
- src/backend/ci/core/plugin/codecc-plugin/common-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/CodeccApi.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/service/ServicePipelineInitResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/AtomMarketInitPipelineService.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/common/enums/BusinessEnum.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/MarketAtomBuildInfoDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/common/BusinessConfigDao.kt
feature:插件上架支持代码扫描和质量红线 #1483
fix #1483
> feature:插件上架支持代码扫描和质量红线 #1483

- src/backend/ci/core/dockerhost/api-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/api/ServiceDockerHostResource.kt
- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/dispatch/DockerHostBuildResourceApi.kt
- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/init/CommonBuildClusterCronConfiguration.kt
- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/resources/ServiceDockerHostResourceImpl.kt
- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/DockerService.kt
> refactor：调整dockerhost dockerRungetLog接口，降低接口耗时 #2055

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildBuildResource.kt
> feature: build获取子流水线变量 build头命名 #1034

- src/backend/ci/core/artifactory/api-artifactory-sample/src/main/kotlin/com/tencent/devops/artifactory/api/BuildFileResource.kt
- src/backend/ci/core/artifactory/biz-artifactory-sample/src/main/kotlin/com/tencent/devops/artifactory/resources/BuildFileResourceImpl.kt
- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/service/ArchiveFileService.kt
- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/service/impl/ArchiveFileServiceImpl.kt
- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/service/impl/DiskArchiveFileServiceImpl.kt
- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/service/impl/JFrogArchiveFileServiceImpl.kt
> feature: artifactory新增【跨项目拷贝文件】build接口 #2054

- src/backend/ci/core/artifactory/api-artifactory-sample/src/main/kotlin/com/tencent/devops/artifactory/api/BuildFileResource.kt
- src/backend/ci/core/artifactory/biz-artifactory-sample/src/main/kotlin/com/tencent/devops/artifactory/resources/BuildFileResourceImpl.kt
- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/service/ArchiveFileService.kt
- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/service/impl/ArchiveFileServiceImpl.kt
- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/service/impl/DiskArchiveFileServiceImpl.kt
- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/service/impl/JFrogArchiveFileServiceImpl.kt
> release-1.1

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/AtomCommonDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/impl/StorePipelineServiceImpl.kt
feature: 支持动态刷新store组件构建流水线model #1646
#1646
> feature: 支持动态刷新store组件构建流水线model #1646

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/ContainerControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineVMBuildService.kt
> perf: 被禁用或跳过的[无用]插件任务在启动构建时不需要存储 #2046

- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/service/vm/DockerDownloaderService.kt
- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/DownloadScriptService.kt
- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/DownloaderService.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdPartyAgent/DownloadAgentInstallService.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdPartyAgent/UpgradeService.kt
- src/backend/ci/core/image/biz-image/src/main/kotlin/com/tencent/devops/image/utils/ImageFileUtils.kt
> Issue 2044

- src/gateway/core/lua/set_jwt_token.lua
- src/gateway/core/nginx.conf
- src/gateway/core/nginx.status.conf
- support-files/templates/gateway#core#lua#init.lua
1、增加网关单个worker的连接数worker_connections=10240，
2、worker最大打开文件数量worker_rlimit_nofile=163840
3、开启nginx状态查询路径
4、跨域头部支持X-DEVOPS-TOKEN
> feature：调整网关的连接参数 #2080

- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/utils/SigarUtil.kt
Signed-off-by: Hingbong <Hingbonglo@gmail.com>
> fix: 适配Debian的iostat命令 #1946

- src/agent/src/pkg/agent/agent.go
- src/agent/src/pkg/config/config.go
- src/agent/src/pkg/config/config_test.go
- src/agent/src/pkg/config/version.go
- src/agent/src/pkg/cron/cron.go
- src/agent/src/pkg/cron/cron_test.go
- src/agent/src/pkg/job/build.go
- src/agent/src/pkg/util/systemutil/systemutil.go
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Runner.kt
- src/backend/ci/core/worker/worker-common/src/main/resources/logback.xml
- support-files/agent-package/script/linux/install.sh
- support-files/agent-package/script/linux/start.sh
- support-files/agent-package/script/linux/stop.sh
- support-files/agent-package/script/linux/uninstall.sh
- support-files/agent-package/script/macos/install.sh
- support-files/agent-package/script/macos/start.sh
- support-files/agent-package/script/macos/stop.sh
- support-files/agent-package/script/macos/uninstall.sh
- support-files/agent-package/script/windows/install.bat
- support-files/agent-package/script/windows/start.bat
- support-files/agent-package/script/windows/stop.bat
- support-files/agent-package/script/windows/uninstall.bat
> Issue 2075

- src/frontend/devops-pipeline/src/components/AtomSelector/imageSelector.vue
- src/frontend/devops-pipeline/src/store/modules/pipelines/pipelines.js
> 镜像列表搜索支持从根据简介搜索

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/StageControl.kt
补充缺少代码
Conflicts:
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/StageControl.kt
#2036
> fix: Stage下有多个Job在并发结束时，可能导致后续本该跳过的Stage内的Job被意外拉起 #2036

- src/backend/ci/core/image/api-image/src/main/kotlin/com/tencent/devops/image/pojo/DockerTag.kt
> feature:DockerTag增加商店关联标识 #2117

- src/backend/ci/core/common/common-service/src/main/java/com/tencent/devops/common/service/Log4j2Initializer.java
> perf: log4j日志文件优化 #2073

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/impl/StoreCommonServiceImpl.kt
feat:研发商店组件发布进度页面提示信息优化 #2111
#2111
> feat:研发商店组件发布进度页面提示信息优化 #2111

- scripts/bkenv.properties
> fix: bkenv.properties变量名错误 #2119

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/CallBackControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
> bug: 删除流水线，流水线删除事件没有触发 #2091

- src/agent/src/pkg/config/config.go
> bugfix: agent检测版本冲突报 permission denied #2128

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildContainerDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildStageDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildTaskDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildVarDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/BuildVariableService.kt
- src/backend/ci/core/process/biz-process/src/test/kotlin/com/tencent/devops/process/engine/service/BuildVariableServiceTest.kt
refactor: 防止向流水线构建变量表插入重复数据 #2110
#2110
> refactor: 防止向流水线构建变量表插入重复数据 #2110

- .github/workflows/release.yml
> del: 删除重复的agent控制脚本文件 #2122

- src/backend/ci/core/plugin/codecc-plugin/common-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/CodeCCAutoConfiguration.kt
- src/backend/ci/core/plugin/codecc-plugin/common-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/CodeccApi.kt
- src/backend/ci/core/plugin/codecc-plugin/common-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/config/CodeccConfig.kt
> feature: Codecc增加代理配置 #2147

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/Stages/AtomList.vue
- src/frontend/devops-pipeline/src/components/pipelineList/PipelineTemplatePopup/index.vue
bugfix: 研发商店模板搜索支持按简介搜索  issue #2069
> bugfix: 研发商店模板搜索支持按简介搜索  issue #2069

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineTaskService.kt
> bug: 清理redisKey #2180

- .github/workflows/release.yml
- src/agent/README.md
> doc: 更新agent README文档 #2183

- src/backend/ci/core/store/api-store-image/src/main/kotlin/com/tencent/devops/store/pojo/image/response/BaseImageInfo.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageBuildResourceServiceImpl.kt
> fix:构建资源支持多种默认配置切换 #1985

- src/frontend/devops-pipeline/src/components/AtomSelector/index.vue
- src/frontend/devops-pipeline/src/store/modules/atom/getters.js
> fix: 研发商店搜索支持按简介搜索 issue #2169

- src/frontend/devops-atomstore/src/assets/scss/devops-common.scss
- src/frontend/devops-atomstore/src/components/detailInfo.vue
- src/frontend/devops-atomstore/src/views/imageProgress.vue
- src/frontend/devops-atomstore/src/views/release_progress.vue
> Bugfix 修改研发商店进度页面ui 2150

- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/ContainerContent.vue
> 构建资源支持多种默认配置切换

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildBuildResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/engine/common/Timeout.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/BuildVariables.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildBuildResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/BuildMonitorControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/ContainerControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildDetailService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineVMBuildService.kt
- src/backend/ci/core/worker/worker-agent/src/main/kotlin/com/tencent/devops/agent/AgentVersion.kt
- src/backend/ci/core/worker/worker-api-sdk/src/main/kotlin/com/tencent/devops/worker/common/api/process/BuildResourceApi.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Runner.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/process/BuildSDKApi.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/heartbeat/Heartbeat.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/ProcessService.kt
> bug: 插件已运行失败，但Job状态一直在运行中 #2074

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserScmWebhookResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserScmWebhookResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineWebhookDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/listener/pipeline/MQPipelineCreateListener.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineWebhookService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/webhook/WebHookTriggerElementBizPlugin.kt
- support-files/sql/2003_ci_process-update_v1.0_mysql.sql
> feature: webhookRedis存储结构优化 #1587

- src/frontend/devops-pipeline/src/components/AtomSelector/index.vue
- src/frontend/devops-pipeline/src/store/modules/atom/getters.js
- 插件列表搜索结构在接口的基准上，加上项目已安装且搜索没有的插件
> feature: 研发商店支持按简介搜索 issue #2169

- src/frontend/devops-pipeline/src/components/AtomFormComponent/selectorMixins.js
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/NormalAtomV2.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/atomMixin.js
- src/frontend/devops-pipeline/src/components/Stages/AtomList.vue
- src/frontend/devops-pipeline/src/components/Stages/Stage.vue
- src/frontend/devops-pipeline/src/components/Stages/StageContainer.vue
- src/frontend/devops-pipeline/src/utils/util.js
feature: 插件字段根据url动态获取选项，url参数较验逻辑优化 issue #2191
> feature: 插件字段根据url动态获取选项，url参数较验逻辑优化 issue #2191

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/template/TemplateService.kt
模式实例化时添加对远程触发插件相关判断。若存在创建pipelineId对应auth
> bug: 模板实例化不支持远程触发方式 #2231

- src/frontend/devops-atomstore/src/components/common/file-upload/index.vue
- src/frontend/devops-atomstore/src/views/edit_atom.vue
> feature: 商店开源版无编译环境 issue #2157

- src/frontend/devops-pipeline/src/components/pipelineList/PipelineTemplatePopup/index.vue
> bugfix: 安装模板后，缺失模板相关信息 issue #2237

- support-files/templates/boot-service.sh
> chore: 调整启动脚本JVM配置 #2217

- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/user/UserProjectResource.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/UserProjectResourceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
fix #2185
resolve #2185
close #2185
> 编辑项目，修改logo，点击保存，失败 #2185

- src/frontend/devops-pipeline/src/components/atomFormField/EnumInput/index.vue
chore: 修改enum-input 多列展示 issue #2240
> chore: 修改enum-input 多列展示 issue #2240

- src/frontend/.commitlintrc.json
- src/frontend/changelog.config.js
- src/frontend/commitlint.config.js
- src/frontend/devops-pipeline/src/components/Stages/StageContainer.vue
- src/frontend/devops-pipeline/src/components/pipeline/triggers.vue
- src/frontend/devops-pipeline/src/mixins/pipeline-operate-mixin.js
- src/frontend/devops-pipeline/src/store/modules/pipelines/pipelines.js
- src/frontend/devops-pipeline/src/views/list/newlist.vue
- src/frontend/devops-pipeline/src/views/subpages/preview.vue
- src/frontend/package.json
bug: 流水线编排线条样式展示有误 issue #2210
> bug: 流水线编排线条样式展示有误 issue #2210

- README_EN.md
> bug: 修复英文README的链接问题 #2251

- support-files/sql/5001_ci_store-init_dml_mysql.sql
feature:job支持选无编译环境 #2268
#2268
> feature:job支持选无编译环境 #2268

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/FormField.vue
- src/frontend/devops-pipeline/src/components/Stages/Stage.vue
bugfix: 样式优化：stage name太长会超出显示范围 issue #2274
> bugfix: 样式优化：stage name太长会超出显示范围  issue #2274

- src/backend/ci/build.gradle
- src/backend/ci/core/common/common-api/build.gradle
- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/constant/CommonConstants.kt
- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/pojo/AtomMonitorData.kt
- src/backend/ci/core/common/common-event/src/main/kotlin/com/tencent/devops/common/event/dispatcher/pipeline/mq/MQ.kt
- src/backend/ci/core/common/common-event/src/main/kotlin/com/tencent/devops/common/event/pojo/measure/AtomMonitorReportBroadCastEvent.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/BuildTaskResult.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/PipelineEngineConfiguration.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineVMBuildService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/measure/AtomMonitorEventDispatcher.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Runner.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/ProcessService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/TaskDaemon.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/AtomResult.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
- support-files/templates/#etc#ci#application-process.yml
feature:agent支持插件监控数据上报 #2178
#2178
> feature:agent支持插件监控数据上报 #2178

- src/backend/ci/boot-assembly/build.gradle
- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/dao/PipelineDockerHostZoneDao.kt
> feat: assembly增加新增的微服务 #2294

- src/frontend/devops-pipeline/src/components/BuildHistoryTab/index.vue
- src/frontend/devops-pipeline/src/components/BuildHistoryTable/index.vue
- src/frontend/devops-pipeline/src/components/InfiniteScroll/index.vue
- src/frontend/devops-pipeline/src/components/StagePropertyPanel/StageReviewPanel.vue
- src/frontend/devops-pipeline/src/components/StagePropertyPanel/index.vue
- src/frontend/devops-pipeline/src/components/Stages/Stage.vue
- src/frontend/devops-pipeline/src/components/outputOption/index.vue
- src/frontend/locale/pipeline/en-US.json
bugfix: 流水线执行历史更新时不应该显示loading issue #2315
> bugfix: 流水线执行历史更新时不应该显示loading issue #2315

- src/backend/ci/core/log/api-log/build.gradle
- src/backend/ci/core/log/biz-log/build.gradle
- src/backend/ci/core/log/build.gradle
> bugfix: log服务指定Lucene依赖版本避免全局版本影响 #2310

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/template/ServicePTemplateResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/template/TemplateDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/template/TemplateService.kt
bug:模板查询逻辑在模板列表查询为空时会查询所有源模板等问题修复 #2322
#2322
> bug:模板查询逻辑在模板列表查询为空时会查询所有源模板等问题修复 #2322

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/BuildVariables.kt
- src/backend/ci/core/worker/worker-agent/src/main/kotlin/com/tencent/devops/agent/AgentVersion.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/AbstractBuildResourceApi.kt
> perf: Agent支持部分网络异常的自动重试 #2353

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchVMStartupTaskAtom.kt
> bugfix: 有编译环境构建机启动错误码上报遗漏 #2114

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/measure/pojo/PipelineBuildData.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/measure/MeasureService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/measure/MeasureServiceImpl.kt
> perf: 执行历史改为包含所有插件错误信息 #2144

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/AtomSelector/index.vue
- src/frontend/devops-pipeline/src/components/Stages/AtomList.vue
> feature: 修改选择插件样式 issue #2382

- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/gray/RepoGray.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/op/OPProjectResource.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/OPProjectResourceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/OpProjectService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsOpProjectServiceImpl.kt
> feature: 版本仓库灰度配置优化 #2379

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/setting/PipelineSetting.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/Constants.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/dao/PipelineSettingDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/template/TemplateService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineSettingService.kt
feature:API接口方式编辑流水线也支持清理流水线历史模型版本 #2256
#2256
> feature:API接口方式编辑流水线也支持清理流水线历史模型版本 #2256

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/Stages/AtomList.vue
- src/frontend/devops-pipeline/src/components/atomFormField/Accordion/index.vue
> 流水线预设变量展开/收起图标优化

- scripts/bkenv.properties
- scripts/generate_boot.sh
- src/backend/ci/core/artifactory/api-artifactory/src/main/kotlin/com/tencent/devops/artifactory/api/user/UserReportStorageResource.kt
- src/backend/ci/core/artifactory/biz-artifactory-sample/src/main/kotlin/com/tencent/devops/artifactory/SampleArtifactoryServiceConfig.kt
- src/backend/ci/core/artifactory/biz-artifactory-sample/src/main/kotlin/com/tencent/devops/artifactory/resources/UserReportStorageResourceImpl.kt
- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/mq/ArtifactoryPipelineExtendConfiguration.kt
- src/backend/ci/core/auth/biz-auth-blueking/src/main/kotlin/com/tencent/devops/auth/service/ResourceService.kt
- src/backend/ci/core/misc/biz-misc-sample/src/main/kotlin/com/tencent/devops/misc/SampleMiscServiceConfig.kt
- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/cron/ThirdPartyAgentHeartBeat.kt
- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/dao/EnvironmentEnvNodeDao.kt
- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/dao/EnvironmentNodeDao.kt
- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/dao/EnvironmentThirdPartyAgentDao.kt
- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/service/AgentUpgradeService.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildRepositoryMaterialResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildRepositoryMaterialResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/parser/DispatchTypeParserImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/store/StoreImageHelper.kt
- src/backend/ci/core/project/api-project-sample/src/main/kotlin/com/tencent/devops/project/api/service/ServiceAuthProjectResource.kt
- src/backend/ci/core/project/biz-project-sample/src/main/kotlin/com/tencent/devops/project/resources/service/ServiceAuthProjectResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/ServiceAuthRepositoryResourceImpl.kt
- src/backend/ci/core/store/biz-store-sample/src/main/kotlin/com/tencent/devops/store/SampleStoreServiceConfig.kt
> fix: 因同名类导致boot-assembly无法正常启动 #2397

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwCredentialResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwCredentialResourceV3Impl.kt
> freyzheng feature:openapi支持凭据资源 #2326

- src/backend/ci/core/common/common-security/src/main/kotlin/com/tencent/devops/common/security/jwt/JwtManager.kt
> fix: 在微服务关闭jwt时仍然定时刷新token #2440

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/ScriptEnvUtils.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/ScriptTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/ExecutorUtil.kt
构建机操作文件添加随机数，做到并行Container 间的隔离， 避免误写误读
> bug: 流水线存在并行Container会存在setEnv失效bug #954

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/ICommand.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/ScriptTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/bat/CommandBatImpl.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/powershell/CommandPowerShellImpl.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/shell/CommandShellImpl.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/BatScriptUtil.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/ShellUtil.kt
> feat:插件执行日志优化 #1098

- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/mq/Constants.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/mq/CoreRabbitMQConfiguration.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/mq/ExtendRabbitMQConfiguration.kt
- support-files/templates/#etc#ci#common.yml
> bugfix: 双MQ的加载方式修复 #2452

- src/backend/ci/core/ticket/biz-ticket-sample/src/main/kotlin/com/tencent/devops/ticket/service/MockCertPermissionService.kt
- src/backend/ci/core/ticket/biz-ticket-sample/src/main/kotlin/com/tencent/devops/ticket/service/V3CertPermissionService.kt
- src/backend/ci/core/ticket/biz-ticket/src/main/kotlin/com/tencent/devops/ticket/dao/CertDao.kt
> bugfix: ticket新增证书后无法查看到 #2472

- support-files/templates/#etc#ci#common.yml
- support-files/templates/gateway#core#lua#init.lua
> chore: bkiam v3对接, 占位符调整. #2475

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/scm/git/GitUpdateTask.kt
> feat: 拉取git submodule代码支持本地相对路径 #2447

- support-files/sql/5001_ci_process-init_ddl_mysql.sql
> bug: 修复空白流水线的部分字段显示为中文 #2524

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchVMStartupTaskAtom.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildWebhookService.kt
> feature: 如果是push触发，就增加回写commit checker的逻辑 #458

- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/JobQuotaBusinessService.kt
> feat: 杜绝浪费，在Job上增加相关特性，避免不必要的开销 #970

- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/handler/PermissionForbiddenExceptionMapper.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/handler/RuntimeExceptionMapper.kt
> fix: 权限不足时提示信息优化 #2514

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserScmResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserScmResourceImpl.kt
> bug: 插件下拉选择代码库后报错404 #2516

- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/BuildParams.vue
- src/frontend/devops-pipeline/src/components/FileParamInput/index.vue
- src/frontend/devops-pipeline/src/components/pipelineParamsForm.vue
- src/frontend/devops-pipeline/src/store/modules/atom/paramsConfig.js
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
增加自定义仓库文件变量类型，允许用户上在执行流水线时传文件到自定义仓库
> feature: 流水线预设变量类型支持上传文件至自定义仓库 issue #133

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomOutput.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/NormalAtomV2.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/PreviewAtom.vue
- src/frontend/devops-pipeline/src/components/copyIcon.js
feature 插件输出支持一键复制 issue #1837
> feature 插件输出支持一键复制 issue #1837

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/pojo/agent/NodeStatus.kt
> format: 代码缺陷规范处理 #2558

- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
> perf: 修改Stage详情页文案 #2493

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
feature: 编辑界面，插件帮助文档入口调整 issue #1838
> feature: 编辑界面，插件帮助文档入口调整 issue #1838

- src/frontend/devops-codelib/src/components/CodeLibDialog/index.vue
- src/frontend/devops-codelib/src/components/LinkCodeLib/index.vue
- src/frontend/devops-codelib/src/config/index.js
- src/frontend/locale/codelib/en-US.json
- src/frontend/locale/codelib/zh-CN.json
feat: 新增腾讯工蜂git.code.tencent.com的事件监听 #1180
> feat: 新增腾讯工蜂git.code.tencent.com的事件监听 #1180

- support-files/templates/#etc#ci#common.yml
> perf: 保证consul的instanceId全局唯一 #2573

- src/frontend/devops-pipeline/src/components/AtomFormComponent/DynamicParameter/parameterInput.vue
feature: 动态参数组件支持连接符参数 issue #2534
> feature: 动态参数组件支持连接符参数 issue #2534

- src/frontend/devops-nav/src/views/ProjectManage.vue
> bugfix: 项目管理有创建权限时弹窗申请权限弹窗 issue #2547

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
> feature: 修改插件帮助文档的显示 issue #1838

- src/frontend/devops-environment/src/views/env_list.vue
bugfix: 对接权限中心v3交互问题集合 issue #2547
> bugfix: 对接权限中心v3交互问题集合 issue #2547

- src/backend/ci/core/auth/biz-auth-blueking/src/main/kotlin/com/tencent/devops/auth/service/IamService.kt
- src/backend/ci/core/common/common-auth/common-auth-v3/src/main/kotlin/com/tencent/devops/common/auth/pojo/Action.kt
> bug:创建项目权限跳转处理 #2579

- src/frontend/devops-environment/src/views/env_list.vue
bugfix: 环境管理有权限时仍无法编辑 issue #2547
>     bugfix: 环境管理有权限时仍无法编辑 issue #2547

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
feature: 流水线历史记录中展示的代码原材料按字符串首字母排序 #2435
添加sort逻辑
> feature: 流水线历史记录中展示的代码原材料按字符串首字母排序 #2435

- support-files/templates/#etc#ci#common.yml
chore: 增加微服务access_log日志配置 #2591
> chore: 增加微服务access_log日志配置 #2591

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/enums/BuildFormPropertyType.kt
feature:字符串类型的流水线变量支持换行 #2116
#2116
> feature:字符串类型的流水线变量支持换行 #2116

- src/frontend/devops-environment/src/views/node_list.vue
- src/frontend/devops-nav/src/views/ProjectManage.vue
- src/frontend/devops-pipeline/src/mixins/pipeline-operate-mixin.js
- src/frontend/devops-pipeline/src/views/list/newlist.vue
bugfix: 去掉项目管理内用户管理入口，环境管理权限跳转issue修复  issue #2547
> bugfix: 去掉项目管理内用户管理入口，环境管理权限跳转issue修复  issue #2547

- src/backend/ci/core/auth/biz-auth-blueking/src/main/kotlin/com/tencent/devops/auth/service/ResourceService.kt
- src/backend/ci/core/common/common-auth/common-auth-v3/src/main/kotlin/com/tencent/devops/common/auth/utlis/AuthUtils.kt
- src/backend/ci/core/common/common-auth/common-auth-v3/src/test/kotlin/com/tencent/devops/common/auth/utlis/AuthUtilsTest.kt
- src/backend/ci/core/environment/api-environment/src/main/kotlin/com/tencent/devops/environment/api/RemoteEnvResource.kt
- src/backend/ci/core/environment/api-environment/src/main/kotlin/com/tencent/devops/environment/api/RemoteNodeResource.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/dao/EnvDao.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/dao/NodeDao.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/resources/RemoteEnvResourceImpl.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/resources/RemoteNodeResourceImpl.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/EnvService.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/IEnvService.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/NodeService.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceAuthPipelineResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServiceAuthPipelineResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineInfoDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/ServiceAuthRepositoryResource.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/ServiceAuthRepositoryResourceImpl.kt
- src/backend/ci/core/ticket/api-ticket/src/main/kotlin/com/tencent/devops/ticket/api/ServiceAuthCallbackResource.kt
- src/backend/ci/core/ticket/biz-ticket/src/main/kotlin/com/tencent/devops/ticket/resources/ServiceAuthCredentialResourceImpl.kt
- support-files/bkiam/0007_bk_ci_20200804-1047_iam.json
1.权限回调接口翻页查询调整。
2.新建关联补齐项目管理。
3.权限获取project AND 获取调整
#2604
> bug: 权限中心回调翻页bug #2604

- src/frontend/devops-codelib/src/components/CodeLibDialog/index.vue
- src/frontend/devops-codelib/src/utils/index.js
bug: gitlab类型的代码库应该支持https协议 issue #2605
> bug: gitlab类型的代码库应该支持https协议 issue #2605

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildSubPipelineResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildSubPipelineResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStartUpService.kt
> feat: 启动子流水线的时候传入channelCode #2465

- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/CommitService.kt
> feature: 获取流水线的最新一次commit可以支持不通过代码库获取 #2461

- src/backend/ci/core/worker/worker-agent/src/main/kotlin/com/tencent/devops/agent/AgentVersion.kt
> chore: 修改work-agent版本 #2487

- src/backend/ci/core/plugin/codecc-plugin/common-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/CodeccUtils.kt
> feature: 调整CodeCC三个版本插件的判断逻辑 #2629

- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/ContainerContent.vue
bugfix: macOS公共构建机，值更新异常 issue #2634
> bugfix: macOS公共构建机，值更新异常 issue #2634

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/OwnerUtils.kt
- src/backend/ci/core/environment/biz-environment-sample/src/main/kotlin/com/tencent/devops/environment/permission/config/EnvironmentPermConfiguration.kt
- src/backend/ci/core/environment/biz-environment-sample/src/main/kotlin/com/tencent/devops/environment/permission/service/impl/V3EnvironmentPermissionService.kt
- src/backend/ci/core/process/biz-process-sample/src/main/kotlin/com/tencent/devops/process/permission/config/PipelinePermConfiguration.kt
- src/backend/ci/core/process/biz-process-sample/src/main/kotlin/com/tencent/devops/process/permission/service/impl/V3PipelinePermissionService.kt
- src/backend/ci/core/repository/biz-repository-sample/build.gradle
- src/backend/ci/core/repository/biz-repository-sample/src/main/kotlin/com/tencent/devops/repository/config/RepositoryPermConfiguration.kt
- src/backend/ci/core/repository/biz-repository-sample/src/main/kotlin/com/tencent/devops/repository/service/impl/V3RepositoryPermissionService.kt
- src/backend/ci/core/ticket/biz-ticket-sample/build.gradle
- src/backend/ci/core/ticket/biz-ticket-sample/src/main/kotlin/com/tencent/devops/ticket/config/TicketPermConfiguration.kt
- src/backend/ci/core/ticket/biz-ticket-sample/src/main/kotlin/com/tencent/devops/ticket/service/V3CertPermissionService.kt
- src/backend/ci/core/ticket/biz-ticket-sample/src/main/kotlin/com/tencent/devops/ticket/service/V3CredentialPermissionService.kt
> feat:项目管理员无其他人创建资源权限 #2650

- src/backend/ci/core/dispatch/api-dispatch/src/main/kotlin/com/tencent/devops/dispatch/api/OpJobQuotaSystemResource.kt
- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/controller/OpJobQuotaSystemResourceImpl.kt
- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/JobQuotaBusinessService.kt
bug: JOB配额，OP接口调整，增加一个统计接口 #2636
> bug: JOB配额，OP接口调整 #2636

- src/frontend/devops-nav/src/index.html
- support-files/templates/gateway#core#lua#init.lua
> chore: 占位符统一梳理 #2640

- src/backend/ci/.gitignore
- src/backend/ci/task_deploy_to_maven.gradle
保留原有uploadArchives（非标方式，不需要证书）
fix #2336
> 增加Publish插件上传自公网仓库

- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/ExternalCodeccRepoResource.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/ExternalCodeccRepoResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/CommonRepoFileService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/GitService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/IGitService.kt
> feature: 增加获取工蜂所有项目成员接口 #2653

- src/gateway/core/error/error.html.handler.conf
- src/gateway/core/static/401.html
> chore: 修改网关跳转登录逻辑 #2640

- src/backend/ci/core/common/common-event/build.gradle
- src/backend/ci/core/common/common-event/src/main/kotlin/com/tencent/devops/common/event/listener/pipeline/BaseListener.kt
- src/backend/ci/core/common/common-event/src/main/kotlin/com/tencent/devops/common/event/pojo/pipeline/IPipelineEvent.kt
- src/backend/ci/core/common/common-service/build.gradle
- src/backend/ci/core/common/common-service/src/main/java/com/tencent/devops/common/service/Log4j2Initializer.java
- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/trace/TraceFilter.kt
- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/trace/TraceTag.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
核心埋点：
1.springboot请求入口。获取Head
2.MQ消息统一埋点。
3.MQ出口统一处理MDC，消费完单条删除MDC信息。
4.修改Log patten。 需调整fileBeat收集规则。
5.调整了common需要重启所有微服务才能生效。
> feature: 添加traceId  去skywalking #1824

- src/backend/ci/core/dispatch/api-dispatch/src/main/kotlin/com/tencent/devops/dispatch/pojo/enums/JobQuotaVmType.kt
> feat: JOB配额增加工蜂CI类型 #2702

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwEnvironmentResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/build.gradle
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwEnvironmentResourceV3Impl.kt
添加两个openAPI接口.
1. 获取项目下节点列表.
2. 获取项目下指定节点哈希ID 状态.  #2675
> feat: 提供第三方构建机列表及状态的OpenAPI接口 #2675

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/template/UserPTemplateResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/template/UserPTemplateResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/template/TemplateDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/template/TemplatePipelineDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/template/TemplateService.kt
模板同个版本保存多次后，每次删除版本只会删除版本最近记录 #1804
#1804
> bug:模板同个版本保存多次后，每次删除版本只会删除版本最近记录 #1804

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/ParamService.kt
> bug: 代码库删除后，编辑流水线资源报“请求资源不存在” #2504

- src/frontend/devops-atomstore/src/components/common/selectLogo/index.vue
- src/frontend/devops-atomstore/src/components/manage/detail/atom-detail/edit.vue
- src/frontend/devops-atomstore/src/components/manage/detail/image-detail/edit.vue
- src/frontend/devops-atomstore/src/components/manage/release-manage/version/atom.vue
- src/frontend/devops-atomstore/src/store/atom.js
- src/frontend/devops-atomstore/src/views/edit_atom.vue
- src/frontend/devops-atomstore/src/views/edit_image.vue
- src/frontend/devops-atomstore/src/views/edit_template.vue
bug: 修复store组件在上架时根据组件logoUrl压缩成icon因为网络问题而失败 issue #2666
> bug: 修复store组件在上架时根据组件logoUrl压缩成icon因为网络问题而失败 issue #2666 release 1.2

- src/backend/ci/core/store/api-store-image/src/main/kotlin/com/tencent/devops/store/pojo/image/request/ImageBaseInfoUpdateRequest.kt
- src/backend/ci/core/store/api-store-image/src/main/kotlin/com/tencent/devops/store/pojo/image/request/MarketImageUpdateRequest.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/common/UserStoreLogoResource.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/atom/AtomBaseInfoUpdateRequest.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/atom/AtomUpdateRequest.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/atom/MarketAtomUpdateRequest.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/common/StoreLogoInfo.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/dao/image/MarketImageDao.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageReleaseService.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/SupportService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/AtomDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/MarketAtomDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/common/UserStoreLogoResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/StoreLogoService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/impl/StoreLogoServiceImpl.kt
bug:修复store组件在上架时根据组件logoUrl压缩成icon因为网络问题而失败 #2666
#2666
> bug:修复store组件在上架时根据组件logoUrl压缩成icon因为网络问题而失败 #2666

- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/pojo/CodeGitlabRepository.kt
> bug: gitlab类型的代码库应该支持https协议 #2605

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/utils/code/git/GitUtils.kt
- src/backend/ci/core/common/common-scm/src/test/kotlin/com/tencent/devops/scm/utils/code/git/GitUtilsTest.kt
> refactor: 优化git域名配置问题 #2731

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/StageControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
> bugfix: 准入后的stage重试时取消判断 #2022

- src/frontend/devops-environment/src/views/node_list.vue
> bugfix: 对接权限中心v3交互问题集合 节点管理请求资源类型出错 issue #2547

- src/backend/ci/core/process/biz-process-sample/src/main/kotlin/com/tencent/devops/process/service/PipelineBuildExtServiceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildExtService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineVMBuildService.kt
> feat: 拆离turbo强依赖 #2726

- src/backend/ci/core/process/biz-process-sample/src/main/kotlin/com/tencent/devops/process/service/code/ScmWebhookMatcherBuilderImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildWebhookService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/code/GitWebHookMatcher.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/code/ScmWebhookMatcherBuilder.kt
> refactor: webhook事件匹配代码优化 #2748

- src/backend/ci/core/worker/worker-agent/src/main/kotlin/com/tencent/devops/agent/AgentVersion.kt
> chore: 修改work-agent版本到12.8 #2487

- src/frontend/devops-atomstore/src/components/common/selectLogo/index.vue
- src/frontend/devops-atomstore/src/components/manage/detail/atom-detail/edit.vue
- src/frontend/devops-atomstore/src/components/manage/detail/image-detail/edit.vue
- src/frontend/devops-atomstore/src/components/manage/release-manage/version/atom.vue
- src/frontend/devops-atomstore/src/store/atom.js
- src/frontend/devops-atomstore/src/views/edit_atom.vue
- src/frontend/devops-atomstore/src/views/edit_image.vue
- src/frontend/devops-atomstore/src/views/edit_template.vue
bugfix: 修复store组件在上架时根据组件logoUrl压缩成icon因为网络问题而失败 issue #2666
>  bugfix: 修复store组件在上架时根据组件logoUrl压缩成icon因为网络问题而失败 issue #2666

- src/frontend/devops-pipeline/src/components/Stages/StatusIcon.vue
> fix: Stage-Job编号展示不全 #2685

- src/frontend/devops-codelib/src/components/CodeLibDialog/index.vue
- src/frontend/devops-codelib/src/utils/index.js
- src/frontend/devops-environment/src/views/node_list.vue
- src/frontend/devops-nav/src/views/ProjectManage.vue
- src/frontend/devops-pipeline/src/mixins/pipeline-operate-mixin.js
- src/frontend/devops-pipeline/src/views/list/newlist.vue
> gitlab支持https

- src/frontend/devops-atomstore/src/views/workList/template.vue
- src/frontend/devops-pipeline/src/components/template/templateTable.vue
bugfix: 模板管理到研发商店链接失效 issue #2743
> bugfix: 模板管理到研发商店链接失效 issue #2743

- src/frontend/devops-pipeline/src/store/modules/pipelines/pipelinesTemplate.js
- src/frontend/devops-pipeline/src/views/template/edit.vue
bugfix: 模板同个版本保存多次后，每次删除版本只会删除版本最近记录 issue #1804
> bugfix: 模板同个版本保存多次后，每次删除版本只会删除版本最近记录 issue #1804

- src/frontend/devops-pipeline/src/components/AtomSelector/index.vue
bugfix: 触发器搜索结果面板，显示可选择 issue #2721
> bugfix: 触发器搜索结果面板，显示可选择 issue #2721

- src/frontend/devops-pipeline/src/components/atomFormField/EnumInput/index.vue
- src/frontend/devops-pipeline/src/store/modules/atom/actions.js
feature: 增加radio间隙&mac os必填 issue #2699
> feature: 增加radio间隙&mac os必填 issue #2699

- support-files/templates/#etc#ci#application-assembly.yml
- support-files/templates/#etc#ci#application-process.yml
> chore: 占位符统一梳理 #2640 同步梳理补充单体服务的配置

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/agent/ManualReviewUserTaskElement.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/task/ManualReviewTaskAtom.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/init/AtomConfig.kt
> feat: 人工审核，支持输出审核人变量 #1860

- support-files/sql/2001_ci_store-update_v0.1_mysql.sql
bug:调整T_REASON_REL表STORE_TYPE字段类型 #2766
resolve #2766
> bug:调整T_REASON_REL表STORE_TYPE字段类型 #2766

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/Stages/AtomList.vue
- src/frontend/devops-ticket/src/views/create_credential.vue
> bug：新增凭据型切换类型不触发数据变更

- src/backend/ci/core/artifactory/api-artifactory/src/main/kotlin/com/tencent/devops/artifactory/api/user/UserFileResource.kt
- src/backend/ci/core/artifactory/biz-artifactory-sample/src/main/kotlin/com/tencent/devops/artifactory/resources/UserFileResourceImpl.kt
> bugfix: artifactory微服务restful路径冲突问题 #2818

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/enums/RepositoryTypeNew.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/Element.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/CodeGitGenericWebHookTrigger.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/utils/RepositoryConfigUtils.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/webhook/WebhookEventType.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserScmWebhookResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineWebhookDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/listener/pipeline/MQPipelineCreateListener.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildWebhookService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineWebhookService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/code/GitGenericWebHookElementParams.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/code/GitGenericWebHookElementStartParam.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/code/GitWebHookStartParam.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/code/GithubWebHookStartParam.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/code/ScmWebhookParamsFactory.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/code/TGitWebHookStartParam.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/utils/RepositoryUtils.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/webhook/WebHookTriggerElementBizPlugin.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/scm/ScmProxyService.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/scm/ServiceScmResource.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/scm/ServiceScmResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/IScmService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/ScmService.kt
> feature: git通用事件触发插件 #2518

- src/frontend/devops-pipeline/src/views/subpages/exec_detail.vue
- src/frontend/devops-pipeline/src/views/subpages/index.vue
> bug: stage审核弹窗层级太低，无法点击 issue #2829

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
启动流水线时 添加history表内 buildParameters #2800
> BUG: 构建过程中可获取构建启动参数 #2800

- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/resources/thirdPartyAgent/OpThirdPartyAgentResourceImpl.kt
bug:第三方构建机资源相关接口调整 #2815
#2815
> bug:第三方构建机资源相关接口调整 #2815

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomServiceImpl.kt
>  feature: op插件更新接口，如果htmlTemplateVersion是1.1，但是classType不是marketBuild或marketBuildLess，则不更新 #2712

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/code/GitWebHookMatcher.kt
> bug: 构建历史webhookInfo字段信息不正确 #2804

- src/frontend/devops-codelib/src/components/CodeLibTable/index.vue
> bugfix: 代码库申请删除权限跳转至申请编辑权限 issue #2547

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/ManualReviewUserTask.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
feature: 人工审核，支持输出变量 issue #1860
> feature: 人工审核，支持输出变量 issue #1860

- src/frontend/devops-nav/src/utils/bsWebSocket.js
bugfix: webhook的异常推送没有生效 issue #2792
> bugfix: webhook的异常推送没有生效 issue #2792

- src/backend/ci/core/common/common-api/src/test/kotlin/com/tencent/devops/common/api/util/HashUtilTest.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleService.kt
- src/backend/ci/core/repository/biz-repository-sample/src/main/kotlin/com/tencent/devops/repository/service/impl/V3RepositoryPermissionService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/impl/AbstractRepositoryPermissionService.kt
1. 调整代码库创建校验逻辑。
2. 权限获取代码库id， hash-> id
> BUG:代码库添加权限校验调整 #2819

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/ScriptEnvUtils.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/ScriptTask.kt
> BUG:result.log文件即时删除 #2845

- support-files/templates/#etc#ci#common.yml
bug:调整common.yml的devopsGateway.host和devopsGateway.api配置 #2840
#2840
> bug:调整common.yml的devopsGateway.host和devopsGateway.api配置 #2840

- support-files/templates/#etc#ci#application-log.yml
> feature: 日志模块支持基于磁盘文件的存储 #2725

- src/frontend/devops-pipeline/package.json
- src/frontend/devops-pipeline/src/components/ExecDetail/job.vue
- src/frontend/devops-pipeline/src/components/ExecDetail/log/jobLog.vue
feature: job日志支持切换执行次数 issue #2769
> feature: job日志支持切换执行次数 issue #2769

- src/backend/ci/core/worker/worker-agent/src/main/kotlin/com/tencent/devops/agent/AgentVersion.kt
> chore: 修改work-agent版本到12.11

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwPipelineResourceV3.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServicePipelineResource.kt
> bugfix: 批量获取流水线编排接口改为POST方法 #2868

- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/ServiceAutoConfiguration.kt
> feat: 部分服务缺失traceId #2878

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/pojo/ErrorCode.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/engine/atom/IAtomTask.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/AtomUtils.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/plugin/MarketBuildAtomElementBizPlugin.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/task/ManualReviewTaskAtom.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/utils/QualityUtils.kt
> perf: 质量红线准入准出失败和人工审核超时补充对应错误码 #2788

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineService.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/ProjectInfoResponse.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/ProjectInfoResponseMacOSGray.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/ProjectInfoResponseRepoGray.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/OpProjectUpdateInfoRequest.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/ProjectVO.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/ProjectDao.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsOpProjectServiceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/util/ProjectUtils.kt
- support-files/sql/1001_ci_project_ddl_mysql.sql
- support-files/sql/2001_ci_project-update_v0.1_mysql.sql
> feat: 每个项目最多创建N条流水线 #2362

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/BuildEndControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/BuildStartControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/lock/PipelineBuildNoLock.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/pojo/event/PipelineBuildStartEvent.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildDetailService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
bug:推荐版本号应在开始构建时完成+1 #2126
#2126
> bug:推荐版本号应在开始构建时完成+1 #2126

- src/frontend/devops-pipeline/src/components/AtomFormComponent/Tips/index.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/Stages/AtomList.vue
- src/frontend/devops-pipeline/src/components/copyIcon.js
bugfix: 流水线查看执行时的配置快照页面，链接点击不了 issue #2847
> bugfix: 流水线查看执行时的配置快照页面，链接点击不了 issue #2847

- scripts/bkci-op.sh
chore: 新增bkci-op.sh注册公共构建机 #2909
> chore: 新增bkci-op.sh注册公共构建机 #2909

- src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/handler/SessionHandler.kt
只在sessionId， userId同时存在的情况下做清理动作
> bug: websocket断连报错处理 #2912

- support-files/templates/#etc#ci#application-artifactory.yml
- support-files/templates/#etc#ci#application-assembly.yml
- support-files/templates/#etc#ci#application-auth.yml
- support-files/templates/#etc#ci#application-dispatch.yml
- support-files/templates/#etc#ci#application-environment.yml
- support-files/templates/#etc#ci#application-image.yml
- support-files/templates/#etc#ci#application-log.yml
- support-files/templates/#etc#ci#application-misc.yml
- support-files/templates/#etc#ci#application-notify.yml
- support-files/templates/#etc#ci#application-openapi.yml
- support-files/templates/#etc#ci#application-plugin.yml
- support-files/templates/#etc#ci#application-process.yml
- support-files/templates/#etc#ci#application-project.yml
- support-files/templates/#etc#ci#application-quality.yml
- support-files/templates/#etc#ci#application-repository.yml
- support-files/templates/#etc#ci#application-store.yml
- support-files/templates/#etc#ci#application-ticket.yml
> chore: jdbc url使用sessionVariables参数配置sql_mode #2920

- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/ContainerContent.vue
> bug: 移除新增自定义镜像入口 issue #2547

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildService.kt
> bug: webhook触发的流水线，rebuild后触发器的标记不对 #2821

- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/FeignConfiguration.kt
> feat: 部分服务缺失traceId 服务间调用 #2878

- src/backend/ci/core/sign/api-sign/src/main/kotlin/com/tencent/devops/sign/api/builds/BuildIpaResource.kt
- src/backend/ci/core/sign/api-sign/src/main/kotlin/com/tencent/devops/sign/api/pojo/SignDetail.kt
- src/backend/ci/core/sign/api-sign/src/main/kotlin/com/tencent/devops/sign/api/service/ServiceIpaResource.kt
- src/backend/ci/core/sign/api-sign/src/main/kotlin/com/tencent/devops/sign/api/user/UserIpaResource.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/impl/SignServiceImpl.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/resources/BuildIpaResourceImpl.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/resources/ServiceIpaResourceImpl.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/resources/UserIpaResourceImpl.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/service/SignInfoService.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/service/SignService.kt
> perf: 签名模块状态查询接口优化 #2924

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/compatibility/v2/V2BuildParametersCompatibilityTransformer.kt
- src/backend/ci/core/process/biz-process/src/test/kotlin/com/tencent/devops/process/engine/compatibility/v2/V2BuildParametersCompatibilityTransformerTest.kt
> perf: 启动构建接口不传变量参数则使用编排中的默认值 #2802

- support-files/bkiam/0003_bk_ci_20200623-2120_iam.json
> refactor:权限中心业务名称调整 #2942

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/AtomUtils.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/task/ManualReviewTaskAtom.kt
> feat: 【人工审核】插件增加用户的审核意见变量 #2893

- src/backend/ci/core/worker/worker-agent/src/main/kotlin/com/tencent/devops/agent/AgentVersion.kt
> chore: 修改work-agent版本到12.12 #2487

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/ManualReviewUserTask.vue
- src/frontend/devops-pipeline/src/components/Stages/AtomList.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
feature: 人工审核插件增加审核意见变量 issue #2893
> feature: 人工审核插件增加审核意见变量 issue #2893

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/Stages/AtomList.vue
- src/frontend/devops-pipeline/src/components/Stages/CheckAtomDialog.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
feature: 人工审核，支持修改默认审核结果 issue #2319
> feature: 人工审核，支持修改默认审核结果 issue #2319

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/Stages/AtomList.vue
- src/frontend/devops-pipeline/src/components/pipelineParamsForm.vue
- src/frontend/devops-pipeline/src/views/template/instance_create.vue
bugfix: 中文版 模板实例化时，构建版本号应展示为中文 issue #648
> bugfix: 中文版 模板实例化时，构建版本号应展示为中文 issue #648

- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
bugfix: 私有构建机/构建集群的默认workspace提示错误 issue #917
> bugfix: 私有构建机/构建集群的默认workspace提示错误 issue #917

- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/resources/ServiceDockerHostResourceImpl.kt
> feat: 容器化版本迁移 #2953

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/pojo/ErrorCode.kt
- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/script/CommandLineExecutor.kt
- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/script/CommandLineUtils.kt
- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/script/ShellUtil.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Runner.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/CommandLineExecutor.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/CommandLineUtils.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/ExecutorUtil.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/ShellUtil.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/WindowsCommandLineUtils.kt
> bugfix: 未分离Bash插件执行出错中的用户错误 #2955

- src/frontend/devops-nav/src/components/ProjectDialog/index.vue
- src/frontend/locale/nav/en-US.json
- src/frontend/locale/nav/zh-CN.json
feature: 项目名称放宽为32个字符 issue #2907
> feature: 项目名称放宽为32个字符 issue #2907

- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwProjectResourceV3Impl.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/service/ServiceProjectResource.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/user/UserProjectResource.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/ProjectLogo.kt
- src/backend/ci/core/project/biz-project-sample/src/main/kotlin/com/tencent/devops/project/service/ProjectServiceImpl.kt
- src/backend/ci/core/project/biz-project-sample/src/main/kotlin/com/tencent/devops/project/service/SimpleProjectServiceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/pojo/ProjectCreateExtInfo.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/OPProjectResourceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/ServiceProjectResourceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/UserProjectResourceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/ProjectService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
> refactor: project 代码结构调整  #2886

- src/backend/ci/core/worker/worker-agent/src/main/kotlin/com/tencent/devops/agent/AgentVersion.kt
> chore: 修改work-agent版本到12.13 #2487

- .github/workflows/agent.yml
- .github/workflows/backend.yml
- .github/workflows/frontend.yml
- .github/workflows/sql.yml
> chore: release分支也支持触发Actions检查 #2983

- src/frontend/devops-codelib/src/components/CodeLibDialog/index.vue
- src/frontend/devops-codelib/src/components/LinkCodeLib/index.vue
- src/frontend/devops-codelib/src/config/index.js
- src/frontend/devops-codelib/src/utils/index.js
- src/frontend/devops-codelib/src/views/Index.vue
- src/frontend/locale/codelib/en-US.json
- src/frontend/locale/codelib/zh-CN.json
feature: 代码库服务迁移对工蜂外网版的支持 issue #2977
>  feature: 代码库服务迁移对工蜂外网版的支持 issue #2977

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/HeartbeatControl.kt
> fix: 插件报错心跳超时时，需输出用户类型错误码 #2952

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/Watcher.kt
- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/utils/LogUtils.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServiceAuthPipelineResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServicePipelineResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/BuildCancelControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/BuildEndControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/BuildStartControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/ContainerControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/StageControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/TaskControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineInfoDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/init/PipelineCoreConfiguration.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/listener/pipeline/MQPipelineCreateListener.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/listener/pipeline/MQPipelineDeleteListener.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/listener/pipeline/MQPipelineUpdateListener.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/listener/run/finish/PipelineBuildCancelListener.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildDetailService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/template/TemplateService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/ParamService.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageProjectService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/impl/StoreProjectServiceImpl.kt
- src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/listener/WebSocketListener.kt
> perf: 构建队列MQ的弹性最大并发线程保持一致 #2994

- src/frontend/devops-codelib/src/components/CodeLibDialog/index.vue
- src/frontend/devops-codelib/src/config/index.js
feature: 支持git.code.tencent.com issue #1180
> feature: 支持git.code.tencent.com issue #1180

- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/UserGithubResource.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/UserGithubResourceImpl.kt
> fix: 迁移github触发器相关接口 #3006

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/VersionConfig.vue
- src/frontend/devops-pipeline/src/components/Stages/AtomList.vue
> 流水线参数有变更时的配色调整 #2976

- src/frontend/devops-pipeline/src/components/AtomFormComponent/Parameter/index.vue
feature: 子流水线调用时，按需传递参数 issue #945
> feature: 子流水线调用时，按需传递参数 issue #945

- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/es/ESAutoConfiguration.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/lucene/LuceneAutoConfiguration.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/mq/LogListener.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/LogServiceDispatcher.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/impl/LogServiceESImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/impl/LogServiceLuceneImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/util/Constants.kt
1 调整单个请求大小
2 各类rest出现的并发异常捕获
3 增加写入重试的退避机制
4 去掉已经不再使用的旧逻辑
resolve #2996
> pref: 日志模块REST Client连接池与返回值优化 #2996

- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/JobQuotaBusinessService.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServicePipelineResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServicePipelineResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineService.kt
feat: JOB配额，清理日志打印，增加流水线是否还在执行的校验
> feat: JOB配额，清理日志打印，增加流水线是否还在执行的校验

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineWebhookDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineWebhookService.kt
>  bug: 修复webhook刷新task_id产生的错误数据 #2954

- src/backend/ci/core/project/biz-project-sample/src/test/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImplTest.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
> bug: 创建项目支持中划线分割 #3030

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwSignResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwSignResourceV3Impl.kt
> feat: 签名OpenAPI提供签后文件的下载链接获取接口 #3042

- src/frontend/devops-pipeline/src/store/modules/soda/optionConfigMixin.js
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
feature: 流水线TASK执行前支持自动暂停 issue #1260
> feature: 流水线TASK执行前支持自动暂停 issue #1260

- src/frontend/devops-codecc/src/api/index.js
- src/frontend/devops-nav/package.json
- src/frontend/devops-nav/src/assets/static/devops-utils.js
- src/frontend/devops-nav/src/assets/static/login_success.html
- src/frontend/devops-nav/src/typings/index.d.ts
- src/frontend/devops-nav/src/utils/iframeUtil.ts
- src/frontend/devops-nav/src/utils/request.ts
- src/frontend/devops-nav/src/views/Index.vue
- src/frontend/devops-pipeline/src/utils/request.js
feature: 登录小窗口 issue #860961755
> feature: 登录小窗口 issue #860961755

- src/frontend/devops-nav/src/views/Index.vue
> feature: 登录支持小窗弹窗登录 issue #3060

- src/gateway/core/lua/util/consul_util.lua
- src/gateway/core/nginx.conf
> feat: gateway的getAllWhitelistIp加上本地缓存

- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/handler/NotFoundExceptionMapper.kt
> bug: NotFoundExceptionMapper不应该抛出堆栈信息 #3063

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwTemplateInstanceResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwTemplateInstanceResourceV3Impl.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/template/ServiceTemplateInstanceResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/template/ServiceTemplateInstanceResourceImpl.kt
fix #3027 
resolve #3027 
close #3027
> feat: OpenAPI提供批量获取流水线模板实例接口 #3027

- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwPipelineResourceV3Impl.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServicePipelineResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServicePipelineResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineService.kt
fix #2987 
resolve #2987 
close #2987
> bugfix：Service类获取流水线编排接口未做用户鉴权 issue #2987

- scripts/bkenv.properties
> perf: 配置项调整 #3041

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/git/api/GitApi.kt
> bug: gitApi获取分支信息，分支名需要转义 #3056

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/utils/QualityUtils.kt
> bug: dependon开启质量红线不生效 #3018

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/AtomMarketInitPipelineService.kt
> feat:插件集成代码扫描 #2541

- src/frontend/devops-nav/package.json
- src/frontend/devops-pipeline/package.json
feature: 升级magic box组件库到2.2.8  issue #3077
> feature: 升级magic box组件库到2.2.8  issue #3077

- src/frontend/devops-nav/src/components/ProjectDialog/index.vue
feature: 编辑项目保存时，允许项目英文名包含下划线、以下划线开头 issue #2945
> feature: 编辑项目保存时，允许项目英文名包含下划线、以下划线开头 issue #2945

- src/frontend/devops-codelib/src/components/CodeLibDialog/index.vue
- src/frontend/devops-codelib/src/config/index.js
- src/frontend/devops-codelib/src/utils/index.js
- src/frontend/devops-codelib/src/views/Index.vue
- src/frontend/locale/codelib/en-US.json
- src/frontend/locale/codelib/zh-CN.json
feature: 代码库服务迁移对工蜂外网版的支持 issue #2977
> feature: 代码库服务迁移对工蜂外网版的支持 issue #2977

- src/gateway/core/lua/router_srv.lua
- src/gateway/core/nginx.conf
> feat: 优化gateway的dns:query #3079

- src/gateway/core/lua/router_srv.lua
> bug: 修复gatway缓存没有区分灰度环境的问题

- src/frontend/devops-codelib/src/utils/index.js
feature: 代码库链接支持端口正则 issue #3105
> feature: 代码库链接支持端口正则 issue #3105

- src/frontend/devops-pipeline/src/components/AtomFormComponent/DevopsSelect/index.vue
bugfix: 下拉框组件无法回显带点和下划线的变量 issue #3109
> bugfix: 下拉框组件无法回显带点和下划线的变量 issue #3109

- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/BuildParams.vue
- src/frontend/devops-pipeline/src/components/MiniMap/index.vue
- src/frontend/devops-pipeline/src/components/pipeline/triggers.vue
- src/frontend/devops-pipeline/src/components/pipelineParamsForm.vue
- src/frontend/devops-pipeline/src/views/subpages/preview.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
feature: 触发构建时，支持填入构建信息 issue #2902
> feature: 触发构建时，支持填入构建信息 issue #2902

- src/backend/ci/core/sign/biz-sign-sample/build.gradle
- src/backend/ci/core/sign/build.gradle
> bugfix: 签名模块gradle配置调整 #3115

- src/frontend/devops-pipeline/src/components/AtomFormComponent/Selector/index.vue
- src/frontend/devops-pipeline/src/store/modules/atom/actions.js
feature: 插件列表拉取数量增加到1500 issue #3126
> feature: 插件列表拉取数量增加到1500 issue #3126

- src/gateway/core/lua/init_common.lua
- src/gateway/core/lua/router_srv.lua
> fix: 修复gateway相关问题 #3136

- src/frontend/devops-nav/src/index.html
feature: 开源版导航支持自定义域名 issue #3132
> feature: 开源版导航支持自定义域名 issue #3132

- src/backend/ci/build.gradle
> chore: 指定依赖的kotlin版本 issue #3117

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/code/ScmWebhookParamsFactory.kt
> bug: 构建信息移除emoji符号 #3167

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildWebhookService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/code/GitWebHookMatcher.kt
> perf: webhook增加耗时日志埋点 #3163

- src/gateway/core/nginx.conf
> feature: gateway新增一个缓存区域 #3172

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwProjectResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwProjectResourceV3Impl.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/service/ServiceProjectResource.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/user/UserProjectResource.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/ServiceProjectResourceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
1. 调整user类校验接口 name位置到query
2. 添加openAPI校验接口
#3125
> feat: 新建项目，使用特殊字符不能通过校验 #3125

- src/backend/ci/build.gradle
- src/backend/ci/core/process/biz-process-sample/src/main/kotlin/com/tencent/devops/process/service/PipelinePauseExtServiceImpl.kt
> refactor: 补充@Service 注解 #3272

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomServiceImpl.kt
bug:插件构建打包时，agent有权查询处于构建中的插件信息 #3276
#3276
> bug:插件构建打包时，agent有权查询处于构建中的插件信息 #3276

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/dao/PipelineFavorDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/BuildVariableService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/label/PipelineGroupService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/websocket/push/StatusWebsocketPush.kt
websocket status推送单独获取信息，去除权限，模板相关信息
#3113
> feat: websocket卡片页数据源优化 #3113

- src/frontend/devops-nav/src/utils/customRules.js
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/Stages/AtomList.vue
feature: 新建项目，使用特殊字符不能通过校验 issue #3125
> feature: 新建项目，使用特殊字符不能通过校验 issue #3125

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/AtomReleaseService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
bug:插件代码检查开关关闭后，修复置标志位逻辑 #3282
#3282
> bug:插件代码检查开关关闭后，修复置标志位逻辑 #3282

- src/backend/ci/core/dispatch-docker/boot-dispatch-docker/src/main/resources/application.yml
> bug: dispatch-docekr增加suffix配置 #3289

- src/backend/ci/core/common/common-auth/common-auth-v3/src/main/kotlin/com/tencent/devops/common/auth/utlis/AuthUtils.kt
- src/backend/ci/core/common/common-auth/common-auth-v3/src/test/kotlin/com/tencent/devops/common/auth/utlis/AuthUtilsTest.kt
> bug: 权限策略添加对“任意”的处理 #3292

- src/backend/ci/core/common/common-auth/common-auth-v3/src/main/kotlin/com/tencent/devops/common/auth/utlis/AuthUtils.kt
- src/backend/ci/core/common/common-auth/common-auth-v3/src/test/kotlin/com/tencent/devops/common/auth/utlis/AuthUtilsTest.kt
> BUG:权限策略添加对“任意”的处理 #3292

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/ScmFactory.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/ScmOauthFactory.kt
> fix: ScmFactory对svn的region字段不合理的使用 #3288

- src/backend/ci/core/plugin/biz-plugin/src/main/kotlin/com/tencent/devops/plugin/service/git/CodeWebhookService.kt
- src/backend/ci/core/plugin/biz-plugin/src/main/kotlin/com/tencent/devops/plugin/service/git/GitWebhookUnlockService.kt
- src/backend/ci/core/plugin/biz-plugin/src/main/kotlin/com/tencent/devops/plugin/service/git/GitWebhookUnlockServiceImpl.kt
> feature: git增加hook解锁功能 #3131

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/AtomUtils.kt
refactor:兼容管理员在插件未进行大版本升级的情况下就把插件从有编译类型改为无编译类型 #3324
#3324
> refactor:兼容管理员在插件未进行大版本升级的情况下就把插件从有编译类型改为无编译类型 #3324

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineService.kt
feat: websocket卡片页数据源优化 判空优化 #3113
> feat: websocket卡片页数据源优化 判空优化 #3113

- src/backend/ci/core/store/biz-store-sample/src/main/kotlin/com/tencent/devops/store/service/container/impl/SampleContainerServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/container/impl/ContainerServiceImpl.kt
feat:构建资源类型可选操作支持配置化 #3328
#3328
> feat:构建资源类型可选操作支持配置化 #3328

- src/frontend/devops-pipeline/src/components/MiniMap/index.vue
> bugfix: 小地图偶现报错 issue #3334

- src/gateway/core/lua/set_real_ip.lua
> bug: 修复某些情况下set_real_ip无法获取用户真实IP的BUG #3366

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/task/ManualReviewTaskAtom.kt
> bugfix: 人工审核的审核意见未输出到环境变量 #3343

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/task/ManualReviewTaskAtom.kt
> feat:【人工审核】插件能否支持下审核结果输出 #3122

- src/backend/ci/core/common/common-event/src/main/kotlin/com/tencent/devops/common/event/dispatcher/pipeline/mq/MQ.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/pipeline/SubPipelineStatus.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildSubPipelineResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/BuildEndControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/init/PipelineExtendConfiguration.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/listener/run/finish/SubPipelineBuildFinishListener.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStartUpService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStatusService.kt
> chore: 子流水线轮询判断运行状态优化 #2928

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/code/GitWebHookMatcher.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/code/SvnWebHookMatcher.kt
> bug: 代码库事件触发排除路径逻辑bug #1163

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildDetailService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
> bug: 显示资源别名的字段显示错误 #1750

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/enums/BuildStatus.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/ContainerControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/DependOnControl.kt
> bug:"Job依赖"与"何时运行本Job优先级问题" #3336

- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdPartyAgent/UpgradeService.kt
> bugfix: agent版本设置过期问题 #3375

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/constant/ProcessMessageCode.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/view/PipelineViewService.kt
> pref: 视图数量太少，不能自定义排序 #1486

- src/backend/ci/core/sign/api-sign/src/main/kotlin/com/tencent/devops/sign/api/constant/SignMessageCode.kt
- src/backend/ci/core/sign/api-sign/src/main/kotlin/com/tencent/devops/sign/api/pojo/IpaSignInfo.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/impl/SignServiceImpl.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/utils/SignUtils.kt
> pref: iOS重签名逻辑的几个重要优化 #3318

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwQualityResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwQualityResourceV3Impl.kt
- src/backend/ci/core/quality/api-quality/src/main/kotlin/com/tencent/devops/quality/api/v2/ServiceQualityInterceptResource.kt
- src/backend/ci/core/quality/api-quality/src/main/kotlin/com/tencent/devops/quality/api/v2/ServiceQualityRuleResource.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/resources/v2/ServiceQualityInterceptResourceImpl.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/resources/v2/ServiceQualityRuleResourceImpl.kt
> feat: 质量红线openapi #3386

- src/backend/ci/task_shadow_jar.gradle
> chore: worker-agent打包的manifest增加WorkerAgent-Version属性 #3392

- src/backend/ci/core/artifactory/api-artifactory/src/main/kotlin/com/tencent/devops/artifactory/pojo/FileDetailForApp.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/impl/LogServiceESImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/AppRepositoryResourceImpl.kt
> feat: 蓝盾新版APP #2932

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/template/TemplateService.kt
bug:模板勾选推荐版本号后再不勾选保存一个新版本，用这个新版本实例化流水线时还显示推荐版本信息 #3407
#3407
> bug:模板勾选推荐版本号后再不勾选保存一个新版本，用这个新版本实例化流水线时还显示推荐版本信息 #3407

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/BuildStartControl.kt
> bug: 触发器耗时为负数 #3370

- support-files/templates/#etc#ci#application-repository.yml
> bug: 增加tgit配置 #3390

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwCallBackResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwCallBackResourceV3Impl.kt
> feature:流水线webhook管理 #1523

- src/backend/ci/core/sign/api-sign/src/main/kotlin/com/tencent/devops/sign/api/pojo/IpaSignInfo.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/impl/SignServiceImpl.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/utils/SignUtils.kt
> feat: iOS签名服务支持带有watchapp的重签 #3353

- src/frontend/devops-nav/package.json
- src/frontend/devops-pipeline/package.json
- src/frontend/devops-pipeline/src/components/ReviewDialog.vue
feature: 升级 1.2release 的组件库版本 issue #3387
> feature: 升级 1.2release 的组件库版本 issue #3387

- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/ProjectDao.kt
根据项目中文名称获取项目信息， 对应字段已添加索引
#3429
> feat: 通过项目中文名获取项目 #3429

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/pojo/ErrorCode.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/svn/api/SVNApi.kt
- src/backend/ci/core/image/biz-image/src/main/kotlin/com/tencent/devops/image/utils/FileStoreUtils.kt
- src/backend/ci/core/plugin/codecc-plugin/common-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/CodeccApi.kt
- src/backend/ci/core/plugin/codecc-plugin/worker-plugin-codecc/src/main/kotlin/com/tencent/devops/plugin/worker/task/codecc/util/CodeccRepoHelper.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/HeartbeatControl.kt
- src/backend/ci/core/worker/worker-api-sdk/src/main/kotlin/com/tencent/devops/worker/common/api/dispatch/CodeccDownloadResourceApi.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/archive/AtomBuildArchiveTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/archive/BuildPushDockerImageTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/image/MarketCheckImageTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/scm/git/GitUpdateTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
> perf: 内置插件和心跳超时的执行错误信息优化 #2993

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/BuildParams.vue
- src/frontend/devops-pipeline/src/components/Stages/AtomList.vue
> fix: 流水线参数侧滑框布局错乱

- src/frontend/devops-environment/src/views/create_env.vue
- src/frontend/devops-environment/src/views/env_detail.vue
fix: 环境管理导入节点的ip搜索统一为精确匹配 issue #3140
> fix: 环境管理导入节点的ip搜索统一为精确匹配 issue

- src/frontend/devops-pipeline/src/components/AtomFormComponent/DynamicParameter/index.vue
bugfix: 动态参数组件没有实时更新值 issue #3455
> bugfix: 动态参数组件没有实时更新值 issue #3455

- src/frontend/devops-pipeline/src/components/AtomFormComponent/Tips/index.vue
feature: 标签组件支持展示 json 字符串  issue #3459
> feature: 标签组件支持展示 json 字符串  issue #3459

- src/frontend/devops-nav/src/index.html
- src/frontend/devops-nav/src/views/Home.vue
feat: 增加超级管理员请求独立项目接口 issue #3111
> 增加超级管理员请求独立项目接口 #3111

- src/backend/ci/core/auth/biz-auth-blueking/src/main/kotlin/com/tencent/devops/auth/service/BkOrganizationService.kt
> refractor: OrganizationService实现类 #3472

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/StageControl.kt
> feat: stage审核的说明支持变量引用 #3395

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwCallBackResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwCallBackResourceV3Impl.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceCallBackResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserCallBackResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/CreateCallBackResult.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserCallBackResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceCallBackResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/dao/ProjectPipelineCallbackDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/dao/ProjectPipelineCallbackHistoryDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/ProjectPipelineCallBackService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/ProjectPipelineCallBackUrlGenerator.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/ProjectPipelineCallBackUrlGeneratorImpl.kt
> feature: callback增加批量新增接口 #3443

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/enums/PlatformEnum.kt
> feature: 找不到平台统一返回null

- src/frontend/devops-pipeline/src/components/viewPart/index.vue
Reverts Tencent/bk-ci#3151
对二维码以及扩展点展示有影响，先回退
> Revert "流水线查看构件列表列宽支持拖拽调整"

- src/backend/ci/core/common/common-log/src/main/kotlin/com/tencent/devops/common/log/pojo/ILogEvent.kt
- src/backend/ci/core/common/common-log/src/main/kotlin/com/tencent/devops/common/log/pojo/LogBatchEvent.kt
- src/backend/ci/core/common/common-log/src/main/kotlin/com/tencent/devops/common/log/pojo/LogEvent.kt
- src/backend/ci/core/common/common-log/src/main/kotlin/com/tencent/devops/common/log/pojo/LogStatusEvent.kt
> bug: 【流水线】JOB日志缺失，如启动镜像相关的日志 #3493

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildDetailService.kt
详情处理添加对插件类型的判断。 只有研发商店的插件才获取版本信息 #3424
> feat: 详情获取插件版本只对研发商店插件生效 #3424

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildService.kt
详情接口添加buildId,pipelineId匹配校验 #3461
> bug: 流水线详情页添加匹配校验 #3461

- src/backend/ci/core/sign/biz-sign-sample/src/main/kotlin/com/tencent/devops/sign/service/impl/ArchiveServiceImpl.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/impl/SignServiceImpl.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/service/ArchiveService.kt
> feature: sign服务归档ipa的时候可以修改properties数据 #3497

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/CodeGitWebHookTrigger.vue
feature: 多个分支ABCD触发了流水线，并且B分支触发了多次的场景  issue #411
> feature: 多个分支ABCD触发了流水线，并且B分支触发了多次的场景  issue #411

- src/backend/ci/core/worker/worker-agent/src/main/kotlin/com/tencent/devops/agent/AgentVersion.kt
> chore: 修改work-agent版本至12.16 #3490

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomEnvServiceImpl.kt
refactor:插件查询环境信息接口当查询插件不存在时不报错而返回空 #3523
#3523
> refactor:插件查询环境信息接口当查询插件不存在时不报错而返回空 #3523

- src/backend/ci/core/common/common-auth/common-auth-api/src/main/kotlin/com/tencent/devops/common/auth/api/AuthPermission.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/user/UserProjectResource.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/UserProjectResourceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/ProjectService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
- support-files/bkiam/0005_bk_ci_20200623-2120_iam.json
- support-files/bkiam/0006_bk_ci_20200623-2120_iam.json
- support-files/bkiam/0007_bk_ci_20200804-1047_iam.json
> bug: 创建视图页面404 路径 #3519

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineInfoDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineService.kt
> bug: 创建视图页面404 添加校验接口 #3519

- src/backend/ci/core/common/common-service/src/main/java/com/tencent/devops/common/service/Log4j2Initializer.java
> perf: 日志参数改成从配置中读取 #3513

- src/backend/ci/core/worker/worker-api-sdk/src/main/kotlin/com/tencent/devops/worker/common/api/archive/ArchiveResourceApi.kt
- src/backend/ci/core/worker/worker-api-sdk/src/main/kotlin/com/tencent/devops/worker/common/api/report/ReportResourceApi.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/AbstractBuildResourceApi.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/env/AgentEnv.kt
> feature: worker支持从第二网关上传文件 #3508

- src/backend/ci/core/worker/worker-api-sdk/src/main/kotlin/com/tencent/devops/worker/common/api/log/LogResourceApi.kt
> feat: agent 上报日志超时设置 #3546

- src/frontend/devops-pipeline/src/components/createViewDialog/index.vue
- src/frontend/devops-pipeline/src/store/modules/pipelines/pipelinesView.js
- src/frontend/devops-pipeline/src/views/list/view.vue
fix: 企业版创建视图页面404，移除role/list接口，改调用hasPermission/VIEWS_MANAGER issue #3519
> fix: 企业版创建视图页面404

- src/frontend/devops-pipeline/src/App.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/BuildHistoryTab/index.vue
- src/frontend/devops-pipeline/src/components/InfiniteScroll/index.vue
- src/frontend/devops-pipeline/src/components/Stages/AtomList.vue
- src/frontend/devops-pipeline/src/main.js
- src/frontend/devops-pipeline/src/mixins/infinite-scroll-mixin.js
fix: 流水线详情页添加匹配校验, 不匹配时跳回流水线列表页 issue #3461
> fix: 流水线详情页添加匹配校验, 不匹配时跳回流水线列表页

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/scm/CodePullTask.kt
> feature:git内置插件的执行错误信息优化 #3482

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/ScriptEnvUtils.kt
> bug: 拉取代码报“没有那个文件或目录”错误 #3453

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/git/api/GitApi.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/pojo/CommitCheckRequest.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/scm/ServiceScmOauthResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/scm/ServiceScmResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/GitService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/ScmOauthService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/ScmService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/scm/git/GitlabPullCodeSetting.kt
> bug: 去掉日志中输出的token #3588

- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/cron/ManagerUserTimeoutCron.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/UserPermissionService.kt
> bug: 管理员缓存定期同步 #3600

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/label/PipelineGroupService.kt
> 流水线标签分组数量上限调整为10 #3347

- src/backend/ci/core/notify/api-notify/src/main/kotlin/com/tencent/devops/notify/pojo/BaseMessage.kt
> feature: 通知模块添加扩展字段 #3576

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/label/PipelineGroupService.kt
> feature: 流水线标签分组数量上限调整为10 #3347

- .gitignore
- src/gateway/core/lua/auth/auth_gray.lua
- src/gateway/core/lua/util/gray_util.lua
- support-files/templates/gateway#core#lua#init.lua
> feature : 新增codecc灰度网关 #3596

- src/backend/ci/core/misc/model-misc/task_misc_gen_jooq.gradle
> bug:修改misc打包脚本 #3606

- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/config/MiscBuildDataClearConfig.kt
- support-files/templates/#etc#ci#application-misc.yml
bug:修改清理构建流水记录时间配置 #3623
#3623
> bug:修改清理构建流水记录时间配置 #3623

- src/frontend/devops-codecc/src/views/task/detail.vue
- src/frontend/devops-codecc/src/views/task/settings.vue
> del: 去掉总览的管理员和设置的人员权限

- src/gateway/core/backend.conf
- src/gateway/core/error/error.html.handler.conf
> bugfix: 同步最新的gateway代码 #3681

- src/backend/ci/core/common/common-environment-thirdpartyagent/src/main/kotlin/com/tencent/devops/common/environment/agent/AgentGrayUtils.kt
- src/backend/ci/core/environment/api-environment/src/main/kotlin/com/tencent/devops/environment/api/thirdPartyAgent/OpThirdPartyAgentResource.kt
- src/backend/ci/core/environment/api-environment/src/main/kotlin/com/tencent/devops/environment/pojo/thirdPartyAgent/UpdateAgentRequest.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/dao/thirdPartyAgent/ThirdPartyAgentDao.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/resources/thirdPartyAgent/OpThirdPartyAgentResourceImpl.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/slave/SlaveGatewayService.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdPartyAgent/ThirdPartyAgentMgrService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
feature: 内置归档插件写入displayName #3649
> feature: 内置归档插件写入displayName #3649

- src/frontend/devops-pipeline/src/components/ReviewDialog.vue
bugfix: stage 审核自定义变量没有默认值 issue #3619
> bugfix: stage 审核自定义变量没有默认值 issue #3619

- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/es/ESAutoConfiguration.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/es/NormalX509ExtendedTrustManager.kt
> 【release-1.2】feat: 日志模块支持https和账号密码方式访问ES #3618

- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/impl/LogServiceESImpl.kt
> pref: 日志查询排序优化 #3661

- src/backend/ci/core/plugin/biz-plugin/src/main/kotlin/com/tencent/devops/plugin/service/git/CodeWebhookService.kt
> feature: git触发事件回写工蜂需区分MR和MR Accept事件 #3637

- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/utils/ZipUtil.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/dao/SignIpaInfoDao.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/impl/SignServiceImpl.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/utils/SignUtils.kt
>  feat: 签名支持拓展不替换bundle信息 #3636

- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/pojo/RepositoryInfoWithPermission.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepositoryService.kt
> feature: 代码库服务下，支持展示代码库的当前授权人和重置授权 #2787

- src/frontend/devops-atomstore/src/views/edit_atom.vue
- src/frontend/devops-atomstore/src/views/edit_image.vue
- src/frontend/devops-atomstore/src/views/edit_template.vue
- src/frontend/devops-atomstore/src/views/imageProgress.vue
- src/frontend/devops-atomstore/src/views/release_progress.vue
- src/frontend/devops-atomstore/src/views/upgrade_template.vue
- src/frontend/devops-atomstore/src/views/workList/index.vue
- src/frontend/devops-environment/src/components/devops/environment/third-construct-dialog.vue
- src/frontend/devops-ticket/src/views/create_credential.vue
bugfix: 【社区版】前端问题修复 #3706 issue #3706
> bugfix: 【社区版】前端问题修复 #3706 issue #3706

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceReportResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/ReportListDTO.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/TaskReport.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServiceReportResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/ReportService.kt
> feat:提供报告获取接口 #3657

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
> pref: 【流水线插件】执行失败时的日志优化 #3625

- src/gateway/core/backend.conf
> auth通用回调优化 #3654

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/Stages/AtomList.vue
- src/frontend/devops-pipeline/src/components/pipelineList/taskTable/index.vue
- src/frontend/devops-pipeline/src/views/list/newlist.vue
fix: 流水线列表 表格视图，样式错乱 issue #3581
> fix: 流水线列表 表格视图，样式错乱

- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/enums/ProjectChannelCode.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/ProjectDao.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/ServiceProjectResourceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/UserProjectResourceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/ProjectService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
> feat: 项目添加来源通道字段 #3567

- src/backend/ci/core/misc/model-misc/task_misc_gen_jooq.gradle
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/enums/ProjectChannelCode.kt
- src/backend/ci/core/project/biz-project-sample/src/main/kotlin/com/tencent/devops/project/service/SimpleProjectServiceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/ProjectDao.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/ServiceProjectResourceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/UserProjectResourceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/ProjectService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
> feat: 创建项目填充组织信息 #3564

- src/frontend/devops-artifactory/src/views/repo.vue
- src/frontend/devops-atomstore/src/views/edit_atom.vue
- src/frontend/devops-atomstore/src/views/edit_image.vue
- src/frontend/devops-atomstore/src/views/edit_template.vue
- src/frontend/devops-atomstore/src/views/imageProgress.vue
- src/frontend/devops-atomstore/src/views/release_progress.vue
- src/frontend/devops-atomstore/src/views/upgrade_template.vue
- src/frontend/devops-atomstore/src/views/workList/index.vue
- src/frontend/devops-environment/src/components/devops/environment/third-construct-dialog.vue
- src/frontend/devops-ticket/src/views/create_credential.vue
bugfix: 【社区版】前端问题修复 #3706 issue #3706
bugfix: 版本仓库文件预览为空 issue #3718
> [bugfix]版本仓库预览问题修复

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServicePipelineAtomResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/service/ServicePipelineAtomResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineAtomReplaceCronService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineAtomService.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/atom/OpAtomReplaceResource.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/atom/OpAtomReplaceResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/AtomReplaceService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReplaceServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/impl/StoreProjectServiceImpl.kt
refactor:插件替换逻辑优化，默认插件无需判断安装权限 #3634
#3634
> refactor:插件替换逻辑优化，默认插件无需判断安装权限 #3634

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/impl/StoreLogoServiceImpl.kt
bug:svg图片上传无需压缩生成icon #3711
#3711
> bug:svg图片上传无需压缩生成icon #3711

- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/dao/image/ImageDao.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageService.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/MarketImageService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/AtomDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/MarketAtomDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/MarketAtomEnvInfoDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReplaceServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomEnvServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/template/impl/MarketTemplateServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/utils/VersionUtils.kt
bug:store组件下架某些版本下架不了修复 #3710
#3710
> bug:store组件下架某些版本下架不了修复 #3710

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwPipelineWebhookResourceV3.kt
> feature: 增加查询webhook列表的接口,方便定位问题 #3573

- src/frontend/locale/pipeline/zh-CN.json
fix: Stage准入审核倒计时文案优化 issue #3629
> Stage准入审核倒计时文案优化

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/VersionConfig.vue
- src/frontend/devops-pipeline/src/components/Stages/AtomList.vue
fix: 流水线变量类型为布尔值的，构建变量与默认值没有差异也展示了绿色 issue #3509
> fix: 流水线变量类型为布尔值的，构建变量与默认值没有差异也展示了绿色

- src/backend/ci/core/common/common-redis/src/main/kotlin/com/tencent/devops/common/redis/RedisOperation.kt
- src/backend/ci/core/common/common-redis/src/main/kotlin/com/tencent/devops/common/redis/concurrent/SimpleRateLimiter.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/control/VmOperateTaskGenerator.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineBuildService.kt
- 解决存在跳过的插件时，Rebuild可能导致构建机没关闭的问题
- 改变Lock强硬方式，改为使用单位时间内锁数量做限流
>  feat: 引擎核心代码拆分出biz-process业务模块 #3400

- LICENSE.txt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/ContainerControl.kt
> feat: 引擎核心代码拆分出biz-process业务模块 #3400

- src/frontend/devops-pipeline/src/components/AtomFormComponent/DevopsSelect/index.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/Stages/AtomList.vue
feature: 插件的select控件，在接口失败的情况下，没有显示值 issue #3763
> feature: 插件的select控件，在接口失败的情况下，没有显示值 issue #3763

- src/agent/src/pkg/config/version.go
chore: 修改agent版本号为v1.0.9 #3813
> chore: 修改agent版本号为v1.0.9 #3813

- src/backend/ci/boot-assembly/build.gradle
- src/backend/ci/boot-assembly/src/main/kotlin/com/tencent/devops/AssemblyApplication.kt
- src/backend/ci/core/artifactory/boot-artifactory/src/main/kotlin/com/tencent/devops/artifactory/ArtifactoryApplication.kt
- src/backend/ci/core/auth/boot-auth/src/main/kotlin/com/tencent/devops/auth/service/AuthApplication.kt
- src/backend/ci/core/dispatch-docker/boot-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/docker/DispatchDockerApplication.kt
- src/backend/ci/core/dispatch/boot-dispatch/src/main/kotlin/com/tencent/devops/dispatch/DispatchApplication.kt
- src/backend/ci/core/dockerhost/boot-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/DockerhostApplication.kt
- src/backend/ci/core/environment/boot-environment/src/main/kotlin/com/tencent/devops/environment/EnvironmentApplication.kt
- src/backend/ci/core/image/boot-image/src/main/kotlin/com/tencent/devops/image/ImageApplication.kt
- src/backend/ci/core/log/boot-log/src/main/kotlin/com/tencent/devops/log/LogApplication.kt
- src/backend/ci/core/misc/boot-misc/src/main/kotlin/com/tencent/devops/misc/MiscApplication.kt
- src/backend/ci/core/monitoring/boot-monitoring/src/main/kotlin/com/tencent/devops/monitoring/MonitoringApplication.kt
- src/backend/ci/core/notify/boot-notify/src/main/kotlin/com/tencent/devops/notify/NotifyApplication.kt
- src/backend/ci/core/openapi/boot-openapi/src/main/kotlin/com/tencent/devops/openapi/OpenApiApplication.kt
- src/backend/ci/core/plugin/boot-plugin/src/main/kotlin/com/tencent/devops/plugin/PluginApplication.kt
- src/backend/ci/core/process/boot-process/src/main/kotlin/com/tencent/devops/process/ProcessApplication.kt
- src/backend/ci/core/project/boot-project/src/main/kotlin/com/tencent/devops/project/ProjectApplication.kt
- src/backend/ci/core/quality/boot-quality/src/main/kotlin/com/tencent/devops/quality/QualityApplication.kt
- src/backend/ci/core/repository/boot-repository/src/main/kotlin/com/tencent/devops/repository/RepositoryApplication.kt
- src/backend/ci/core/sign/boot-sign/src/main/kotlin/com/tencent/devops/sign/SignApplication.kt
- src/backend/ci/core/store/boot-store/src/main/kotlin/com/tencent/devops/store/StoreApplication.kt
- src/backend/ci/core/ticket/boot-ticket/src/main/kotlin/com/tencent/devops/ticket/TicketApplication.kt
- src/backend/ci/core/websocket/boot-websocket/src/main/kotlin/com/tencent/devops/websocket/WebSocketApplication.kt
- src/backend/detekt.yml
- src/backend/kotlin_code_style.xml
- 调整ApplicationKt命名，让Idea自动检测生成的启动类更清晰
- 调整detekt代码规范配置 
- add kotlin code style xml
> Issue 3793

- src/frontend/devops-pipeline/src/components/pipelineList/extMenu/index.vue
fix:流水线列表表格视图操作面板浮层显示问题  issue #3581
> fix:流水线列表表格视图操作面板浮层显示问题  issue #3581

- src/backend/ci/core/common/common-log/src/main/kotlin/com/tencent/devops/common/log/pojo/message/LogMessage.kt
- src/backend/ci/core/common/common-log/src/main/kotlin/com/tencent/devops/common/log/utils/LogMQEventDispatcher.kt
> pref: 日志服务配置增加单行字符上限 #3837

- src/backend/ci/boot-assembly/src/main/kotlin/com/tencent/devops/AssemblyApplication.kt
- src/backend/ci/core/artifactory/boot-artifactory/src/main/kotlin/com/tencent/devops/artifactory/ArtifactoryApplication.kt
- src/backend/ci/core/auth/boot-auth/src/main/kotlin/com/tencent/devops/auth/service/AuthApplication.kt
- src/backend/ci/core/dispatch-docker/boot-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/docker/DispatchDockerApplication.kt
- src/backend/ci/core/dispatch/boot-dispatch/src/main/kotlin/com/tencent/devops/dispatch/DispatchApplication.kt
- src/backend/ci/core/dockerhost/boot-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/DockerhostApplication.kt
- src/backend/ci/core/environment/boot-environment/src/main/kotlin/com/tencent/devops/environment/EnvironmentApplication.kt
- src/backend/ci/core/image/boot-image/src/main/kotlin/com/tencent/devops/image/ImageApplication.kt
- src/backend/ci/core/log/boot-log/src/main/kotlin/com/tencent/devops/log/LogApplication.kt
- src/backend/ci/core/misc/boot-misc/src/main/kotlin/com/tencent/devops/misc/MiscApplication.kt
- src/backend/ci/core/monitoring/boot-monitoring/src/main/kotlin/com/tencent/devops/monitoring/MonitoringApplication.kt
- src/backend/ci/core/notify/boot-notify/src/main/kotlin/com/tencent/devops/notify/NotifyApplication.kt
- src/backend/ci/core/openapi/boot-openapi/src/main/kotlin/com/tencent/devops/openapi/OpenApiApplication.kt
- src/backend/ci/core/plugin/boot-plugin/src/main/kotlin/com/tencent/devops/plugin/PluginApplication.kt
- src/backend/ci/core/process/boot-process/src/main/kotlin/com/tencent/devops/process/ProcessApplication.kt
- src/backend/ci/core/project/boot-project/src/main/kotlin/com/tencent/devops/project/ProjectApplication.kt
- src/backend/ci/core/quality/boot-quality/src/main/kotlin/com/tencent/devops/quality/QualityApplication.kt
- src/backend/ci/core/repository/boot-repository/src/main/kotlin/com/tencent/devops/repository/RepositoryApplication.kt
- src/backend/ci/core/sign/boot-sign/src/main/kotlin/com/tencent/devops/sign/SignApplication.kt
- src/backend/ci/core/store/boot-store/src/main/kotlin/com/tencent/devops/store/StoreApplication.kt
- src/backend/ci/core/ticket/boot-ticket/src/main/kotlin/com/tencent/devops/ticket/TicketApplication.kt
- src/backend/ci/core/websocket/boot-websocket/src/main/kotlin/com/tencent/devops/websocket/WebSocketApplication.kt
> Issue 3793 rel 1.3

- src/frontend/devops-pipeline/src/components/AtomSelector/index.vue
bugfix: 选择插件界面，偶现不能选择插件问题fix issue #3281
> bugfix: 选择插件界面，偶现不能选择插件问题fix issue #3281

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
> perf: 非插件上报错误统一调整为系统错误 #3704

- src/frontend/devops-pipeline/src/components/atomFormField/RemoteCurlUrl/index.vue
feature: 远程触发curl路径变更 issue #3528
> feature: 远程触发curl路径变更 issue #3528

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/extend/DefaultModelCheckPlugin.kt
> feat: 优化process日志 #3873

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/utils/StoreUtils.kt
- support-files/templates/#etc#ci#application-store.yml
refactor:开源版，研发商店组件logo、文档链接中域名在数据库硬编码，导致用户切换域名后无法查看图片 #3780
#3780
> refactor:开源版，研发商店组件logo、文档链接中域名在数据库硬编码，导致用户切换域名后无法查看图片 #3780

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeTGitScmImpl.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/git/api/GitApi.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/config/GitConfig.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/external/ExternalScmResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/op/OpScmWebhookResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/external/ExternalScmResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/op/OpScmWebhookResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineWebhookService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/webhook/PipelineBuildWebhookService.kt
> feature: tgit webhook请求头增加token字段 #3856

- src/backend/ci/core/process/plugin-trigger/src/main/kotlin/com/tencent/devops/process/plugin/trigger/timer/quartz/QuartzTraceJobListener.kt
> bug: 定时任务增加日志，排查流水线延迟启动原因 #3730

- src/backend/ci/core/ticket/biz-ticket/src/main/kotlin/com/tencent/devops/ticket/service/CredentialServiceImpl.kt
> bug: 凭证别名为空时，无法创建凭证 #3849

- src/backend/ci/core/common/common-service/src/main/resources/common-service.properties
> depend: SpringBoot版本升级 #2656

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/engine/common/Timeout.kt
> feat: Stage审核时间改为30天 #3779

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/code/git/GitTagPushEvent.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/code/GitWebHookMatcher.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/code/GitWebHookStartParam.kt
> fix: “Job依赖”与“何时运行本Job”优先级问题 #3850

- src/backend/ci/core/misc/api-misc/src/main/kotlin/com/tencent/devops/misc/pojo/project/ProjectDataClearConfig.kt
- src/backend/ci/core/misc/api-misc/src/main/kotlin/com/tencent/devops/misc/pojo/project/ProjectInfo.kt
- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/cron/process/PipelineBuildHistoryDataClearJob.kt
- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/dao/process/ProcessDataClearDao.kt
- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/dao/project/ProjectDao.kt
- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/service/project/BsProjectDataClearConfigService.kt
- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/service/project/CodeccProjectDataClearConfigService.kt
- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/service/project/ProjectDataClearConfigFactory.kt
- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/service/project/ProjectDataClearConfigService.kt
- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/service/project/ProjectDataClearConfigTemplateService.kt
- support-files/templates/#etc#ci#application-misc.yml
feat: 细化定期归档流水线构建历史记录的策略 #3891
#3891
> feat: 细化定期归档流水线构建历史记录的策略 #3891

- src/backend/ci/core/sign/biz-sign/build.gradle
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/impl/FileServiceImpl.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/service/SignInfoService.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/utils/SignUtils.kt
支持unity新版本的内嵌framework目录重签 #3785
> feat: 支持unity新版本的内嵌framework目录重签 #3785

- src/backend/ci/build.gradle
- src/backend/ci/core/auth/biz-auth-blueking/src/main/kotlin/com/tencent/devops/auth/service/ResourceService.kt
- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/ApiUtil.kt
- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/DHUtil.kt
- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/HashUtil.kt
- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/OwnerUtils.kt
- src/backend/ci/core/common/common-event/src/main/kotlin/com/tencent/devops/common/event/pojo/pipeline/IPipelineEvent.kt
- src/backend/ci/core/common/common-log/src/main/kotlin/com/tencent/devops/common/log/Ansi.kt
- src/backend/ci/core/common/common-log/src/main/kotlin/com/tencent/devops/common/log/pojo/ILogEvent.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/utils/SkipElementUtils.kt
- src/backend/ci/core/common/common-redis/src/main/kotlin/com/tencent/devops/common/redis/RedisLock.kt
- src/backend/ci/core/common/common-redis/src/main/kotlin/com/tencent/devops/common/redis/RedisLockByValue.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/utils/code/github/GithubUtils.kt
- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/MicroServiceApplication.kt
- src/backend/ci/core/common/common-websocket/src/main/kotlin/com/tencent/devops/common/websocket/dispatch/message/SendMessage.kt
- src/backend/ci/core/common/common-websocket/src/main/kotlin/com/tencent/devops/common/websocket/dispatch/push/TransferPush.kt
- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/utils/RandomUtil.kt
- src/backend/ci/core/image/biz-image/src/main/kotlin/com/tencent/devops/image/utils/FileStoreUtils.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/mq/ProjectBroadCastEvent.kt
- src/backend/ci/core/quality/api-quality/src/main/kotlin/com/tencent/devops/quality/api/v2/pojo/ControlPointPosition.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/util/ThresholdOperationUtil.kt
- src/backend/ci/detekt.gradle
- src/backend/detekt.yml
> docs: 补充开源文档 #3793

- src/frontend/devops-pipeline/src/views/list/index.vue
> feature: 视图问题优化 issue #3085

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/NormalAtom.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/NormalAtomV2.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/atomMixin.js
- src/frontend/devops-pipeline/src/scss/devops-common.scss
- src/frontend/devops-pipeline/src/store/modules/atom/atomUtil.js
- src/frontend/devops-pipeline/src/store/modules/atom/getters.js
- src/frontend/devops-pipeline/src/store/modules/atom/index.js
- src/frontend/devops-pipeline/src/store/modules/atom/mutations.js
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
feature: 切换插件版本时，新版本中新增的参数、修改类型的参数需高亮，给出风险提示 issue #3362
> feature: 切换插件版本时，新版本中新增的参数、修改类型的参数需高亮，给出风险提示 issue #3362

- src/frontend/devops-atomstore/src/views/market/index.vue
bugfix: 研发商店首页左侧样式 issue #3771
> bugfix: 研发商店首页左侧样式 issue #3771

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/Stages/AtomList.vue
- src/frontend/devops-pipeline/src/views/list/group.vue
> 流水线标签长度限制修改 

- src/frontend/devops-pipeline/src/views/list/group.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
fix: 流水线标签长度开放为20个字符 issue #3945
> 流水线标签长度开放为20个字符

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/Stages/AtomList.vue
- src/frontend/devops-pipeline/src/components/pipelineSetting/BaseInfo.vue
- src/frontend/devops-pipeline/src/components/pipelineSetting/settingBase/index.vue
- src/frontend/locale/pipeline/zh-CN.json
> 流水线标签文案应统一

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
> bug: 插件执行结束的日志打印问题 #3883

- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/service/AsyncSignService.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/utils/SignUtils.kt
> feat: 签名模块解压缩工具的优化 #3939

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineListFacadeService.kt
> feature: 流水线列表接口新增过滤没有权限流水线字段 #3876

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
feat:安装模版到项目/模版实例化时，自动安装模版中需安装的容器镜像 #3756
#3756
> feat:安装模版到项目/模版实例化时，自动安装模版中需安装的容器镜像 #3756

- src/frontend/devops-pipeline/src/views/list/audit.vue
feature: 流水线增加操作审计功能,隐藏fail状态过滤 issue #672
> feature: 流水线增加操作审计功能,隐藏fail状态过滤 issue #672

- support-files/sql/2004_ci_project-update_v1.2_mysql.sql
- support-files/sql/2004_ci_project-update_v1.4_mysql.sql
> feat: 请求服务支持consul tags路由 #3815

- src/frontend/devops-pipeline/src/views/subpages/exec_detail.vue
bug: 流水线详情申请权限请求参数错误 issue #3999
> bug: 流水线详情申请权限请求参数错误 issue #3999

- src/backend/ci/core/log/biz-log-sample/src/main/kotlin/com/tencent/devops/log/service/impl/V3LogPermissionService.kt
> bug: 他人创建的项目下流水线日志报无权限 #3991

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/template/service/PipelineTemplateService.kt
> bug:模板对已安装插件判断优化 #4006

- src/frontend/devops-nav/src/views/ProjectManage.vue
feat: 移除项目管理页面项目名称的点击效果 issue #3821
> 移除项目管理页面项目名称的点击效果

- src/frontend/devops-pipeline/webpack.config.js
feature: atom-ace-editor组件支持[lua|rust|typescript|kotlin] 语法高亮
> feature: atom-ace-editor组件增加kotlin支持[lua|rust|typescript|kotlin] #3928

- src/backend/ci/check.yml
- src/backend/ci/core/sign/biz-sign-sample/src/main/kotlin/com/tencent/devops/sign/service/impl/ArchiveServiceImpl.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/impl/SignServiceImpl.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/jmx/SignBean.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/service/AsyncSignService.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/service/SignService.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/utils/SignUtils.kt
> pref: 签名模块优化与增加业务指标采集 #3960

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/OkhttpUtils.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineAtomReplaceCronService.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/atom/AtomReplaceParamConvertRequest.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/common/StoreProjectRelDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/impl/StoreProjectServiceImpl.kt
feat: 插件替换工具支持参数的自定义转换功能 #3953
#3953
> feat: 插件替换工具支持参数的自定义转换功能 #3953

- src/gateway/core/lua/util/gray_util.lua
- src/gateway/core/lua/util/tag_util.lua
> ci网关去掉老的灰度逻辑 ,codecc预埋新的tag逻辑 #4041
