TencentBlueKing/bk-ci

- src/frontend/devops-pipeline/src/components/pipelineList/PipelineTemplatePopup/index.vue
bug: 【1.3】流水线新建重名无提示 issue #4045
> bug: 【1.3】流水线新建重名无提示 issue #4045

- src/frontend/devops-pipeline/src/components/pipelineList/PipelineTemplatePopup/index.vue
> bug: 流水线新建重名无提示 issue #4045

- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/ResourceService.kt
只有默认系统才校验project相关传参，以访第三方接入系统权限模型不同导致的异常
> feat: 调整权限中心回调校验 #4029

- src/backend/ci/core/common/common-client/src/main/kotlin/com/tencent/devops/common/client/consul/ConsulConstants.kt
> feat: 增加CodeCC consul相关的op接口 #4051

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/EnvUtils.kt
- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/ReplacementUtils.kt
- src/backend/ci/core/common/common-api/src/test/kotlin/com/tencent/devops/common/api/util/EnvUtilTest.kt
- src/backend/ci/core/common/common-api/src/test/kotlin/com/tencent/devops/common/api/util/ReplacementUtilsTest.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/ScriptTask.kt
feat: GITCI2.0-流水线支持Variables和项目级settings，支持双花括号引用 #4063
> feat: GITCI2.0-流水线支持Variables和项目级settings，支持双花括号引用 #4063

- src/frontend/devops-pipeline/src/components/pipelineList/PipelineTemplatePopup/index.vue
fix: 新建流水线未自动聚焦input框 issue #3820
> 修复新建流水线未自动聚焦input框

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/CodeGitlabWebHookTrigger.vue
> feat: bk-ci gitlab插件支持监听指定的事件 issue #3664

- src/frontend/devops-atomstore/src/components/common/card/index.vue
- src/frontend/devops-atomstore/src/components/common/detail-info/atom.vue
- src/frontend/devops-atomstore/src/components/manage/over-view/trend/atom.vue
- src/frontend/devops-atomstore/src/views/market/detail.vue
- src/frontend/devops-atomstore/src/views/market/home.vue
- src/frontend/devops-atomstore/src/views/market/list.vue
> feature: 热度定义 issue #1855

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/TaskDaemon.kt
> pref: 优化构建机侧worker-Agent的任务管理 #3769

- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/impl/SignServiceImpl.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/IosUtils.kt
> feat: sign需要解析得到应用名 #4058

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/option/JobControlOption.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/control/ControlUtils.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/CheckInterruptStageCmd.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/StartContainerStageCmd.kt
> feat: job支持失败继续 #4095

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/ElementAdditionalOptions.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/ITask.kt
> feat: 插件支持自定义环境变量 #4093

- src/frontend/devops-pipeline/package.json
- src/frontend/devops-pipeline/src/components/ExecDetail/log/jobLog.vue
- src/frontend/devops-pipeline/src/components/ExecDetail/log/pluginLog.vue
- src/frontend/devops-pipeline/src/store/modules/atom/actions.js
feature: 支持默认不展示debug日志，可手动打开 issue #1934
> feature: 支持默认不展示debug日志，可手动打开 issue #1934

- src/frontend/devops-atomstore/src/store/index.js
- src/frontend/devops-atomstore/src/views/manage/setting/member-setting.vue
feature: 插件支持修改调式项目 issue #1975
> feature: 插件支持修改调式项目 issue #1975

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/expression/EvalExpress.kt
- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/expression/ExpressionException.kt
- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/expression/GrammarAnalysis.kt
- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/expression/GrammarAnalysisFinishedException.kt
- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/expression/Lex.kt
- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/expression/SemanticAnalysis.kt
- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/expression/Word.kt
- src/backend/ci/core/common/common-api/src/test/kotlin/com/tencent/devops/common/api/expression/GrammarAnalysisTest.kt
- src/backend/ci/core/common/common-api/src/test/kotlin/com/tencent/devops/common/api/expression/SemanticAnalysisTest.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/control/ControlUtils.kt
- src/backend/ci/core/process/biz-base/src/test/kotlin/com/tencent/devops/process/engine/control/ControlUtilsTest.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/CheckConditionalSkipContainerCmd.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/StartActionTaskContainerCmd.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/CheckConditionalSkipStageCmd.kt
feat:stage/job/task支持自定义表达式执行 #4067
> feat:stage/job/task支持自定义表达式执行 #4067

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/control/ControlUtils.kt
feat:stage/job/task支持自定义表达式执行 #4067
> feat:stage/job/task支持自定义表达式执行 #4067 

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildCancelControl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildStartControl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/UpdateStateForStageCmdFinally.kt
> bug: 部分情况下流水线执行历史会错乱 #4074 

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/OkhttpUtils.kt
> bug: gitlab获取文件内容失败 #4140

- src/frontend/devops-pipeline/src/mixins/pipeline-operate-mixin.js
- src/frontend/devops-pipeline/src/views/list/index.vue
bugfix: 标签管理、模板管理等页面url进入的是流水线列表页 issue:4141
> bugfix: 标签管理、模板管理等页面url进入的是流水线列表页 issue:4141

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/BatScriptUtil.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/CommandLineUtils.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/ShellUtil.kt
feat: 根据输出日志::set-variable name=<my-var-1>::<my-var-value-1> ，刷新变量 #4123
> feat: 根据输出日志::set-variable name=<my-var-1>::<my-var-value-1> ，刷新变量 #4123

- src/backend/ci/core/environment/api-environment/src/main/kotlin/com/tencent/devops/environment/pojo/EnvCreateInfo.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/resources/UserEnvironmentResourceImpl.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/node/ExistNodeEnvCreatorImpl.kt
feat: 环境管理-创建环境时可以不关联node #4118
> feat: 环境管理-创建环境时可以不关联node #4118

- src/agent/go.mod
fix: 修复go依赖问题导致agent无法构建的问题 #4146
> fix: 修复go依赖问题导致agent无法构建的问题 #4146

- src/frontend/devops-codecc/mock/ajax/util.js
- src/frontend/devops-nav/src/utils/bsWebSocket.js
- src/frontend/devops-pipeline/src/components/AtomFormComponent/mixins.js
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/RemoteAtom.vue
- src/frontend/devops-pipeline/src/store/modules/soda/list.js
- src/frontend/devops-pipeline/src/views/subpages/history.vue
- src/frontend/devops-pipeline/src/views/subpages/index.vue
bug: 访问模板流水线后无法正常导入 issue #4116
feature: 流水线插件能获取到pipelineId issue #4115
> 访问模板流水线后无法正常导入

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
fix: 去掉未支持质量红线相关插件入口 issue #3822
> 去掉未支持质量红线相关插件入口

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/constant/CommonMessageCode.kt
- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/OkhttpUtils.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/GitService.kt
> feature: 限制获取代码库文件内容大小不能超过1M #4152

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwMarketTemplateResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwMarketTemplateResourceV3Impl.kt
> api: 安装模板至指定项目 #4158

- support-files/templates/#etc#ci#application-misc.yml
> bug:补充开源版缺失配置 #4174

- src/backend/ci/core/artifactory/boot-artifactory/src/main/resources/application.yml
- src/backend/ci/core/auth/boot-auth/src/main/resources/application.yml
- src/backend/ci/core/dispatch-docker/boot-dispatch-docker/src/main/resources/application.yml
- src/backend/ci/core/dispatch/boot-dispatch/src/main/resources/application.yml
- src/backend/ci/core/dockerhost/boot-dockerhost/src/main/resources/application.yml
- src/backend/ci/core/environment/boot-environment/src/main/resources/application.yml
- src/backend/ci/core/image/boot-image/src/main/resources/application.yml
- src/backend/ci/core/log/boot-log/src/main/resources/application.yml
- src/backend/ci/core/misc/boot-misc/src/main/resources/application.yml
- src/backend/ci/core/monitoring/boot-monitoring/src/main/resources/application.yml
- src/backend/ci/core/notify/boot-notify/src/main/resources/application.yml
- src/backend/ci/core/openapi/boot-openapi/src/main/resources/application.yml
- src/backend/ci/core/plugin/boot-plugin/src/main/resources/application.yml
- src/backend/ci/core/process/boot-engine/src/main/resources/application.yml
- src/backend/ci/core/process/boot-process/src/main/resources/application.yml
- src/backend/ci/core/project/boot-project/src/main/resources/application.yml
- src/backend/ci/core/quality/boot-quality/src/main/resources/application.yml
- src/backend/ci/core/repository/boot-repository/src/main/resources/application.yml
- src/backend/ci/core/sign/boot-sign/src/main/resources/application.yml
- src/backend/ci/core/store/boot-store/src/main/resources/application.yml
- src/backend/ci/core/ticket/boot-ticket/src/main/resources/application.yml
- src/backend/ci/core/websocket/boot-websocket/src/main/resources/application.yml
- support-files/templates/#etc#ci#common.yml
> bug: spring.main.allow-bean-definition-overriding 默认为false #4175

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/Element.kt
- src/backend/ci/core/common/common-pipeline/src/test/kotlin/com/tencent/devops/common/pipeline/pojo/element/ElementTest.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/context/StartBuildContext.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineElementService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
解决Stage重试时，之前因为失败而跳过的状态也能进行重试。
> feat: finally stage #3138

- src/gateway/core/backend.conf
- src/gateway/core/lua/lua_format.ini
- src/gateway/core/nginx.conf
> feat: 网关新增外部组织标识 #4199

- .github/workflows/release.yml
- scripts/bk-ci-connect-bkce.sh
- scripts/bk-ci-gen-docker-conf.sh
- scripts/bk-ci-gen-jrezip.sh
- scripts/bk-ci-init-bkce.sh
- scripts/bk-ci-install.sh
- scripts/bk-ci-reg-cmdb-topo.sh
- scripts/bk-ci-reg-paas-app.sh
- scripts/bk-ci-reg-systemd.sh
- scripts/bk-ci-setup.sh
- scripts/bk-ci-slim.sh
- scripts/bk-ci-start-pre.sh
- scripts/bk-ci-start.sh
- scripts/bk-ci-unreg-paas-app.sh
- scripts/bk-ci-unreg-systemd.sh
- scripts/bk-ci-upgrade.sh
- scripts/bk-ci-utils-https.sh
> chore: 部署体验优化 #4193

- src/frontend/devops-atomstore/package.json
- src/frontend/devops-nav/package.json
- src/frontend/devops-pipeline/package.json
- src/frontend/devops-pipeline/src/scss/pipelineStatus.scss
feat: [Vulnerable] npm package version update issue #4182
> feat: [Vulnerable] npm package version update issue #4182

- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/utils/MessageCodeUtil.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineAtomRollBackCronService.kt
> bug：插件替换回滚异常兼容处理 #4156

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/CodeGitlabWebHookTriggerElement.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/code/GitlabWebhookElementParams.kt
> feature: 希望 bk-ci gitlab插件可以支持监听指定的事件 #3664

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/ScriptTask.kt
> feat: bash插件异常退出，红线没输出自定义指标 #4186

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/BuildFormProperty.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/IScm.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeGitScmImpl.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeGitScmOauthImpl.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeGitlabScmImpl.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeSvnScmImpl.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeTGitScmImpl.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/git/api/GitApi.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserScmResource.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/CodeService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/scm/ScmProxyService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserScmResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/ParamFacadeService.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/scm/ServiceScmOauthResource.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/scm/ServiceScmResource.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/scm/ServiceScmOauthResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/scm/ServiceScmResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/IScmOauthService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/IScmService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/ScmOauthService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/ScmService.kt
> feature: 流水线变量 Git 分支选择应当优先拉取最近修改过的分支 #1546

- src/frontend/devops-pipeline/src/components/AtomFormComponent/Tips/index.vue
bug: tip组件显示对象string，保留原格式 #4162
> bug: tip组件显示对象string，保留原格式 #4162

- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/pojo/enums/SystemEnums.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsOpProjectServiceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/DefaultOpProjectServiceImpl.kt
> feat: 设置灰度支持扩展 #4148

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwRepositoryResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwRepositoryResourceV3Impl.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/ServiceRepositoryResource.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/ServiceRepositoryResourceImpl.kt
> feature: 补齐代码库服务的V3版openAPI #4081

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwBuildResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwBuildResourceV3Impl.kt
Stage审核的OpenAPI接口缺少参数 ，增加重试接口 #4207
> bug: Stage审核的OpenAPI接口缺少参数 #4207

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildMonitorControl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/TaskControl.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/engine/impl/EngineBuildResourceApi.kt
- src/backend/ci/core/worker/worker-common/src/main/resources/logback.xml
> bug: stage STAGE_SUCCESS状态在超时监控未排除 #4209

- src/gateway/core/lua/agent_update.lua
- src/gateway/core/vhosts/devops.backend.special.conf
- src/gateway/core/vhosts/devops.proxy.conf
- src/gateway/core/vhosts/devops.static.conf
- support-files/templates/gateway#core#devops.server.conf
- support-files/templates/gateway#core#lua#init.lua
>  构建机agent部署启动优化 #3707

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/StartActionTaskContainerCmd.kt
bug: stage STAGE_SUCCESS状态在超时监控未排除 #4209
> bug: stage STAGE_SUCCESS状态在超时监控未排除 #4209 

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/impl/NodeJsAtomTargetHandleServiceImpl.kt
perf:执行nodejs插件插件的node版本问题优化 #3894
#3894
> perf:执行nodejs插件插件的node版本问题优化 #3894

- src/frontend/devops-pipeline/src/components/atomFormField/RequestSelector/index.vue
- src/frontend/devops-pipeline/src/components/atomFormField/Selector/index.vue
- src/frontend/devops-pipeline/src/components/atomFormField/atomFieldMixin.js
feature: 流水线变量 Git 分支支持实时搜索 issue #1546
> feature: 流水线变量 Git 分支支持实时搜索 issue #1546

- src/backend/ci/build.gradle.kts
> feature: gradle使用kts替换groovy #3918

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/constant/CommonMessageCode.kt
- src/gateway/core/vhosts/devops.static.conf
> 构建机agent部署启动优化 #3707

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineStageService.kt
> bug: Stage审核的流水线运行构建计数的漏洞 #4255

- src/backend/ci/build.gradle.kts
- src/backend/ci/buildSrc/src/main/kotlin/Versions.kt
- src/backend/ci/core/log/biz-log/build.gradle.kts
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/IndexService.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/impl/LogServiceESImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/impl/LogServiceLuceneImpl.kt
- src/backend/ci/core/log/biz-log/src/test/kotlin/com/tencent/devops/log/util/IndexNameUtilsTest.kt
> feat: 日志模块的关键日志输出 #4265 

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/agent/ManualReviewUserTaskElement.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/atom/ManualReviewParam.kt
> feat: 人工审核插件自定义参数显示优化 #4180

- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/IndexService.kt
日志模块的关键日志输出 #4265 获取索引的redis锁细分为每个构建
> feat: 日志模块的关键日志输出 #4265 获取索引的redis锁细分为每个构建

- src/frontend/devops-pipeline/src/components/AtomFormComponent/DefineParam/index.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/ManualReviewUserTask.vue
- src/frontend/devops-pipeline/src/components/Stages/CheckAtomDialog.vue
- src/frontend/devops-pipeline/src/components/atomFormField/VuexInput/index.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
feat: 人工审核，自定义参数显示优化 issue #4180
> feat: 人工审核，自定义参数显示优化

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/EnvUtils.kt
- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/ReplacementUtils.kt
- src/backend/ci/core/common/common-api/src/test/kotlin/com/tencent/devops/common/api/util/EnvUtilTest.kt
- src/backend/ci/core/common/common-api/src/test/kotlin/com/tencent/devops/common/api/util/ReplacementUtilsTest.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildExtService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineVMBuildService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/init/PipelineServiceConfigure.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineBuildExtServiceImpl.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineContextService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/CheckConditionalSkipContainerCmd.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/StartActionTaskContainerCmd.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/CheckConditionalSkipStageCmd.kt
- src/backend/ci/core/worker/worker-agent/src/main/kotlin/com/tencent/devops/agent/runner/WorkRunner.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Constants.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/engine/EngineBuildSDKApi.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/engine/impl/EngineBuildResourceApi.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/EngineService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/IAtom.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/ICommand.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/bat/CommandBatImpl.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/shell/CommandShellImpl.kt
> feat:支持上下文功能 #4179

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/git/api/GitApi.kt
> bug: gitlab获取分支列表报错 #4282

- src/backend/ci/core/log/biz-log-sample/src/main/kotlin/com/tencent/devops/log/service/impl/BluekingLogPermissionService.kt
- src/backend/ci/core/log/biz-log-sample/src/main/kotlin/com/tencent/devops/log/service/impl/SimpleLogPermissionService.kt
- src/backend/ci/core/log/biz-log-sample/src/main/kotlin/com/tencent/devops/log/service/impl/V3LogPermissionService.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/resources/UserLogResourceImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/LogPermissionService.kt
- src/backend/ci/core/ticket/biz-ticket/src/main/kotlin/com/tencent/devops/ticket/service/CredentialServiceImpl.kt
1. Log内权限校验接口提供permission类型的扩展。支持不同permission的权限校验
> feat: Log权限校验支持提供action #4286

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineContextService.kt
> feat: 上下文增加对凭证ID的引用 #4288

- README.md
- README_EN.md
Signed-off-by: Chengwei Yang <yangchengwei@qiyi.com>
> fix: delete wiki since it hasn't been enabled for this project #4294

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwBuildResourceV3.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/BuildHistoryWithVars.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> feat: 获取构建状态OpenAPI增加stageStatus等信息 #4295

- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/configuration/LogMQConfiguration.kt
> perf: 日志模块MQ消费者数量可用启动参数控制 #4190

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/utils/PipelineConstants.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineContextService.kt
> bugfix: 流水线上下文调整 #4306

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineAtomReplaceCronService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineAtomRollBackCronService.kt
bug:流水线修改后model中的latestVersion和T_PIPELINE_INFO的version不一致会影响部分业务逻辑 #4296
#4296
> bug:流水线修改后model中的latestVersion和T_PIPELINE_INFO的version不一致会影响部分业务逻辑 #4296

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/StartActionTaskContainerCmd.kt
> feat: 私有构建机Agent异常判定的优先级高于“失败时继续” #4301

- src/frontend/devops-pipeline/src/components/viewPart/index.vue
- src/frontend/devops-pipeline/src/store/modules/soda/pipeline.js
bug: 流水线的构件路径带#号会出现问题 issue #4210
> bug: 流水线的构件路径带#号会出现问题 issue #4210

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/expression/EvalExpress.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/CommandLineUtils.kt
feat: 上下文增加::set-output替换 #4310
> feat: 上下文增加::set-output替换 #4310

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/ElementAdditionalOptions.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineContextService.kt
> bugfix: 统一上下文缺少流水线ID变量 #4322

- support-files/templates/#etc#ci#application-sign.yml
> chore: 增加sign服务的部署配置 #4329

- README.md
- README_EN.md
- scripts/bkenv.properties
- src/frontend/devops-artifactory/src/views/depot/image-library.vue
- src/frontend/devops-artifactory/src/views/depot/project-image.vue
- src/frontend/devops-atomstore/src/views/edit_atom.vue
- src/frontend/devops-atomstore/src/views/edit_image.vue
- src/frontend/devops-atomstore/src/views/edit_template.vue
- src/frontend/devops-atomstore/src/views/imageProgress.vue
- src/frontend/devops-atomstore/src/views/release_progress.vue
- src/frontend/devops-atomstore/src/views/upgrade_template.vue
- src/frontend/devops-atomstore/src/views/workList/index.vue
- src/frontend/devops-environment/src/components/devops/environment/third-construct-dialog.vue
- src/frontend/devops-ticket/src/views/create_credential.vue
新版文档中心上线：https://docs.bkci.net
> feat: 上线文档官网 #4333

- src/backend/ci/core/common/common-dispatch-sdk/src/main/kotlin/com/tencent/devops/common/dispatch.sdk/service/DispatchService.kt
bug: 修复dispatch-sdk中redis过期时间错误问题 #4350
> bug: 修复dispatch-sdk中redis过期时间错误问题 #4350

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/enums/BuildStatus.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/utils/BuildStatusSwitcher.kt
- src/backend/ci/core/common/common-pipeline/src/test/kotlin/com/tencent/devops/common/pipeline/utils/BuildStatusSwitcherTest.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineStatusService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildCancelControl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildEndControl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/MutexControl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/UpdateStateForStageCmdFinally.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineListFacadeService.kt
- src/backend/ci/core/worker/worker-agent/src/main/kotlin/com/tencent/devops/agent/AgentVersion.kt
- src/backend/ci/core/worker/worker-agent/src/main/kotlin/com/tencent/devops/agent/Application.kt
- src/backend/ci/core/worker/worker-agent/src/test/kotlin/com/tencent/devops/worker/common/utils/WorkspaceUtilsTest.kt
- src/backend/ci/core/worker/worker-agent/workspace/p-abcdefghijklmnopqrstuvwxyz123456/src/workspace.txt
> feat: 规范化Pipeline/Stage/Job/Task的构建状态 #4315

- src/frontend/devops-pipeline/src/views/list/index.vue
- src/frontend/devops-pipeline/src/views/subpages/index.vue
feat: 修复bk-tab样式错误 issue #4300
> feat: 修复bk-tab样式错误 issue #4300

- .github/workflows/release.yml
- scripts/bk-ci-install.sh
- scripts/bk-ci-reg-systemd.sh
- scripts/bk-ci-start.sh
- scripts/bk-ci-upgrade.sh
- scripts/packager-ci.sh
chore: 部署体验优化 #4193
提供出包脚本. 修正一些部署问题.
> chore: 部署体验优化 #4193 提供出包脚本. 修正一些部署问题 

- src/backend/ci/core/artifactory/api-artifactory/src/main/kotlin/com/tencent/devops/artifactory/api/service/ServiceArtifactoryResource.kt
- src/backend/ci/core/artifactory/biz-artifactory-sample/src/main/kotlin/com/tencent/devops/artifactory/resources/ServiceArtifactoryResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/app/AppBuildService.kt
> feat: 文件查询接口升级 #4320

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/utils/BuildStatusSwitcher.kt
- src/backend/ci/core/common/common-pipeline/src/test/kotlin/com/tencent/devops/common/pipeline/utils/BuildStatusSwitcherTest.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/StartActionTaskContainerCmd.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/StartContainerStageCmd.kt
> 针对第三方构建集群的调度超时的状态处理

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
bug: ci.token在插件市场插件参数中未能替换 #4385
> bug: ci.token在插件市场插件参数中未能替换 #4385

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/utils/BuildStatusSwitcher.kt
- src/backend/ci/core/common/common-pipeline/src/test/kotlin/com/tencent/devops/common/pipeline/utils/BuildStatusSwitcherTest.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineStatusService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/StartActionTaskContainerCmd.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/StartContainerStageCmd.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineListFacadeService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/BatScriptUtil.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/WorkspaceUtils.kt
> Issue 4315

- src/frontend/devops-nav/src/index.html
> feat: 首页增加版本号显示 issue #4300

- src/frontend/devops-pipeline/src/store/modules/atom/actions.js
- src/frontend/devops-pipeline/src/views/list/atomManage.vue
feature: 项目下已安装的插件列表，支持分页 issue #3869
> feature: 项目下已安装的插件列表，支持分页 issue #3869

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildQualityService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/utils/QualityUtils.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/quality/QualityGateInTaskAtom.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/quality/QualityGateOutTaskAtom.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleCheckService.kt
> feat: 质量红线希望可以支持通过流水线变量指定审核人和通知人 #4167

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityIndicatorService.kt
> feat: 增加一些红线配置项 #4401

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/utils/BuildStatusSwitcher.kt
- src/backend/ci/core/common/common-pipeline/src/test/kotlin/com/tencent/devops/common/pipeline/utils/BuildStatusSwitcherTest.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/control/VmOperateTaskGenerator.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/TaskAtomService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/TaskControl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/listener/run/PipelineTaskPauseListener.kt
- src/backend/ci/core/process/biz-engine/src/test/kotlin/com/tencent/devops/process/engine/control/DependOnControlTest.kt
- src/backend/ci/core/process/biz-engine/src/test/kotlin/com/tencent/devops/process/engine/control/VmOperateTaskGeneratorTest.kt
- src/backend/ci/core/process/biz-engine/src/test/kotlin/com/tencent/devops/process/engine/utils/TestTool.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelinePauseBuildFacadeService.kt
- src/backend/ci/core/worker/worker-agent/src/main/kotlin/com/tencent/devops/agent/AgentVersion.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Runner.kt
> 完善用户取消与系统强制终止的状态区别 #4420 

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/expression/Lex.kt
> bug: if表达式支持变量名中带横线- #4430

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/expression/EvalExpress.kt
feat: if表达式支持带与不带${{}}的情况 #4432
> feat: if表达式支持带与不带${{}}的情况 #4432

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/template/TemplatePipelineDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
> bug：按版本删除模板bug修复 #4440

- support-files/templates/gateway#core#devops.server.conf
> bugfix: 修复"构建已结束"提醒 #4389

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Runner.kt
> bug: mr触发时，提交人没有项目权限，导致无法获取settings下的凭证 #4393

- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageService.kt
- src/backend/ci/core/store/biz-store-sample/src/main/kotlin/com/tencent/devops/store/service/common/impl/SampleStoreUserServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/impl/StoreTotalStatisticServiceImpl.kt
feat:插件概览页增加权限管理，非插件成员不能查看概览 #3994
#3994
> feat:插件概览页增加权限管理，非插件成员不能查看概览 #3994

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/cron/QualityHisMetadataJob.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/dao/v2/QualityHisMetadataDao.kt
- support-files/sql/2007_ci_quality-update_v1.6_mysql.sql
> feat: 增加红线构建数据，定时清理逻辑 #4459

- src/backend/ci/core/plugin/biz-plugin/src/main/kotlin/com/tencent/devops/plugin/utils/QualityUtils.kt
> bug: 红线mr页面支持v3插件跳转 #4464

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwPipelineGroupResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwPipelineGroupResourceV3Impl.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServicePipelineGroupResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServicePipelineGroupResourceImpl.kt
> OpenAPI：添加标签(组)增删改的接口 #4262

- src/frontend/devops-nav/package.json
- src/frontend/devops-nav/src/router/index.ts
refactor: 锁定vue-router版本号 3.5.2
> refactor: 锁定vue-router版本号 issue #4492

- src/backend/ci/core/store/api-store-image/src/main/kotlin/com/tencent/devops/store/api/image/user/UserImageReleaseResource.kt
- src/backend/ci/core/store/api-store-image/src/main/kotlin/com/tencent/devops/store/pojo/image/response/ImageAgentTypeInfo.kt
- src/backend/ci/core/store/biz-store-image-sample/src/main/kotlin/com/tencent/devops/store/service/image/impl/SampleImageReleaseService.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/resources/image/user/UserImageReleaseResourceImpl.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageReleaseService.kt
- support-files/templates/#etc#ci#application-store.yml
feat:【研发商店】容器镜像上架时，适用机器和流水线JOB支持的机器对齐 #3614
#3614
> feat:【研发商店】容器镜像上架时，适用机器和流水线JOB支持的机器对齐 #3614

- src/gateway/core/lua/set/set_project_id.lua
> bug: 网关subrequest修改project_id导致获取项目信息错误 #4483

- src/backend/ci/core/process/biz-process-sample/src/main/kotlin/com/tencent/devops/process/permission/service/impl/V3PipelinePermissionService.kt
- src/backend/ci/core/quality/biz-quality-sample/src/main/kotlin/com/tencent/devops/quality/QualityConfiguration.kt
- src/backend/ci/core/quality/biz-quality-sample/src/main/kotlin/com/tencent/devops/quality/service/AbsQualityPermissionServiceImpl.kt
- src/backend/ci/core/quality/biz-quality-sample/src/main/kotlin/com/tencent/devops/quality/service/SampleQualityPermissionServiceImpl.kt
- src/backend/ci/core/quality/biz-quality-sample/src/main/kotlin/com/tencent/devops/quality/service/V3QualityPermissionServiceImpl.kt
- src/backend/ci/core/ticket/biz-ticket-sample/src/main/kotlin/com/tencent/devops/ticket/service/V3CertPermissionService.kt
- src/backend/ci/core/ticket/biz-ticket-sample/src/main/kotlin/com/tencent/devops/ticket/service/V3CredentialPermissionService.kt
1. 补齐质量红线V3权限中心实现。
2. 调整原有权限列表越界逻辑
> feat: 质量红线权限补齐 #4510

- src/backend/ci/core/quality/biz-quality-sample/src/main/kotlin/com/tencent/devops/quality/QualityConfiguration.kt
> feat: 质量红线权限补齐 #4510 #4511

- src/backend/ci/core/common/common-websocket/src/main/kotlin/com/tencent/devops/common/websocket/pojo/WebSocketType.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/websocket/PipelineWebSocketConfiguration.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/websocket/page/DefaultDetailPageBuild.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/websocket/page/DefaultHistoryPageBuild.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/websocket/page/DefaultStatusPageBuild.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/websocket/page/DetailPageBuild.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/websocket/page/HistoryPageBuild.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/websocket/page/StatusPageBuild.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/websocket/service/PipelineWebsocketService.kt
- src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/cron/ClearTimeoutCron.kt
- src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/servcie/WebsocketService.kt
1.定义扩展接口。并提供默认实现。
2. loginOut不删除用户sessionId
> feat: websocket page添加提供扩展 #4470

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/extend/ModelCheckPlugin.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/extend/DefaultModelCheckPlugin.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/CheckPauseReviewStageCmd.kt
> bugfix: stage审核关闭需去除model内的相关变量 #3742

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/TimerTriggerElement.kt
- src/backend/ci/core/plugin/codecc-plugin/common-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/element/LinuxCodeCCScriptElementBizPlugin.kt
- src/backend/ci/core/plugin/codecc-plugin/common-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/element/LinuxPaasCodeCCScriptElementBizPlugin.kt
- src/backend/ci/core/plugin/codecc-plugin/common-codecc/src/test/kotlin/com/tencent/devops/plugin/codecc/element/LinuxCodeCCScriptElementBizPluginTest.kt
- src/backend/ci/core/plugin/codecc-plugin/common-codecc/src/test/kotlin/com/tencent/devops/plugin/codecc/element/LinuxPaasCodeCCScriptElementBizPluginTest.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/atom/plugin/MarketBuildAtomElementBizPlugin.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/atom/plugin/MarketBuildLessAtomElementBizPlugin.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/webhook/WebHookTriggerElementBizPlugin.kt
- src/backend/ci/core/process/plugin-sdk/src/main/kotlin/com/tencent/devops/process/plugin/ElementBizPlugin.kt
- src/backend/ci/core/process/plugin-trigger/src/main/kotlin/com/tencent/devops/process/plugin/trigger/element/TimerTriggerElementBizPlugin.kt
> feat: 定时触发器支持流水线变量 #4073

- src/frontend/devops-pipeline/src/components/pipelineList/extMenu/index.vue
- src/frontend/devops-pipeline/src/views/list/newlist.vue
- src/frontend/devops-pipeline/src/views/subpages/index.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
feat: 支持根据实例化出来的流水线反向查找模板的功能 issue #370
> feat: 支持根据实例化出来的流水线反向查找模板的功能

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/Pipeline.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/PipelineDetailInfo.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineSettingService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineListFacadeService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomCommonServiceImpl.kt
feat:支持：根据实例化出来的流水线反向查找模板的功能 #370
#370
> feat:支持：根据实例化出来的流水线反向查找模板的功能 #370

- src/backend/ci/core/store/api-store-image/src/main/kotlin/com/tencent/devops/store/pojo/image/response/ImageDetail.kt
- src/backend/ci/core/store/api-store-image/src/main/kotlin/com/tencent/devops/store/pojo/image/response/JobMarketImageItem.kt
- src/backend/ci/core/store/api-store-image/src/main/kotlin/com/tencent/devops/store/pojo/image/response/MarketImageItem.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageProjectService.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageService.kt
bug:流水线选择镜像界面，搜索结果中，已安装标识丢失问题fix #3984
#3984
> bug:流水线选择镜像界面，搜索结果中，已安装标识丢失问题fix #3984

- src/frontend/devops-pipeline/src/views/template/edit.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
feature: 模板版本名超64字符报错不明确 issue #2970
> feature: 模板版本名超64字符报错不明确 issue #2970

- src/frontend/devops-pipeline/src/components/AtomSelector/imageCard.vue
- src/frontend/devops-pipeline/src/components/AtomSelector/imageSelector.vue
feature: 流水线选择镜像界面，搜索结果中，已安装标识丢失问题fix issue #3984
> feature: 流水线选择镜像界面，搜索结果中，已安装标识丢失问题fix issue #3984

- src/gateway/core/vhosts/devops.redirect.conf
- support-files/codecc/templates/gateway#core#ci-redirect.d#codecc.conf
- support-files/templates/gateway#core#devops.server.conf
> feat: 网关新增codecc的302跳转 #4533

- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/pojo/CodeGitRepository.kt
> feat: 关联工蜂代码库后台需支持https #4248

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/context/StartBuildContext.kt
> bug: rebuild跳过的job应该能够再次检测是否能运行 #4499

- src/backend/ci/build.gradle.kts
- src/backend/ci/core/worker/worker-agent/src/main/kotlin/com/tencent/devops/agent/AgentVersion.kt
> feat: 优化无编译构建环境镜像选择逻辑 #4521

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/enums/VMBaseOS.kt
- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/dispatcher/agent/ThirdPartyAgentDispatcher.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineContextService.kt
- src/backend/ci/core/worker/worker-agent/src/main/kotlin/com/tencent/devops/agent/runner/WorkRunner.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Constants.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/EngineService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/ICommand.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/ScriptTask.kt
> feat: 第三方构建机选择支持不指定操作系统 #4529

- src/frontend/devops-pipeline/package.json
- src/frontend/devops-pipeline/src/components/ExecDetail/log/jobLog.vue
- src/frontend/devops-pipeline/src/components/ExecDetail/log/pluginLog.vue
- src/frontend/devops-pipeline/src/main.js
- src/frontend/devops-pipeline/src/mixins/pipeline-operate-mixin.js
- src/frontend/devops-pipeline/src/store/modules/atom/actions.js
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
- src/frontend/webpack.base.js
> pref: 日志模块的相关熔断能力 issue #3772

- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitMrTriggerHandler.kt
> feat: 新增工蜂CR事件触发 #3734

- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
> feat: 内置单选下拉框优化 issue #4495

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/logger/LoggerService.kt
> fix: 日志模块的相关熔断能力 #3772 处理循环调用bug

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildTaskDao.kt
> 统计耗时调整，EXECUTE_TIME统一为毫秒

- src/backend/ci/core/ticket/biz-ticket/src/main/kotlin/com/tencent/devops/ticket/service/CredentialServiceImpl.kt
- src/frontend/devops-ticket/src/views/create_credential.vue
- src/frontend/locale/ticket/en-US.json
- src/frontend/locale/ticket/zh-CN.json
> feat: 梳理现在的名称字段，适当扩大长度 #4358

- scripts/bk-ci-setup.sh
chore: 部署问题ci-dockerhost启动后如果sysctl -p会导致容器断网 #4501
> chore: 部署问题ci-dockerhost启动后如果sysctl -p会导致容器断网 #4501

- scripts/bk-ci-gen-docker-conf.sh
- scripts/bk-ci-install.sh
- scripts/bk-ci-utils-https.sh
> chore: 部署问题汇总202106 #4591 

- src/backend/ci/build.gradle.kts
移除 jsr311-api-1.1.1.jar
表现: 提示后端异常 日志 java.lang.NoSuchMethodError: javax.ws.rs.core.Application.getProperties()Ljava/util/Map;
> chore: 部署问题汇总202106 #4591

- src/frontend/devops-codecc/src/components/tool-config-form/index.vue
- src/frontend/devops-codecc/src/views/defect/ccn-list.vue
- src/frontend/devops-codecc/src/views/defect/coverity-list.vue
- src/frontend/devops-codecc/src/views/defect/dupc-list.vue
- src/frontend/devops-codecc/src/views/defect/list.vue
- src/frontend/devops-codecc/src/views/task/detail.vue
- src/frontend/devops-codecc/src/views/task/settings.vue
CodeCC frontend同步release-1.3分支修改代码到release-1.5 issue #4615
> feat: CodeCC frontend同步release-1.3分支修改代码到release-1.5 issue #4615

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/logger/LoggerService.kt
优化subTag的解析方式，使得执行Apache Common Exec时即使输出ANSI控制码也可解析 #4616
> bug: 捕获插件日志的subTag偶尔会失败 #4616

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/engine/EngineBuildSDKApi.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/engine/impl/EngineBuildResourceApi.kt
feat: SDK 提供获取查看当前构建详情的链接（区分蓝盾、工蜂CI） #4603
> feat: SDK 提供获取查看当前构建详情的链接（区分蓝盾、工蜂CI） #4603

- src/gateway/core/vhosts/devops.proxy.conf
- support-files/templates/gateway#core#lua#init.lua
> feat: 蓝盾插件自定义前端URI前缀规范. #4649

- src/frontend/devops-pipeline/src/components/AtomFormComponent/DefineParam/index.vue
- src/frontend/devops-pipeline/src/components/AtomFormComponent/DefineParam/show.vue
- src/frontend/devops-pipeline/src/components/Stages/CheckAtomDialog.vue
> 人工审核公共部分提取优化

- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/cron/process/PipelineBuildHistoryDataClearJob.kt
perf:misc多线程清理构建数据优化 #4645
#4645
> perf:misc多线程清理构建数据优化 #4645

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwBuildResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwBuildResourceV3Impl.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceBuildResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserBuildResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/BuildTaskPauseInfo.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServiceBuildResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserBuildResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelinePauseBuildFacadeService.kt
> feat: 对于流水线TASK执行前支持自动暂停，希望能开放应用态接口，使插件继续执行或者中止 #4132

- src/gateway/core/lua/util/tag_util.lua
> feat: 网关新增强制路由集群 #4662

- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/resources/BuildLogPrintResourceImpl.kt
> bugfix: 取消构建机上报日志的异步处理 #4658

- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/constant/BkStyleEnum.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/common/UserSensitiveConfResource.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/common/SensitiveConfResp.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/common/enums/FieldTypeEnum.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/common/SensitiveConfDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/common/BuildStoreResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/common/UserSensitiveConfResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/UserSensitiveConfService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/impl/UserSensitiveConfServiceImpl.kt
- support-files/sql/2006_ci_store-update_v1.5_mysql.sql
feat:流水线插件自定义前端框架，支持使用插件私有配置 #4600
#4600
> feat:流水线插件自定义前端框架，支持使用插件私有配置 #4600

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/exception/ScmException.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/IScm.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeGitScmImpl.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeGitScmOauthImpl.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeGitlabScmImpl.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeSvnScmImpl.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeTGitScmImpl.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/git/api/GitApi.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/exception/ScmException.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/CodeService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/scm/ScmProxyService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserScmResourceImpl.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/scm/ServiceScmOauthResource.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/scm/ServiceScmResource.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/scm/ServiceScmOauthResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/scm/ServiceScmResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/IScmOauthService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/IScmService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/ScmOauthService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/ScmService.kt
> feat: 优化获取git分支列表接口 #4674

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Runner.kt
> bug: worker在结束Job后再停止心跳上报 #4718

- src/frontend/devops-pipeline/src/components/AtomFormComponent/DynamicParameterSimple/index.vue
- src/frontend/devops-pipeline/src/components/AtomFormComponent/DynamicParameterSimple/parameterCom.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/NormalAtomV2.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/PreviewAtom.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
feat: 简化dynamic-parameter-simple组件 issue #4583
> feat: 简化dynamic-parameter-simple组件 issue #4583

- src/backend/ci/core/common/common-client/src/main/kotlin/com/tencent/devops/common/client/consul/ConsulContent.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/resources/AppLogResourceImpl.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/app/AppPipelineBuildResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/Pipeline.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/pipeline/AppModelDetail.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/app/AppPipelineBuildResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> feat: 接口支持GIT channel的流水线 #4740

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/constant/CommonConstants.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/constant/ProcessMessageCode.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomServiceImpl.kt
> bug: 导出商店插件yml注释补充默认值 #4738

- src/frontend/.gitignore
- src/frontend/devops-atomstore/src/index.js
- src/frontend/devops-nav/src/index.ts
- src/frontend/devops-pipeline/src/components/ExportDialog.vue
- src/frontend/devops-pipeline/src/main.js
- src/frontend/devops-pipeline/src/store/modules/atom/actions.js
feature: 修改流水线导出的下载方式 #4738
feature: 错误提示弹框，默认展示三行信息 #2947
> 修改流水线导出的下载方式

- src/frontend/devops-pipeline/src/store/modules/atom/actions.js
> feature: 修改流水线导出的下载方式 #4738

- scripts/bk-ci-init-bkce.sh
- scripts/deploy-codecc/bk-codecc-init-bkce.sh
> chore: 部署脚本检查接口返回的结果 #4763

- src/backend/ci/buildSrc/src/main/kotlin/task-gen-jooq.gradle.kts
> feat: jooq generator 兼容多数据源 #4737

- scripts/deploy-codecc/bk-codecc-setup.sh
chore: 在蓝鲸社区版部署CodeCC #4526
修正codecc-setup.sh的bug.
> chore: 在蓝鲸社区版部署CodeCC #4526

- src/backend/codecc/build.gradle
> CodeCC For 1.5 #4572

- src/frontend/devops-atomstore/src/components/transition-tab.vue
fix: 研发商店工作台Tab栏样式错乱调整 issue #4755
> 研发商店工作台Tab栏样式错乱调整

- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/ResourceService.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/resources/ServiceEnvironmentAuthResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServiceProcessAuthResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/ServiceRepositoryAuthResourceImpl.kt
- src/backend/ci/core/ticket/biz-ticket/src/main/kotlin/com/tencent/devops/ticket/resources/ServiceTicketAuthResourceImpl.kt
>  bug: 无权限跳转失败 #4788

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/utils/code/git/GitUtils.kt
- src/backend/ci/core/common/common-scm/src/test/kotlin/com/tencent/devops/scm/utils/code/git/GitUtilsTest.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwRepositoryResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwRepositoryResourceV3Impl.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/ServiceRepositoryResource.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/pojo/CodeGitRepository.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/pojo/CodeGitlabRepository.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/pojo/CodeTGitRepository.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/ServiceRepositoryResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/UserRepositoryResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepositoryService.kt
> feature：OpenApi：支持编辑代码库 #4567

- src/backend/ci/core/artifactory/api-artifactory/src/main/kotlin/com/tencent/devops/artifactory/api/service/ServiceArtifactoryResource.kt
- src/backend/ci/core/artifactory/biz-artifactory-sample/src/main/kotlin/com/tencent/devops/artifactory/resources/ServiceArtifactoryResourceImpl.kt
- src/backend/ci/core/artifactory/biz-artifactory-sample/src/main/kotlin/com/tencent/devops/artifactory/resources/UserPipelineFileResourceImpl.kt
- src/backend/ci/core/common/common-util/src/main/kotlin/com/tencent/devops/common/util/RegexUtils.kt
- src/backend/ci/core/common/common-util/src/test/kotlin/com/tencent/devops/common/util/RegexUtilsTest.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwArtifactoryResourceV3Impl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/task/SubPipelineCallAtom.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/report/UserReportResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineWebHookQueueService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineAtomService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleCheckService.kt
> feat: 接口返回的完整平台访问url整改，只返回context-path,不返回域名 #4796

- src/backend/ci/core/common/common-util/src/main/kotlin/com/tencent/devops/common/util/RegexUtils.kt
- src/backend/ci/core/common/common-util/src/test/kotlin/com/tencent/devops/common/util/RegexUtilsTest.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/atom/UserMarketAtomResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/MarketAtomService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomServiceImpl.kt
> feat: 接口返回的完整平台访问url整改，只返回content-path,不返回域名 #4796

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/Constants.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
feat:【流水线插件】插件执行时，增加插件标识、插件别名、插件版本号 #3622
#3622
> feat:【流水线插件】插件执行时，增加插件标识、插件别名、插件版本号 #3622

- src/backend/ci/core/ticket/biz-ticket/src/main/kotlin/com/tencent/devops/ticket/service/CredentialHelper.kt
> feat: SSH KEY凭据支持ed25519 #4088

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/TimerTriggerElement.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/handler/RuntimeExceptionMapper.kt
- src/backend/ci/core/process/plugin-trigger/src/main/kotlin/com/tencent/devops/process/plugin/trigger/element/TimerTriggerElementBizPlugin.kt
> bug: 定时触发支持流水线变量,变量可支持linux格式的cron #4805

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/CodeGitWebHookTriggerElement.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/CodeGitlabWebHookTriggerElement.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/CodeSVNWebHookTriggerElement.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/CodeTGitWebHookTriggerElement.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/enums/PathFilterType.kt
- src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/pojo/code/PathFilterConfig.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/filter/PathFilterFactory.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/filter/PathPrefixFilter.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/filter/PathRegexFilter.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/svn/SvnCommitTriggerHandler.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitMrTriggerHandler.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitPushTriggerHandler.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/test/kotlin/com/tencent/devops/common/webhook/service/code/filter/PathRegexFilterTest.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/code/GitWebhookElementParams.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/code/GitlabWebhookElementParams.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/code/SvnWebhookElementParams.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/code/TGitWebhookElementParams.kt
> feature: git/svn触发插件的路径希望增加模糊 #2142

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/detail/TaskBuildDetailService.kt
feat: 流水线插件高级特性：即使前面有插件运行失败也运行，即使被取消也运行 #1156
#1156
> feat: 流水线插件高级特性：即使前面有插件运行失败也运行，即使被取消也运行 #1156

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/engine/api/BuildJobResource.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/api/BuildJobResourceImpl.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/engine/impl/EngineBuildResourceApi.kt
feat:加新的心跳接口以避免对旧的agent产生影响 #4835
#4835
> feat:加新的心跳接口以避免对旧的agent产生影响 #4835

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/engine/api/BuildJobResource.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/api/BuildJobResourceImpl.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
feat:回退旧的心跳接口的逻辑以避免对旧的agent产生影响 #4838
#4838
> feat:回退旧的心跳接口的逻辑以避免对旧的agent产生影响 #4838

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityIndicatorService.kt
> bug: 兼容插件市场部分插件，配置红线指标时，没带desc描述字段的场景 #4831

- src/frontend/devops-pipeline/src/components/pipelineParamsForm.vue
bugfix: 前端select控件，远程搜索数据无法选择 issue #4425
> bugfix: 前端select控件，远程搜索数据无法选择 issue #4425

- scripts/bk-ci-install.sh
- scripts/bk-ci-reg-paas-app.sh
- scripts/bk-ci-utils-https.sh
- scripts/bkci-op.sh
- scripts/deploy-codecc/bk-codecc-utils-https.sh
- scripts/deploy-codecc/codecc.properties
- scripts/deploy-codecc/packager-codecc.sh
- support-files/codecc/templates/gateway#core#vhosts#codecc.server.conf
chore: 部署问题汇总202107 #4795
chore: 在蓝鲸社区版部署CodeCC #4526 
chore: 修正https切回http的变量渲染问题. #4612
> chore: 部署问题汇总202107 #4795

- src/frontend/devops-nav/src/index.html
- src/frontend/locale/index.js
fix: 页面websocket 功能失效 issue #4820
> fix: 页面websocket 功能失效 issue #4820

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
> feat: 流水线在重试时需要刷新排队时间 #4866

- src/gateway/core/lua/util/tag_util.lua
>  feat: 根据module name路由到指定tag

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/code/WebhookInfo.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
> feat: 流水线历史记录webhookInfo字段增加触发commitId #4851

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomOption.vue
- src/frontend/devops-pipeline/src/store/modules/common/optionConfigMixin.js
feature: 勾选【可自动重试】后，输入框前需添加文案：“自动重试次数：”，暂时先将该选项隐藏掉。issue #4793
> feature: 勾选【可自动重试】后，输入框前需添加文案：“自动重试次数：”，暂时先将该选项隐藏掉。issue #4793

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/engine/atom/IAtomTask.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/TaskAtomService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/TaskControl.kt
bug:人工审核这种内置插件取消异常问题修复 #4871
#4871
> bug:人工审核这种内置插件取消异常问题修复 #4871

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/ElementAdditionalOptions.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/constant/ProcessMessageCode.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/control/VmOperateTaskGenerator.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/util/TaskUtils.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildCancelControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
feat: Final Stage允许被取消 #4781
#4781
> feat: Final Stage允许被取消 #4781

- src/frontend/devops-atomstore/src/components/transition-tab.vue
- src/frontend/devops-atomstore/src/views/manage/over-view/statistic-pipeline.vue
feature: 研发商店导出提示优化 issue #4849
> feature: 研发商店导出提示优化 issue #4849

- src/backend/ci/core/common/common-redis/src/main/kotlin/com/tencent/devops/common/redis/RedisLock.kt
- src/backend/ci/core/common/common-redis/src/main/kotlin/com/tencent/devops/common/redis/RedisLockByValue.kt
- src/backend/ci/core/common/common-redis/src/main/kotlin/com/tencent/devops/common/redis/RedisOperation.kt
- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/cron/process/PipelineBuildHistoryDataClearJob.kt
feat:redis支持按redis名称保存和读取对象 #4859
#4859
> feat:redis支持按redis名称保存和读取对象 #4859

- src/backend/ci/core/quality/api-quality/src/main/kotlin/com/tencent/devops/quality/constant/CodeccConstants.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleCheckService.kt
> feat: 质量红线链接支持按维度跳转 #4852

- src/frontend/devops-pipeline/src/components/BuildHistoryTable/index.vue
- src/frontend/devops-pipeline/src/components/VersionSideslider.vue
对很久以前的历史构建进行备注修改时，页面会卡住很久。且期望修改完成后不刷新整个页面。 #4324
> bug: 对很久以前的历史构建进行备注修改时，页面会卡住很久。且期望修改完成后不刷新整个页面。 #4324

- src/frontend/devops-pipeline/src/store/modules/soda/atom.js
- support-files/templates/#etc#ci#application-repository.yml
> fix: 迁移github触发器前端相关接口 #3006

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
feat: 已完成无法停止的构建需要在接口返回体现原因 #4722
> feat: 已完成无法停止的构建需要在接口返回体现原因 #4722

- src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/common/log/pojo/EndPageQueryLogs.kt
- src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/common/log/pojo/PageQueryLogs.kt
- src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/common/log/pojo/QueryLogs.kt
- src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/common/log/pojo/enums/LogStatus.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/impl/LogServiceESImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/impl/LogServiceLuceneImpl.kt
feat: OpenAPI的日志查询接口枚举映射失败 #4670
> feat: OpenAPI的日志查询接口枚举映射失败 #4670

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/dao/v2/QualityControlPointDao.kt
> bug: 调整发布插件时的质量红线默认控制点 #4951

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwPipelineResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwPipelineResourceV3Impl.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServicePipelineResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServicePipelineResourceImpl.kt
> feat: 新增复制流水线的openAPI #4881

- src/gateway/core/lua/util/tag_util.lua
> feat: 调整service路由到低优先级 #4965

- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/impl/SignServiceImpl.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/service/AsyncSignService.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/service/SignService.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/utils/SignUtils.kt
- src/backend/ci/core/sign/biz-sign/src/test/kotlin/com/tencent/devops/sign/utils/IpaSignUtilTest.kt
> feat: 签名模块后台逻辑优化 #4885

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/control/VmOperateTaskGenerator.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
bug:dispatchVMStartupTaskAtom内置插件修改runCondition #4971
#4971
> bug:dispatchVMStartupTaskAtom内置插件修改runCondition #4971

- src/backend/ci/build.gradle.kts
- src/backend/ci/buildSrc/src/main/kotlin/Versions.kt
- src/backend/ci/core/openapi/biz-openapi/build.gradle.kts
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/filter/ApiFilter.kt
- src/backend/ci/core/openapi/boot-openapi/build.gradle.kts
> fix: 移除json-lib依赖 #4963

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/CheckPauseReviewStageCmd.kt
> feat: stage支持质量红线的准入准出 #4732 保存变量时不转为string

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/archive/BuildArchiveGetTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/archive/CustomizeArchiveGetTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/archive/ReportArchiveTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/ScriptTask.kt
feat:支持按token方式上传报告 #4693
#4693
> feat:支持按token方式上传报告 #4693

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/detail/ContainerBuildDetailService.kt
bug: 2分钟内取消并直接重试，可能导致构建机无法正常启动 #4779
#4779
> bug: 2分钟内取消并直接重试，可能导致构建机无法正常启动 #4779

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/logger/LoggerService.kt
Job结束时主动清理临时日志文件 #4939
feat: 日志熔断的交互优化 #4587
> bugfix: Job结束时主动清理临时日志文件 #4939

- src/gateway/core/lua/auth/auth_gray.lua
- src/gateway/core/lua/util/tag_util.lua
- src/gateway/core/nginx.conf
- support-files/codecc/templates/gateway#core#vhosts#codecc.server.conf
>  feat: 网关路由前端不同目录 #4972

- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/common/BuildStoreResource.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/common/BuildStoreResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/UserSensitiveConfService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/impl/UserSensitiveConfServiceImpl.kt
> bug:sdk接口安全限制 #4987

- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/atom/ServiceMarketAtomResource.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/atom/UserMarketAtomResource.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/atom/ElementThirdPartySearchParam.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/atom/GetRelyAtom.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/AtomBaseDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/atom/ServiceMarketAtomResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/atom/UserMarketAtomResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/MarketAtomService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomServiceImpl.kt
> yaml导出附加依赖关系 #4978

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleBuildHisService.kt
- support-files/sql/1001_ci_store_ddl_mysql.sql
> feat: 质量红线支持stage准入准出拦截 #4863

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/CheckPauseReviewStageCmd.kt
> feat: Stage准入支持审核流 #4531

- src/frontend/devops-pipeline/src/components/StageReviewPanel/approve.vue
- src/frontend/devops-pipeline/src/components/StageReviewPanel/index.vue
- src/frontend/devops-pipeline/src/views/subpages/exec_detail.vue
feature: stage审核支持审核流 issue #4531
> feature: stage审核支持审核流 issue #4531

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/Stages/AtomList.vue
- src/frontend/locale/environment/en-US.json
- src/frontend/locale/environment/zh-CN.json
feat: agent安装目录文案优化 issue #3658
>  agent安装目录文案优化

- src/frontend/devops-pipeline/src/components/Stages/CheckAtomDialog.vue
- src/frontend/devops-pipeline/src/components/Stages/CheckParams.vue
format: 人工审核公共部分代码提取优化 issue #4655
> format: 人工审核公共部分代码提取优化 issue #4655

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/Stages/AtomList.vue
- src/frontend/devops-pipeline/src/components/devops/progressBar/index.vue
- src/frontend/devops-pipeline/src/components/pipelineList/taskCard/index.vue
- src/frontend/devops-pipeline/src/components/pipelineList/taskTable/index.vue
- src/frontend/devops-pipeline/src/store/modules/pipelines/staticList.js
- src/frontend/devops-pipeline/src/views/list/newlist.vue
feat: 用户取消等黄颜色状态的构建，在流水线列表页应统一展示黄颜色状态 issue #3917
> 用户取消等黄颜色状态的构建，在流水线列表页应统一展示黄颜色状态

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/AbstractBuildResourceApi.kt
> perf:插件包下载支持自动重试 #5013

- src/frontend/devops-turbo/src/api/index.js
feature: turbo frontend issue #5038
> feature: turbo frontend issue #5038

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildEndControl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/TaskControl.kt
bug:流水线构建取消时子流水线也应该一并取消 #5064
#5064
> bug:流水线构建取消时子流水线也应该一并取消 #5064

- scripts/bkenv.properties
- src/backend/ci/core/auth/biz-auth-blueking/src/main/kotlin/com/tencent/devops/auth/service/BKPermissionGraderServiceImpl.kt
- src/backend/ci/core/auth/biz-auth-blueking/src/main/kotlin/com/tencent/devops/auth/service/BkIamPermissionRoleExtService.kt
- src/backend/ci/core/auth/biz-auth-blueking/src/main/kotlin/com/tencent/devops/auth/service/BkPermissionRoleMemberImpl.kt
- src/backend/ci/core/auth/biz-auth-blueking/src/main/kotlin/com/tencent/devops/auth/service/BkPermissionUrlService.kt
> feat: 全量对接权限中心V3 #3854 bkenv.properties调整

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/CallBackControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/init/PipelineCallBackConfiguration.kt
> feat: 解决callback延迟 #5060

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/CheckPauseContainerCmd.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/StartActionTaskContainerCmd.kt
> feat: 插件暂停偶现自动取消 #5030

- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/IamCacheService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/impl/AbsPermissionProjectService.kt
- src/backend/ci/core/common/common-auth/common-auth-api/src/main/kotlin/com/tencent/devops/common/auth/api/pojo/DefaultGroupType.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/dao/NodeDao.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/resources/ServiceEnvironmentAuthResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/AuthPipelineService.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/resources/v2/ServiceQualityAuthResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/ServiceRepositoryAuthResourceImpl.kt
- src/backend/ci/core/ticket/biz-ticket/src/main/kotlin/com/tencent/devops/ticket/resources/ServiceTicketAuthResourceImpl.kt
1. 默认分组列表顺序调整。
2. isProject判断逻辑调整：从project_view权限校验 ->  是否有加入项目下任意分组
> feat: 权限中心V3优化项 #5053

- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/GitOauthService.kt
> feat: 获取代码库accessToken校验调整 #5020

- src/gateway/core/lua/router_srv.lua
> feat: 去掉网关兜底策略 #5119

- src/backend/ci/core/plugin/biz-plugin/src/main/kotlin/com/tencent/devops/plugin/utils/QualityUtils.kt
- src/backend/ci/core/quality/api-quality/src/main/kotlin/com/tencent/devops/quality/constant/CodeccConstants.kt
> feat: 维度的质量红线跳转需要自动进行快照筛选 issue #5099

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/impl/GolangAtomTargetHandleServiceImpl.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/impl/PythonAtomTargetHandleServiceImpl.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/AtomTargetFactory.kt
feat:【流水线插件】golang 和 nodejs 开发的插件支持 post-actions #4969
#4969
> feat:【流水线插件】golang 和 nodejs 开发的插件支持 post-actions #4969

- src/backend/ci/core/process/plugin-trigger/build.gradle.kts
> 去除quartz-scheduler 内HikariCP 依赖 #5146

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/ScriptTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/CommandLineUtils.kt
> perf: Windows构建机的batch脚本执行编码问题 #4601 默认值保持为系统默认字符集

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildBuildResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildVarResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceVarResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/PipelineVarUtil.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/BuildVariableService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineContextService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildBuildResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildVarResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceVarResourceImpl.kt
#5155 增加获取预置上下文的Service和Build类接口
> feat: 新增引擎的预置上下文获取接口 #5155

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/atom/plugin/MarketBuildAtomElementBizPlugin.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/atom/plugin/MarketBuildLessAtomElementBizPlugin.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/atom/plugin/MarketBuildUtils.kt
> feat: 插件回调机制可配置 #5091

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildCancelControl.kt
bug:流水线job配置了dependOn依赖的情况构建无法正常取消 #5113
#5113
> bug:流水线job配置了dependOn依赖的情况构建无法正常取消 #5113

- src/backend/ci/core/artifactory/api-artifactory/src/main/kotlin/com/tencent/devops/artifactory/api/service/ServiceLogFileResource.kt
- src/backend/ci/core/artifactory/biz-artifactory-sample/src/main/kotlin/com/tencent/devops/artifactory/resources/ServiceLogFileResourceImpl.kt
- src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/log/api/ServiceLogResource.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/resources/AppLogResourceImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/resources/ServiceLogResourceImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/resources/UserLogResourceImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/BuildLogQueryService.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwArtifactoryResourceV3.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwLogResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwArtifactoryResourceV3Impl.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwLogResourceV3Impl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/impl/StoreLogServiceImpl.kt
> feat: 新增日志熔断后下载全量日志的OpenAPI #5145

- src/backend/ci/core/common/common-client/src/main/kotlin/com/tencent/devops/common/client/Client.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/FeignConfiguration.kt
> fix: feign 11.6 默认会decodeSlash , 需要关闭手动关闭 #5205

- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/ContainerContent.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
bug: 移除不可用的[新增自定义构建镜像] 功能按钮 #5130
> bug: 移除不可用的[新增自定义构建镜像] 功能按钮 #5130

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleBuildHisService.kt
>  feat: 质量红线服务创建的规则加上指标类型校验 #5204

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/event/CallBackData.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/listener/run/PipelineTaskPauseListener.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/CallBackControl.kt
1. 暂停添加 BUILD_TASK_PAUSE事件
2. 暂停终止 添加 BUILD_END 事件
> feat: 流水线callback增加支持 插件支持执行前暂停&插件继续执行 事件 #5160

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwMarketTemplateResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwMarketTemplateResourceV3Impl.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwTemplateResourceV3Impl.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/template/ServicePTemplateResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/PipelineTemplateInfo.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/template/TemplateDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/template/ServicePTemplateResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityPipelineService.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/template/impl/MarketTemplateServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/template/impl/TemplateReleaseServiceImpl.kt
> feat: template/install接口返回流水线模板ID 

- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/ProjectRouteTagService.kt
> Bug:判断项目集群逻辑 #5194

- src/backend/ci/core/process/plugin-trigger/build.gradle.kts
- src/backend/ci/core/process/plugin-trigger/src/main/kotlin/com/tencent/devops/process/plugin/trigger/configuration/TriggerConfiguration.kt
- src/backend/ci/core/process/plugin-trigger/src/main/kotlin/com/tencent/devops/process/plugin/trigger/timer/quartz/PipelineQuartzService.kt
> feat: 不同集群定时任务独立触发 #5213

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/dao/v2/QualityControlPointDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomQualityServiceImpl.kt
> feat: 插件发布操作做成幂等 #5201

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildTaskDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/pojo/UpdateTaskInfo.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/detail/TaskBuildDetailService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineTaskService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/util/TaskUtils.kt
bug:插件重试时把task任务表的开始时间覆盖了从而造成job耗费时间不准 #5041
#5041
> bug:插件重试时把task任务表的开始时间覆盖了从而造成job耗费时间不准 #5041

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildLabelResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/classify/PipelineLabelDetail.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/label/PipelineLabelService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildLabelResourceImpl.kt
feat:【流水线插件】支持获取当前流水线的标签的build接口，供插件使用 #5066
#5066
> feat:【流水线插件】支持获取当前流水线的标签的build接口，供插件使用 #5066

- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/service/impl/ArchiveFileServiceImpl.kt
- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/service/impl/DiskArchiveFileServiceImpl.kt
> feat: 支持流水线变量[文件]类型 #5176

- src/backend/ci/core/artifactory/api-artifactory/src/main/kotlin/com/tencent/devops/artifactory/api/service/ServiceArtifactoryResource.kt
- src/backend/ci/core/artifactory/biz-artifactory-sample/src/main/kotlin/com/tencent/devops/artifactory/resources/ServiceArtifactoryResourceImpl.kt
- src/backend/ci/core/artifactory/biz-artifactory-sample/src/main/kotlin/com/tencent/devops/artifactory/resources/UserPipelineFileResourceImpl.kt
- src/backend/ci/core/common/common-util/src/main/kotlin/com/tencent/devops/common/util/RegexUtils.kt
- src/backend/ci/core/common/common-util/src/test/kotlin/com/tencent/devops/common/util/RegexUtilsTest.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwArtifactoryResourceV3Impl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/task/SubPipelineCallAtom.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/report/UserReportResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineWebHookQueueService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineAtomService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleCheckService.kt
> feat: 接口返回的完整平台访问url整改，只返回context-path,不返回域名 [1.5]

- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/service/impl/ArchiveFileServiceImpl.kt
- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/service/impl/DiskArchiveFileServiceImpl.kt
> Issue 5176

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/enums/CharsetType.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/agent/WindowsScriptElement.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/ICommand.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/ScriptTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/bat/CommandBatImpl.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/powershell/CommandPowerShellImpl.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/shell/CommandShellImpl.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/BatScriptUtil.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/CommandLineUtils.kt
> perf: Windows构建机的batch脚本执行编码问题 #4601 修复兼容问题

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/components/Stages/AtomList.vue
- src/frontend/devops-pipeline/src/store/modules/atom/paramsConfig.js
feat:开源版流水线变量，变量类型为代码库时，代码库类型和代码库服务未对齐 issue #3422
> 开源版流水线变量，变量类型为代码库时，代码库类型和代码库服务未对齐

- src/backend/ci/core/common/common-redis/build.gradle.kts
> feat: redis连接池化 #5242

- src/backend/ci/core/worker/worker-agent/src/main/kotlin/com/tencent/devops/agent/runner/WorkRunner.kt
- src/backend/ci/core/worker/worker-api-sdk/src/main/kotlin/com/tencent/devops/worker/common/api/quality/QualityGatewayResourceApi.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/archive/BuildPushDockerImageTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/image/MarketCheckImageTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/scm/git/GitUpdateTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/scm/svn/RevertUpdateTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/scm/svn/SvnUpdateTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/scm/util/RepoCommitUtil.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/scm/util/SSHAgentUtils.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Runner.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/heartbeat/Heartbeat.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/logger/LoggerService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/ProcessService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/TaskDaemon.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/ScriptTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/ArchiveUtils.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/CommandLineUtils.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/CredentialUtils.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/ShellUtil.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/WindowsCommandLineUtils.kt
> feat: agent日志流处理逻辑优化 #5093

- src/backend/ci/core/notify/biz-notify-wework/src/main/kotlin/com/tencent/devops/notify/wework/service/inner/WeworkServiceImpl.kt
- src/backend/ci/core/notify/boot-notify/build.gradle.kts
> feat: 提供企业微信“蓝盾Bot”，用于推送蓝盾相关消息 #3797

- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/api/service/ServicePermissionAuthResource.kt
- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/api/service/ServiceProjectAuthResource.kt
- src/backend/ci/core/auth/biz-auth-blueking/src/main/kotlin/com/tencent/devops/auth/service/BkAuthPermissionProjectService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/service/ServicePermissionAuthResourceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/service/ServiceProjectAuthResourceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/AuthGroupService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/PermissionProjectService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/impl/AbsPermissionProjectService.kt
- src/backend/ci/core/project/biz-project/build.gradle.kts
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/AuthProjectService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/ServiceProjectAuthCallBackResourceImpl.kt
1. 添加项目回调接口内管理员approve
2. 添加批量action接口
> feat: IAM回调添加项目审批人 #5228

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
> feat: 节省空间压缩Json串存储 #5192

- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/constant/BkStyleEnum.kt
- src/backend/ci/core/store/api-store-image/src/main/kotlin/com/tencent/devops/store/api/image/user/UserImageReleaseResource.kt
- src/backend/ci/core/store/api-store-image/src/main/kotlin/com/tencent/devops/store/pojo/image/request/MarketImageRelRequest.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/template/UserTemplateReleaseResource.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/template/MarketTemplateRelRequest.kt
feat:流水线插件/容器镜像标识和名称规范 #3561
#3561
> feat:流水线插件/容器镜像标识和名称规范 #3561

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/JsonUtil.kt
- src/backend/ci/core/common/common-api/src/test/kotlin/com/tencent/devops/common/api/util/JsonUtilTest.kt
- src/backend/ci/core/store/biz-store-image/src/test/kotlin/com/tencent/devops/store/service/atom/action/AtomDecorateFactoryTest.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/AtomDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/action/AtomDecorate.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/action/AtomDecorateFactory.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/action/impl/AbstractAtomDecorateImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/action/impl/FirstAtomDataDecorateImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/action/impl/FirstAtomPropsDecorateImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomServiceImpl.kt
> feat: 前端插件属性详情的扩展处理 #5001

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/PropertyUtil.kt
perf:流水线插件安装包存储和获取逻辑优化 #4602
#4602
> perf:流水线插件安装包存储和获取逻辑优化 #4602

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/StartContainerStageCmd.kt
> feat: stage 准入准出上的质量红线，支持把关人忽略红线发现的问题 #5246 修复finally的状态不准问题

- src/backend/ci/core/worker/worker-agent/src/main/resources/.agent.properties
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/impl/NodeJsAtomTargetHandleServiceImpl.kt
bug:nodejs插件执行环境node版本不匹配 #5467
#5467
> bug:nodejs插件执行环境node版本不匹配 #5467

- src/backend/ci/core/common/common-quality/src/main/kotlin/com/tencent/devops/common/quality/pojo/RuleCheckSingleResult.kt
- src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/common/log/utils/BuildLogPrinter.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildQualityService.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleCheckService.kt
> feat: 质量红线拦截结果页不同结果用不同颜色显示 #5435

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/CommandLineUtils.kt
> feat: 支持使用echo设置质量红线 #5473

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/dao/HistoryDao.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityHistoryService.kt
> feat: 获取红线拦截次数逻辑优化 #5487

- src/gateway/core/init.conf
- src/gateway/core/lua/init_common.lua
> feat: 网关uuid避免冲突 #5427

- src/gateway/core/lua/util/tag_util.lua
> feat: 网关tag路由支持项目配置 #5471

- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/GitOauthService.kt
代码库Oauth授权时反查获取token的真实身份 #5430
> feat: 代码库Oauth授权时反查获取token的真实身份 #5430

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwTemplateInstanceResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwTemplateInstanceResourceV3Impl.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/template/ServiceTemplateInstanceResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/template/UserTemplateInstanceResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/enums/TemplateSortTypeEnum.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/template/TemplatePipelineDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/template/service/TemplateService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/template/ServiceTemplateInstanceResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/template/UserTemplateInstanceResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
> feat: 流水线模板实例列表排序优化 #1921

- src/backend/ci/core/environment/api-environment/src/main/kotlin/com/tencent/devops/environment/api/ServiceEnvironmentResource.kt
- src/backend/ci/core/environment/api-environment/src/main/kotlin/com/tencent/devops/environment/pojo/AddSharedProjectInfo.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/dao/EnvShareProjectDao.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/resources/ServiceEnvironmentResourceImpl.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/environment/ApigwEnvironmentResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/environment/ApigwEnvironmentResourceV3Impl.kt
> feat: 提供共享环境的openapi接口 #5501

- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/dao/RepositoryDao.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepositoryUserService.kt
> bug:插件重置授权报代码库不存在 #5503

- src/backend/ci/build.gradle.kts
- src/backend/ci/buildSrc/src/main/kotlin/constants/Versions.kt
feat: 添加apache common-text 相关依赖项 #5523
> feat: 添加apache common-text 相关依赖项 #5523

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchVMStartupTaskAtom.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/ITask.kt
> feat: 支持job局部上下文的变量传递 #5443

- src/backend/ci/core/openapi/biz-openapi/build.gradle.kts
> bug: openapi去掉biz-process依赖 #5526

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildCancelControl.kt
> bug: Job启动插件的状态在取消构建时未刷新 #5547

- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/trace/TraceFilter.kt
- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/trace/TraceTag.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/FeignConfiguration.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/handler/RemoteServiceExceptionMapper.kt
> feature: 将网关生成的rid在调用链中传递 #2405

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/expression/Lex.kt
- src/backend/ci/core/common/common-api/src/test/kotlin/com/tencent/devops/common/api/expression/GrammarAnalysisTest.kt
bugfix: 修复词法分析遇到 / 等符号解析错误的问题 #5477
> bugfix: 修复词法分析遇到 / 等符号解析错误的问题 #5477

- src/frontend/devops-pipeline/src/components/BuildHistoryTab/index.vue
- src/frontend/devops-pipeline/src/mixins/pipeline-operate-mixin.js
bug：非Admin用户 复制另一个项目的流水线链接 打开，提示没有权限 点击申请权限没有反应 issue #5461
> bug：非Admin用户 复制另一个项目的流水线链接 打开，提示没有权限 点击申请权限没有反应 issue #5461

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/AbstractBuildResourceApi.kt
> feat: 调整agent接口调用默认超时时间 #5528

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/StagePauseCheck.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/UpdateStateForStageCmdFinally.kt
> bug: stage被跳过时准出依然被拦截 #5580

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/utils/code/svn/SvnUtils.kt
- src/backend/ci/core/common/common-scm/src/test/kotlin/com/tencent/devops/scm/utils/code/svn/SvnUtilsTest.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepoFileService.kt
> bug: svn获取文件内容提示没有权限 #5575

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/bean/DefaultPipelineUrlBeanImpl.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/bean/PipelineUrlBean.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/config/PipelineUrlBeanConfiguration.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildBuildResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/notify/PipelineBuildNotifyListener.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/notify/PipelineExtendsNotifyConfiguration.kt
> feat：biz-process下pipelineUrlBean+DefaultPipelineUrlBeanImpl转移到公共部分biz-base

- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/AbstractDockerHostBuildService.kt
> feat：bazel cache rsyn时排除install和cache目录 #5595

- src/backend/ci/core/store/biz-store-image-sample/src/main/kotlin/com/tencent/devops/store/service/image/impl/SampleImageInitService.kt
> [1.5] bug: 市场镜像初始化op接口报错 #5603

- src/backend/ci/core/common/common-environment-thirdpartyagent/src/main/kotlin/com/tencent/devops/common/environment/agent/AgentGrayUtils.kt
- src/backend/ci/core/common/common-environment-thirdpartyagent/src/main/kotlin/com/tencent/devops/common/environment/agent/config/ThirdPartyAgentConfiguration.kt
- src/backend/ci/core/environment/api-environment/src/main/kotlin/com/tencent/devops/environment/api/thirdPartyAgent/OpThirdPartyAgentUpgradeResource.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/resources/thirdPartyAgent/OpThirdPartyAgentUpgradeResourceImpl.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdPartyAgent/AgentUpgradeService.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdPartyAgent/AgentUpgrdeJob.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdPartyAgent/UpgradeService.kt
- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/service/environment/AgentUpgradeService.kt
> bug: agent版本控制区分集群 #5579

- src/gateway/core/lua/util/tag_util.lua
> bug: 网关获取tag , devops_project不能为空 #5608

- src/backend/ci/core/common/common-dispatch-sdk/src/main/kotlin/com/tencent/devops/common/dispatch.sdk/service/DispatchService.kt
- src/backend/ci/core/dispatch-docker/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/docker/config/ScheduleConfig.kt
- src/backend/ci/core/dispatch-docker/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/docker/service/DockerHostBuildService.kt
- src/backend/ci/core/dispatch-docker/boot-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/docker/DispatchDockerApplication.kt
> feat: dispatch-docker定时任务优化 #5615

- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/dispatcher/Dispatcher.kt
- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/dispatcher/agent/ThirdPartyAgentDispatcher.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/mq/PipelineAgentStartupEvent.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchVMStartupTaskAtom.kt
feat: 【第三方构建资源池】支持配置任务排队超时时间 #5563
> feat: 【第三方构建资源池】支持配置任务排队超时时间 #5563

- src/backend/ci/core/auth/biz-auth-blueking/src/main/kotlin/com/tencent/devops/auth/AuthConfiguration.kt
- src/backend/ci/core/auth/biz-auth-blueking/src/main/kotlin/com/tencent/devops/auth/service/BkAuthPermissionService.kt
- src/backend/ci/core/auth/biz-auth-blueking/src/main/kotlin/com/tencent/devops/auth/service/BkPermissionProjectService.kt
- src/backend/ci/core/auth/biz-auth-blueking/src/main/kotlin/com/tencent/devops/auth/service/BkPermissionService.kt
- support-files/bkiam/0005_bk_ci_20200623-2120_iam.json
- support-files/bkiam/bk_ci_action_20211124_v.1.7_iam.json
1. 添加auth 企业版相关实现。
2. 添加all_action权限模型
> feat: 添加企业版auth相关实现 #5601

- support-files/bkiam/0003_resource_20211125_iam-v1.7.json
- support-files/bkiam/0004_instance-views_20211125_iam-v1.7.json
- support-files/bkiam/0005_action_20211125_iam-v1.7.json
- support-files/bkiam/0006_group_20211125_iam-v1.7.json
- support-files/bkiam/0007_create-related_20211125_iam-v1.7.json
> feat: 开源版质量红线 #5585 添加红线iamjson

- src/backend/ci/core/sign/api-sign/src/main/kotlin/com/tencent/devops/sign/api/pojo/IpaSignInfo.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/impl/SignServiceImpl.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/utils/SignUtils.kt
> feat: codesign签名命令支持自定义传参 #5622

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
> bug: 历史页面推荐版本号丢失 #5629

- src/agent/build_windows.bat
- src/agent/src/cmd/daemon/main_win.go
> feat: 构建机导入流程优化 #4686

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/dao/v2/QualityRuleDao.kt
> bug: 停用红线接口报错 #5633

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> feat:流水线列表页筛选条件优化 #5660

- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/common/OpenStoreResource.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/common/OpenStoreResourceImpl.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/env/AgentEnv.kt
feat:增加组件与项目间的权限校验open类接口 #5667
> feat:增加组件与项目间的权限校验open类接口 #5667

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/option/JobControlOption.kt
- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/dispatcher/agent/ThirdPartyAgentDispatcher.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/mq/PipelineAgentStartupEvent.kt
feat: 【第三方构建资源池】支持配置任务排队超时时间 #5563 取消默认值
> feat: 【第三方构建资源池】支持配置任务排队超时时间 #5563 取消默认值

- src/backend/ci/core/common/common-client/src/main/kotlin/com/tencent/devops/common/client/consul/ConsulConstants.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/ProjectRouteTagService.kt
> feat: 项目所属集群添加cache #5674

- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/p4/P4ShelveTriggerHandler.kt
> feat: 新增支持Perforce(P4)代码库配置和触发能力 #5312

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/event/CallBackData.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/CallBackControl.kt
> feat: callback添加name相关字段 #5707

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/constant/ProcessMessageCode.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
bug: 模板更新时，需要更新setting的name #5645
> bug: 模板更新时，需要更新setting的name #5645

- src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/log/meta/Ansi.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/logger/LoggerService.kt
feat: bash/batch脚本执行失败时，增加通用提示 #5659
> feat: bash/batch脚本执行失败时，增加通用提示 #5659

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
> bug:修复插件input环境变量替换问题 #5682

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/dao/v2/QualityRuleBuildHisDao.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleBuildHisService.kt
bug: 批量处理后台超过24h未审核的红线失败记录 #5695.
> bug: 批量处理后台超过24h未审核的红线失败记录 #5695

- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/image/ImageBuildHandler.kt
> feat：镜像推送异步模式 #5640

- src/backend/ci/build.gradle.kts
- src/backend/ci/buildSrc/src/main/kotlin/constants/Versions.kt
> feat: 升级log4j #5752

- src/gateway/core/lua/util/tag_util.lua
> bug: tag路由优先级会被local cache给占用 , 导致策略失效问题 #5741

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwQualityResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwQualityResourceV3Impl.kt
- src/backend/ci/core/quality/api-quality/src/main/kotlin/com/tencent/devops/quality/api/v3/ServiceQualityRuleResource.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/resources/v3/ServiceQualityRuleV3ResourceImpl.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityHistoryService.kt
> feat: 新增获取流水线红线接口 #5764

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/Constants.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/PipelineVarUtil.kt
> feat： ci上下文补充 #5750

- src/frontend/devops-pipeline/src/views/list/restore.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
feat: 流水线回收站增加删除人字段 issue #5692
> feat: 流水线回收站增加删除人字段 issue #5692

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeGitScmImpl.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeGitScmOauthImpl.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeGitlabScmImpl.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeSvnScmImpl.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeTGitScmImpl.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/pojo/RevisionInfo.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/scm/ScmProxyService.kt
feat: getLatestRevision方法添加字段 #5709
> feat: getLatestRevision方法添加字段 #5709

- src/backend/ci/core/quality/api-quality/src/main/kotlin/com/tencent/devops/quality/api/v2/pojo/QualityIndicator.kt
- src/backend/ci/core/quality/api-quality/src/main/kotlin/com/tencent/devops/quality/api/v3/BuildQualityIndicatorResource.kt
- src/backend/ci/core/quality/api-quality/src/main/kotlin/com/tencent/devops/quality/pojo/enum/RunElementType.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/resources/v3/BuildQualityIndicatorV3ResourceImpl.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityIndicatorService.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleBuildHisService.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleService.kt
> feat: 脚本执行插件中，支持设置红线指标值 #5598

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserPipelineGroupResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineGroupResourceImpl.kt
> bug: 流水线标签不生效 #5787

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityIndicatorService.kt
bug: 研发商店查看质量红线指标界面，过滤掉已下架的指标 #5810
> bug: 研发商店查看质量红线指标界面，过滤掉已下架的指标 #5810

- src/backend/ci/core/dispatch-docker/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/docker/dao/PipelineDockerBuildDao.kt
- src/backend/ci/core/dispatch-docker/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/docker/service/DockerHostBuildService.kt
- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/DockerService.kt
> bug: 构建镜像扫描输入字段缺失fix #5818

- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/service/process/ProcessMiscService.kt
bug:刷新projectId构建详情记录空数组判断优化 #5684
#5684
> bug:刷新projectId构建详情记录空数组判断优化 #5684

- scripts/bkenv.properties
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/ProjectTagService.kt
- support-files/templates/#etc#ci#application-project.yml
> feat:项目集群相关代码优化 #5775

- src/gateway/core/map.conf
- support-files/templates/gateway#core#server.common.conf
> feat: 网关获取访问的agent类型 #5795

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/AbstractBuildResourceApi.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/env/DockerEnv.kt
> feat: 优化agent download接口重试策略 #5857

- src/backend/ci/core/buildless/biz-buildless/src/main/kotlin/com/tencent/devops/buildless/ContainerPoolExecutor.kt
> bug: BuildLess codecc问题修复 #5869

- src/backend/codecc/build.gradle
- src/backend/codecc/core/defect/biz-defect/src/main/java/com/tencent/bk/codecc/defect/component/NewCCNDefectTracingComponent.java
- src/backend/codecc/core/defect/biz-defect/src/main/java/com/tencent/bk/codecc/defect/component/NewLintDefectTracingComponent.java
- src/backend/codecc/core/defect/biz-defect/src/main/java/com/tencent/bk/codecc/defect/consumer/CLOCDefectCommitConsumer.java
- src/backend/codecc/core/defect/biz-defect/src/main/java/com/tencent/bk/codecc/defect/consumer/DUPCDefectCommitConsumer.java
- src/backend/codecc/core/defect/biz-defect/src/main/java/com/tencent/bk/codecc/defect/service/impl/UpdateDefectBizServiceImpl.java
bugfix: 修复CodCC白名单无效问题
bugfix: 升级Log4j2版本
> bugfix: 修复CodCC白名单无效问题 #5802

- src/backend/ci/core/artifactory/api-artifactory/src/main/kotlin/com/tencent/devops/artifactory/api/service/ServiceArtifactoryResource.kt
- src/backend/ci/core/artifactory/biz-artifactory-sample/src/main/kotlin/com/tencent/devops/artifactory/resources/ServiceArtifactoryResourceImpl.kt
> feat: Artifactory创建下载链接新增creatorId #5848

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
feat:【人工审核插件】审核人配置把自己剔除后，历史构建rebuild无法触发审核 #5728
> feat:【人工审核插件】审核人配置把自己剔除后，历史构建rebuild无法触发审核 #5728

- src/frontend/devops-nav/src/index.html
feature: cookie写到三级域名下 issue #5609
> feature: cookie写到三级域名下 issue #5609

- src/backend/ci/core/common/common-dispatch-sdk/src/main/kotlin/com/tencent/devops/common/dispatch.sdk/config/MQConfiguration.kt
- src/backend/ci/core/common/common-event/src/main/kotlin/com/tencent/devops/common/event/dispatcher/pipeline/mq/MQ.kt
- src/backend/ci/core/common/common-event/src/main/kotlin/com/tencent/devops/common/event/pojo/pipeline/PipelineBuildCancelBroadCastEvent.kt
- src/backend/ci/core/common/common-quality/src/main/kotlin/com/tencent/devops/common/quality/pojo/enums/RuleInterceptResult.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineStageService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/CheckPauseReviewStageCmd.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/UpdateStateForStageCmdFinally.kt
- src/backend/ci/core/quality/api-quality/src/main/kotlin/com/tencent/devops/quality/constant/MQ.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/dao/v2/QualityRuleBuildHisDao.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/listener/PipelineBuildQualityListener.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityHistoryService.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleBuildHisService.kt
bug: 流水线重试和取消执行时，红线状态问题fix #5740
> bug: 流水线重试和取消执行时，红线状态问题fix #5740

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/Stage.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildContainerDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/extend/DefaultModelCheckPlugin.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildDetailService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineContainerService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildCancelControl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildMonitorControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineInfoFacadeService.kt
> bug: stage准出红线拦截状态不刷新 #5873

- src/backend/ci/core/common/common-event/src/main/kotlin/com/tencent/devops/common/event/dispatcher/pipeline/mq/MQ.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/Stage.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/StagePauseCheck.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/extend/DefaultModelCheckPlugin.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildDetailService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineStageService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineContextService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/init/BuildEngineCoreContainerConfiguration.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineInfoFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> bug: 矩阵上下文覆盖问题 #5881

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildVarResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildVarResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/enums/VariableType.kt
feat： 【流水线插件】适配上下文方式传递变量 - Java插件 sdk方法 #5860
> feat： 【流水线插件】适配上下文方式传递变量 - Java插件 sdk方法 #5860

- src/backend/ci/core/openapi/api-openapi/build.gradle.kts
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwSignResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwSignResourceV3Impl.kt
- src/backend/ci/core/sign/api-sign/src/main/kotlin/com/tencent/devops/sign/api/pojo/SignHistory.kt
- src/backend/ci/core/sign/api-sign/src/main/kotlin/com/tencent/devops/sign/api/service/ServiceIpaResource.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/dao/SignHistoryDao.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/resources/ServiceIpaResourceImpl.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/service/SignInfoService.kt
> api: 添加iOS企业签名任务列表拉取接口 #5015

- src/backend/booster/Makefile
- src/backend/booster/tools/hook_ld_preload/hook_lib/execve_hook.cpp
- src/backend/booster/win_compile.bat
> bug: avoid crash with setenv, issue: #5817

- src/backend/ci/core/common/common-auth/common-auth-api/src/main/kotlin/com/tencent/devops/common/auth/api/AuthResourceType.kt
- src/backend/ci/core/quality/biz-quality-sample/src/main/kotlin/com/tencent/devops/quality/QualityConfiguration.kt
- src/backend/ci/core/quality/biz-quality-sample/src/main/kotlin/com/tencent/devops/quality/service/AbsQualityPermissionServiceImpl.kt
- src/backend/ci/core/quality/biz-quality-sample/src/main/kotlin/com/tencent/devops/quality/service/SampleQualityPermissionServiceImpl.kt
- src/backend/ci/core/quality/biz-quality-sample/src/main/kotlin/com/tencent/devops/quality/service/V3QualityPermissionServiceImpl.kt
- support-files/bkiam/0003_resouce_20211221_iam-v1.7.json
- support-files/bkiam/0004_instance-views_20211125_iam-v1.7.json
- support-files/bkiam/0005_action_20211125_iam-v1.7.json
- support-files/bkiam/0006_group_20211125_iam-v1.7.json
- support-files/bkiam/0007_create-related_20211125_iam-v1.7.json
- support-files/ms-init/auth/iam-callback-resource-registere.conf
1. 质量红线兼容*相关逻辑。
2. 调整iam权限模型。
3. 添加iam回调资源相关配置
> feat:质量红线开源权限相关调整 #5849

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/Stage.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/extend/DefaultModelCheckPlugin.kt
> bug: 插件标识判断增加step id #5881

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/BuildParameters.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/context/StartBuildContext.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineContainerService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
> bug: 补充修复重试次数刷新 #5881

- docs/install/gateway.en.md
- docs/install/gateway.md
> fix: 更新OpenResty下载路径 #5923

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwSignResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwSignResourceV3Impl.kt
- src/backend/ci/core/sign/api-sign/src/main/kotlin/com/tencent/devops/sign/api/service/ServiceIpaResource.kt
- src/backend/ci/core/sign/biz-sign-sample/src/main/kotlin/com/tencent/devops/sign/service/impl/ArchiveServiceImpl.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/resources/BuildIpaResourceImpl.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/service/ArchiveService.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/utils/SignUtils.kt
> feat: 签名插件支持归档到父流水线的操作 #5737

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/template/TemplateDao.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/leaf/JooqIDAllocDaoImpl.kt
pref:取最新模板的方式由ID排序改为创建时间排序 #5938
#5938
> pref:取最新模板的方式由ID排序改为创建时间排序 #5938

- src/backend/booster/bk_dist/booster/command/command.go
- src/backend/booster/bk_dist/booster/command/process.go
- src/backend/booster/bk_dist/ubttool/command/process.go
- src/backend/booster/bk_dist/ubttool/common/types.go
- src/backend/booster/bk_dist/ubttool/pkg/ubttool.go
优化 bk-ubt-tool 处理编译错误时的逻辑，当任务有错误发生时，后续依赖该任务的其它任务不会再执行
> bug: bk-ubt-tool在错误处理时，和ue原始逻辑有差异

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineContextService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/ContainerControl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/MatrixExecuteContainerCmd.kt
> bug: Container事件处理缺少状态校验 #5951

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineTaskService.kt
> bug: 失败插件变量传值异常 #5969

- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/config/DataSourceConfig.kt
- src/backend/ci/core/misc/boot-misc/src/main/kotlin/com/tencent/devops/misc/MiscApplication.kt
perf:蓝盾引擎模块对应的数据库支持分库 #5267
#5267
> perf:蓝盾引擎模块对应的数据库支持分库 #5267

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/context/StartBuildContext.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineContextService.kt
> bug: 跳过插件时stage状态刷新异常 #5974

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/template/TemplateDao.kt
> pref:获取最新模板优化 #5979

- src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/enums/code/tgit/TGitObjectKind.kt
- src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/enums/code/tgit/TGitTagPushKind.kt
- src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/pojo/code/git/GitEvent.kt
- src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/pojo/code/git/GitPushEvent.kt
- src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/pojo/code/git/GitTagPushEvent.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitPushTriggerHandler.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitTagPushTriggerHandler.kt
【触发器】支持监听分支/tag删除事件的core部分改动 #5907
> 【触发器】支持监听分支/tag删除事件的core部分改动 #5907

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/CodeGitWebHookTrigger.vue
bug: git事件触发选择锁定提交，就一定回写commit check issue #5820
> bug: git事件触发选择锁定提交，就一定回写commit check issue #5820

- src/frontend/devops-pipeline/src/components/AtomFormComponent/DynamicParameter/index.vue
feature: 动态参数组件模型变更兼容老数据 issue #5927
> feature: 动态参数组件模型变更兼容老数据 issue #5927

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
bug:模板版本列表显示的第一个版本不一定是最新的 #5989
#5989
> bug:模板版本列表显示的第一个版本不一定是最新的 #5989

- src/backend/ci/core/common/common-client/src/main/kotlin/com/tencent/devops/common/client/consul/ConsulFilter.kt
- src/backend/ci/core/common/common-client/src/main/kotlin/com/tencent/devops/common/client/ms/MicroServiceTarget.kt
> bug: Process路由信息被OpenAPI污染，导致router错误 #5990

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/pojo/GitProjectGroupInfo.kt
- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/dispatcher/agent/ThirdPartyAgentDispatcher.kt
- src/backend/ci/core/environment/biz-environment/build.gradle.kts
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/dao/EnvShareProjectDao.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdPartyAgent/ThirdPartyAgentMgrService.kt
- src/backend/ci/core/environment/model-environment/build.gradle.kts
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/scm/ServiceGitResource.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/scm/ServiceGitResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/GitService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/IGitService.kt
feat: 跨项目使用构建机支持分享给项目组下的所有项目 #5922
> feat: 跨项目使用构建机支持分享给项目组下的所有项目 #5922

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/impl/UserSensitiveConfServiceImpl.kt
pref:插件私有配置为FRONTEND或者ALL类型时不做校验 #6002
#6002
> pref:插件私有配置为FRONTEND或者ALL类型时不做校验 #6002

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/PipelineStageTagDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineRuleDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/dao/PipelineRemoteAuthDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/template/TemplateInstanceBaseDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/template/TemplateInstanceItemDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
pref:分库的公共表的插入动作防止主键冲突 #6000
#6000
> pref:分库的公共表的插入动作防止主键冲突 #6000

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/constant/CommonMessageCode.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/agent/LinuxScriptElement.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/agent/WindowsScriptElement.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceBuildResource.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServiceBuildResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/ScriptTask.kt
feat: bash/batch脚本执行失败时，增加常见错误FAQ链接 #5985
feat: 获取构建历史API支持根据时间段查询 #5993
> feat: 获取构建历史API支持根据时间段查询 #5993

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleCheckService.kt
> bug: stream流水线重试红线状态不正确 #6017

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/setting/PipelineSetting.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineInfoFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
> bug:源模板查询逻辑修改 #6025

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/template/TemplateDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/template/service/TemplateService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/template/TemplateInstanceCronService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
bug:研发商店安装的模板业务逻辑查询优化 #6031
#6031
> bug:研发商店安装的模板业务逻辑查询优化 #6031

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
插件setEnv可设置备注。且立即生效。 多次设置，后一次会覆盖前一次
> feat: 执行历史界面，支持部分字段能在流水线执行过程中展示 #650

- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/param/GitWebhookElementParams.kt
> bug: git事件触发选择锁定提交，就一定回写commit check #5820

- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/sharding/BkProcessDatabaseShardingAlgorithm.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/template/TemplateDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/sharding/BkProcessDatabaseShardingAlgorithm.kt
bug:查项目下公共模板or条件优化 #6047
#6047
> bug:查项目下公共模板or条件优化 #6047

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserPipelineQualityResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserPipelineResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineQualityResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineResourceImpl.kt
- src/backend/ci/core/quality/api-quality/src/main/kotlin/com/tencent/devops/quality/api/v2/UserQualityRuleResource.kt
fix: 开源版质量红线相关异常 #1579. fix api path
> fix: 开源版质量红线相关异常 #1579

- src/backend/ci/buildSrc/build.gradle.kts
- src/backend/ci/buildSrc/src/main/kotlin/constants/Versions.kt
- src/backend/codecc/build.gradle
> fix: Upgrade log4j 2.17.0 to 2.17.1 #6030

- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/config/JooqConfiguration.kt
- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/cron/process/PipelineBuildHistoryDataClearJob.kt
- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/dao/process/ProcessDao.kt
- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/service/process/ProcessMiscService.kt
- support-files/templates/#etc#ci#application-assembly.yml
- support-files/templates/#etc#ci#application-misc.yml
pref:数据库分库完后对冗余历史数据清理 #6053
#6053
> pref:数据库分库完后对冗余历史数据清理 #6053

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/Container.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/NormalContainer.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/TriggerContainer.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/VMBuildContainer.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineContextService.kt
> bug: 自定义执行条件判断未支持矩阵上下文 #6071

- src/backend/ci/core/notify/api-notify/src/main/kotlin/com/tencent/devops/notify/Constants.kt
> feat: notify新增通知类型 #6105

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/PipelineSettingDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/label/PipelineLabelPipelineDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineResDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/template/TemplatePipelineDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/label/PipelineGroupService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineStatusService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineListFacadeService.kt
> feat: 优化listPermissionPipeline方法 #6066

- src/backend/ci/build.gradle.kts
- src/backend/ci/buildSrc/src/main/kotlin/constants/Versions.kt
> fix: bcprov版本升级 #5903 

- src/frontend/devops-pipeline/src/views/template/edit.vue
fix: 模板里面设置版本号带有/无法进行删除 issue #6023
> fix: 模板里面设置版本号带有/无法进行删除 issue #6023

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/index.vue
> feat: 插件名字长度限制30个字符 #734

- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
perf: Stage准入审批时间限制提示文案优化 #6086
> perf: Stage准入审批时间限制提示文案优化 #6086

- src/frontend/devops-quality/src/views/create_rules.vue
pref: 编辑红线规则生效范围文案调整 issue #6112
> pref: 编辑红线规则生效范围文案调整 issue #6112

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomEnvServiceImpl.kt
feat:支持老插件的前端使用新插件的渲染方式 #6111
#6111
> feat:支持老插件的前端使用新插件的渲染方式 #6111

- src/gateway/core/lua/util/build_util.lua
- src/gateway/core/nginx.conf
> feat: 蓝盾网关新增build鉴权缓存 #6134

- src/backend/ci/core/store/biz-store-sample/src/main/kotlin/com/tencent/devops/store/service/atom/impl/SampleAtomReleaseServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
bug:插件大版本下小版本更新取分支代码信息修复 #6120
#6120
> bug:插件大版本下小版本更新取分支代码信息修复 #6120

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwBuildResourceV3.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwBuildResourceV4.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwBuildResourceV4Impl.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/service/IndexService.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceBuildResource.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildDetailService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServiceBuildResourceImpl.kt
feat: openapi参数优化 #5968 仅优化了部分接口
> feat: openapi参数优化 #5968

- src/backend/ci/.gitignore
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwSignResourceV3Impl.kt
- src/backend/ci/core/sign/api-sign/src/main/kotlin/com/tencent/devops/sign/api/pojo/SignHistory.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/dao/SignHistoryDao.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/dao/SignIpaInfoDao.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/service/SignInfoService.kt
> feat: 签名增加历史信息查询 #4716

- src/backend/ci/core/plugin/biz-plugin/src/main/kotlin/com/tencent/devops/plugin/service/ScmCheckService.kt
- src/backend/ci/core/plugin/biz-plugin/src/main/kotlin/com/tencent/devops/plugin/utils/QualityUtils.kt
- src/backend/ci/core/quality/api-quality/src/main/kotlin/com/tencent/devops/quality/api/v2/ServiceQualityInterceptResource.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityHistoryService.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/util/QualityUrlUtils.kt
> feat: 红线git评论分开发送 #6118

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleCheckService.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleService.kt
需要人工审批的质量红线，告警通知时除“审批人”之外，希望也能通知“流水线触发者”
> 需要人工审批的质量红线，告警通知时除“审批人”之外，希望也能通知“流水线触发者” #3741

- src/backend/ci/core/quality/api-quality/src/main/kotlin/com/tencent/devops/quality/constant/CodeccConstants.kt
> feat: 查看CodeCC红线指标详情过滤已修复状态 #6125

- src/frontend/devops-environment/src/components/devops/environment/node-select-dialog.vue
feat: 环境管理-环境-选择节点-页面这里能够显示机器别名 issue #2601
> feat: 环境管理-环境-选择节点-页面这里能够显示机器别名 issue #2601

- src/frontend/devops-pipeline/src/components/Stages/Job.vue
- src/frontend/devops-pipeline/src/components/Stages/Stage.vue
> bug: Stage1应不能被删除 issue #6122

- src/frontend/devops-pipeline/src/store/modules/atom/getters.js
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
fix： 流水线名称为空时流水线编排不应被写入后台 issue #6140
> fix： 流水线名称为空时流水线编排不应被写入后台 issue #6140

- scripts/bk-ci-gen-jrezip.sh
change bk-ci/scripts/bk-ci-gen-jrezip.sh with bcprov-jdk*.jar
> gateway install fail #6145

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/matrix/MatrixConfig.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/option/MatrixControlOption.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/utils/MatrixContextUtils.kt
- src/backend/ci/core/common/common-pipeline/src/test/kotlin/com/tencent/devops/common/pipeline/option/MatrixControlOptionTest.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-process/src/test/kotlin/com/tencent/devops/process/util/MatrixYamlCheckUtilsTest.kt
> feat: 矩阵策略fromJson解析优化 #6099

- src/backend/ci/core/quality/api-quality/src/main/kotlin/com/tencent/devops/quality/constant/CodeccConstants.kt
查看CodeCC红线指标详情过滤已修复状态 #6125. rollback
> feat: 查看CodeCC红线指标详情过滤已修复状态 #6125. rollback

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityControlPointService.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityIndicatorService.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityMetadataService.kt
feat: quality侧增加插件指标相关日志方便问题定位
> feat: quality侧增加插件指标相关日志方便问题定位 #6191

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityIndicatorService.kt
> bug: 研发商店红线指标列表返回空数据 #6175

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwBuildResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwBuildResourceV3Impl.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceBuildResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/BuildHistory.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServiceBuildResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
- support-files/sql/2008_ci_process-update_v1.9_mysql.sql
[【API】build_list接口提供历史构建更新时间字段，并支持构建列表按更新时间排序]
> 【API】build_list接口提供历史构建更新时间字段，并支持构建列表按更新时间排序 #5774

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineListFacadeService.kt
> feat: listPermissionPipeline加一个特殊项目的配置 #6195

- src/backend/ci/core/common/common-util/src/main/kotlin/com/tencent/devops/common/util/HttpRetryUtils.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/AbstractBuildResourceApi.kt
> bug：下载插件超时问题 fix #6178

- src/backend/booster/bk_dist/controller/pkg/manager/manager.go
之前是按照 batch mode处理的，只会找到一个work并设置工具链信息
在非batch mode下，会导致工具链信息设置不全
现在改成设置到所有满足条件的work里
> bug: fix missing set tool chain in ue with non-batch mode ，issue: #6154

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildSummaryDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineListFacadeService.kt
> perf: 优化拉取有权限的流水线列表接口 #6195

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/CommandLineUtils.kt
> feat: 流水线编辑页面增加 Step ID配置 #5947

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/ReferenceVariable.vue
- src/frontend/devops-pipeline/src/components/PipelineVersionsForm.vue
fix: 开启推荐版本号后，版本号变量展示新版变量 issue #6162
> fix: 开启推荐版本号后，版本号变量展示新版变量 issue #6162

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineBuildExtServiceImpl.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineContextService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/CheckConditionalSkipContainerCmd.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/StartActionTaskContainerCmd.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/CheckConditionalSkipStageCmd.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceVarResourceImpl.kt
[feat: stage上下文增加执行状态信息](https://github.com/Tencent/bk-ci/commit/d112fd4f029e407520ef444e189b13dcb26702b9) https://github.com/Tencent/bk-ci/issues/6201
> feat: stage上下文增加执行状态信息 #6201

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomServiceImpl.kt
feat: 【研发商店】当插件输入组件类型为 key-value-normal 时，YAML片段优化 #6224
> feat: 【研发商店】当插件输入组件类型为 key-value-normal 时，YAML片段优化 #6224

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineListFacadeService.kt
> bug: listPermissionPipeline 的分页需要限制 #6228

- src/backend/ci/core/dispatch-docker/api-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/docker/pojo/DockerHostBuildInfo.kt
- src/backend/ci/core/dispatch-docker/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/docker/client/DockerHostClient.kt
- src/backend/ci/core/dispatch-docker/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/docker/utils/RedisUtils.kt
- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/DockerService.kt
- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/container/ContainerHandlerContext.kt
- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/generator/impl/SystemDockerBindGenerator.kt
> feat: 专机集群挂载路径配置优化 #6226

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/utils/VersionUtils.kt
bug:插件按版本查询task.json逻辑优化 #5909
#5909
> bug:插件按版本查询task.json逻辑优化 #5909

- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/cron/process/PipelineBuildHistoryDataClearJob.kt
- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/dao/process/ProcessDao.kt
- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/service/process/ProcessMiscService.kt
pref:清数据逻辑避免对大项目的构建数据进行深度分页 #6143
#6143
> pref:清数据逻辑避免对大项目的构建数据进行深度分页 #6143

- scripts/bkenv.properties
- support-files/templates/#etc#ci#application-project.yml
> feat: 多级群配置文件更新 #6119

- src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/resources/ServiceDockerHostResourceImpl.kt
> feat: 拉取代码加速缓存方案优化 #6241

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/template/UserPTemplateResourceImpl.kt
模板里面设置版本号带有“/”无法进行删除 issue:#6023
>  模板里面设置版本号带有“/”无法进行删除 issue:Tencent#6023

- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/filter/UserFilter.kt
- src/backend/ci/core/process/plugin-trigger/src/main/kotlin/com/tencent/devops/process/plugin/trigger/configuration/TriggerConfiguration.kt
> bug: git事件触发插件配置过滤用户使用变量时不触发 #6270

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/detail/TaskBuildDetailService.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/atom/ServiceAtomResource.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/AtomDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/MarketAtomDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/MarketAtomEnvInfoDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/atom/ServiceAtomResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/AtomService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/MarketAtomCommonService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomCommonServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomEnvServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/OpAtomServiceImpl.kt
- support-files/sql/1001_ci_store_ddl_mysql.sql
- support-files/sql/2008_ci_store-update_v1.8_mysql.sql
pref:获取插件环境信息接口性能优化 #6265
#6265
> pref:获取插件环境信息接口性能优化 #6265

- src/frontend/devops-environment/src/components/devops/environment/node-select-dialog.vue
> fix: 导入环境弹窗优化 issue #6171

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
bug：插件task.json的demands数组解析存在异常 #6127
> bug：插件task.json的demands数组解析存在异常 #6127

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/AuthPipelineService.kt
> bug: 流水线IAM回调不再获取管理员信息 #6298

- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepositoryService.kt
>  feat:希望代码库能支持关联企业版工蜂 Tencent#6088

- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/aspect/ApiAspect.kt
> feat: openapi新增gitProjectId支持 #6307

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
fix: 模板更新时，模板中存在当前项目没有有权限使用的插件、镜像不报错 #4751
> fix: 模板更新时，模板中存在当前项目没有有权限使用的插件、镜像不报错 #4751

- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwLogResourceV3Impl.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwLogResourceV4Impl.kt
fix v3_app_log_download header问题 #6337
> fix v3_app_log_download header问题 #6337

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/logger/LoggerService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/SensitiveValueService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/TaskDaemon.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/CredentialUtils.kt
日志脱敏 #4273 在agent内处理敏感信息的打印与上报
> feat: 日志脱敏 #4273 在agent内处理敏感信息的打印与上报

- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/jmx/LogStorageBean.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/LogService.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/impl/LogServiceESImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/impl/LogServiceLuceneImpl.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/TaskDaemon.kt
> feat: 日志脱敏 #4273 优化日志下载接口

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserPipelineAtomResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineAtomResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineAtomService.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/atom/ServiceAtomResource.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/atom/AtomBaseInfoUpdateRequest.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/atom/AtomProp.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/atom/MarketAtomUpdateRequest.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/AtomDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/AtomPropDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/MarketAtomDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/atom/ServiceAtomResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/AtomPropService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomPropServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
feat:根据流水线ID获取流水线下插件属性数据 #6285
#6285
> feat:根据流水线ID获取流水线下插件属性数据 #6285

- scripts/bkenv.properties
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/client/InfluxdbClient.kt
- support-files/templates/gateway#core#devops.server.conf
> feat: 开启influxdb采集构建机详情 #6275

- src/backend/ci/core/worker/worker-api-sdk/src/main/kotlin/com/tencent/devops/worker/common/api/archive/BkRepoResourceApi.kt
> bug: 归档文件名包含特殊字符导致归档失败 #6348

- src/backend/codecc/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/utils/MessageCodeUtil.kt
> fix: CodeCC 错误信息提示不正确 #6339

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/AtomDao.kt
bug:当一个项目被多次设置一个插件的调试项目会造成查出多条重复版本记录 #6375
#6375
> bug:当一个项目被多次设置一个插件的调试项目会造成查出多条重复版本记录 #6375

- support-files/templates/#etc#ci#application-misc.yml
perf:开源版清数据逻辑开关调整为默认关闭 #6378
#6378
> perf:开源版清数据逻辑开关调整为默认关闭 #6378

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/control/ControlUtils.kt
> feat : 当stage/job/step 因为不满足条件而跳过时，增加日志明确展示跳过的原因 #6366

- src/agent/src/pkg/job/build.go
- src/agent/src/pkg/job/build_manager.go
> feat: 完善私有构建机不认领任务的出错信息 #5806

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/ScmFactory.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/ScmOauthFactory.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeGitlabScmImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/dao/RepositoryCodeGitLabDao.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepositoryService.kt
- support-files/sql/2008_ci_repository-update_v1.8_mysql.sql
> Feat:【代码库】关联gitlab代码库时，去掉只支持http协议的限制 #3355

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/OkhttpUtils.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/git/api/GitApi.kt
> bug: okhttp3 状态码为301时会把post请求转换成get请求 #2894

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/context/StartBuildContext.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/control/DependOnUtils.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> bug: Job2依赖Job1，Job1首次执行失败，重试成功后Job2没有执行 #5175

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/CredentialUtils.kt
> feat: 上下文部分逻辑优化 #6372

- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/ThirdPartyAgentMonitorService.kt
3分钟如果Agent端发起了构建任务领取后还没启动，尝试回退到队列让其以便能重新领取到。
用于解决Agent端几类极端问题场景：
*  1、网络问题导致Agent侧领取中断，数据包丢失，没有收到领取任务，但任务已经被改成RUNNING，需要回退。
*  2、Agent领取后未处理构建前，进程意外退出
未解决的场景：
*  本次不涉及构建机集群重新漂移指定其他构建机，需要重新设计。
> fix: Mac构建机切换用户因代理问题导致无法正常领取任务？ #4943

- src/frontend/devops-turbo/src/assets/js/util.js
- src/frontend/devops-turbo/src/components/exception/permission.vue
- src/frontend/devops-turbo/src/views/history/detail.vue
- src/frontend/devops-turbo/src/views/history/list.vue
- src/frontend/devops-turbo/src/views/index.vue
- src/frontend/devops-turbo/src/views/over-view/index.vue
- src/frontend/devops-turbo/src/views/task/detail.vue
- src/frontend/devops-turbo/src/views/task/init.vue
- src/frontend/devops-turbo/src/views/task/list.vue
feature: 编译加速服务下，无权限时展示优化 issue #6255
> feature: 编译加速服务下，无权限时展示优化 issue #6255

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/task/ManualReviewTaskAtom.kt
> bug: 人工审核插件通知标题未进行变量替换 #6430

- src/backend/booster/bk_dist/controller/pkg/manager/manager.go
> bug:add some logs for mac shader tool chain, issue: #6371

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/atom/ManualReviewParam.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineContextService.kt
[【stage审核】stage审核时，下拉类型的自定义变量支持通过变量动态定义可选值](https://github.com/Tencent/bk-ci/commit/c556680138d06ec584dbb68d042a18e202a01498) https://github.com/Tencent/bk-ci/issues/6465
> 【stage审核】stage审核时，下拉类型的自定义变量支持通过变量动态定义可选值 #6465

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/utils/ModelUtils.kt
> feat: task失败可以立即重试 #6400

- src/backend/codecc/core/codeccjob/biz-codeccjob/src/main/kotlin/com/tencent/bk/codecc/codeccjob/consumer/CodeScoringConsumer.kt
- src/backend/codecc/core/schedule/biz-schedule/src/main/java/com/tencent/bk/codecc/schedule/service/impl/ScheduleServiceImpl.java
bug: CodeCC没有读取到配置时未初始化默认值 #6499
> bug: CodeCC没有读取到配置时未初始化默认值 #6499

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/AbstractBuildResourceApi.kt
pref:worker模块下载接口读取文件流出错应该整个接口重试 #6404
> pref:worker模块下载接口读取文件流出错应该整个接口重试 #6404 

- README.md
- README_EN.md
> docs: README中增加JOB的外链 #6496

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/template/TemplateInstanceCronService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
> feat：模板实例化失败时没有原因提示 #6323

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/interceptor/TimerTriggerScmChangeInterceptor.kt
> bug: git拉取插件增加post ation后，导致定时触发插件“源代码未更新时不触发”失效 #6526

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/PipelineVarUtil.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineBuildService.kt
> feat: 支持variables上下文 #6482

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
> fix:关联模板到商店界面，切换项目 bug#6370

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/utils/code/git/GitUtils.kt
- src/backend/ci/core/common/common-scm/src/test/kotlin/com/tencent/devops/scm/utils/code/git/GitUtilsTest.kt
> bug: GitUtils#getDomainAndRepoName获取的项目名错误 #6513

- src/agent/src/cmd/agent/main.go
- src/agent/src/cmd/daemon/main.go
- src/agent/src/cmd/daemon/main_win.go
- src/agent/src/pkg/config/version.go
- src/agent/src/pkg/job/build.go
- src/agent/src/pkg/job/build_manager.go
- src/agent/src/pkg/util/command/command.go
- src/agent/src/pkg/util/systemutil/dir_operation.go
- src/agent/src/pkg/util/systemutil/dir_operation_win.go
- src/agent/src/pkg/util/systemutil/systemutil.go
- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/ThirdPartyAgentMonitorService.kt
#6545 
解决一个较极端的问题： Mac下使用root帐号安装Agent，但在devops.slave.user 指定了其他普通帐号来执行构建报无权限。
> fix: agent build_tmp 目录权限问题 #6545

- src/backend/codecc/build.gradle
> fix: CodeCC升级高危组件版本 #6575

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServicePipelineResource.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineInfoDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServicePipelineResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineSettingFacadeService.kt
updateLastModifyUser 存在问题 #6590
> updateLastModifyUser 存在问题 #6590

- support-files/templates/gateway#core#devops.server.conf
> bug: 网关启动报错修复 #6594

- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/service/ServiceProjectResource.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/ProjectDao.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/ServiceProjectResourceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/ProjectService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/ProjectTagService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
提供3个servcie接口。
1. 创建CI外的项目。
2. 修改项目名
3. 根据projectName获取项目信息。
以上三个接口都服务于stream开源
> feat: project 基础信息Service类接口 #6554

- src/backend/ci/core/process/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/modelCreate/ModelContainer.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/scm/ServiceGitResourceImpl.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/service/StreamTGitTransferService.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/StreamTriggerRequestService.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/StreamYamlBaseBuild.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/listener/components/SendNotify.kt
> feat: 新增Stream YAML服务 #6457

- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectDataSourceAssignServiceImpl.kt
- support-files/templates/#etc#ci#application-project.yml
pref:当process数据源都不处于可用状态时，给项目分配数据源时加上熔断配置 #6612
#6612
> pref:当process数据源都不处于可用状态时，给项目分配数据源时加上熔断配置 #6612

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
feat:模板管理-模板版本显示为按时间排序 #6563
#6563
> feat:模板管理-模板版本显示为按时间排序 #6563

- .github/ISSUE_TEMPLATE/support.md
- CODEOWNERS
> docs: 更新获得社区支持的方法

- src/backend/booster/bk_dist/handler/cc/utils.go
> feat: 编译加速支持gcc参数 -fprofile-dir #6569

- src/backend/ci/core/openapi/api-openapi/build.gradle.kts
- src/backend/turbo/api-turbo/build.gradle.kts
- src/backend/turbo/api-turbo/src/main/kotlin/com/tencent/devops/turbo/vo/TurboPlanDetailVO.kt
- src/backend/turbo/api-turbo/src/main/kotlin/com/tencent/devops/turbo/vo/TurboRecordHistoryVO.kt
- src/backend/turbo/biz-turbo/src/main/kotlin/com/tencent/devops/turbo/controller/ServiceTurboController.kt
- src/backend/turbo/biz-turbo/src/main/kotlin/com/tencent/devops/turbo/service/TurboRecordService.kt
- src/backend/turbo/build.gradle.kts
- src/backend/turbo/buildSrc/build.gradle.kts
- src/backend/turbo/buildSrc/settings.gradle.kts
- src/backend/turbo/buildSrc/src/main/kotlin/plugins/task-deploy-to-maven.gradle.kts
- src/backend/turbo/gradle.properties
> bugfix: 【编译加速】调用加速历史列表、加速方案详情的API时，响应体缺少时间字段 #6617

- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/configuration/LogMQConfiguration.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/BuildLogListenerService.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/LogService.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/impl/LogServiceESImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/impl/LogServiceLuceneImpl.kt
日志模块缓冲MQ队列机制优化 #3089 补充状态刷新时间处理
> perf: 日志模块缓冲MQ队列机制优化 #3089 补充状态刷新时间处理

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/engine/api/BuildJobResource.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/api/BuildJobResourceImpl.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/engine/EngineBuildSDKApi.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/engine/impl/EngineBuildResourceApi.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/EngineService.kt
- support-files/templates/#etc#ci#common.yml
> bug: 修复重试和任务认领失败的逻辑问题 #6646 [补充]

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/Constants.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/PipelineVarUtil.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineBuildExtServiceImpl.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineContextService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/CheckConditionalSkipContainerCmd.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/StartActionTaskContainerCmd.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/CheckConditionalSkipStageCmd.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildVarResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceVarResourceImpl.kt
- src/backend/ci/core/process/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/modelCreate/ModelCreate.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Constants.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/EngineService.kt
> bug: 修复重试和任务认领失败的逻辑问题 #6646

- src/backend/ci/core/ticket/biz-ticket/build.gradle.kts
- src/backend/ci/settings.gradle.kts
> feat: 升级存在漏洞的开源依赖组件 #6691

- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/atom/Atom.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/atom/AtomFeatureRequest.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/atom/AtomUpdateRequest.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/MarketAtomFeatureDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/OpAtomServiceImpl.kt
- support-files/sql/1001_ci_store_ddl_mysql.sql
- support-files/sql/2008_ci_store-update_v1.9_mysql.sql
feat:【研发商店】插件支持是否认证属性 #6539
#6539
> feat:【研发商店】插件支持是否认证属性 #6539

- src/backend/ci/core/artifactory/biz-artifactory-sample/src/main/kotlin/com/tencent/devops/artifactory/resources/UserPipelineFileResourceImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/resources/BuildLogPrintResourceImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/resources/UserLogResourceImpl.kt
- src/backend/ci/core/monitoring/biz-monitoring/src/main/kotlin/com/tencent/devops/monitoring/consumer/AtomMonitorReportListener.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserBuildResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineResourceImpl.kt
> feat: 新增一些prometheus的监控采集 #6628

- src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/enums/code/tgit/TGitPushKind.kt
- src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/pojo/code/git/GitPushEvent.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitPushTriggerHandler.kt
- src/backend/ci/core/process/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v2/enums/StreamTriggerAction.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/StreamYamlBuild.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/StreamYamlTrigger.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/BaseAction.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/data/context/StreamTriggerContext.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/streamActions/StreamDeleteAction.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/streamActions/StreamManualAction.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/streamActions/StreamOpenApiAction.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/streamActions/StreamRepoTriggerAction.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/streamActions/StreamScheduleAction.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/tgit/TGitActionGit.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/tgit/TGitMrActionGit.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/tgit/TGitPushActionGit.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/parsers/triggerMatch/TriggerMatcher.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/util/StreamTriggerMessageUtils.kt
[【stream】新建分支导致获取文件变更信息异常](https://github.com/Tencent/bk-ci/commit/0fe2caf903c335c927670d7f26342d615aa5b590) https://github.com/Tencent/bk-ci/issues/6723
> 【stream】新建分支导致获取文件变更信息异常 #6723

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildEndControl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildStartControl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/ContainerControl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/StageControl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/TaskControl.kt
> feat: 流水线SLA数据上报 #6737

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildTaskDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/pojo/UpdateTaskInfo.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineTaskService.kt
> bug: 修复重试和任务认领失败的逻辑问题 #6646 修复task表修改索引字段问题

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceWebhookBuildResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServiceWebhookBuildResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> feat: 新增webhook启动流水线接口 #6343

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceVarResourceImpl.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
> feat: Job环境变量支持凭据上下文引用 #6568 修复部分上下文问题

- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/mq/CoreRabbitMQConfiguration.kt
> bug: mq创建channel timed out #6764

- src/frontend/devops-codelib/src/components/CodeLibDialog/index.vue
- src/frontend/devops-codelib/src/store/actions.js
feature: 代码库获取项目列表耗时太长 issue #4290
> feature: 代码库获取项目列表耗时太长 issue #4290

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/ShellUtil.kt
> 第三方构建机工作空间校验 #5555

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
> feat: Job环境变量支持凭据上下文引用 #6568 解决工作空间变量问题

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
> feat: Job环境变量支持凭据上下文引用 #6568 解决无编译环境有工作空间变量问题

- src/backend/ci/core/stream/api-stream/src/main/kotlin/com/tencent/devops/stream/api/user/UserStreamGitResource.kt
- src/backend/ci/core/stream/api-stream/src/main/kotlin/com/tencent/devops/stream/pojo/StreamGitProjectPipeline.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/dao/GitRequestEventBuildDao.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/resources/user/UserStreamGitResourceImpl.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/service/StreamPipelineService.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/service/StreamRequestService.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/StreamTriggerRequestService.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/streamActions/StreamDeleteAction.kt
feat:对接前端接口 1、跳转查看yaml链接。2、人员选择器接口 #6772
> feat:对接前端接口 1、跳转查看yaml链接。2、人员选择器接口 #6772

- .github/workflows/release.yml
feat: 升级存在漏洞的开源依赖组件 Tencent#6691
> feat: 升级存在漏洞的开源依赖组件 Tencent#6691

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/notify/command/impl/NotifyPipelineCmd.kt
> feat: 流水线结束部分参数优化 #6741 处理消息展示耗时

- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/common/UserStoreEnvVarResource.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/common/StoreEnvVarDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/common/UserStoreEnvVarResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/StoreEnvVarService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/impl/StoreEnvVarServiceImpl.kt
> 【微扩展】环境变量bug fix #5023

- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepositoryService.kt
> feat: 【微扩展】支持删除微扩展 #2494

- support-files/sql/2007_ci_project-update_v1.10_mysql.sql
> feat: 在某个服务内弹出公告 #6510

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildEndControl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildStartControl.kt
> feat: 流水线SLA 粒度调整 #6825

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/git/api/GitApi.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/pojo/GitMrReviewInfo.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/pojo/TapdWorkItem.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/scm/ServiceGitResource.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/scm/ServiceGitResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/GitService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/IGitService.kt
> feat: 新增获取工蜂mr绑定的TAPD单接口 #6815

- .github/workflows/agent.yml
- .github/workflows/release.yml
- src/agent/Makefile
feat: 原生适配 Apple M系列Mac构建机 #6495
> feat: 原生适配 Apple M系列Mac构建机 #6495

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
bug: 【社区版】上架了个支持质量红线的插件，但编辑页面没有出来配置红线入口 issue #6847
> bug: 【社区版】上架了个支持质量红线的插件，但编辑页面没有出来配置红线入口 issue #6847

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/archive/ReportArchiveTask.kt
> bug: 归档报告插件找不到文件夹时运行失败 #6850

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineRetryFacadeService.kt
> bug:运行中重试bug #6831

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/CheckInterruptStageCmd.kt
pref:stage配置了fastkill，点击取消最终的构建状态不应该为失败 #6859
#6859
> pref:stage配置了fastkill，点击取消最终的构建状态不应该为失败 #6859

- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepositoryService.kt
> bug: 保存SVN代码库插件报错 #72

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildStartControl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/DependOnControl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepositoryService.kt
> bug: 代码库创建别名重复返回具体错误码 #6814

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/InitializeMatrixGroupStageCmd.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/MatrixExecuteContainerCmd.kt
> feat: Job 所有属性设置支持 matrix 上下文 #6818

- src/backend/booster/bk_dist/booster/command/command.go
- src/backend/booster/bk_dist/booster/command/process.go
- src/backend/booster/bk_dist/booster/pkg/booster.go
- src/backend/booster/bk_dist/common/sdk/controller.go
- src/backend/booster/bk_dist/controller/config/config.go
- src/backend/booster/bk_dist/controller/pkg/api/v1/sdk.go
- src/backend/booster/bk_dist/controller/pkg/manager/basic/mgr.go
- src/backend/booster/bk_dist/controller/pkg/manager/local/executor.go
- src/backend/booster/bk_dist/controller/pkg/manager/local/mgr.go
- src/backend/booster/bk_dist/controller/pkg/manager/remote/mgr.go
- src/backend/booster/bk_dist/controller/pkg/manager/remote/slots.go
- src/backend/booster/bk_dist/controller/pkg/manager/resource/mgr.go
- src/backend/booster/bk_dist/controller/pkg/manager/resource/res.go
- src/backend/booster/bk_dist/controller/pkg/types/interface.go
- src/backend/booster/bk_dist/controller/pkg/types/work.go
- src/backend/booster/bk_dist/handler/cc/handler.go
- src/backend/booster/bk_dist/handler/custom/handler.go
- src/backend/booster/bk_dist/handler/echo/handler.go
- src/backend/booster/bk_dist/handler/find/handler.go
- src/backend/booster/bk_dist/handler/handler.go
- src/backend/booster/bk_dist/handler/tc/handler.go
- src/backend/booster/bk_dist/handler/ue4/cc/handler.go
- src/backend/booster/bk_dist/handler/ue4/cl/handler.go
- src/backend/booster/bk_dist/handler/ue4/clfilter/handler.go
- src/backend/booster/bk_dist/handler/ue4/handler.go
- src/backend/booster/bk_dist/handler/ue4/lib/handler.go
- src/backend/booster/bk_dist/handler/ue4/link/handler.go
- src/backend/booster/bk_dist/handler/ue4/shader/handler.go
- src/backend/booster/bk_dist/handler/winclangcl/handler.go
- src/backend/booster/bk_dist/shadertool/pkg/shadertool.go
> feat: 支持使用的远端资源的管理, issue: #6579

- src/backend/codecc/build.gradle.kts
- src/backend/codecc/buildSrc/src/main/kotlin/Versions.kt
- src/backend/codecc/core/common/common-util/build.gradle.kts
- src/backend/codecc/core/defect/biz-defect/src/main/kotlin/com/tencent/bk/codecc/defect/service/impl/TaskLogOverviewServiceImpl.kt
- src/backend/codecc/core/defect/model-defect/build.gradle.kts
- src/backend/codecc/core/quartz/sdk-quartz/src/main/kotlin/com/tencent/bk/codecc/quartz/job/ActiveGongfengProjScheduleTask.kt
> bug: fastjson 高危版本修复 #6866

- src/backend/booster/bk_dist/common/util/util.go
- src/backend/booster/bk_dist/controller/pkg/api/v1/sdk.go
修正 bk-dist-controller路径有空格拉起失败的问题
> bug: quote bk-dist-controller path if has space, issue: #6873

- src/backend/booster/bk_dist/handler/ue4/astc/handler.go
- src/backend/booster/bk_dist/handler/ue4/handler.go
> feat: support astc picture compress in ue, issue: #6879

- helm-charts/core/ci/README.md
- src/backend/ci/core/common/common-event/src/main/kotlin/com/tencent/devops/common/event/dispatcher/pipeline/mq/Tools.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/type/BuildType.kt
- src/backend/ci/core/common/common-service/src/main/resources/logback-spring.xml
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/mq/ExtendRabbitMQConfiguration.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/ProjectTagService.kt
- src/backend/ci/core/store/api-store-image/src/main/kotlin/com/tencent/devops/store/pojo/image/enums/ImageAgentTypeEnum.kt
> feat: 提供kubernetes部署方案 issue #4935

- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/StreamYamlBuild.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/mq/streamRequest/StreamRequestListener.kt
> bug: Stream 异常处理 #6886

- src/backend/ci/core/ticket/api-ticket/src/main/kotlin/com/tencent/devops/ticket/api/BuildCredentialResource.kt
- src/backend/ci/core/ticket/biz-ticket/src/main/kotlin/com/tencent/devops/ticket/resources/BuildCredentialResourceImpl.kt
> feat: build类接口中支持新增凭据 #6913

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/detail/BaseBuildDetailService.kt
- src/backend/ci/core/sign/api-sign/src/main/kotlin/com/tencent/devops/sign/api/pojo/IpaSignInfo.kt
- src/backend/ci/core/sign/biz-sign-sample/src/main/kotlin/com/tencent/devops/sign/service/impl/MobileProvisionServiceImpl.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/impl/SignServiceImpl.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/service/MobileProvisionService.kt
- src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/utils/SignUtils.kt
> feat: 签名服务支持自定义写入keychain #6915

- src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/common/log/pojo/QueryLogLineNum.kt
- src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/log/api/ServiceLogResource.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/resources/ServiceLogResourceImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/BuildLogQueryService.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/IndexService.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwLogResourceV3.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwLogResourceV4.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwLogResourceV3Impl.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwLogResourceV4Impl.kt
> api: 提供日志行数查询接口 #6923

- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/cron/DataCleanJob.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildStartControl.kt
> bug: 触发插件日志显示异常 #6834

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityIndicatorService.kt
bug: stream执行详情界面查看红线，提示指标不存在 #6921
> bug: stream执行详情界面查看红线，提示指标不存在 #6921

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/AtomDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomServiceImpl.kt
bug:选插件页面应该能搜索出未安装的插件 #6951
#6951
> bug:选插件页面应该能搜索出未安装的插件 #6951

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/MarketAtomDao.kt
pref:插件task.json内容压缩后再存储 #6933
#6933
> pref:插件task.json内容压缩后再存储 #6933

- src/backend/booster/bk_dist/handler/ue4/cl/handler.go
- src/backend/booster/bk_dist/handler/ue4/cl/utils.go
support relative path for cl.exe
> bug: support relative path for cl.exe, issue: #6957

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/context/StartBuildContext.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineContainerService.kt
- src/backend/ci/core/process/biz-base/src/test/kotlin/com/tencent/devops/process/engine/context/StartBuildContextTest.kt
> bug: Job1失败后重试成功，依赖Job1的Job被跳过 #6726

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/git/api/GitApi.kt
> feat:工蜂接口度量 #6616

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/event/CallBackData.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/pipeline/ModelDetail.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildDetailService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/CallBackControl.kt
> feat:callback增加返回流水线触发人信息，目前仅返回流水线启动人 #4724

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/p4/P4Server.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/p4/api/P4Api.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/webhook/PipelineBuildWebhookService.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/ExternalCodeccRepoResource.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/ServiceP4Resource.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/utils/RepositoryUtils.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/ExternalCodeccRepoResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/ServiceP4ResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepoFileService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/Ip4Service.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/P4Service.kt
> feat: 蓝盾支持查看P4代码片段 #6476

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/code/WebhookInfo.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
> feat: 构建列表中的webhookInfo增加mrid和mriid变量 #6956

- src/agent/src/pkg/config/version.go
- src/agent/src/pkg/logs/log_rotate.go
- src/agent/src/pkg/logs/logs.go
支持配置agent构建日志文件的过期清理时间 [#6944](https://github.com/fitzcao/bk-ci/issues/6944) 支持按时间切分
> 支持配置agent构建日志文件的过期清理时间 #6944 支持按时间切分

- src/backend/codecc/build.gradle.kts
- src/backend/codecc/buildSrc/src/main/kotlin/Versions.kt
- src/backend/codecc/core/common/common-util/build.gradle.kts
- src/backend/codecc/core/defect/biz-defect/src/main/kotlin/com/tencent/bk/codecc/defect/service/impl/TaskLogOverviewServiceImpl.kt
- src/backend/codecc/core/defect/model-defect/build.gradle.kts
- src/backend/codecc/core/quartz/sdk-quartz/src/main/kotlin/com/tencent/bk/codecc/quartz/job/ActiveGongfengProjScheduleTask.kt
> bug: fastjson 高危版本修复 #6866 

- src/backend/ci/core/common/common-client/src/main/kotlin/com/tencent/devops/common/client/ClientAutoConfiguration.kt
> feat: bkTag只对第一个consulTag有效 #6992

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/control/lock/ConcurrencyGroupLock.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeExtService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildEndControl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildStartControl.kt
> bug: 修复stream的并发执行判断问题 #6987 锁问题修复

- src/backend/booster/bk_dist/booster/pkg/booster.go
- src/backend/booster/bk_dist/common/env/env.go
- src/backend/booster/bk_dist/handler/cc/booster.go
- src/backend/booster/bk_dist/handler/cc/handler.go
- src/backend/booster/bk_dist/handler/ue4/cl/handler.go
- src/backend/booster/bk_dist/handler/ue4/cl/utils.go
- src/backend/booster/tools/hook_ld_preload/hook_lib/execve_hook.cpp
feat:支持mac下hook方式编译加速，issue: #6980
> feat:支持mac下hook方式编译加速，issue: #6980

- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/Profile.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/ShardingRoutingRuleDao.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/ShardingRoutingRuleServiceImpl.kt
> bug:根据profile判断集群环境信息调整 #7065

- src/backend/booster/bk_dist/common/syscall/syscall_unix.go
- src/backend/booster/bk_dist/controller/pkg/server.go
bug:do not save pid for controller, issue: #7082
> bug:do not save pid for controller, issue: #7082

- CODEOWNERS
> feature: 添加前端代码权限 issue #7105

- src/agent/src/pkg/config/config.go
- src/agent/src/pkg/config/version.go
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/detail/BaseBuildDetailService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/WorkRunner.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Runner.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
#5555 
对于在工作空间使用了A变量，但A变量在流水线运行过程中没有被定义出来的，将会失败：
提示：
工作空间未定义变量(undefined variable): ${A}
> job启动时检查工作空间路径是否合法，如是非法路径直接失败 #5555

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/StageControl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/StartContainerStageCmd.kt
前置设置finalStage场景的status。 直接按前一个stage的状态赋值
> bug: final stage终止可能出现执行成功的状态 #7023

- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/api/service/ServiceManagerResource.kt
/service/auth/manager/projects/{projectCode} -> /open/service/auth/manager/projects/{projectCode}
添加open前缀，供网关做逻辑
> feat: Auth 管理员接口路径调整 #7048

- src/backend/booster/bk_dist/controller/pkg/server.go
- src/backend/booster/tools/get_toolchain/test.go
1. 新增cl.exe工具链小工具， 
2. 去掉controller的文件锁
> 1. 新增cl.exe工具链小工具， 2. 去掉controller的文件锁

- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/BuildLogListenerService.kt
> bug: 日志行数缓存失效后自增导致key无法过期 #7003 增加记录以及缓存准备

- src/frontend/devops-pipeline/src/components/BuildHistoryTable/index.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
perf: 执行历史页面，构建列表的操作按钮提示不明确 issue #2755
> perf: 执行历史页面，构建列表的操作按钮提示不明确 issue #2755

- src/frontend/devops-pipeline/src/components/BuildHistoryTable/index.vue
perf: 流水线构建列表tips浮窗支持文本选中复制 issue #2639
> perf: 流水线构建列表tips浮窗支持文本选中复制 issue #2639

- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/BkTag.kt
- src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/common/log/utils/BuildLogPrinter.kt
- src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/log/api/print/BuildLogPrintResource.kt
- src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/log/api/print/ServiceLogPrintResource.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/dao/LogStatusDao.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/resources/BuildLogPrintResourceImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/resources/ServiceLogPrintResourceImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/BuildLogListenerService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildStartControl.kt
> bug: 修复若干日志与并发问题 #7168

- src/frontend/devops-pipeline/src/components/pipelineList/PipelineFilter/index.vue
feat: 流水线筛选框无法直接回车过滤 issue #2407
> feat: 流水线筛选框无法直接回车过滤 issue #2407

- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/ScheduleTriggerService.kt
> bug: 【stream】定时触发获取YAML时，使用开启人身份获取 #7176

- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitMrTriggerHandler.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineBuildService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStartUpService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/webhook/PipelineBuildWebhookService.kt
> feat: 流水线执行期间所更改的流水线变量，重试时应重置为第一次执行前的值 #6090

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/matrix/MatrixStatusElement.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/InitializeMatrixGroupStageCmd.kt
> bug: 矩阵分裂后的模板插件需保留市场atomCode #7046

- src/frontend/devops-atomstore/src/components/common/detailTab/detailScore.vue
perf: 【研发商店】插件详细说明默认展示全部 #7208
> perf: 【研发商店】插件详细说明默认展示全部 #7208

- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/dao/process/ProcessDataClearDao.kt
- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/service/process/ProcessDataClearService.kt
> feat: 自动清理T_PIPELINE_WEBHOOK_BUILD_PARAMETER表数据 #7223

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
pref:插件上架接口过滤掉前端传的标签数组中的null对象 #7191
#7191
> pref:插件上架接口过滤掉前端传的标签数组中的null对象 #7191

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
pref:插件私有配置写入逻辑支持开关控制 #7158
#7158
> pref:插件私有配置写入逻辑支持开关控制 #7158

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomServiceImpl.kt
feat: 研发商店可观测性监控-服务SLA&指标 #6908
> feat: 研发商店可观测性监控-服务SLA&指标 #6908

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/template/TemplateInstanceCronService.kt
- support-files/templates/#etc#ci#application-process.yml
perf:流水线模板更新实例化失败时原因提示信息长度增加并配置化 #7113
> perf:流水线模板更新实例化失败时原因提示信息长度增加并配置化-#7113

- src/frontend/devops-atomstore/src/views/edit_atom.vue
- src/frontend/devops-atomstore/src/views/edit_template.vue
bug: 研发商店未选择标签接口参数为空 issue #7026
> bug: 研发商店未选择标签接口参数为空 issue #7026

- src/frontend/devops-pipeline/src/components/pipelineParamsForm.vue
fix: 流水线变量-代码库，设置了默认值，执行预览时流水线变量默认值回显失败 issue #7124
> fix: 流水线变量-代码库，设置了默认值，执行预览时流水线变量默认值回显失败 issue #7124

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> bug: 修复若干日志与并发问题 #7168 启动参数执行次数传值错误修

- src/frontend/devops-pipeline/src/views/subpages/exec_detail.vue
fetat: 流水线执行详情页面打开时支持定位到task/job issue #6897
> fetat: 流水线执行详情页面打开时支持定位到task/job issue #6897

- src/frontend/devops-pipeline/src/views/list/atomManage.vue
bugfix: 流水线插件管理页，接口返回空值报错 issue #7235
> bugfix: 流水线插件管理页，接口返回空值报错 issue #7235

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
>  bug: 修复若干日志与并发问题 Tencent#7168

- src/frontend/devops-stream/src/views/metric.vue
--story=876183881 【蓝盾网关】stream域名支持访问上级的metrics
> --story=876183881 【蓝盾网关】stream域名支持访问上级的metrics

- src/gateway/core/lua/util/build_util.lua
> feat: macos的build 鉴权cache缓存缩短 #7247

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineBuildService.kt
> bug: 手动触发填写构建信息失效 #7214

- src/frontend/devops-pipeline/src/components/BuildHistoryTable/index.vue
bug: 在流水线构件列表里，点击下载会被文字挡住 #7256
> bug: 在流水线构件列表里，点击下载会被文字挡住 #7256

- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/aop/SensitiveApiPermissionAspect.kt
> feat: 【流水线插件SDK】权限控制机制接口增加缓存 #7262

- src/backend/turbo/build.gradle.kts
> bugfix: 修复turbo启动失败 #7272

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/op/OpPipelineSettingResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/setting/PipelineSetting.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/PipelineSettingDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/interceptor/QueueInterceptor.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineBuildService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/op/OpPipelineSettingResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineInfoFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineSettingFacadeService.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/service/StreamPipelineService.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/StreamYamlBaseBuild.kt
feat:【模块名称】白名单设置对流水线的pipeline_setting设置特殊设置
> feat:【模块名称】白名单设置对流水线的pipeline_setting设置特殊设置

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> BUG: PR/MR触发的流水线，在运行的时候把流水线删除或者修改流水线名称，状态回写失败 #2469

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/TimerTriggerElement.kt
> feat: 定时触发器自定义crontab表达式支持文本框变量 #6766

- src/backend/ci/core/process/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v2/utils/ScriptYmlUtils.kt
增加一行日志： logger.info("IF|CONDITION|$condition")
> 【Stream】技术需求：request&trigger 监听mq的traceId设置优化 #7301

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/pojo/event/PipelineBuildAtomTaskEvent.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildEndControl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/TaskControl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/StartActionTaskContainerCmd.kt
bug:质量红线插件这种审核类插件点击取消后然后立马重试导致构建异常 #7246
#7246
> bug:质量红线插件这种审核类插件点击取消后然后立马重试导致构建异常 #7246

- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/BuildParams.vue
- src/frontend/devops-pipeline/src/components/atomFormField/Selector/index.vue
- src/frontend/devops-pipeline/src/components/pipelineParamsForm.vue
> perf: 复选框流水线变量支持全选 #2404

- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/resources/user/UserGitBasicSettingResourceImpl.kt
> bug：stream开启CI时报400错误 #7298

- src/backend/ci/core/process/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v2/models/YmlName.kt
- src/backend/ci/core/process/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v2/utils/ScriptYmlUtils.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/service/StreamPipelineService.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/StreamYamlTrigger.kt
> 【stream】同步name时机优化 #7212

- src/agent/src/pkg/config/version.go
- src/agent/src/pkg/logs/log_rotate.go
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/BluekingAgentUrlServiceImpl.kt
- support-files/agent-package/script/linux/install.sh
- support-files/agent-package/script/macos/install.sh
bug: go agent定时日志切割重试逻辑不生效 #7318
feat: 优化agent下载脚本中的agentUrl为后台拼接 #7325
> bug: go agent定时日志切割重试逻辑不生效 #7318

- src/backend/ci/core/metrics/api-metrics/src/main/kotlin/com/tencent/devops/metrics/api/ServiceMetricsDataReportResource.kt
- src/backend/ci/core/metrics/api-metrics/src/main/kotlin/com/tencent/devops/metrics/pojo/dto/CodeccDataReportDTO.kt
- src/backend/ci/core/metrics/api-metrics/src/main/kotlin/com/tencent/devops/metrics/pojo/dto/QualityDataReportDTO.kt
- src/backend/ci/core/metrics/api-metrics/src/main/kotlin/com/tencent/devops/metrics/pojo/dto/TurboDataReportDTO.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/listener/CodeCheckDailyMessageListener.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/listener/TurboDailyReportMessageListener.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/resources/ServiceMetricsDataReportResourceImpl.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/MetricsThirdPlatformDataReportFacadeService.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/impl/MetricsThirdPlatformDataReportFacadeServiceImpl.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/impl/MetricsThirdPlatformDataReportServiceImpl.kt
bug:metrics第三方平台数据上报逻辑支持跨集群数据上报 #7334
#7334
> bug:metrics第三方平台数据上报逻辑支持跨集群数据上报 #7334

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/engine/impl/EngineBuildResourceApi.kt
> bug: Job互斥组锁因父流水线并发取消导致锁未释放 #5048

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelinePauseBuildFacadeService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/ErrorMsgLogUtil.kt
> 防止已经结束的构建被暂停操作再次呼起 #5048

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/p4/P4Server.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/filter/BasePathFilter.kt
> feat: p4获取文件变更列表限制最大1000条 #7344

- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/UserRepositoryResource.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/pojo/enums/RepositorySortEnum.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/pojo/enums/RepositorySortTypeEnum.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/dao/RepositoryDao.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/UserRepositoryResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepositoryService.kt
> feat:列表页属性支持点击排序 #2946

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwBuildResourceV4.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwBuildResourceV4Impl.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceBuildResource.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/CodeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServiceBuildResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/ParamFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> feat: 构建参数搜索提供open api接口 #7303

- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/atom/BuildAtomResource.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/AtomDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/atom/BuildAtomResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/AtomService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomServiceImpl.kt
feat:增加获取插件默认推荐最新可用版本号build接口 #7324
#7324
> feat:增加获取插件默认推荐最新可用版本号build接口 #7324

- src/backend/ci/build.gradle.kts
> feat: 修改devops-framework版本到0.0.6 #7391

- src/frontend/devops-atomstore/src/views/edit_atom.vue
> pref:【流水线插件】插件执行环境初始化 #3666

- src/frontend/devops-metrics/src/components/charts/line.tsx
- src/frontend/devops-metrics/src/css/main.css
- src/frontend/devops-metrics/src/main.ts
- src/frontend/devops-metrics/src/views/child-view/fail-analysis/children/error-table.vue
- src/frontend/devops-metrics/src/views/child-view/fail-analysis/children/fail-filter.vue
- src/frontend/devops-metrics/src/views/child-view/metrics-overview/children/overview-filter.vue
- src/frontend/devops-metrics/src/views/child-view/plugin-trend/common/add-plugin.vue
- src/frontend/devops-metrics/src/views/child-view/plugin-trend/plugin-fail-analysis/children/analysis-filter.vue
- src/frontend/devops-metrics/src/views/child-view/plugin-trend/plugin-fail-analysis/children/analysis-table.vue
- src/frontend/devops-metrics/src/views/child-view/plugin-trend/plugin-run-analysis/children/analysis-filter.vue
- src/frontend/devops-metrics/src/views/child-view/plugin-trend/plugin-run-analysis/children/analysis-table.vue
- src/frontend/devops-metrics/src/views/child-view/plugin-trend/plugin-run-analysis/run-analysis-main.vue
- src/frontend/devops-stream/src/components/Pipeline.vue
> feat：数据分析服务下，选择时间段逻辑优化 #7326

- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/resources/BuildLogPrintResourceImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/resources/ServiceLogPrintResourceImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/BuildLogPrintService.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/impl/LogServiceESImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/impl/LogServiceLuceneImpl.kt
> feat: 优化程序后台打印的运行日志内容及级别 #7243

- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/parsers/modelCreate/InnerModelCreatorImpl.kt
> 【stream】手动触发时缺少分支信息fix #7328

- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/utils/JooqUtils.kt
- src/backend/ci/core/metrics/api-metrics/src/main/kotlin/com/tencent/devops/metrics/constant/Constants.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/dao/AtomStatisticsDao.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/dao/PipelineFailDao.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/dao/PipelineOverviewDao.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/impl/AtomStatisticsServiceImpl.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/impl/PipelineFailServiceImpl.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/impl/PipelineOverviewServiceImpl.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/utils/QueryParamCheckUtil.kt
bug: 调整数据分析服务查询平均数据接口查询逻辑 #7393
> bug: 调整数据分析服务查询平均数据接口查询逻辑 #7393

- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/ApiAccessTokenService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/AuthDeptServiceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/AuthGroupService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/AuthHttpClientService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/AuthUserBlackListService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/ManagerOrganizationService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/IamCacheService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/impl/AbsPermissionGradeServiceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/impl/AbsPermissionGrantServiceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/impl/AbsPermissionProjectService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/impl/AbsPermissionRoleMemberImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/impl/AbsPermissionRoleServiceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/impl/AbsPermissionService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/impl/IamPermissionRoleExtService.kt
- src/backend/ci/core/project/biz-project-sample/src/main/kotlin/com/tencent/devops/project/service/MessageCodeDetailService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsOpProjectServiceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
> 优化程序后台打印的运行日志内容及级别 #7243

- src/backend/ci/core/monitoring/biz-monitoring/src/main/kotlin/com/tencent/devops/monitoring/client/InfluxdbClient.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/atom/BuildAtomResource.kt
bug:monitoring服务把为空的数值的字段插入Influxdb报错 #7409
#7409
> bug:monitoring服务把为空的数值的字段插入Influxdb报错 #7409

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/utils/code/svn/SvnUtils.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/pojo/CodeSvnRepository.kt
> feat:关联svn代码库增加拉取代码方式 #5514

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildSummaryDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineListFacadeService.kt
> pref：流水线首页分页逻辑优化 #7370

- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/config/MetricsConfig.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/impl/MetricsThirdPlatformDataReportFacadeServiceImpl.kt
pref:metrics第三方平台数据支持按集群上报 #7424
> pref:metrics第三方平台数据支持按集群上报 #7424

- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/common/OpStoreDockingPlatformResource.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/common/OpStoreLogoResource.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/common/StoreDockingPlatformDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/common/OpStoreDockingPlatformResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/common/OpStoreLogoResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/StoreDockingPlatformService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/StoreLogoService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/impl/StoreDockingPlatformServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/impl/StoreLogoServiceImpl.kt
feat:【op】工具平台注册时，支持上传logo #7387
> feat:【op】工具平台注册时，支持上传logo #7387

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/TaskAtomService.kt
bug:取消操作导致流水线模型中插件版本号变成1.0.0 #7447
#7447
> bug:取消操作导致流水线模型中插件版本号变成1.0.0 #7447

- src/frontend/devops-metrics/src/components/scroll-load-select.tsx
- src/frontend/devops-metrics/src/http/fetch/index.ts
> fix: metrics流水线数据重复修复 #7326

- src/agent/src/pkg/collector/collector.go
- src/agent/src/pkg/config/version.go
- src/agent/src/pkg/util/command/user.go
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/client/GenericMemoryMetrics.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/client/InfluxdbClient.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/client/LinuxCpuUsageMetrics.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/client/LinuxDiskioMetrics.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/client/LinuxNetMetrics.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/client/WindowsCpuUsageMetrics.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/client/WindowsDiskioMetrics.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/client/WindowsNetMetrics.kt
1、优化Influxdb出错时默认数据
2、增加上报ProjectId，为后续接入监控平台预留
> Agent Telegraf上报增加ProjectId #7479

- src/frontend/devops-metrics/src/components/charts/bar.tsx
- src/frontend/devops-metrics/src/components/charts/double-y-area-line.tsx
- src/frontend/devops-metrics/src/http/fetch/error-interceptor.ts
- src/frontend/devops-metrics/src/http/fetch/index.ts
- src/frontend/devops-metrics/src/views/child-view/metrics-overview/children/run-trend.vue
fix: metrics多个接口报错时,只展示一个错误信息 #7490
> fix: metrics多个接口报错时,只展示一个错误信息 #7490

- src/backend/ci/build.gradle.kts
- src/backend/ci/core/process/plugin-trigger/build.gradle.kts
- src/backend/ci/core/stream/biz-stream/build.gradle.kts
> 去掉HikariCP-java7 #7451

- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/aop/SensitiveApiPermissionAspect.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/utils/AtomRuntimeUtil.kt
> feat: 敏感接口能识别是系统调用还是插件调用 #7348

- src/backend/ci/build.gradle.kts
- src/backend/ci/buildSrc/src/main/kotlin/constants/Versions.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeGitScmImpl.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeGitlabScmImpl.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeSvnScmImpl.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeTGitScmImpl.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/handler/ScmExceptionMapper.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/interceptor/TimerTriggerScmChangeInterceptor.kt
- src/backend/ci/core/process/biz-process/build.gradle.kts
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/dao/ProjectPipelineCallbackDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/CallBackControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/ProjectPipelineCallBackService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/init/CallbackCircuitBreakerProperties.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/init/PipelineCallBackConfiguration.kt
- src/backend/ci/core/process/biz-process/src/test/kotlin/com/tencent/devops/process/engine/control/CallBackControlTest.kt
> feat: 回调增加熔断处理 #7468

- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageProjectService.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageReleaseService.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/configuration/StoreDetailUrlConfig.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/impl/StoreCommonServiceImpl.kt
feat:store组件详情地址支持可配置为空 #7523
#7523
> feat:store组件详情地址支持可配置为空 #7523

- src/frontend/devops-pipeline/src/store/modules/atom/mutations.js
bugfix: 插件切换版本时部分表单不应该变 issue #4304
> bugfix: 插件切换版本时部分表单不应该变 issue #4304

- src/frontend/devops-atomstore/src/views/workList/atom.vue
feature: 研发商店支持codecc检查 issue #7547
> feature: 研发商店支持codecc检查 issue #7547

- src/backend/ci/core/common/common-pipeline/src/test/kotlin/com/tencent/devops/common/pipeline/EnvReplacementParserTest.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/control/DependOnUtils.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/MutexControl.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/ITask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/ICommand.kt
> feat: 引擎支持高级表达式解析 #7115 补充开关使用位置

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/EnvReplacementParser.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
> feat: 引擎支持高级表达式解析 #7115 增加开关覆盖

- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageReleaseService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomCommonServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/impl/StoreCommonServiceImpl.kt
pref:研发商店组件升级时重复提交时给出明确错误提示 #7561
#7561
> pref:研发商店组件升级时重复提交时给出明确错误提示 #7561

- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/es/ESAutoConfiguration.kt
- src/backend/ci/core/worker/worker-api-sdk/src/main/kotlin/com/tencent/devops/worker/common/api/log/LogResourceApi.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/log/LogSDKApi.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/logger/LoggerService.kt
> pref: 调整日志服务ES连接数 #7583

- src/frontend/devops-codelib/src/utils/index.js
- src/frontend/locale/codelib/en-US.json
- src/frontend/locale/codelib/zh-CN.json
> feat: 关联svn代码库增加拉取代码方式 #5514

- src/backend/ci/core/process/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/modelCreate/ModelCommon.kt
- src/backend/ci/core/process/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/modelCreate/ModelStage.kt
- src/backend/ci/core/process/common-pipeline-yaml/src/test/kotlin/com/tencent/devops/process/yaml/modelCreate/ModelCommonTest.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/listener/components/SendNotify.kt
【stream】notices关键字下的receivers和ccs 字段支持每个item中指定多个用户，使用逗号分隔 #7592
> 【stream】notices关键字下的receivers和ccs 字段支持每个item中指定多个用户，使用逗号分隔 #7592

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/matrix/MatrixConfig.kt
- src/backend/ci/core/common/common-pipeline/src/test/kotlin/com/tencent/devops/common/pipeline/option/MatrixControlOptionTest.kt
> bug: 修复矩阵计算时include/exclude组合逻辑 #7593

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomCommonServiceImpl.kt
bug:nodejs插件上架时如果task.json未指定runtimeVersion字段时默认给runtimeVersion赋值10.* #7623
> bug:nodejs插件上架时如果task.json未指定runtimeVersion字段时默认给runtimeVersion赋值10.*

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceVarResource.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/BuildVariableService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceVarResourceImpl.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/StreamYamlTrigger.kt
> feat: 引擎支持高级表达式解析 #7115 stream新增流水线获取项目设置

- src/backend/booster/server/config/config.go
- src/backend/booster/server/pkg/resource/crm/operator/k8s/operator.go
- src/backend/booster/server/pkg/resource/crm/operator/mesos/operator.go
- src/backend/booster/server/template/container.json.template
- src/backend/booster/server/template/k8s_container.yaml.template
1、修改k8s和mesos请求时的request配置为默认配置，limit配置为可选配置，资源可用数目按照request配置计算
> bug: fix request and limit config #7612

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/MarketAtomEnvInfoDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomEnvServiceImpl.kt
bug:插件大版本中最新的版本下架的情况会导致agent下载到该已下架的版本 #7641
#7641
> bug:插件大版本中最新的版本下架的情况会导致agent下载到该已下架的版本 #7641

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/util/TaskUtils.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/TaskControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
bug:取消某个运行时间很短的任务时可能导致状态异常 #7599
#7599
> bug:取消某个运行时间很短的任务时可能导致状态异常 #7599

- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/EnvService.kt
> feat: 环境共享的项目限制100放开到500 #7650

- src/frontend/locale/metrics/zh-CN.json
【stream】修改 Metrics 服务的中文名 #7493
> 【stream】修改 Metrics 服务的中文名 #7493

- src/frontend/devops-stream/src/views/pipeline/build-list.vue
> feat: 【stream】手动触发UI优化 #7476

- src/backend/ci/core/notify/biz-notify/src/main/kotlin/com/tencent/devops/notify/resources/BuildNotifyResourceImpl.kt
- src/backend/ci/core/notify/biz-notify/src/main/kotlin/com/tencent/devops/notify/resources/ServiceNotifyResourceImpl.kt
> bug: 发送企业微信通知改成异步 #7629

- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/NodeService.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityControlPointService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/OPRepositoryService.kt
feat: 对db中主键ID的hash入库功能加日志 #7649
> feat: 对db中主键ID的hash入库功能加日志 #7649

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/devops-pipeline/src/store/modules/atom/actions.js
perf: 获取插件详情接口是否查下架版本的标识调整为前端输入 #7657
> perf: 获取插件详情接口是否查下架版本的标识调整为前端输入 #7657

- src/frontend/devops-quality/src/views/metadata_list.vue
feat: 质量红线-指标列表-去掉表格指标所包含数据列 #7627
> feat: 质量红线-指标列表-去掉表格指标所包含数据列 #7627

- src/frontend/locale/stream/zh-CN.json
> feat: steam开源版 #6457

- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepositoryAuthService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepositoryService.kt
> bug: 代码库回调方法兼容 #6885 

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/GolangAtomBusHandleHandleServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/NodeJsAtomBusHandleHandleServiceImpl.kt
bug:修复go插件支持mac操作系统bug #7711
#7711
> bug:修复go插件支持mac操作系统bug #7711

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStartUpService.kt
> feat: 子流水线循环校验跳过没有开启的子流水线插件 #7715

- src/backend/ci/core/common/common-auth/common-auth-mock/src/main/kotlin/com/tencent/devops/common/auth/MockAuthAutoConfiguration.kt
- src/backend/ci/core/common/common-auth/common-auth-mock/src/main/kotlin/com/tencent/devops/common/auth/MockAuthCodeServiceAutoConfiguration.kt
> feat: Stream腾讯云部署 #7028 auth启动调整

- src/backend/ci/core/common/common-auth/common-auth-mock/src/main/resources/META-INF/spring.factories
> feat: Stream腾讯云部署 Tencent#7028 auth启动调整

- src/frontend/devops-stream/src/components/setting/agent-detail/node-overview-chart.vue
- src/frontend/devops-stream/src/utils/chart-option.js
bugfix: stream 构建机使用图表不展示 issue #7534
> bugfix: stream 构建机使用图表不展示 issue #7534

- helm-charts/core/ci/templates/artifactory/statefulset.yaml
- helm-charts/core/ci/templates/auth/deployment.yaml
- helm-charts/core/ci/templates/dispatch/deployment.yaml
- helm-charts/core/ci/templates/dispatchKubernetes/deployment.yaml
- helm-charts/core/ci/templates/environment/deployment.yaml
- helm-charts/core/ci/templates/image/deployment.yaml
- helm-charts/core/ci/templates/log/deployment.yaml
- helm-charts/core/ci/templates/misc/deployment.yaml
- helm-charts/core/ci/templates/process/deployment.yaml
- helm-charts/core/ci/templates/project/deployment.yaml
- helm-charts/core/ci/templates/quality/deployment.yaml
- helm-charts/core/ci/templates/repository/deployment.yaml
- helm-charts/core/ci/templates/store/deployment.yaml
- helm-charts/core/ci/templates/ticket/deployment.yaml
- helm-charts/core/ci/templates/turbo/deployment.yaml
- helm-charts/core/ci/templates/websocket/deployment.yaml
- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/BkTag.kt
- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/trace/TraceFilter.kt
- src/gateway/core/lua/init_common.lua
- src/gateway/core/lua/util/loadbalance_util.lua
- src/gateway/core/lua/util/tag_util.lua
- src/gateway/core/proxy.set.header.common.conf
- support-files/templates/gateway#core#lua#init.lua
> feat: 容器化上线优化 #7774

- helm-charts/core/ci/templates/artifactory/statefulset.yaml
- helm-charts/core/ci/templates/auth/deployment.yaml
- helm-charts/core/ci/templates/dispatch/deployment.yaml
- helm-charts/core/ci/templates/dispatchDocker/deployment.yaml
- helm-charts/core/ci/templates/dispatchKubernetes/deployment.yaml
- helm-charts/core/ci/templates/environment/deployment.yaml
- helm-charts/core/ci/templates/image/deployment.yaml
- helm-charts/core/ci/templates/log/deployment.yaml
- helm-charts/core/ci/templates/metrics/deployment.yaml
- helm-charts/core/ci/templates/misc/deployment.yaml
- helm-charts/core/ci/templates/notify/deployment.yaml
- helm-charts/core/ci/templates/openapi/deployment.yaml
- helm-charts/core/ci/templates/plugin/deployment.yaml
- helm-charts/core/ci/templates/process/deployment.yaml
- helm-charts/core/ci/templates/project/deployment.yaml
- helm-charts/core/ci/templates/quality/deployment.yaml
- helm-charts/core/ci/templates/repository/deployment.yaml
- helm-charts/core/ci/templates/store/deployment.yaml
- helm-charts/core/ci/templates/stream/deployment.yaml
- helm-charts/core/ci/templates/ticket/deployment.yaml
- helm-charts/core/ci/templates/turbo/deployment.yaml
- helm-charts/core/ci/templates/websocket/deployment.yaml
> feat: 修改deployment的failureThreshold #7741

- src/backend/ci/core/common/common-third-sdk/common-github-sdk/src/main/kotlin/com/tencent/devops/common/sdk/github/pojo/GithubMilestone.kt
- src/backend/ci/core/common/common-third-sdk/common-github-sdk/src/main/kotlin/com/tencent/devops/common/sdk/github/pojo/GithubRepo.kt
- src/backend/ci/core/common/common-third-sdk/common-github-sdk/src/main/kotlin/com/tencent/devops/common/sdk/github/response/CheckRunResponse.kt
- src/backend/ci/core/common/common-third-sdk/common-github-sdk/src/main/kotlin/com/tencent/devops/common/sdk/github/response/CreateIssueCommentResponse.kt
- src/backend/ci/core/common/common-third-sdk/common-github-sdk/src/main/kotlin/com/tencent/devops/common/sdk/github/response/GetUserResponse.kt
- src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/pojo/code/github/GithubEvent.kt
- src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/pojo/code/github/GithubPullRequestEvent.kt
> bug: github pr事件有milestone时不触发 #7767

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/template/TemplateDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
> bug: 研发商店来源模板的实例更新异常 #7746

- src/frontend/devops-stream/src/views/pipeline/build-list.vue
feat: 记录 stream 构建列表的筛选条件 #7707
> feat: 记录 stream 构建列表的筛选条件 #7707

- src/frontend/devops-stream/src/components/Pipeline.vue
- src/frontend/devops-stream/src/components/exec-detail/job.vue
- src/frontend/devops-stream/src/components/exec-detail/log/pluginLog.vue
- src/frontend/devops-stream/src/views/pipeline/build-list.vue
- src/frontend/devops-stream/src/views/setting/basic.vue
- src/frontend/locale/stream/en-US.json
- src/frontend/locale/stream/zh-CN.json
feature: stream提示和展示优化 issue #7784
> feature: stream提示和展示优化 issue #7784

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildEndControl.kt
> perf: 质量红线相关错误信息优化 #7787 修复task id误传

- src/backend/ci/core/stream/api-stream/src/main/kotlin/com/tencent/devops/stream/api/user/UserStreamGitResource.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/dao/GitRequestEventBuildDao.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/resources/user/UserStreamGitResourceImpl.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/service/StreamHistoryService.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/StreamTriggerRequestService.kt
> [stream] 获取分支新增本地方式 #7786

- src/frontend/devops-stream/src/http/pipelines.js
- src/frontend/devops-stream/src/views/pipeline/build-list.vue
feature: [stream] 获取分支新增本地方式 issue #7786
> feature: [stream] 获取分支新增本地方式 issue #7786

- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/ManagerUserService.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeGitScmImpl.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/filter/BasePathFilter.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/filter/PathStreamFilter.kt
- src/backend/ci/core/plugin/biz-plugin/src/main/kotlin/com/tencent/devops/plugin/service/git/CodeWebhookService.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/Constants.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/parsers/triggerMatch/TriggerMatcher.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/parsers/triggerMatch/matchUtils/PathMatchUtils.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
> 【stream】feat：paths和paths-ignore组合时的匹配策略问题fix #7513

- src/backend/ci/core/common/common-third-sdk/common-github-sdk/src/main/kotlin/com/tencent/devops/common/sdk/github/pojo/GithubMilestone.kt
- src/backend/ci/core/common/common-third-sdk/common-github-sdk/src/main/kotlin/com/tencent/devops/common/sdk/github/pojo/GithubRepo.kt
- src/backend/ci/core/common/common-third-sdk/common-github-sdk/src/main/kotlin/com/tencent/devops/common/sdk/github/response/CheckRunResponse.kt
- src/backend/ci/core/common/common-third-sdk/common-github-sdk/src/main/kotlin/com/tencent/devops/common/sdk/github/response/CreateIssueCommentResponse.kt
- src/backend/ci/core/common/common-third-sdk/common-github-sdk/src/main/kotlin/com/tencent/devops/common/sdk/github/response/GetUserResponse.kt
- src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/pojo/code/github/GithubEvent.kt
- src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/pojo/code/github/GithubPullRequestEvent.kt
> bug: github pr事件有milestone时不触发 #7767 

- src/backend/ci/core/stream/api-stream/src/main/kotlin/com/tencent/devops/stream/pojo/GitRequestEvent.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/github/GithubPRActionGit.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/tgit/TGitMrActionGit.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/git/service/GithubApiService.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/parsers/triggerParameter/GithubRequestEventHandle.kt
> [stream]github 审核权限优化 #7812

- src/gateway/core/vhosts/devops.proxy.conf
> feat: 网关支持dispatch-kubernetes的登录调试 #7798

- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitMrTriggerHandler.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitNoteTriggerHandler.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitReviewTriggerHandler.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/util/WebhookUtils.kt
> feat: 【上下文】当 mr 有关联的 review 时，希望能在 mr 事件触发时获取到 review 相关信息 #7824

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/IosUtils.kt
> feat: IPA的Scheme提取规避NullPointException的情况 #7781

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
bug:流水线人工取消时页面上的取消人显示为System #7843
#7843
> bug:流水线人工取消时页面上的取消人显示为System #7843

- src/backend/ci/buildSrc/src/main/kotlin/constants/Versions.kt
> depend:升级leaf依赖版本 #7842

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/CodeGitWebHookTrigger.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
> feat: git事件触发插件支持第三方服务过滤 #7743

- src/frontend/devops-stream/src/views/dashboard.vue
feature: [stream github版]项目描述太长 issue #7832
> feature: [stream github版]项目描述太长 issue #7832

- src/frontend/devops-stream/src/components/project-header.vue
- src/frontend/devops-stream/src/views/pipeline/build-list.vue
- src/frontend/locale/stream/en-US.json
- src/frontend/locale/stream/zh-CN.json
feature: 【执行历史】按照状态搜索执行历史时，支持中间态 issue #7859
> feature: 【执行历史】按照状态搜索执行历史时，支持中间态 issue #7859

- src/frontend/devops-stream/src/views/pipeline/build-detail/detail.vue
- src/frontend/devops-stream/src/views/pipeline/build-list.vue
feature: 进入 mr 审核的构建，支持取消构建 issue #7873
> feature: 进入 mr 审核的构建，支持取消构建 issue #7873

- helm-charts/core/ci/build/values.yaml
- helm-charts/core/ci/templates/init/init.sql.yaml
- helm-charts/core/ci/templates/store/deployment.yaml
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/type/BuildType.kt
- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/utils/KubernetesUtils.kt
> feat: 公共构建机支持可配置 #7856

- src/frontend/devops-stream/package.json
- src/frontend/devops-stream/src/components/setting/edit-credential.vue
- src/frontend/devops-stream/src/views/setting/agent-pools/agent-list.vue
- src/frontend/locale/stream/en-US.json
- src/frontend/locale/stream/zh-CN.json
- src/frontend/package.json
feature: 【凭据管理】创建凭据优化 issue #7857
> feature: 【凭据管理】创建凭据优化 issue #7857

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/event/CallBackData.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/interceptor/TimerTriggerScmChangeInterceptor.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/CallBackControl.kt
> bug: 定时触发器中判断代码库是否有变更的操作会忽略checkout插件 #7516

- scripts/bkenv.properties
> feat: BK_CI_STREAM_HOST设置默认值 #7894

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Runner.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/logger/LoggerService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/SensitiveValueService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/TaskDaemon.kt
> bugfix：插件执行完毕后错误信息中未脱敏，打印出来的日志中包含敏感信息 #7818

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> feat: 事件触发增加openapi接口重放 #7904

- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/OPRepositoryResource.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/dao/RepositoryDao.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/OPRepositoryResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/OPRepositoryService.kt
> feat: Op接口批量修改代码库中保存的git旧域名 #7838

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildCancelControl.kt
bug:流水线job处于审核状态时点击取消未清理redis中的取消标识 #7888
#7888
> bug:流水线job处于审核状态时点击取消未清理redis中的取消标识 #7888

- src/frontend/devops-pipeline/package.json
- src/frontend/devops-stream/package.json
- src/frontend/devops-stream/src/views/dashboard.vue
> feature: 日志搜索优化 issue #7952

- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/dao/StreamUserMessageDao.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/StreamYamlBaseBuild.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/service/StreamEventService.kt
> [stream] repo hook 增加审计必要信息 #7827 bug fix

- .ci/pr_check.yml
- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/utils/CommonUtils.kt
> feat: bk-ci开启stream检查 #7587

- src/backend/ci/core/common/common-pipeline/build.gradle.kts
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/EnvReplacementParser.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/matrix/MatrixConfig.kt
- src/backend/ci/core/common/common-pipeline/src/test/kotlin/com/tencent/devops/common/pipeline/EnvReplacementParserTest.kt
- src/backend/ci/core/common/common-pipeline/src/test/kotlin/com/tencent/devops/common/pipeline/option/MatrixControlOptionTest.kt
> feat: matrix支持js对象的值访问 #7872

- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/StreamTriggerRequestService.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/template/YamlTemplateService.kt
> [stream] repo hook 异步执行 #7881

- scripts/bkenv.properties
- support-files/templates/#etc#ci#application-repository.yml
> feat: repository 需要 aes.key 变量注入 #7782

- src/frontend/devops-stream/src/components/StageReviewPanel/approve.vue
- src/frontend/devops-stream/src/components/StageReviewPanel/components/params/approve.vue
- src/frontend/devops-stream/src/components/setting/agent-pool-card.vue
- src/frontend/devops-stream/src/views/pipeline/build-detail/detail.vue
- src/frontend/devops-stream/src/views/pipeline/build-list.vue
feature: 优化setting展示 issue #7973
> feature: 优化setting展示 issue #7973

- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/EventCacheService.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/util/EventCacheUtil.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/GitActionCommon.kt
> bug: scm接口调用缓存key应该带projectId #7943

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/EnvReplacementParser.kt
- src/backend/ci/core/common/common-pipeline/src/test/kotlin/com/tencent/devops/common/pipeline/EnvReplacementParserTest.kt
> feat: matrix支持js对象的值访问 #7872 未命名表达式返回空字符串

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildSummaryDao.kt
> 新增构建状态手动修复接口 #7944

- src/backend/ci/core/common/common-event/src/main/kotlin/com/tencent/devops/common/event/dispatcher/pipeline/mq/Tools.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/config/MetricsListenerConfiguration.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/config/MetricsThirdPartyListenerConfiguration.kt
pref:metrics服务的RabbitMQ的prefetch参数实现可配置化 #7947
#7947
> pref:metrics服务的RabbitMQ的prefetch参数实现可配置化 #7947

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
> [bug] 构建机完成任务上报task状态异常 #7984

- src/frontend/devops-stream/package.json
feature: Stream 锁定组件库版本号 issue #7991
> feature: Stream 锁定组件库版本号 issue #7991

- docker-images/core/ci/dockerfile/backend.bkci.Dockerfile
- docker-images/core/ci/dockerfile/jdk.Dockerfile
- helm-charts/core/ci/templates/artifactory/statefulset.yaml
- helm-charts/core/ci/templates/auth/deployment.yaml
- helm-charts/core/ci/templates/dispatch/deployment.yaml
- helm-charts/core/ci/templates/dispatchDocker/deployment.yaml
- helm-charts/core/ci/templates/dispatchKubernetes/deployment.yaml
- helm-charts/core/ci/templates/environment/deployment.yaml
- helm-charts/core/ci/templates/image/deployment.yaml
- helm-charts/core/ci/templates/log/deployment.yaml
- helm-charts/core/ci/templates/metrics/deployment.yaml
- helm-charts/core/ci/templates/misc/deployment.yaml
- helm-charts/core/ci/templates/notify/deployment.yaml
- helm-charts/core/ci/templates/openapi/deployment.yaml
- helm-charts/core/ci/templates/plugin/deployment.yaml
- helm-charts/core/ci/templates/process/deployment.yaml
- helm-charts/core/ci/templates/project/deployment.yaml
- helm-charts/core/ci/templates/quality/deployment.yaml
- helm-charts/core/ci/templates/repository/deployment.yaml
- helm-charts/core/ci/templates/store/deployment.yaml
- helm-charts/core/ci/templates/stream/deployment.yaml
- helm-charts/core/ci/templates/ticket/deployment.yaml
- helm-charts/core/ci/templates/websocket/deployment.yaml
- support-files/templates/#etc#ci#common.yml
> feat: 优化java镜像 #7948

- src/backend/codecc/core/defect/biz-defect/src/main/java/com/tencent/bk/codecc/defect/dao/mongotemplate/LintDefectV2Dao.java
- src/backend/codecc/core/defect/biz-defect/src/main/java/com/tencent/bk/codecc/defect/resources/UserDefectRestResourceImpl.java
- src/backend/codecc/core/defect/biz-defect/src/main/java/com/tencent/bk/codecc/defect/service/IQueryWarningBizService.java
- src/backend/codecc/core/defect/biz-defect/src/main/java/com/tencent/bk/codecc/defect/service/impl/CCNQueryWarningBizServiceImpl.java
- src/backend/codecc/core/defect/biz-defect/src/main/java/com/tencent/bk/codecc/defect/service/impl/CLOCQueryWarningBizServiceImpl.java
- src/backend/codecc/core/defect/biz-defect/src/main/java/com/tencent/bk/codecc/defect/service/impl/CommonQueryWarningBizServiceImpl.java
- src/backend/codecc/core/defect/biz-defect/src/main/java/com/tencent/bk/codecc/defect/service/impl/DUPCQueryWarningBizServiceImpl.java
- src/backend/codecc/core/defect/biz-defect/src/main/java/com/tencent/bk/codecc/defect/service/impl/LintQueryWarningBizServiceImpl.java
- src/backend/codecc/core/task/biz-task/src/main/java/com/tencent/bk/codecc/task/service/impl/AnalyzeConfigServiceImpl.java
bug: codecc 扫描虚拟分支错误使用超快增量 #7956
> bug: codecc 扫描虚拟分支错误使用超快增量 #7956

- src/backend/ci/core/common/common-db-sharding/src/main/kotlin/com/tencent/devops/common/db/config/BkShardingDataSourceConfiguration.kt
bug:解决升级ShardingSphere给metrics服务带来的分表问题 #8010
> bug:解决升级ShardingSphere给metrics服务带来的分表问题 #8010

- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/dao/StreamUserMessageDao.kt
> [stream] MESSAGE信息在高并发情况下存在插入重复信息 #7961
