TencentBlueKing/bk-ci

src/backend/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/pojo/CodeSvnRepository.kt
src/backend/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/dao/RepositoryCodeSvnDao.kt
src/backend/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepositoryService.kt

由于SVN插件的区域为空，导致与模型定义出现冲突。 改为允许为空，并设置一个默认值 。该值目前无用，可忽略。

[backend]修复保存SVN代码库插件报错 fixed #72

---

src/pipeline-plugin/bksdk/pom.xml

升级pipeline-plugin所依赖的jackson-databind版本到2.9.9.2

---

src/frontend/devops-atomstore/src/images/placeholder.svg

fix: svg文件中出现License注释导致svg不可用

---

src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/type/DispatchRouteKeySuffix.kt

--story=856430647 【M蓝盾&Keystore】蓝盾支持提供支持iOS企业证书的MacOS公共构建集群

---

src/backend/ci/core/store/api-store-image/src/main/kotlin/com/tencent/devops/store/pojo/image/enums/ImageStatusEnum.kt
src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageReleaseService.kt
support-files/sql/0004_ci_store-update-table_20191225-1831_mysql.sql

bugfix:镜像上架中止后再次上架镜像详情回显中应有上一次适用机器范围 #564
bugfix:上架镜像时适用机器需要有不为空校验 #565

bugfix:修复镜像适用范围(agentType)相关问题 #564

---

src/backend/ci/core/common/common-event/src/main/kotlin/com/tencent/devops/common/event/dispatcher/pipeline/mq/MQ.kt
src/backend/ci/core/common/common-websocket/src/main/kotlin/com/tencent/devops/common/websocket/dispatch/TransferDispatch.kt
src/backend/ci/core/common/common-websocket/src/main/kotlin/com/tencent/devops/common/websocket/dispatch/push/TransferPush.kt
src/backend/ci/core/common/common-websocket/src/main/kotlin/com/tencent/devops/common/websocket/utils/RedisUtlis.kt
src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/configuration/WebsocketConfiguration.kt
src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/controller/WsController.kt
src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/cron/ClearTimeoutCron.kt
src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/event/ChangePageTransferEvent.kt
src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/event/ClearUserSessionTransferEvent.kt
src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/event/LoginOutTransferEvent.kt
src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/handler/BKHandshakeInterceptor.kt
src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/keys/WebsocketKeys.kt
src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/listener/WebSocketListener.kt
src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/pojo/ChangePageDTO.kt
src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/pojo/ClearUserDTO.kt
src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/pojo/LoginOutDTO.kt
src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/servcie/ProjectProxyServiceImpl.kt
src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/servcie/WebsocketService.kt

1. 实例内部维护session，非本实例session不push。
2. 添加消息下发mq功能，前端只需与websocket交互，由websocket广播其他消息。
3. 修改timeout数据接口。由原来的大list改为1000个桶，超时计算遍历此1000个桶。
4. 校验项目添加redis缓存，加快changePage速度，解决推送偶现有延迟问题。

feature:实例维护session，timeout数据结构调整

---

src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceBuildResource.kt

fix #660 
process迁移部分接口url中的变量名和接口定义的接收变量名不一致

bugfix: process迁移部分接口url中的变量名和接口定义的接收变量名不一致 issue #660

---

src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/type/BuildType.kt

refactor: BuildType枚举类外部Docker公共构建机的名称规范 issue #712

---

src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/dao/PipelineSettingDao.kt

Feature request: 流水线企业微信群通知应支持 Markdown 格式 Pipeline notification should support markdown when push to Wechat work group issue #416
修复数据库字段写入错误的bug

Feature: 流水线企业微信群通知应支持 Markdown 格式 Pipeline notification should support markdown when push to Wechat work group issue #416

---

src/gateway/core/nginx.conf

bugfix:网关在域名多的情况下，nginx启动失败 issue #803

bugfix:网关在域名多的情况下，nginx启动失败 issue #803

---

src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/dao/PipelineDockerHostDao.kt
src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/dao/PipelineDockerTaskDao.kt
src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/service/DockerHostBuildService.kt
src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/service/DockerHostDebugService.kt
src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/utils/DockerUtils.kt

专用构建机上存在一些特殊的依赖环境或配置，所以即使飘移到公共集群也会无法正常构建，所以专用构建机不允许柔性处理
如果专用构建机故障，则无法正常工作，需要解决专用构建机故障问题

bugfix: docker项目专用构建机 #781

---

src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServiceMeasurePipelineResourceImpl.kt

bugfix: 插件详情页流水线个数显示0，但实际使用该插件的流水线个数不为0 #924

bugfix: 插件详情页流水线个数显示0，但实际使用该插件的流水线个数不为0 #924

---

src/frontend/devops-pipeline/src/components/trendData/index.vue

bugfix: safari不支持解析类似2020/3-23这种日期格式，而chrome是支持的，统一改成2020/3/23 #949

bugfix: safari不支持解析类似2020/3-23这种日期格式，而chrome是支持的，统一改成2020/3/23 #949

---

src/backend/ci/core/store/biz-store-image-sample/src/main/kotlin/com/tencent/devops/store/service/image/impl/SampleImageReleaseService.kt
src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageReleaseService.kt

bugfix: 镜像首次上架镜像验证通过时点击继续按钮对镜像状态校验优化 #969
fix #969

bugfix: 镜像首次上架镜像验证通过时点击继续按钮对镜像状态校验优化 #969

---

src/backend/ci/core/common/common-api/src/main/java/com/tencent/devops/common/api/util/ObjectReplaceEnvVarUtil.java
src/backend/ci/core/common/common-api/src/test/java/com/tencent/devops/common/api/util/ObjectReplaceEnvVarUtilTest.java

bugfix: 流水线插件参数转义时会将“12E2”这种字符串转换成1200.00 #1007
fix #1007

bugfix: 流水线插件参数转义时会将“12E2”这种字符串转换成1200.00 #1007

---

src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/TaskAtomService.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/listener/run/finish/PipelineBuildCancelListener.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineVMBuildService.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/measure/MeasureService.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/measure/MeasureServiceImpl.kt

将PipelineBuildTaskFinishBroadCastEvent事件触耦迁移至MeasureService中处理，作为可选项，不影响核心流程。

bug:流水线插件全部执行完成后，构建无法自动终止 #927

---

src/backend/ci/core/environment/biz-environment-sample/src/main/kotlin/com/tencent/devops/environment/permission/config/EnvironmentPermConfiguration.kt
src/backend/ci/core/process/biz-process-sample/src/main/kotlin/com/tencent/devops/process/permission/config/PipelinePermConfiguration.kt
src/backend/ci/core/repository/biz-repository-sample/src/main/kotlin/com/tencent/devops/repository/config/RepositoryPermConfiguration.kt
src/backend/ci/core/ticket/biz-ticket-sample/src/main/kotlin/com/tencent/devops/ticket/config/TicketPermConfiguration.kt

fix: 补充所有微服务对接蓝鲸权限中心逻辑 #1318

---

src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt

bugfix:开源版插件在quality.json不存在时兼容处理插件的质量红线测试数据 #1349
fix #1349

bugfix:开源版插件在quality.json不存在时兼容处理插件的质量红线测试数据 #1349

---

src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/permission/AbstractEnvironmentPermissionService.kt
support-files/iam/0001_bk_ci_20190728-1036_iam.json
support-files/iam/0002_bk_ci_20190728-1036_iam.json

#1368 
修改之后，以前如果有接入蓝鲸权限中心的项目， 则以前从环境节点中导入的构建机(节点）是存在于环境资源中，会导致没有权限，这块可能需要通过权限中心的迁移，或者重新导入构建机来解决

bug: environment权限判断中，节点的资源类型是否有误？ #1368

---

src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/handler/ErrorCodeExceptionMapper.kt

fix #818 
出现这个问题主要原因是因为错误码没有保存到数据库，导致提示默认信息，默认信息是加了uniqueId这些信息的，现在去掉了uniqueid这些信息。最好错误码也添加到数据库中

feature: 优化流水线编辑报错信息 #818

---

src/backend/ci/core/common/common-api/src/main/java/com/tencent/devops/common/api/util/ObjectReplaceEnvVarUtil.java
src/backend/ci/core/common/common-api/src/test/java/com/tencent/devops/common/api/util/ObjectReplaceEnvVarUtilTest.java

流水线参数传递时对象里的数值被转为字符串问题fix #1555
fix #1555

流水线参数传递时对象里的数值被转为字符串问题fix #1555

---

src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildService.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt

当前逻辑是重试的stage所有原子都重新跑, 包括执行成功的
就是原本的retry接口的taskId 传 stageId 例如 stage-2

feat: stage 重试功能接口 #1565

---

src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildSummaryDao.kt

bugfix:流水线列表按名称查询应该倒序 #1617
fix #1617

bugfix:流水线列表按名称查询应该倒序 #1617

---

src/frontend/devops-pipeline/src/components/pipelineParamsForm.vue

bugfix: 修复流水线变量使用js关键字报错 issue #1588

bugfix: 修复流水线变量使用js关键字报错 issue #1588

---

src/gateway/core/lua/router_srv.lua
src/gateway/core/lua/util/redis_util.lua
src/gateway/core/nginx.conf

1、修改consul dns请求次数为5次，2秒超时
2、修改redis的连接超时未2秒
3、bkrepo不做频率限制
4、增大nginx的连接数

bugfix:网关连接consul和redis超时&请求数量超过最大值&bkrepo不限制频率 issue #1703

---

src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/ContainerControl.kt

bugfix: 插件设置“失败时继续”后，若执行超时，流水线状态不正确 #1526

---

src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/AbstractBuildResourceApi.kt

bug: 开源默认的归档插件中对归档文件的所在路径分隔符统一转换为Unix格式 #1818

---

src/frontend/devops-atomstore/src/components/common/selectLogo/index.vue
src/frontend/devops-pipeline/src/components/AtomFormComponent/Tips/index.vue

fix: 修复插件和商店选图样式 issue #1798

---

src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineWebhookService.kt

fix #1426 
当流水线被删除后，触发webhook时，因为webhook的流水线ID会保留到redis，流水线删除但是redis没有删除，会导致空指针错误

perf: 错误日志修复 #1426

---

src/frontend/devops-pipeline/src/components/PipelineEditTabs/VerticalTab.vue

bugfix: 产出物报告纵向滚动条 issue #1885

---

src/gateway/core/lua/access_control_ip.lua
src/gateway/core/lua/router_srv.lua

1、report、bkrepo、schedule、task模块不做频率限制
2、build和external类请求，频率限制到每秒100次，浮动50.

feature:调整网关的频率限制 #2006

---

src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServiceBuildResourceImpl.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildService.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineRemoteAuthService.kt

1、手动触发接口新增frequencyLimit字段来控制是否要限制启动频率。
2、服务间调用接口frequencyLimit设置为false
3、远程触发接口frequencyLimit设置为false

bugfix:远程触发和openapi启动流水线会遇到能”流水线: 不能太频繁启动构建“的错误 #2027

---

src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/ContainerControl.kt

修正：解决已经执行过的end-xxxx拦截点又被重新置为UNEXEC
#2046

perf: 被禁用或跳过的[无用]插件任务在启动构建时不需要存储 #2046

---

src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineWebhookDao.kt

老数据，当流水线触发事件删除，然后再添加相同的代码库时，TASK_ID字段为空的问题

feature: webhookRedis存储结构优化 #1587

---

src/backend/ci/core/common/common-security/src/main/kotlin/com/tencent/devops/common/security/jwt/JwtManager.kt

这里enable只是在自己作为消费端时, 判断"是否需要解析jwt" 
而自己作为生产端时, 是否需要jwt加密, 是根据privateKey和publicKey来判断

开源版的gateway不用开启jwt验证 #2201

---

src/frontend/devops-nav/src/components/User/index.vue
src/frontend/devops-pipeline/src/components/pipeline/triggers.vue
src/frontend/devops-pipeline/src/mixins/pipeline-operate-mixin.js

bugfix: 短时间内连续点击“执行”按钮会出现多个构建任务，容易误操作 issue #890

bugfix: 短时间内连续点击“执行”按钮会出现多个构建任务，容易误操作 issue #890

---

src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/TaskControl.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineVMBuildService.kt

fix #2400 
明确UNEXEC与SKIP的用途
UNEXEC  仅因为系统平台或用户的构建脚本导致的出错，导致构建需要进行终止时，后续未执行的插件（从QUEUE-->UNEXEC）
SKIP 仅当是用户意愿明确正常运行情况要跳过执行的，不影响主流程的才能是SKIP

bug: 重试时导致后续能满足条件才运行的插件被意外跳过 #2400

---

src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/code/github/GithubEvent.kt

当git客户端中的user.name设置和github中的用户名不一致时,username这个字段就会为空,触发流水线时就会报错
#2450

bug: github webhook事件GithubUser对象中的username是可以为空 #2450

---

src/backend/ci/core/common/common-es/src/main/kotlin/com/tencent/devops/common/es/ESAutoConfiguration.kt

perf: 日志模块采用Rest Client方式访问ES #2596

---

src/frontend/devops-nav/src/index.html

登录路径逻辑：
1、若有%s，则替换%s
2、如果参数为空：直接追加 ?c_url=ci_url
3、有参数且=结尾，则直接添加ci_url
4、有参数非=结尾，添加&c_url=ci_url

chore: 梳理前端登录跳转路径拼接逻辑 issue#2640

---

src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/BatScriptUtil.kt
src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/ShellUtil.kt

WORKSPACE 变量，在非 Bash 插件里通过环境变量取到的值，不是真正的工作空间 #2298
#2298

bug:WORKSPACE 变量，在非 Bash 插件里通过环境变量取到的值，不是真正的工作空间 #2298

---

src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/enums/BuildStatus.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt

原则：当存在多个失败插件时，进行失败插件重试时，一次只能对单个插件进行重试，其他失败插件不会重试，所以：
如果是插件失败重试，并且当前的Job状态是失败的，则检查重试的插件是不是属于该失败Job:
如果不属于，则表示该Job在本次重试不会被执行到，则不做处理，保持原状态, 跳过
#2318

bugfix: 获取日志为空问题 #2318

---

src/backend/ci/core/process/biz-process-sample/src/main/kotlin/com/tencent/devops/process/service/PipelineBuildExtServiceImpl.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildBuildResourceImpl.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchBuildLessDockerStartupTaskAtom.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchVMStartupTaskAtom.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/HeartbeatControl.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/listener/run/monitor/PipelineBuildHeartbeatListener.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildExtService.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildService.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineVMBuildService.kt

fix: 构建机启动时间超过120秒时会导致Agent心跳超时判定消息事件提前结束 #2365
将心跳事件监听事件的触发从构建机开始上报构建机准备就绪开始

fix: 构建机启动时间超过120秒时会导致Agent心跳超时判定消息事件提前结束 #2365

---

src/frontend/devops-pipeline/src/store/modules/soda/atom.js

fix: 迁移github触发器相关接口 #3006

---

src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/compatibility/v2/V2BuildParametersCompatibilityTransformer.kt

perf: 启动构建接口不传变量参数则使用编排中的默认值 #2802

---

src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/mq/PipelineAgentShutdownEvent.kt
src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/mq/PipelineBuildLessShutdownDispatchEvent.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchBuildLessDockerShutdownTaskAtom.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchBuildLessDockerStartupTaskAtom.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchVMShutdownTaskAtom.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchVMStartupTaskAtom.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/BuildCancelControl.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt

startup, shutdown 下发executeCount，供构建机区分同一buildId不同executeCount

feat：流水线重试startup,shutdown 构建次数标识，区分唯一构建记录 #3001

---

src/frontend/devops-pipeline/src/components/Stages/AtomList.vue

fix: 流水线执行详情页面，hook 跳过和未执行的时候显示钩子图标 issue #3360

fix: 流水线执行详情页面，hook 跳过和未执行的时候显示钩子图标 issue #3360

---

src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/ContainerControl.kt

bug: 构建机心跳超时，当没有任务在执行时，流水线状态应该为失败 #3155

---

src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/util/IndexNameUtils.kt

更改日期计算模板，避免按YYYY时年末最后一周跨周时算入下一年 #3379

bug: 日志模块索引名计算的日期模板错误 #3379

---

src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt

bug:1.2开源版本插件首先上架一个版本下架后再上架一个新版本首页查询不到 #3403
#3403

bug:1.2开源版本插件首先上架一个版本下架后再上架一个新版本首页查询不到 #3403

---

src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/listener/run/PipelineTaskPauseListener.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineTaskService.kt

bug: 流水线暂停后，选择操作为停止，流水线的取消用户为空的问题fix #3280

---

src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt

perf: 内置插件和心跳超时的执行错误信息优化 #2993 不能直接通过output判断 回退

---

src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/dao/PipelineSettingDao.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt

1. 只有Channel为BS的流水线才初始化配置通知渠道。
2. BS默认只有失败发送， 成功不发送

refractor: 重构流水线默认创建的设置选项 #3311

---

src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/code/git/GitTagPushEvent.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/code/GitWebHookMatcher.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/code/GitWebHookStartParam.kt

feature: 支持只监听某个branch下的tag #3332

---

src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/ManagerUserService.kt
src/backend/ci/core/common/common-api/src/test/kotlin/com/tencent/devops/common/api/util/DateTimeUtilTest.kt

bug: 分级管理员超时越界问题 #3673

---

src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/utils/PipelineUtils.kt

feat: 引擎核心代码拆分出biz-process业务模块 #3400

---

src/backend/ci/core/store/biz-store-sample/src/main/kotlin/com/tencent/devops/store/service/common/impl/SampleStoreLogoServiceImpl.kt
src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/utils/StoreUtils.kt
support-files/templates/#etc#ci#application-store.yml

refactor:开源版，研发商店组件logo、文档链接中域名在数据库硬编码，导致用户切换域名后无法查看图片 #3780
#3780

refactor:开源版，研发商店组件logo、文档链接中域名在数据库硬编码，导致用户切换域名后无法查看图片 #3780

---

src/frontend/devops-pipeline/src/components/Stages/CheckAtomDialog.vue
src/frontend/devops-pipeline/src/components/atomFormField/atomFieldMixin.js

fix: 人工审核审核时，变量名称hover展示对应的变量描述 issue #3845

人工审核审核时，变量名称hover展示对应的变量描述

---

src/backend/ci/core/common/common-client/src/main/kotlin/com/tencent/devops/common/client/ClientAutoConfiguration.kt
src/backend/ci/core/common/common-client/src/main/kotlin/com/tencent/devops/common/client/consul/ConsulConstants.kt
src/backend/ci/core/common/common-client/src/main/kotlin/com/tencent/devops/common/client/consul/ConsulContent.kt
src/backend/ci/core/common/common-client/src/main/kotlin/com/tencent/devops/common/client/consul/ConsulFilter.kt
src/backend/ci/core/common/common-client/src/main/kotlin/com/tencent/devops/common/client/ms/MicroServiceTarget.kt
src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/FeignConfiguration.kt
src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/aspect/ApiAspect.kt
src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwProjectResourceV3Impl.kt
support-files/sql/1001_ci_project_ddl_mysql.sql
support-files/sql/2004_ci_project-update_v1.2_mysql.sql

1. 增强feign的路由策略。支持根据consul tag做路由。
2. openAPI添加根据projectID设置consul tag的埋点。

feat:请求服务支持consul tags路由

---

src/frontend/devops-pipeline/src/components/pipelineSetting/BaseInfo.vue

bug: 流水线-设置 徽章跳转路径不对 issue #4025

bug: 流水线-设置 徽章跳转路径不对 issue #4025

---

src/frontend/devops-pipeline/src/components/VersionSideslider.vue

fix: 流水线版本列表的创建时间应改为修改时间 issue #4037

fix: 流水线版本列表的创建时间应改为修改时间 issue #4037

---

src/frontend/devops-pipeline/src/views/list/newlist.vue

fix: 修复流水线列表列宽拖拽后仍展示不全流水线名称 issue #3972

修复流水线列表列宽拖拽后仍展示不全流水线名称

---

src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineContextService.kt

bug:上下文jobs.使用jobId引用插件输出，而不是id和containerId #4380

bug:上下文jobs.使用jobId引用插件输出，而不是id和containerId #4380

---

src/frontend/devops-atomstore/src/components/detailInfo.vue
src/frontend/devops-atomstore/src/components/labelList.vue
src/frontend/devops-atomstore/src/components/manage/detail/image-detail/show.vue
src/frontend/devops-atomstore/src/components/transition-tab.vue
src/frontend/devops-atomstore/src/store/atom.js
src/frontend/devops-atomstore/src/store/image.js
src/frontend/devops-atomstore/src/views/edit_image.vue
src/frontend/devops-pipeline/src/mixins/pipeline-operate-mixin.js

镜像上架构建资源不展示腾讯内部逻辑

---

src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildStageDao.kt

修复排队跳过时，最后一个Stage处于禁用时，会导致变成变成成功

修复排队跳过时，最后一个Stage处于禁用时，会导致变成变成成功

---

scripts/bk-ci-start.sh

修正判断端口是否监听函数的bug.
chore: 部署问题汇总202106 #4591

chore: 部署问题汇总202106 #4591

---

support-files/codecc/templates/codecc.frontend.conf

feat: CodeCC For 1.5 #4572

---

src/frontend/devops-pipeline/src/store/modules/common/optionConfigMixin.js
src/frontend/locale/pipeline/en-US.json
src/frontend/locale/pipeline/zh-CN.json

feat: 流水线插件高级特性：即使前面有插件运行失败也运行，即使被取消也运行 issue #1156

流水线插件高级特性：即使前面有插件运行失败也运行，即使被取消也运行

---

src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/EnvUtils.kt
src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/ReplacementUtils.kt
src/backend/ci/core/common/common-api/src/test/kotlin/com/tencent/devops/common/api/util/EnvUtilTest.kt
src/backend/ci/core/common/common-api/src/test/kotlin/com/tencent/devops/common/api/util/ReplacementUtilsTest.kt
src/backend/ci/core/worker/worker-agent/src/main/kotlin/com/tencent/devops/agent/AgentVersion.kt

解决当替换后整个字符串都为blank时，被重置回替换前的字符串

feat: 变量支持二次替换 #4559

---

src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/OkhttpUtils.kt
src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/GlobalProxyConfiguration.kt
src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/WebAutoConfiguration.kt
src/backend/ci/core/common/common-web/src/main/resources/META-INF/spring.factories

com.tencent.devops.common.api.util.OkhttpUtils.okHttpClient 为静态对象，初始化 OkhttpUtils 类就会初始化对象
根据 com.squareup.okhttp3/okhttp/3.9.1/7539531ecf9b6e082fcab195f0835d4f69ead95e/okhttp-3.9.1-sources.jar!/okhttp3/OkHttpClient.java:478 初始化对象时就会选择使用的 ProxySelector

feat: 配置全局请求代理功能 #4749 尽早初始化代理配置

---

scripts/bkci-op.sh

chore: 修正bkci-op.sh的变量引用错误. #4526

chore: 修正bkci-op.sh的变量引用错误. #4526

---

src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineBuildMaterialService.kt

bug: 流水线重试后，原材料字段重复显示 #4403
#4403

bug: 流水线重试后，原材料字段重复显示 #4403

---

src/frontend/devops-pipeline/src/components/StageReviewPanel/approve.vue
src/frontend/devops-pipeline/src/components/Stages/Stage.vue

bugfix: 流水线编排页面变量读取前未较验 issue #5198

bugfix: 流水线编排页面变量读取前未较验 issue #5198

---

src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt

fix: 处于排队构建状态的流水线无法响应排队超时或队列满的退出信号 #5187

---

src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/detail/TaskBuildDetailService.kt

bug:插件选择【即使前面有插件运行失败也运行，即使被取消也运行】这个条件时，该插件的后面插件都没有执行 #5230
#5230

bug:插件选择【即使前面有插件运行失败也运行，即使被取消也运行】这个条件时，该插件的后面插件都没有执行 #5230

---

src/frontend/devops-pipeline/src/views/list/newlist.vue

bug: 配置构建号格式后，构建历史页面展示的构建号和流水线列表页面展示的不一致 issue Tencent#5358

bug: 配置构建号格式后，构建历史页面展示的构建号和流水线列表页面展示的不一致 issue #5358

---

src/frontend/devops-pipeline/src/views/template/instance.vue

fix: 模板实例管理页面，搜索框右侧icon错位 issue #5449

模板实例管理页面，搜索框右侧icon错位 

---

src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchVMShutdownTaskAtom.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/HeartbeatControl.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/StartActionTaskContainerCmd.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/CallBackControl.kt
src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Runner.kt

stop插件执行后会发送shutdown,无需构建机再跑endBuild逻辑,避免造成并发问题。
若stop先到，endBuild未执行。则end插件就一直处于queue状态。导致暂停插件无法终止。

bug: 暂停偶现无法终止 #5530

---

src/frontend/devops-pipeline/src/components/StageReviewPanel/index.vue

bugfix: 审核按钮位置需要浮动在底部 issue #5480

bugfix: 审核按钮位置需要浮动在底部 issue #5480

---

src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomOption.vue

fix: 流水线中插件配置的查看态，group无法展开收起 issue #3014

流水线中插件配置的查看态，group无法展开收起

---

src/frontend/devops-pipeline/src/views/list/newlist.vue

bug: 流水线取消执行后，流水线列表页的流水线进度不应有进度 issue #5496

bug: 流水线取消执行后，流水线列表页的流水线进度不应有进度

---

src/agent/src/cmd/daemon/main.go
src/agent/src/cmd/daemon/main_win.go
src/agent/src/pkg/config/version.go
src/agent/src/pkg/upgrade/operation.go
src/agent/src/pkg/upgrade/upgrade.go
src/agent/src/pkg/upgrader/upgrader.go
src/agent/src/pkg/util/httputil/httputil.go

resolve #4686
- 1、kill devopsDaemon进程的行为在 macos 下， 如果当前是由 launchd 启动的（比如mac重启之后，devopsDaemon会由launchd接管启动）, 当upgrader进程触发kill devopsDaemon时，会导致当前upgrader进程也被系统一并停掉，所以要排除macos的进程停止操作，否则会导致升级中断,  本次只是将{AgentDir}/devopsDaemon文件进行覆盖，但不做进程重启，需要手动重启。
-  2、windows 因早期daemon缺失 pid文件，在安装多个agent的机器上无法很正确的寻找到正确的进程，并且windows的启动方式较多，早期用户会使用直接双击devopsDaemon.exe文件来启动，以此来保证构建进程能够正确拉起带UI的程序，所以这块无法正确查找到进程，因此暂时也不考虑windows的devopsDaemon.exe文件升级。 windows需要手动升级:
- windows的devopsDaemon.exe升级方式是先手动停止devopsDaemon.exe 再将{AgentDir}/tmp/devopsDaemon.exe 复制到 {AgentDir}目录下，再启动即可。

取消windows&macos devopsDaemon自动升级

---

src/agent/src/pkg/upgrade/upgrade.go

devopsDaemon 暂时不考虑单独的替换升级，windows 无法自动升级，仅当devopsAgent有变化时升级。
fix #4686

feat: 构建机导入流程优化 #4686

---

src/backend/ci/core/dockerhost/api-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/api/ServiceDockerHostResource.kt
src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/resources/ServiceDockerHostResourceImpl.kt
src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/DockerService.kt
src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/HandlerContext.kt
src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/container/ContainerCustomizedRunHandler.kt
src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/container/ContainerHandlerContext.kt
src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/container/ContainerPullImageHandler.kt
src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/container/ContainerRunHandler.kt
src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/image/ImageHandlerContext.kt

现在是使用docker run接口的时候，拉取容器等日志输出到启动容器插件里面了，目标是输出到调用docker run接口的插件的流水线日志内

fix: dockerhost的dockerRun日志统一写入到了StartVMTask，分离开来 #5738

---

src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwBuildResourceV3Impl.kt
src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceBuildResource.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServiceBuildResourceImpl.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineRemoteAuthService.kt
src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageReleaseService.kt

1. 定义新接口ServiceBuildResource.manualStartupNew。 projectId按标准在HEAD内
2. 远程触发auth转为为pipeline后，获取到project通过网关转发一次。 通过网关路由到项目对应的集群。
3. 现有的ServiceBuildResource.manualStartup请求逻辑调整为ServiceBuildResource.manualStartupNew

feat: 远程触发兼容多集群的场景 #5779

---

src/frontend/devops-pipeline/src/views/subpages/edit.vue

bugfix: 流水线编排小地图宽度不生效  issue #5754

bugfix: 流水线编排小地图宽度不生效  issue #5754

---

src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwLogResourceV3Impl.kt

feat:  日志下载接口报错 #5757

---

src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityHistoryService.kt

bug: 重试流水线，红线评论指标值重复 #5821.

---

src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildCancelControl.kt

bug:配有互斥组的构建在取消操作时会长时间取消不掉 #5824
#5824

bug:配有互斥组的构建在取消操作时会长时间取消不掉 #5824

---

src/backend/codecc/build.gradle
src/backend/codecc/core/defect/biz-defect/src/main/java/com/tencent/bk/codecc/defect/component/NewCCNDefectTracingComponent.java
src/backend/codecc/core/defect/biz-defect/src/main/java/com/tencent/bk/codecc/defect/component/NewLintDefectTracingComponent.java
src/backend/codecc/core/defect/biz-defect/src/main/java/com/tencent/bk/codecc/defect/consumer/CLOCDefectCommitConsumer.java
src/backend/codecc/core/defect/biz-defect/src/main/java/com/tencent/bk/codecc/defect/consumer/DUPCDefectCommitConsumer.java
src/backend/codecc/core/defect/biz-defect/src/main/java/com/tencent/bk/codecc/defect/service/impl/UpdateDefectBizServiceImpl.java

bugfix: 修复CodCC白名单无效问题
bugfix: 升级Log4j2版本

bugfix: 修复CodCC白名单无效问题 #5802

---

src/frontend/devops-pipeline/src/components/AtomSelector/atomCard.vue

fix: 提示浮窗的层级应在页面最顶层 issue #5715

fix: 提示浮窗的层级应在页面最顶层

---

src/frontend/devops-pipeline/src/views/subpages/preview.vue

bug: 流水线变量类型【GIT分支或TAG】必填项未生效 issue #5807

bug: 流水线变量类型【GIT分支或TAG】必填项未生效

---

src/backend/booster/bk_dist/worker/config/config.go
src/backend/booster/bk_dist/worker/pkg/cmd_handler/handler4dispatchtask.go
src/backend/booster/bk_dist/worker/pkg/manager/manager.go
src/backend/booster/server/pkg/resource/direct/agent/pkg/manager/manager.go

改动点（针对bk-dist-worker）：
1. 增加一个配置项，用于决定是否删除临时文件，默认是需要删除，在某些调试环境下，可以用该配置项保留临时文件，方便调试
2. 增加了几个错误日志，方便定位问题

feat:优化bk-dist-worker的错误日志，增加是否删除临时文件的配置

---

src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/config/PipelineCommonSettingConfig.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/extend/DefaultModelCheckPlugin.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/utils/PipelineUtils.kt
src/backend/ci/core/process/biz-base/src/test/kotlin/com/tencent/devops/process/engine/extend/DefaultModelCheckPluginTest.kt
src/backend/ci/core/process/biz-base/src/test/kotlin/com/tencent/devops/process/engine/utils/PipelineUtilsTest.kt
support-files/templates/#etc#ci#application-process.yml

feat: 流水线长度限制支持255以内动态配置 #6229

---

src/agent/src/pkg/config/version.go
src/agent/src/pkg/job/build.go

macos 下 path会导致重组引起顺序问题， 移除多余的 /etc/profile 指令
see
https://www.softec.lu/site/DevelopersCorner/MasteringThePathHelper

feat: 优化agent启动构建时避免写死Bash shell #5304

---

src/frontend/devops-pipeline/src/store/modules/pipelines/pipelinesTemplate.js
src/frontend/devops-pipeline/src/views/template/edit.vue

bug: 模板管理版本列表删除的模板名称为中文，名称的base64字符串会带有/造成路径错误 issue #6353

bug: 模板管理版本列表删除的模板名称为中文，名称的base64字符串会带有/造成路径错误 issue #6353

---

src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/template/UserPTemplateResource.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/template/UserPTemplateResourceImpl.kt

模板管理版本列表删除的模板名称为中文，名称的base64字符串会带有/造成路径错误 #6353

模板管理版本列表删除的模板名称为中文，名称的base64字符串会带有/造成路径错误 #6353

---

src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/pojo/event/PipelineTaskPauseEvent.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/listener/run/PipelineTaskPauseListener.kt

PipelineTaskPauseEvent 事件处理时，优先判断当前job下的stopVm任务是否有完成。若未完成丢入延迟队列。
每次丢入延迟队列追加3秒。 最多5次。

feat: 插件暂停继续需校验关机状态 #6317

---

src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt

蓝盾task执行超时场景下，BK_CI_BUILD_FAIL_TASKS变量为空 #5249

蓝盾task执行超时场景下，BK_CI_BUILD_FAIL_TASKS变量为空 #5249

---

src/backend/ci/core/process/api-process/build.gradle.kts

将依赖放到api-process,保证可以被依赖加载到 fix #6387

fix: openapi Element 的动态子类加载不全 #6387

---

src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/DataSourceServiceImpl.kt

根据PROJECT_ID获取数据库分片信息的接口PROJECT_ID不存在时会返回错误信息 #6300

根据PROJECT_ID获取数据库分片信息的接口PROJECT_ID不存在时会返回错误信息 #6300

---

src/backend/booster/server/pkg/engine/disttask/task.go

调小分发到远端worker的job数，避免job长时间在worker的队列中，等待超时
减少队列中的任务，有助于更均匀的分配job到远端

feat:lessen jobs dispatched to remote,issue: #6456

---

src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/WorkRunner.kt
src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Runner.kt
src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/logger/LoggerService.kt

搭车fix：LoggerService 提前启动，在未进入构建前失败会导致未完成stop方法，引起构建进程被hold住
修复前复现：
将构建机的并发设置为1
启动一个构建，在准备构建环境那一时刻，立即点“取消”，
tail -f devopsAgent.log 
会有：
parallel task count exceed , wait job done, ParallelTaskCount config: 1, instance count: 1
以及newHeartbeat 信息会包含刚才存在的构建，说明未被释放。
再使用 ps -ef | grep "java"  | grep  {构建ID}
可以看到之前构建进程一直存在。
使用 jstack -F  {进程ID}  可以看到如下信息：
说明LoggerService.start 被触发产生的进程一直在工作中， 而未被调用 LoggerService.stop.
故障点1：（提前启动LoggerService）
https://github.com/Tencent/bk-ci/blob/1c622875e96d3ff24da7e9f001fab9e573e7a10a/src/backend/worker/worker-agent/src/main/kotlin/com/tencent/devops/agent/runner/WorkRunner.kt#L62
故障点2：（LoggerService.stop闭环位置不对）
https://github.com/Tencent/bk-ci/blob/214a90da2e82eb6f74940b56b7a1de310ab37b54/src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/de …

fix: agent build_tmp 目录权限问题 #6545

---

src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/TaskControl.kt

bug:取消操作如果在构建出现异常的情况下没有清理掉redis中缓存的取消任务数据 #6693
#6693

bug:取消操作如果在构建出现异常的情况下没有清理掉redis中缓存的取消任务数据 #6693

---

src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineTaskService.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt

1. 添加重试对STAGE_SUCCESS的判断条件
2. 暂停redis标识位超时时间从task的超时时间->job的最大超时时间. 防止task超时时间配置较小，超时后，点击暂停继续会因为缺失标识位而重复被暂停

bug:运行中重试逻辑需考虑STAGE_SUCCESS的场景 #6651

---

src/backend/ci/core/auth/biz-auth-blueking/src/main/kotlin/com/tencent/devops/auth/AuthConfiguration.kt
src/backend/ci/core/auth/biz-auth-blueking/src/main/kotlin/com/tencent/devops/auth/service/BkLocalManagerServiceImp.kt
src/backend/ci/core/auth/biz-auth-blueking/src/main/kotlin/com/tencent/devops/auth/service/SampleAuthPermissionProjectService.kt
src/backend/ci/core/auth/biz-auth-blueking/src/main/kotlin/com/tencent/devops/auth/service/SampleAuthPermissionService.kt
src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/common/AuthCoreConfiguration.kt

去除PermissionService,PermissionProjectService通过ConditionalOnMissingBean的兜底。 必须idProvider=simple才实例化。 
可能导致非法的idProvider无法启动。但是排除了非法idProvider通过Simple来鉴权的风险

feat:auth内@ConditionalOnMissingBean优化 #6778

---

scripts/bk-ci-modify-http-port.sh
scripts/bk-ci-modify-paas-web-entrance.sh
scripts/bk-ci-special-upgrade.sh
scripts/bkce-set-env03.sh

新增变更依赖脚本：
1. bk-ci-modify-http-port.sh
2. bk-ci-modify-paas-web-entrance.sh
3. bk-ci-special-upgrade.sh

ci支持用户变更访问的web端口

---

src/agent/src/pkg/upgrade/download/download_unix.go

支持配置agent构建日志文件的过期清理时间 #6944

---

.github/workflows/agent.yml
.github/workflows/release.yml

chore: 修复Turbo Service github action执行报错 #7005

---

src/frontend/devops-pipeline/src/views/subpages/preview.vue

bug: 1.7.42 流水线变量选择Git分支或TAG,没有赋值也能跑 issue #7069

bugfix: 1.7.42 流水线变量选择Git分支或TAG,没有赋值也能跑 issue #7069

---

src/frontend/devops-pipeline/src/store/modules/atom/paramsConfig.js

bugfix: 1.7.42流水线参数为代码库，选择gitlab无法保存 issue #7067

bugfix: 1.7.42流水线参数为代码库，选择gitlab无法保存 issue #7067

---

src/frontend/devops-pipeline/src/store/modules/atom/paramsConfig.js

bugfix: 流水线参数为代码库，选择gitlab无法保存 issue #7067

bugfix: 流水线参数为代码库，选择gitlab无法保存 issue #7067

---

src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineRemoteAuthService.kt

因Bktag设置了router_tag 默认为本集群，导致网关不会根据X-DEVOPS-PROJECT-ID路由。故直接根据项目获取router, 不使用client.get直接调用，因client内不支持同服务间的feign调用。故只能通过网关代理转发

bug: 远程触发流水线根据项目动态路由 #7095

---

src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/filter/BasePathFilter.kt
src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/filter/PathPrefixFilter.kt
src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/filter/PathRegexFilter.kt
src/backend/ci/core/common/common-webhook/biz-common-webhook/src/test/kotlin/com/tencent/devops/common/webhook/service/code/filter/PathPrefixFilterTest.kt
src/backend/ci/core/common/common-webhook/biz-common-webhook/src/test/kotlin/com/tencent/devops/common/webhook/service/code/filter/PathRegexFilterTest.kt

bug: 代码库事件监听中，监听路径和排除路径过滤逻辑独立，导致文件范围出现歧义场景 #7137

---

src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/mq/streamRequest/StreamRequestListener.kt
src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/mq/streamTrigger/StreamTriggerListener.kt
src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/mq/streamTrigger/StreamTriggerMQConfig.kt

1、StreamRequestListener去掉显示的traceId传递。
2、StreamTriggerListener去掉显示的traceId传递。
3、StreamTriggerMQConfig中streamRequestTriggerContainer改成调用Tools.kt的方法：createSimpleMessageListenerContainerByAdapter，自动传递traceId。

【Stream】技术需求：request&trigger 监听mq的traceId设置优化 #7301

---

src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildStartControl.kt

bug: 构建已经启动，当新线程再次启动此构建，构建任务依然往下跑 #7572

---

src/backend/booster/bk_dist/booster/command/command.go
src/backend/booster/bk_dist/booster/command/process.go
src/backend/booster/bk_dist/booster/pkg/booster.go
src/backend/booster/bk_dist/booster/pkg/util.go
src/backend/booster/bk_dist/common/env/env.go
src/backend/booster/bk_dist/common/pump/pump.go
src/backend/booster/bk_dist/common/sdk/controller.go
src/backend/booster/bk_dist/common/sdk/worker.go
src/backend/booster/bk_dist/common/syscall/syscall_windows.go
src/backend/booster/bk_dist/common/types/booster.go
src/backend/booster/bk_dist/common/util/util.go
src/backend/booster/bk_dist/controller/config/config.go
src/backend/booster/bk_dist/controller/pkg/api/v1/sdk.go
src/backend/booster/bk_dist/controller/pkg/manager/manager.go
src/backend/booster/bk_dist/controller/pkg/manager/remote/mgr.go
src/backend/booster/bk_dist/controller/pkg/manager/remote/slots.go
src/backend/booster/bk_dist/controller/pkg/manager/resource/mgr.go
src/backend/booster/bk_dist/controller/pkg/manager/resource/res.go
src/backend/booster/bk_dist/handler/ue4/cl/handler.go
src/backend/booster/bk_dist/handler/ue4/cl/utils.go
src/backend/booster/bk_dist/handler/ue4/clfilter/handler.go
src/backend/booster/bk_dist/handler/ue4/shader/handler.go
src/backend/booster/bk_dist/ubttool/pkg/executor.go
src/backend/booster/bk_dist/ubttool/pkg/ubttool.go
src/backend/booster/bk_dist/worker/pkg/client/bkcommondist_handler.go
src/backend/booster/bk_dist/worker/pkg/client/bkcommondist_protocol.go
src/backend/booster/bk_dist/worker/pkg/cmd_handler/handler4dispatchtask.go
src/backend/booster/bk_dist/worker/pkg/manager/manager.go
src/backend/booster/bk_dist/worker/pkg/protocol/pb_protocol.go

1. 主要是windows下ue的pump模式相关
pump : 支持将编译的依赖文件找出来，发送到远端，远端直接编译，无需在本地预处理生成预处理文件（.i 或者 .ii）
pump的cache : 支持将上一步找出来的依赖文件列表缓存到本地
send cork功能 : 发送依赖列表文件时，不是收到请求后直接发送，而是判断缓冲区大小，或者超时发送
发送文件的内存slot : 限制同时发送的文件的大小，避免内存过大崩溃
2. bk-ubt-tool有两个改动，一是支持了失败重试，另外就是精简了打印日志

feat : windows下ue的pump模式支持

---

src/frontend/devops-pipeline/src/components/AtomFormComponent/DynamicParameter/index.vue
src/frontend/devops-pipeline/src/components/AtomFormComponent/Parameter/index.vue
src/frontend/devops-pipeline/src/components/AtomFormComponent/Selector/index.vue
src/frontend/devops-pipeline/src/components/AtomFormComponent/selectorMixins.js
src/frontend/devops-pipeline/src/components/atomFormField/AtomAceEditor/index.vue
src/frontend/devops-pipeline/src/components/atomFormField/CodeModeSelector/index.vue
src/frontend/devops-pipeline/src/components/atomFormField/ParamsView/index.vue
src/frontend/devops-pipeline/src/components/atomFormField/RequestSelector/index.vue

feature: 【流水线插件】支持插件前端获取到当前job的构建资源类型 issue #7747

feature: 【流水线插件】支持插件前端获取到当前job的构建资源类型 issue #7747

---

src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/dao/v2/QualityHisMetadataDao.kt
src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/listener/PipelineBuildQualityListener.kt

bug: 重试流水线后，仍有重试之前的失败指标值导致红线检查不通过 #8005

bug: 重试流水线后，仍有重试之前的失败指标值导致红线检查不通过 #8005

---

src/backend/booster/bk_dist/controller/pkg/manager/local/mgr.go
src/backend/booster/bk_dist/controller/pkg/manager/resource/mgr.go

1. 指定host的死锁
2. remote worker全部失效后，会导致资源一直申请而不释放

修正bk-dist-controller两个bug

---

src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/enums/BuildStatus.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/StartActionTaskContainerCmd.kt

bug：带失败时自动跳过插件的流水线构建时因为构建机网络原因结束后的状态不正确 #8140
#8140

bug：带失败时自动跳过插件的流水线构建时因为构建机网络原因结束后的状态不正确 #8140

---

src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/template/ServiceTemplateInstanceResourceImpl.kt

bug: 质量红线生效流水线信息在红线列表页面和详情页面数据不一致 #8073

---

src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/dao/v2/QualityIndicatorDao.kt

bug: 支持质量红线的插件指标，提示信息无法置空 #8355

bug: 支持质量红线的插件指标，提示信息无法置空 #8355

---

src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/utils/ZipUtil.kt
src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/common/log/pojo/TaskBuildLogProperty.kt
src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/logger/LoggerService.kt
src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/WorkspaceUtils.kt

①原先 >100w行并且>1GB的日志是无法归档的，于是选择压缩之后再归档。
②日志下载处，兼容存量归档日志，先查.zip，查不到再查.log

 feat: 制品库无法归档的第三方构建机日志支持保留至指定目录 TencentBlueKing#8391

---

src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/cron/QualityDailyReportJob.kt
src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityHisMetadataService.kt

bug: 流水线中配有两个相同的codecc任务时，保存指标数据偶现死锁

bug: 流水线中配有两个相同的codecc任务时，保存指标数据偶现死锁 #8008

---

src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/app/StartBuildContext.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt

#8809
修复两个问题：
①选择并发运行时，却也注册了一个值为空的并发组（正常时应当为null）
②流水线整体重试时，注册的并发组没有更新。（保存的依旧是第一次触发的值）

bugfix: 并发组优化 #8809

---

src/backend/ci/core/environment/api-environment/src/main/kotlin/com/tencent/devops/environment/api/ServiceNodeResource.kt
src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/dao/NodeDao.kt
src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/resources/ServiceNodeResourceImpl.kt
src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/EnvService.kt
src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/NodeService.kt
src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/environment/ApigwEnvironmentResourceV4.kt
src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/utils/markdown/Table.kt
src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/environment/ApigwEnvironmentResourceV4Impl.kt
src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/service/doc/DocumentService.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildSummaryDao.kt

#8947
①新增了一个openapi接口，解决目前openapi不能拿到第三方构建环境下构建机的数据（只能拿部署环境的）
②修复了下之前不小心漏掉的"重试时只有最新的构建才能刷新LATEST_STATUS"

feat: 支持获取构建环境的构建机列表 #8947

---

src/frontend/devops-permission/src/views/applyPermission/apply-permission.vue
src/frontend/devops-pipeline/src/views/subpages/edit.vue

bug: 【蓝盾新版权限】取消权限申请后，申请其他操作权限跳转页面筛选选择的用户组会一直复用上一次的 #9077

---

src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/MessageUtil.kt
src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/utils/I18nUtil.kt
src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/NodeJsAtomBusHandleHandleServiceImpl.kt

bug: linux操作系统cpu架构为aarch64应该使用arm64的node包执行node插件 #9070
#9070

bug: linux操作系统cpu架构为aarch64应该使用arm64的node包执行node插件 #9070

---

src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/utils/BkI18nLanguageCacheUtil.kt
src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/utils/I18nUtil.kt
src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/dao/ThirdPartyAgentBuildDao.kt
src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/ThirdPartyAgentService.kt
src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/dispatcher/agent/ThirdPartyAgentDispatcher.kt
src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/utils/ThirdPartyAgentEnvLock.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/StartActionTaskContainerCmd.kt

#9101
- 2.次高优先级的构建机:
- a. 最近构建机中使用过这个构建机, 并且
- **b. 当前有构建任务,选当前正在运行任务最少的构建机(没有达到当前构建机的最大并发数)**
- 4.第四优先级的构建机:
- **a. 当前有构建任务,选当前正在运行任务最少的构建机(没有达到当前构建机的最大并发数)**

feat: 包含动态跳过插件任务的Job的调度逻辑优化 #9101

---

src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/config/MeasureConfig.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildMonitorControl.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/init/BuildEngineCoreTaskConfiguration.kt

删除ip专属队列,无用,在容器化环境还会导致因pod重启(ip重新分配)出现无主队列

缩减process微服务的子模块数量 #9307

---

src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/common/StoreLogoDao.kt
src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/common/StoreMediaInfoDao.kt

bug:静态资源文件的url地址域名支持适配特定环境遗漏点修复 #9581
#9581

bug:静态资源文件的url地址域名支持适配特定环境遗漏点修复 #9581

---

src/backend/ci/core/log/api-log/build.gradle.kts
src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/common/log/utils/BuildLogPrinter.kt
src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/log/configuration/LogPrinterConfiguration.kt
src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/cron/impl/IndexCleanJobESImpl.kt
src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/impl/LogServiceESImpl.kt
src/backend/ci/core/process/biz-engine/src/test/kotlin/com/tencent/devops/process/engine/control/DependOnControlTest.kt
src/backend/ci/core/process/biz-engine/src/test/kotlin/com/tencent/devops/process/engine/control/MutexControlTest.kt
src/backend/ci/core/worker/worker-common/build.gradle.kts
src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/logger/LoggerService.kt

bug: 构建日志的服务调用端增加请求熔断机制 #9602

---

src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/option/StageControlOption.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/extend/DefaultModelCheckPlugin.kt

bug: stage审核取消兼容数据处理 #9611

---

src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/dao/HistoryDao.kt
src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/listener/PipelineBuildQualityListener.kt

bug: 点击人工审核会把流水线中同一条红线规则的两处控制点的数据都刷新，导致另一个控制点的审核失败 #9633

bug: 点击人工审核会把流水线中同一条红线规则的两处控制点的数据都刷新，导致另一个控制点的审核失败 #9633

---

src/frontend/devops-pipeline/src/components/ArtifactDownloadButton.vue
src/frontend/devops-pipeline/src/components/ExecDetail/Artifactory.vue
src/frontend/devops-pipeline/src/components/Outputs/index.vue
src/frontend/locale/pipeline/en-US.json
src/frontend/locale/pipeline/zh-CN.json

feat：流水线支持归档目录 #9320

---

src/frontend/devops-pipeline/src/components/Outputs/CopyToCustomRepoDialog.vue
src/frontend/devops-pipeline/src/components/pipelineList/PipelineTableView.vue

feat: 构建制品页面查询仓库下的一级目录接口按需进行加载， 只有点击复制至按钮后才进行加载 issue #9629

feat: 构建制品页面查询仓库下的一级目录接口按需进行加载， 只有点击复制至按钮后才进行加载 issue #9629

---

src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/interceptor/QueueInterceptor.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildStartControl.kt

#9618
已在test环境压测，同时触发50次构建（包含5种并发组）未发现问题

feat: 构建分组并发时优化 #9618

---

src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/cache/BkDiskLruFileCache.kt
src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/env/AgentEnv.kt
src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt

bug:公共构建机的插件缓存目录挪到工作空间的上一级目录 #9640

bug:公共构建机的插件缓存目录挪到工作空间的上一级目录 #9640

---

src/backend/ci/buildSrc/src/main/kotlin/constants/Versions.kt
src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/RbacPermissionProjectService.kt
src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/RbacPermissionService.kt
src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/AuthDeptServiceImpl.kt
src/backend/ci/core/common/common-auth/common-auth-rbac/src/main/kotlin/com/tencent/devops/common/auth/RbacAuthHttpClientAutoConfiguration.kt

feat: 优化批量添加项目成员接口 #9660

---

src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineAtomReplaceCronService.kt
src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/atom/AtomParamReplaceInfo.kt

feat:进行插件替换时，目标插件的值支持配置默认值参数 #10037
#10037

feat:进行插件替换时，目标插件的值支持配置默认值参数 #10037

---

src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepositoryService.kt

bug: 重命名代码库以后, 使用旧别名关联代码库会报错 #9984

---

src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/MessageUtil.kt

bug:国际化信息进行占位参数替换处理时对信息中非占位符的{ }字符操作异常 #10176

bug:国际化信息进行占位参数替换处理时对信息中非占位符的{ }字符操作异常 #10176

---

src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineContainerService.kt
src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt

1、取消构建的再重试时如果是取消状态的，则不能跳过，取消状态属于要重试再次执行的状态（比如重试的是checkout插件，其post-action如是取消)

perf: 插件执行错误码优化 #10326

---

src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/JsonUtil.kt
src/backend/ci/core/common/common-pipeline/src/test/kotlin/com/tencent/devops/common/pipeline/pojo/element/ElementTest.kt
src/backend/ci/core/common/common-pipeline/src/test/resources/windowsElement.json
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineInfoFacadeService.kt

#10728
本次PR对`jsonMapper`方法进行了优化，主要包括以下几点：
1. **启用属性按字母顺序排序**：通过启用`MapperFeature.SORT_PROPERTIES_ALPHABETICALLY`，确保POJO在反序列化时属性按字母顺序排序。这有助于在某些情况下提高一致性和可预测性，但会对性能产生略微影响。
2. **禁用创建者属性优先排序**：通过禁用`MapperFeature.SORT_CREATOR_PROPERTIES_FIRST`，确保创建者属性不会优先排序。这可以避免在某些情况下的意外行为。

feat: 优化流水线导出结构顺序 #10728

---

src/backend/ci/core/worker/worker-agent/src/test/kotlin/com/tencent/devops/worker/common/utils/CommandLineUtilsTest.kt
src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/CommandLineUtils.kt

#7932 fix
此拉取请求解决了 `reportProgressRate` 函数中的一个致命问题，并引入了若干改进以增强其健壮性和功能。
原始实现中存在一个致命缺陷，即它没有处理进度率字符串无法转换为 `Double` 的情况。这会导致运行时异常和潜在的崩溃。更新后的实现通过使用 `toDoubleOrNull()` 解决了这个问题，该方法安全地处理转换并在转换失败时返回 `null`。
1. **函数可见性**:
- **修改前**: `private fun reportProgressRate(...)`
- **修改后**: `fun reportProgressRate(...)`
- **原因**: 函数的可见性从 `private` 改为 `public`，以允许单测中使用
2. **补充单测**:
- **修改前**: 无。
- **修改后**: 详见文件。
- **原因**: 针对这一块的文本识别，很有必要添加单测。
3. **正则表达式模式**:
- **修改前**: `Pattern.compile("::set-progress-rate\\s*(.*)")`
- **修改后**: `Pattern.compile("^[\"]?::set-progress-rate\\s*(.*)$")`
- **原因**: 更新后的正则表达式模式确保即使进度率字符串被引号包围也能正确匹配。这防止了潜在的匹配错误和解析错误。
4. **进度率解析**:
- **修改前**: `val progressRate = matcher.group(1)`
- **修改后**: `val progressRate = matcher.group(1).removeSuffix("\"").toDoubleOrNull()`
- **原因**: …

【蓝盾-产品-已评审】流水线支持展示运行进度 #7932 fix

---

src/backend/ci/core/stream/api-stream/src/main/kotlin/com/tencent/devops/stream/pojo/message/UserMessageType.kt
src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/pojo/UserMessageData.kt
src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/BaseManualTriggerService.kt
src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/StreamTriggerRequestRepoService.kt
src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/StreamTriggerRequestService.kt
src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/StreamYamlBaseBuild.kt
src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/StreamYamlBuild.kt
src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/StreamYamlTrigger.kt
src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/EventActionFactory.kt
src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/data/ActionData.kt
src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/exception/handler/StreamTriggerExceptionHandler.kt
src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/exception/handler/StreamTriggerExceptionHandlerUtil.kt
src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/mq/streamTrigger/StreamTriggerListener.kt
src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/service/StreamEventService.kt
src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/service/UserMessageConsumer.kt

[stream] 优化大仓触发耗时 #10861

---

src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/interceptor/QueueInterceptor.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildEndControl.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildMonitorControl.kt

解决2个问题：
1、构建结束获取下一个排队构建，PopNextBuild 区分出1.0传统旧版的锁与2.0版本的并发组锁，不再以PipelineBuildStartLock为锁，
2、队列拦截器 QueueIntercepter 用的锁是错误，改为使用并发组锁

bug: 修正取消正在运行中构建可能产生的慢逻辑 #10874 修正锁的粒度，并发组与传统旧版的串行队列区分开

---

src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/app/AppPipelineBuildResource.kt
src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceBuildResource.kt
src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserBuildResource.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildDao.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildDetailService.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineProgressRateService.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/detail/BaseBuildDetailService.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/BaseBuildRecordService.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineStatusService.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServiceBuildResourceImpl.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserBuildResourceImpl.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/app/AppPipelineBuildResourceImpl.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt

feat：草稿版本UI展示 #9861 控制草稿相关查询内容

---

src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildRepositoryMaterialResource.kt
src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/PipelineBuildMaterial.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildDao.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineBuildMaterialService.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildRepositoryMaterialResourceImpl.kt

feat：源材料展示优化 #10733

---

src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineContainerService.kt

bug:某些构建场景下插入T_PIPELINE_BUILD_RECORD_TASK表的CONTAINER_ID字段值错误 #11029

bug:某些构建场景下插入T_PIPELINE_BUILD_RECORD_TASK表的CONTAINER_ID字段值错误 #11029

---

src/frontend/devops-environment/src/components/devops/environment/basic-information.vue
src/frontend/devops-nav/src/store/getters.ts
src/frontend/devops-nav/src/views/Home.vue
src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/BuildParams.vue
src/frontend/devops-pipeline/src/components/ExecDetail/detailContainer.vue
src/frontend/devops-pipeline/src/components/ExecDetail/log/pluginLog.vue
src/frontend/devops-pipeline/src/components/PipelineEditTabs/components/pipeline-param-form.vue
src/frontend/devops-pipeline/src/components/StagePropertyPanel/StageControl.vue
src/frontend/devops-pipeline/src/store/modules/common/jobOptionConfigMixin.js
src/frontend/devops-pipeline/src/store/modules/common/optionConfigMixin.js
src/frontend/locale/pipeline/en-US.json
src/frontend/locale/pipeline/zh-CN.json

访问流水线搜索日志，全屏浏览器查询搜索的日志，上方的搜索栏会消失 #11118

---

src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/dao/AtomDao.kt
src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/AtomServiceImpl.kt

perf:优化插件管理菜单默认插件查询 #11142

---

src/backend/ci/core/common/common-event/src/main/kotlin/com/tencent/devops/common/event/enums/PipelineBuildStatusBroadCastEventType.kt
src/backend/ci/core/common/common-event/src/main/kotlin/com/tencent/devops/common/event/pojo/pipeline/PipelineBuildStatusBroadCastEvent.kt
src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/event/CallBackData.kt
src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/utils/EventUtils.kt
src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/ThirdPartyAgentService.kt
src/backend/ci/core/metrics/api-metrics/src/main/kotlin/com/tencent/devops/metrics/pojo/po/MetricsUserPO.kt
src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/config/MetricsUserConfig.kt
src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/builds/MetricsCacheService.kt
src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/builds/MetricsUserService.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/TaskAtomService.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildEndControl.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildMonitorControl.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildStartControl.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/ContainerCmdLoop.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/StartActionTaskContainerCmd.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/UpdateStateContainerCmdFinally.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/StartContainerStageCmd.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/UpdateStateForStageCmdFinally.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/listener/run/PipelineTaskPauseListener.kt

feat：流水线/Job并发和排队数据落地 #10997

---

src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildQualityService.kt

bug: 使用流水线变量传入多个审核人时，审批不生效 #11127

bug: 使用流水线变量传入多个审核人时，审批不生效 #11127

---

src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/EnvReplacementParser.kt
src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/dialect/ClassicPipelineDialect.kt
src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/dialect/ConstrainedPipelineDialect.kt
src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/dialect/IPipelineDialect.kt
src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/ScriptTask.kt

#10576 
如果同一条流水线监听push和mr，然后在bash插件中根据事件类型读取不同事件的变量，这个时候流水线执行时会报错,导致变量不存在也无法支持

feat：流水线变量语法支持两种风格 #10576

---

src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/dialect/ClassicPipelineDialect.kt
src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/dialect/ConstrainedPipelineDialect.kt
src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/dialect/IPipelineDialect.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineBuildService.kt
src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/ITask.kt

#10576 
回退变量超长报错,因为插件可能输出超长变量,导致流水线报错,但是用户配置的流水线又不能修改

feat：流水线变量语法支持两种风格 #10576 回退变量超长报错

---

src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/op/OpPipelineViewResource.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineYamlInfoDao.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/op/OpPipelineViewResourceImpl.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/yaml/PipelineYamlRepositoryService.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/yaml/PipelineYamlService.kt

bug: [PAC].ci下的目录已经删除,但是关联的流水线组没有删除，也无法手工删除 #11254

---

src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/common/log/utils/BuildLogPrinter.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/interceptor/QueueInterceptor.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/pojo/event/PipelineBuildCancelEvent.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineContainerService.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildCancelControl.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildStartControl.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/StartActionTaskContainerCmd.kt

bug: 心跳超时被取消的插件没有刷新前端状态 #11265

---

src/backend/ci/core/artifactory/api-artifactory/src/main/kotlin/com/tencent/devops/artifactory/constant/ArtifactoryMessageCode.kt
src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/api/service/ServiceProjectAuthResource.kt
src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/cron/AuthCronSyncGroupAndMember.kt
src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/dao/AuthItsmCallbackDao.kt
src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/dao/AuthResourceGroupMemberDao.kt
src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/config/RbacAuthConfiguration.kt
src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionProjectService.kt
src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionResourceGroupSyncService.kt
src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionResourceMemberService.kt
src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/sample/service/SampleAuthPermissionProjectService.kt
src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/sample/service/SamplePermissionResourceMemberService.kt
src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/stream/service/StreamPermissionProjectServiceImpl.kt
src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/service/ServiceProjectAuthResourceImpl.kt
src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/PermissionProjectService.kt
src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/PermissionResourceMemberService.kt
src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/lock/CronSyncGroupMembersExpiredTimeLock.kt
src/backend/ci/core/common/common-archive/src/main/kotlin/com/tencent/devops/common/archive/pojo/BKRepoProjectUpdateRequest.kt
src/backend/ci/core/common/common-archive/src/main/kotlin/com/tencent/devops/common/archive/pojo/ProjectMetadata.kt
src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/dao/AtomDao.kt
support-files/i18n/artifactory/message_en_US.properties
support-files/i18n/artifactory/message_zh_CN.properties

feat：提供项目管理相关openapi接口 #11231

---

src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/atom/MarketAtomUpdateRequest.kt
src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/AtomReleaseServiceImpl.kt

bug:插件最新版本使用历史版本修复方式发布后，再用普通方式发布的分支会继承上一次的 #11301

bug:插件最新版本使用历史版本修复方式发布后，再用普通方式发布的分支会继承上一次的 #11301

---

.github/workflows/release.yml
src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/app/StartBuildContext.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/dao/PipelineTriggerEventDao.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStartUpService.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/code/CodeGitRepositoryService.kt
src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/code/CodeGithubRepositoryService.kt

bug: 修复流水线事件重放报500错误 #11333

---

src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/OauthRepositoryService.kt
src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/github/GithubOAuthService.kt

feat：支持管理我的 OAUTH #10995

---

src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/check/Preconditions.kt
src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/PipelineVersionWithModelRequest.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchBuildLessDockerStartupTaskAtom.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchVMStartupTaskAtom.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServicePipelineVersionResourceImpl.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineVersionResourceImpl.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineVersionFacadeService.kt
src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Runner.kt

feat：导出流水线功能优化 #11304

---

src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionResourceGroupSyncService.kt
src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionResourceMemberService.kt
src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionService.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/permission/AbstractPipelinePermissionService.kt
src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/permission/RbacPipelinePermissionService.kt

bug：用户组续期相关逻辑优化 #11305
feat：获取有权限的资源接口优化 #11246

feat：获取有权限的资源接口优化 #11246

---

src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/engine/atom/IAtomTask.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/control/VmOperateTaskGenerator.kt
src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/TaskAtomService.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchVMStartupTaskAtom.kt
src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/TaskControl.kt
src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Runner.kt

feat: taskControl的loop循环太久导致Consumer线程池被占满问题 #11352

feat: taskControl的loop循环太久导致Consumer线程池被占满问题 #11352

---

src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/environment/ApigwEnvironmentAgentResourceV3.kt
src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/environment/ApigwEnvironmentResourceV3.kt
src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/environment/ApigwEnvironmentAgentResourceV4.kt
src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/environment/ApigwEnvironmentResourceV4.kt
src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/environment/ApigwEnvironmentResourceV3Impl.kt
src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/environment/ApigwEnvironmentResourceV4Impl.kt

feat: api文档更新 #11409

---

src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/BuildParams.vue
src/frontend/devops-pipeline/src/components/PipelineEditTabs/components/children/select-type-param.vue

feat: 支持流水线模板内的输入参数需要支持“从接口获取选项”的功能 #11428

feat: 支持流水线模板内的输入参数需要支持“从接口获取选项”的功能 #11428

---

src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/dao/AtomBaseDao.kt
src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/dao/MarketAtomDao.kt
src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/AtomReleaseServiceImpl.kt
src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/dao/StoreBaseQueryDao.kt
src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreReleaseServiceImpl.kt

pref:优化研发商店组件下架逻辑 #11308

---

src/frontend/devops-pipeline/src/components/AtomPropertyPanel/FormField.vue
src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/BuildParams.vue
src/frontend/devops-pipeline/src/components/PipelineDetailTabs/BaseConfig.vue
src/frontend/devops-pipeline/src/components/PipelineEditTabs/components/children/param-value-option.vue
src/frontend/devops-pipeline/src/components/PipelineEditTabs/components/pipeline-param.vue
src/frontend/devops-pipeline/src/components/atomFormField/FileParamInput/index.vue
src/frontend/devops-pipeline/src/components/atomFormField/FileUpload/index.vue
src/frontend/devops-pipeline/src/components/pipelineParamsForm.vue
src/frontend/devops-pipeline/src/store/modules/atom/paramsConfig.js
src/frontend/devops-pipeline/src/utils/util.js
src/frontend/locale/pipeline/en-US.json
src/frontend/locale/pipeline/zh-CN.json

feat：文件类型变量上传的文件支持版本管理 #11467

---

src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/filter/RequestProjectPermissionFilter.kt
src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/cron/process/PipelineBuildHistoryDataClearJob.kt
src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/dao/process/ProcessDao.kt
src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/service/process/ProcessMiscService.kt

bug: 代码框架升级导致Jersey 的 getAnnotation方法获取不到方法上的注解 #12237

bug: 代码框架升级导致Jersey 的 getAnnotation方法获取不到方法上的注解 #12237
