TencentBlueKing/bk-ci

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomOption.vue
- src/frontend/devops-pipeline/src/store/modules/common/optionConfigMixin.js
feat: 对具有暂停功能的插件，新选择十，默认自动勾选中'执行前暂停' #7830
> feat: 对具有暂停功能的插件，新选择时，默认自动勾选中'执行前暂停' #7830

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleCheckService.kt
> feat:质量红线默认通知人改为流水线触发人 #7934

- src/frontend/devops-pipeline/src/views/subpages/exec_detail.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
> feat: 流水线详情页面执行人改为触发人 #7933

- src/backend/ci/core/process/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/modelCreate/ModelContainer.kt
- src/backend/ci/core/process/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/modelCreate/ModelStage.kt
> docker-on-devcloud 无法正常挂载 #7977

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/TaskControl.kt
bug:插件在构建机网络异常情况下自动重试造成流水线状态异常 #8030
#8030
> bug:插件在构建机网络异常情况下自动重试造成流水线状态异常 #8030

- src/backend/booster/bk_dist/controller/pkg/manager/remote/mgr.go
- src/backend/booster/bk_dist/controller/pkg/manager/resource/mgr.go
- src/backend/booster/bk_dist/controller/pkg/types/interface.go
尽量保证 work锁和resource锁不会相互包含，减少死锁的风险。
> bug: bk-dist-controller有可能死锁, issue: #8063

- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/scm/ServiceGitResource.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/scm/ServiceGitResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/GitService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/IGitService.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/service/StreamGitTransferService.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/service/transfer/StreamGithubTransferService.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/service/transfer/StreamTGitTransferService.kt
> [stream]主动开启工蜂侧ci #8067

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeGitScmOauthImpl.kt
> feat: 工蜂接口api url使用配置apiUrl #8033

- .github/workflows/release.yml
- helm-charts/core/ci/templates/gateway/deployment.yaml
- src/gateway/core/nginx.conf
- src/gateway/core/nginx.status.conf
> feat: nginx进程优雅退出 #8039

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/enums/BuildStatus.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/detail/TaskBuildDetailService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/StartActionTaskContainerCmd.kt
bug:post-action没有正常执行 #8029
#8029
> bug:post-action没有正常执行 #8029

- src/frontend/devops-stream/src/views/notifications.vue
feature: 【commit check】上报代码库的信息优化 issue #8012
> feature: 【commit check】上报代码库的信息优化 issue #8012

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/ShellUtil.kt
> fix: 内置Bash插件过滤掉中文命名的变量 #7987

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/enums/RepositoryTypeNew.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/interceptor/TimerTriggerScmChangeInterceptor.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/ExternalCodeccRepoResource.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/ExternalCodeccRepoResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/CommonRepoFileService.kt
> feat: 给codecc提供判断是否是代码库成员接口 #8004

- src/backend/ci/build.gradle.kts
- src/backend/ci/buildSrc/src/main/kotlin/constants/Versions.kt
- src/backend/ci/core/artifactory/api-artifactory/src/main/kotlin/com/tencent/devops/artifactory/pojo/FileDetail.kt
- src/backend/ci/core/artifactory/api-artifactory/src/main/kotlin/com/tencent/devops/artifactory/pojo/FileDetailForApp.kt
> feat: bkrepo升级--新增nodeMetadata字段 #8079

- src/agent/src/pkg/api/ErrorEnum.go
- src/agent/src/pkg/job/build_docker.go
- support-files/agent-package/script/linux/agent_docker_init.sh
> Agent支持启动docker镜像作为构建机 #7748

- src/backend/ci/core/metrics/api-metrics/src/main/kotlin/com/tencent/devops/metrics/api/ServiceMetricsResource.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/resources/ServiceMetricsResourceImpl.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwMetricsResourceV4.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/pojo/ApigwMetricsSummary.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwMetricsResourceV4Impl.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/BuildHistoryWithVars.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> [openapi]新增metric接口和build_status接口增加排队位置 #8088

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/op/OpPipelineViewResource.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/label/PipelineViewDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/label/PipelineViewGroupDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/op/OpPipelineViewResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineListFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/view/PipelineViewGroupService.kt
> feat: 流水线组及流水线列表页优化 #7101

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/detail/TaskBuildDetailService.kt
bug:执行带有postAction的插件的job耗时计算不准 #8133
#8133
> bug:执行带有postAction的插件的job耗时计算不准 #8133

- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/config/DataSourceConfig.kt
pref:调整misc服务数据连接池连接数量 #8123
#8123
> pref:调整misc服务数据连接池连接数量 #8123

- src/backend/ci/core/metrics/api-metrics/src/main/kotlin/com/tencent/devops/metrics/pojo/po/UpdateErrorCodeInfoPO.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/dao/MetricsDataQueryDao.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/dao/MetricsDataReportDao.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/impl/MetricsDataReportServiceImpl.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/utils/ErrorCodeInfoCacheUtil.kt
pref:metrics数据上报错误信息录入逻辑在高并发场景优化 #8078
#8078
> pref:metrics数据上报错误信息录入逻辑在高并发场景优化 #8078

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/interceptor/QueueInterceptor.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/interceptor/RunLockInterceptor.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildStartControl.kt
> [并发组] 兼容旧流水线版本 #8143

- src/frontend/devops-turbo/src/api/index.js
- src/frontend/devops-turbo/src/components/render/mixins.js
- src/frontend/devops-turbo/src/components/render/select.vue
feature: 编译加速方案参数支持联动和从接口获取 issue #8099
> feature: 编译加速方案参数支持联动和从接口获取 issue #8099

- src/gateway/core/lua/util/tag_util.lua
> feat: 网关路由前端文件夹,判断tag的时候要去掉kubernetes- #8175

- src/backend/ci/build.gradle.kts
- src/backend/ci/buildSrc/build.gradle.kts
- src/backend/ci/buildSrc/src/main/kotlin/plugins/task-docker-build.gradle.kts
- src/backend/ci/core/common/common-client/build.gradle.kts
- src/backend/ci/core/dispatch/boot-dispatch/build.gradle.kts
- src/backend/ci/gradle.properties
- src/backend/ci/settings.gradle.kts
> feat: 编写容器打包插件 #8084

- src/frontend/devops-metrics/src/views/child-view/plugin-trend/plugin-run-analysis/children/analysis-table.vue
feature: 优化metric数据统计展示 issue #8086
> feature: 优化metric数据统计展示 issue #8086

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineStageService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildCancelControl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/UpdateStateForStageCmdFinally.kt
> bug: stage审核在取消构建时状态刷新异常 #8203 修复取消构建异常

- src/frontend/devops-pipeline/package.json
- src/frontend/devops-stream/package.json
> feature: 优化日志搜索空格 issue #8236

- src/frontend/devops-stream/src/http/setting.js
- src/frontend/devops-stream/src/utils/index.js
- src/frontend/devops-stream/src/views/pipeline/build-list.vue
> bug: stream数据库sql优化 #8240

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/cron/QualityBuildHisJob.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/cron/QualityHisMetadataJob.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/dao/v2/QualityHisMetadataDao.kt
> perf: 红线元数据历史记录清理优化 #8222

- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/StreamYamlBuild.kt
> [stream] 调用共享环境时不应需要调用方权限 #8261

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/OpAtomServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/utils/AtomReleaseTxtAnalysisUtil.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/util/RetryUtils.kt
> [stream] 工蜂429限频，重试逻辑优化 #8132

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwPipelineViewResourceV4.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwPipelineResourceV4Impl.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwPipelineViewResourceV4Impl.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServicePipelineViewResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/PipelineVarUtil.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/label/PipelineViewDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServicePipelineViewResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/view/PipelineViewService.kt
- src/backend/ci/core/process/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v2/utils/ScriptYmlUtils.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/listener/components/SendNotify.kt
> [stream]v4_app_pipeline_status接口兼容stream #8241

- helm-charts/core/ci/build/values.yaml
- helm-charts/core/ci/templates/openapi/deployment.yaml
- helm-charts/core/ci/templates/openapi/secret.yaml
- scripts/bkenv.properties
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/filter/impl/BlueKingApiFilter.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/filter/impl/SampleApiFilter.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/utils/ApiGatewayPubFile.kt
- support-files/templates/#etc#ci#application-openapi.yml
> openapi 支持蓝鲸网关jwt鉴权 #8226

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildSummaryDao.kt
> 【蓝盾-无需评审会】perf：流水线删除后的展示优化 #8270

- helm-charts/core/ci/build_chart.py
- scripts/bkenv.properties
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/FeignConfiguration.kt
- src/gateway/core/lua/util/consul_util.lua
- support-files/templates/#etc#ci#common.yml
- support-files/templates/gateway#core#lua#ip_whitelist.lua
> feat: 网关支持ip白名单 #8302

- .github/workflows/release.yml
- docker-images/core/ci/dockerfile/backend.bkci.sh
- helm-charts/core/ci/templates/monitoring/deployment.yaml
- helm-charts/core/ci/templates/monitoring/hpa.yaml
- helm-charts/core/ci/templates/monitoring/service.yaml
> feat: 容器化monitoring上线 #8298

- helm-charts/core/ci/templates/init/init.iam.yaml
> feat: 容器化iam初始化 ,不走public外网回调 #8304

- src/backend/ci/core/common/common-wechatwork/src/main/kotlin/com/tencent/devops/common/wechatwork/WechatWorkService.kt
> feat：人工审核/stage准入支持发送企业微信群消息 #7971

- src/gateway/core/frontend.conf
> feat: 网关开启HSTS #7884

- src/frontend/devops-atomstore/src/views/manage/setting/private-setting.vue
> feat: 【研发商店】插件私有配置当字段值是明文展示时，聚焦编辑框不需要清空 #8288

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelinePostElementService.kt
feat：被禁用的插件的Post action会导致在插件重试时，影响已完成的job #8294
> feat：被禁用的插件的Post action会导致在插件重试时，影响已完成的job #8294

- src/frontend/devops-pipeline/src/components/ExecDetail/log/jobLog.vue
- src/frontend/devops-pipeline/src/components/ExecDetail/log/pluginLog.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
feature: 日志展示中英文调整 issue #8026
> feature: 日志展示中英文调整 issue #8026

- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/utils/ZipUtil.kt
bug:文件解压工具类解压压缩文件时文件流未及时关闭释放 #8342
#8342
> bug:文件解压工具类解压压缩文件时文件流未及时关闭释放 #8342

- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/atom/OpAtomResource.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/AtomDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/atom/OpAtomResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/OpAtomService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/OpAtomServiceImpl.kt
> feat：插件列表支持根据插件标识搜索 #8280

- src/backend/ci/core/common/common-redis/src/main/kotlin/com/tencent/devops/common/redis/RedisLock.kt
> feat: kotlin升级 #7990

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityPipelineService.kt
bug: 质量红线选择生效范围时提示流水线中的代码检查任务为异步 #8333
> bug: 质量红线选择生效范围时提示流水线中的代码检查任务为异步 #8333

- src/backend/ci/core/quality/api-quality/src/main/kotlin/com/tencent/devops/quality/api/v2/pojo/op/IndicatorData.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityIndicatorService.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleCheckService.kt
feat: CodeCC的红线指标链接由指标详情自定义设置 #7545
> feat: CodeCC的红线指标链接由指标详情自定义设置 #7545

- src/backend/ci/build.gradle.kts
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/impl/NodeJsAtomRunConditionHandleServiceImpl.kt
bug:构建机上未安装node环境执行node插件偶报node命令找不到 #8404
> bug:构建机上未安装node环境执行node插件偶报node命令找不到 #8404

- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/FeignConfiguration.kt
> feat: feign在有项目ID的时候, 不强制加入网关路由tag #8380

- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/filter/BlackListAspect.kt
- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/prometheus/BkTimedAspect.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/aspect/ApiAspect.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/StoreApiAspect.kt
> feat: 避免aspectj对jooq的影响 #8335

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/PipelineStatus.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineStatusService.kt
> feat: 流水线websocket返回trigger字段 #8394

- src/frontend/devops-pipeline/src/components/pipelineSetting/settingBase/index.vue
> feat: 模版的并发设置对齐流水线 #8129

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeTGitScmImpl.kt
> feat: 希望Tgit支持commit check评论

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwBuildResourceV4.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwBuildResourceV4Impl.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceBuildResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/setting/PipelineSetting.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServiceBuildResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServicePipelineResourceImpl.kt
> v4_app_build_retry 支持用buildNum 参数来触发。 #8370

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwAuthGrantResourceV3.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwPermissionMoveResourceV3.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwProjectResourceV3.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwAuthGrantResourceV4.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwPermissionMoveResourceV4.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwProjectResourceV4.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/aspect/ApiAspect.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwAuthGrantResourceV3Impl.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwProjectResourceV3Impl.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwAuthGrantResourceV4Impl.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwPermissionMoveResourceV4Impl.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwProjectResourceV4Impl.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/service/OpenapiPermissionService.kt
> openapi调用链路稳定性建设 #8339

- helm-charts/core/ci/build_chart.py
- scripts/bkenv.properties
- src/frontend/devops-nav/src/index.html
- src/frontend/devops-nav/src/index.ts
- src/frontend/devops-pipeline/src/components/pipelineList/PipelineTemplatePopup/index.vue
- src/frontend/locale/index.js
> feat: 支持国际化初始值可配置 issue #8421

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/WorkRunner.kt
> WorkRunner类中异常不退出worker-agent #8360

- src/frontend/devops-nav/src/components/User/index.vue
- src/frontend/devops-pipeline/src/components/CheckParams.vue
> bug: [bug]退出登录不可用 issue #8428

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/measure/MeasureServiceImpl.kt
社区版热度数据异常——MeasureService插件开源调整 #8287
> pref: 社区版热度数据异常issue#8287

- src/backend/ci/core/common/common-archive/src/main/kotlin/com/tencent/devops/common/archive/client/BkRepoClient.kt
- src/backend/ci/core/common/common-archive/src/main/kotlin/com/tencent/devops/common/archive/config/BkRepoClientConfig.kt
> feat: bkrepo的分享链接直接用bkrepo域名下载 #8467

- docker-images/core/ci/dockerfile/backend.bkci.sh
- src/backend/ci/buildSrc/src/main/kotlin/plugins/task-docker-build.gradle.kts
> bug: 修复读取配置文件错误 #8477

- .github/workflows/release.yml
> feat: workflow中去掉codecc和bkrepo的编译 #8439

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/BaseBuildRecordService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/TaskBuildRecordService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> feat：流水线构建详情页重构需求 #7983 并发锁问题

- support-files/templates/#etc#ci#application-process.yml
开源版研发商店热点数据异常 MeasureService插件开源调整
> pref:MeasureService插件开源调整 issue#8287

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Runner.kt
> bug: 构建机报错未兜底上报构建日志 #8373

- src/frontend/devops-metrics/src/components/scroll-load-select.tsx
- src/frontend/devops-metrics/src/http/api.ts
- src/frontend/devops-metrics/src/views/child-view/plugin-trend/plugin-fail-analysis/children/analysis-filter.vue
- src/frontend/devops-metrics/src/views/child-view/plugin-trend/plugin-fail-analysis/common/props-type.ts
- src/frontend/devops-metrics/src/views/child-view/plugin-trend/plugin-fail-analysis/fail-analysis-main.vue
> bug：metrics插件趋势错误流水线构建页面的错误码要按错误类型查询 #8103

- src/frontend/devops-environment/src/components/devops/environment/third-construct-dialog.vue
- src/frontend/devops-environment/src/views/node_list.vue
- src/frontend/locale/environment/en-US.json
- src/frontend/locale/environment/zh-CN.json
主集群和子集群间构建制品网关与流量网关的配置优化 #8505
> 主集群和子集群间构建制品网关与流量网关的配置优化 #8505(前端)

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineContainerService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/BaseBuildRecordService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/ContainerBuildRecordService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/PipelineBuildRecordService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/StageBuildRecordService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/TaskBuildRecordService.kt
> bug: 依赖job重试成功后导致矩阵插件状态异常 #8523

- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/user/UserDeptDetail.kt
> feat:修复TOF同步数据Bug #8516

- src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/common/log/pojo/TaskBuildLogProperty.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/logger/LoggerService.kt
> feat: 制品库无法归档的第三方构建机日志支持保留至指定目录 #8391

- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/Profile.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/template/TemplateInstanceCronService.kt
pref:模板异步更新任务按环境获取redis锁 #8536
#8536
> pref:模板异步更新任务按环境获取redis锁 #8536

- helm-charts/core/ci/base/default_env.yaml
- scripts/bkenv.properties
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/view/PipelineViewGroupService.kt
- support-files/templates/gateway#core#frontend.conf
> feat: 网关前端支持CDN配置 #8493

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/record/BuildRecordStageDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/record/PipelineRecordModelService.kt
bug:新版构建详情页因排序问题导致数据合并异常 #8558
#8558
> bug:新版构建详情页因排序问题导致数据合并异常 #8558

- src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/cron/ClearTimeoutCron.kt
> feat: 优化websocket清理过期session逻辑 #8543

- src/frontend/devops-stream/src/components/setting/edit-credential.vue
- src/frontend/devops-ticket/src/store/index.js
- src/frontend/locale/stream/en-US.json
- src/frontend/locale/stream/zh-CN.json
- src/frontend/locale/ticket/en-US.json
- src/frontend/locale/ticket/zh-CN.json
feature: repo-hook 监听凭据支持 OAUTH token #8216 #8415
>  feature: repo-hook 监听凭据支持 OAUTH token #8216 #8415

- src/backend/ci/core/project/biz-project-sample/src/main/kotlin/com/tencent/devops/project/service/SimpleProjectServiceImpl.kt
> feat: 蓝盾对接权限中心RBAC #7794

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/extend/DefaultModelCheckPlugin.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildMonitorControl.kt
> 超时时间字段支持填写变量 #7954

- src/gateway/core/lua/util/consul_util.lua
- src/gateway/core/lua/util/tag_util.lua
- support-files/templates/gateway#core#lua#init.lua
> feat: 优化kubernetes部署 #8546

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/engine/common/BuildTimeCostUtils.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/record/BuildRecordContainerDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/record/BuildRecordTaskDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineStageService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/ContainerBuildRecordService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/StageBuildRecordService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/TaskBuildRecordService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/UpdateStateForStageCmdFinally.kt
> feat：流水线构建详情页重构需求 issue #7983 优化跳过逻辑

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
模板提示语未格式化问题为全局问题，此次因增加了超时提示而暴露出， 暂时按现有国际化方案继续获得出错信息
> 流水线模板中提示信息未格式化 #7954

- src/frontend/devops-atomstore/src/components/common/detail-info/atom.vue
- src/frontend/devops-atomstore/src/views/market/list.vue
- src/frontend/devops-pipeline/src/components/AtomSelector/atomCard.vue
feature: 流水线插件支持展示获得的荣誉和SLA等信息 issue #8114
> feature: 流水线插件支持展示获得的荣誉和SLA等信息 issue #8114

- src/gateway/core/lua/access_control.lua
- src/gateway/core/lua/router_srv.lua
- src/gateway/core/nginx.conf
- support-files/templates/gateway#core#devops.server.conf
> feat: 网关访问控制对所有路径生效 #8626

- helm-charts/core/ci/base/values.yaml
> feat: turbo的values修复 #8628

- src/backend/ci/core/artifactory/biz-artifactory-store/src/main/kotlin/com/tencent/devops/artifactory/service/impl/ArchiveAtomServiceImpl.kt
pref:开源版上传插件包时取消发布再发布场景不能依据前端传的插件ID上传 #8642
> pref:开源版上传插件包时取消发布再发布场景不能依据前端传的插件ID上传 #8642

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwPipelineViewResourceV4.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/BaseAction.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/github/GithubActionGit.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/streamActions/StreamManualAction.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/streamActions/StreamRepoTriggerAction.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/tgit/TGitActionGit.kt
> [stream]手动触发 #8554

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/time/BuildRecordTimeCost.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwBuildResourceV3.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwCallBackResourceV3.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwCredentialResourceV3.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwLogResourceV3.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwArtifactoryResourceV4.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwBuildResourceV4.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwCallBackResourceV4.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwCredentialResourceV4.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwLogResourceV4.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwRepositoryResourceV4.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/aspect/ApiAspect.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwArtifactoryFileTaskResourceV4Impl.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwArtifactoryResourceV4Impl.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwBuildResourceV4Impl.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwLogResourceV4Impl.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwRepositoryCommitResourceV4Impl.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/service/OpenapiPermissionService.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/BuildHistoryWithVars.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/PipelineCopy.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/setting/PipelineSetting.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/template/TemplateInstanceUpdate.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServiceBuildResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServicePipelineResourceImpl.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/ProjectVO.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/pojo/CodeGitRepository.kt
> api文档优化（2022.10-2023.04） #8594

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/BuildTemplateAcrossInfo.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/PipelineBuildTemplateAcrossInfoDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineBuildTemplateAcrossInfoService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/InitializeMatrixGroupStageCmd.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/StreamYamlBaseBuild.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/StreamYamlBuild.kt
> 矩阵支持跨库凭证引用 #8514

- src/gateway/core/lua/util/consul_util.lua
> feat: 容器换环境不能调用consul #8643

- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/template/YamlTemplateService.kt
> [stream] 优化远程模板凭据引用 #8667

- src/backend/ci/core/common/common-redis/src/main/kotlin/com/tencent/devops/common/redis/RedisOperation.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/filter/PathStreamFilter.kt
- src/backend/ci/core/process/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/modelCreate/ModelCreate.kt
- src/backend/ci/core/process/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/modelCreate/ModelElement.kt
- src/backend/ci/core/process/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/modelCreate/ModelStage.kt
- src/backend/ci/core/process/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/utils/PathMatchUtils.kt
- src/backend/ci/core/process/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v2/models/Concurrency.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/service/StreamHistoryService.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/parsers/triggerMatch/matchUtils/PathMatchUtils.kt
> 【stream】concurrency 和蓝盾功能对齐 #8631

- .github/workflows/release.yml
- helm-charts/core/ci/base/values.yaml
- helm-charts/core/ci/templates/init/init.workerVersion.yaml
> feat: worker-agent设置版本 #8693

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityIndicatorService.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/atom/ServiceMarketAtomResource.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/common/StoreProjectRelDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/atom/ServiceMarketAtomResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/AtomService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomServiceImpl.kt
bug: 质量红线获取项目下可使用插件的指标缺失 #8565
> bug: 质量红线获取项目下可使用插件的指标缺失 #8565

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityIndicatorService.kt
> bug: 创建自定义指标报错英文名已存在 #8605

- .github/workflows/backend_booster.yml
- .github/workflows/release.yml
> feat: github action 的 go 版本升级 #8728

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
bug: 自定义插件task.json中使用demands设置环境变量不生效 #8665
#8665
> bug: 自定义插件task.json中使用demands设置环境变量不生效 #8665

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/StageControl.kt
> bug: Stage条件判断支持新表达式 #8722

- src/gateway/core/backend.conf
- src/gateway/core/lua/util/loadbalance_util.lua
> feat: 转发请求到容器化网关时带上token #8725

- src/frontend/devops-metrics/src/components/scroll-load-select.tsx
- src/frontend/locale/metrics/en-US.json
- src/frontend/locale/metrics/zh-CN.json
> perf：metrics 服务小优化 #8623

- src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/cron/ClearTimeoutCron.kt
> feat: 优化websocket的日志, 避免日志过大 #8756

- src/gateway/core/lua/util/redis_util.lua
- support-files/templates/gateway#core#lua#init.lua
> feat: 调整网关redis线程池大小 #8763

- src/backend/ci/core/process/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/modelCreate/ModelElement.kt
- src/backend/ci/core/process/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/modelCreate/inner/ModelCreateEvent.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/StreamYamlBuild.kt
> [stream]注册插件使用ci开启身份进行 #8767

- src/gateway/core/backend.conf
> feat: 网关backend路径新增remotedev #8768

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildSummaryDao.kt
并发的情况下，不用考虑是否是当前的LATEST_BUILD_ID，而且会造成Slow SQL
> bug: 流水线启动接口性能优化 #8615

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineContextService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/StartActionTaskContainerCmd.kt
> bug: 矩阵内支持上下文缩写引用 #8641 支持上下文缩写

- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/dao/LogStatusDao.kt
> perf: 部分jooq逻辑优化 #8678 日志模块问题修复

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/environment/ApigwEnvironmentAgentResourceV4.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/environment/ApigwEnvironmentAgentResourceV4Impl.kt
> feat: 获取第三方构建机信息使用agentId #8778

- src/backend/ci/core/common/common-db-sharding/src/main/kotlin/com/tencent/devops/common/db/config/BkShardingDataSourceConfiguration.kt
- src/backend/ci/core/common/common-db/src/main/kotlin/com/tencent/devops/common/db/DBAutoConfiguration.kt
> 将数据库连接池大小配置化 #8615

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/interceptor/InterceptData.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/interceptor/QueueInterceptor.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/interceptor/RunLockInterceptor.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineBuildService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
https://github.com/TencentBlueKing/bk-ci/pull/8796#issue-1705833113
> [bug] 并发组排队异常 #8794

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/p4/api/P4Api.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/p4/api/P4ServerInfo.kt
- src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/pojo/code/PathFilterConfig.kt
- src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/pojo/code/p4/P4ChangeEvent.kt
- src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/pojo/code/p4/P4ShelveEvent.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/EventCacheService.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/filter/BasePathFilter.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/filter/PathFilterFactory.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/filter/PathRegexFilter.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/p4/P4ChangeTriggerHandler.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/p4/P4ShelveTriggerHandler.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/pojo/EventRepositoryCache.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/test/kotlin/com/tencent/devops/common/webhook/service/code/filter/PathRegexFilterTest.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/test/kotlin/com/tencent/devops/common/webhook/service/code/matcher/P4WebHookMatcherTest.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/ServiceP4Resource.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/ServiceP4ResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/Ip4Service.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/P4Service.kt
> feat：P4事件触发支持自主选择对大小写是否敏感

- src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/common/log/utils/BuildLogPrinter.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/dao/LogStatusDao.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/event/LogStatusEvent.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/resources/BuildLogPrintResourceImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/resources/ServiceLogPrintResourceImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/BuildLogListenerService.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/LogStatusService.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/impl/LogServiceESImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/impl/LogServiceLuceneImpl.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchBuildLessDockerShutdownTaskAtom.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchVMShutdownTaskAtom.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildEndControl.kt
> bug: 日志时间戳乱序导致重复查询 #8804

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineContextService.kt
> bug: 第三方构建机工作空间变量解析缺少上下文 #8803

- src/gateway/core/lua/util/tag_util.lua
- support-files/templates/gateway#core#lua#init.lua
> issue: 网关支持切换整个route_tag到容器化 #8827

- src/frontend/devops-stream/src/components/exec-detail/job.vue
bugfix: stream 登录调试 vmSeqId 参数 #8818
> bugfix: stream 登录调试 vmSeqId 参数 #8818

- src/frontend/devops-ticket/src/views/create_credential.vue
> feature: 添加项目管理前端服务 issue #7923

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/detail/ContainerBuildDetailService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/ContainerBuildRecordService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
bug:运行开机内置插件时，点击取消可能取消不了构建 #8789
#8789
> bug:运行开机内置插件时，点击取消可能取消不了构建 #8789

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityHistoryService.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/util/QualityUrlUtils.kt
bug: stream的CodeCC红线指标没有关联忽略问题链接 #8821
> bug: stream的CodeCC红线指标没有关联忽略问题链接 #8821

- src/backend/ci/core/common/common-web/src/main/resources/common-web.properties
> feat: spring 优雅停机 #8833

- src/gateway/core/lua/util/tag_util.lua
- support-files/templates/gateway#core#lua#init.lua
> feat: 容器化route_tag区分ci和codecc #8848

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwRepositoryResourceV4.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwRepositoryResourceV4Impl.kt
> feat: 增加获取代码库详情openapi接口 #8850

- src/frontend/devops-environment/src/components/devops/environment/third-construct-dialog.vue
- src/frontend/devops-environment/src/views/node_list.vue
- src/frontend/locale/environment/en-US.json
- src/frontend/locale/environment/zh-CN.json
feat: 主集群和子集群间构建制品网关与流量网关的配置优化 #8505
> feat: 主集群和子集群间构建制品网关与流量网关的配置优化 #8505

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Constants.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/logger/LoggerService.kt
> perf: 日志单行输出超过限制（16KB）自动分行 #8856

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineContextService.kt
> bug: 上下文的状态字段异常 #8861

- src/gateway/core/lua/util/tag_util.lua
> feat: worker路径的tag需要去掉容器化标志 #8869

- src/gateway/core/lua/util/tag_util.lua
- support-files/templates/gateway#core#lua#init.lua
> feat: 网关新增强制容器化header #8863

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomServiceImpl.kt
> pref:蓝盾国际化方案优化 #8211

- helm-charts/core/ci/templates/artifactory/statefulset.yaml
- helm-charts/core/ci/templates/auth/deployment.yaml
- helm-charts/core/ci/templates/dispatch/deployment.yaml
- helm-charts/core/ci/templates/dispatchDocker/deployment.yaml
- helm-charts/core/ci/templates/dispatchKubernetes/deployment.yaml
- helm-charts/core/ci/templates/environment/deployment.yaml
- helm-charts/core/ci/templates/image/deployment.yaml
- helm-charts/core/ci/templates/log/deployment.yaml
- helm-charts/core/ci/templates/metrics/deployment.yaml
- helm-charts/core/ci/templates/misc/deployment.yaml
- helm-charts/core/ci/templates/monitoring/deployment.yaml
- helm-charts/core/ci/templates/notify/deployment.yaml
- helm-charts/core/ci/templates/openapi/deployment.yaml
- helm-charts/core/ci/templates/plugin/deployment.yaml
- helm-charts/core/ci/templates/process/deployment.yaml
- helm-charts/core/ci/templates/project/deployment.yaml
- helm-charts/core/ci/templates/quality/deployment.yaml
- helm-charts/core/ci/templates/repository/deployment.yaml
- helm-charts/core/ci/templates/store/deployment.yaml
- helm-charts/core/ci/templates/stream/deployment.yaml
- helm-charts/core/ci/templates/ticket/deployment.yaml
- helm-charts/core/ci/templates/websocket/statefulset.yaml
> feat: 关闭jvm进程之前等待30秒 #8875

- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/ActivityService.kt
perf：最新动态的时间展示 xxxx-xx-xx hh:mm:ss #8838
> perf：最新动态的时间展示 xxxx-xx-xx hh:mm:ss #8838

- src/frontend/devops-permission/src/views/applyPermission/group-search.vue
- src/frontend/devops-permission/src/views/applyPermission/search-select.vue
> feature: 添加项目管理前端服务  issue #7923

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/TaskAtomService.kt
> bug: Job启动插件收到取消请求时意外返回失败 #8879

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildSummaryDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
> 流水线LATEST STATUS 状态取最新次构建的状态 #8907

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/extend/DefaultModelCheckPlugin.kt
> bug: 新详情页数据问题修复 #8890

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> hotfix:蓝盾国际化方案优化 #8211

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/BaseBuildRecordService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/PipelineBuildRecordService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> bug: 新详情页数据问题修复 #8890 增加耗时计算

- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/ProjectService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/service/StreamBasicSettingService.kt
> feat: 增加stream开启pac模式的环境配置 #8939

- src/backend/ci/core/common/common-web/src/main/resources/common-web.properties
> feat: JerseyConfig初始化完之后端口才可以访问 #8946

- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/migrate/MigrateV3PolicyService.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/pipeline/record/BuildRecordContainer.kt
> feat: 蓝盾对接权限中心RBAC优化 #8941

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/app/StartBuildContext.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildQualityService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/TaskBuildRecordService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/task/ManualReviewTaskAtom.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/InitializeMatrixGroupStageCmd.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineRetryFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/websocket/listener/PipelineWebSocketListener.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/websocket/page/RecordPageBuild.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/websocket/push/RecordWebsocketPush.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/websocket/service/PipelineWebsocketService.kt
> feat：构建详情页问题优化 #8955 增加websocket推送

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/PipelineSettingDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/PipelineSettingVersionDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineInfoDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/util/NotifyTemplateUtils.kt
- support-files/i18n/process/message_en_US.properties
- support-files/i18n/process/message_zh_CN.properties
> hotfix：bug:流水线通知信息异常 #8983

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/record/PipelineRecordModelService.kt
> feat：构建详情页问题优化 #8955 补充矩阵内容

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/pipeline/record/BuildRecordContainer.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineContainerService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/record/PipelineRecordModelService.kt
> feat：构建详情页问题优化 #8955 补充矩阵post内容

- src/backend/ci/core/common/common-db-sharding/build.gradle.kts
- src/backend/ci/core/common/common-db-sharding/src/main/kotlin/com/tencent/devops/common/db/config/BkShardingDataSourceConfiguration.kt
- src/backend/ci/core/common/common-redis/build.gradle.kts
- src/backend/ci/core/common/common-redis/src/main/kotlin/com/tencent/devops/common/redis/RedisAutoConfiguration.kt
- src/backend/ci/core/common/common-service/build.gradle.kts
- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/MicroService.kt
- src/backend/ci/core/common/common-service/src/main/resources/common-service.properties
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/BkJerseyTagProvider.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/WebAutoConfiguration.kt
> feat: shardingDatabase接入micrometer #8999

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/pipeline/record/BuildRecordContainer.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/pipeline/record/BuildRecordStage.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/pipeline/record/BuildRecordTask.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildTaskDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/pojo/UpdateTaskInfo.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineContainerService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineTaskService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/BaseBuildRecordService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/PipelineBuildRecordService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/record/PipelineRecordModelService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/TaskAtomService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildStartControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineRetryFacadeService.kt
> feat：构建详情页问题优化 #8955

- src/frontend/devops-pipeline/src/components/StartParams.vue
- src/frontend/devops-pipeline/src/components/pipelineSetting/RunningLock.vue
feat: 并发组排队的队列长度上限由20调整到200 #8989
feat：构建详情页问题优化 issue #8955
> feat：构建详情页问题优化 issue #8955

- src/backend/ci/build.gradle.kts
> feat: framework更新到0.0.7 #9027

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/record/PipelineRecordModelService.kt
bug:构建详情页针对矩阵场景post插件渲染修复 #9026
#9026
> bug:构建详情页针对矩阵场景post插件渲染修复 #9026

- src/backend/ci/core/common/common-service/src/main/resources/logback/appender.xml
> feat: 日志每1GB就切割 #9048

- helm-charts/core/ci/base/values.yaml
- helm-charts/core/ci/templates/init/init.plugin.yaml
> feat: github插件下载加速 #8938

- src/frontend/devops-nav/src/index.ts
> bug: 关联代码库，添加一个仓库接口报错后页面一直处于loading状态 #9046

- src/backend/ci/buildSrc/src/main/kotlin/constants/Versions.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/config/RbacAuthConfiguration.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/migrate/MigrateResourceService.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/migrate/MigrateResultService.kt
- src/backend/ci/core/common/common-auth/common-auth-rbac/src/main/kotlin/com/tencent/devops/common/auth/RbacAuthAutoConfiguration.kt
- src/backend/ci/core/common/common-auth/common-auth-rbac/src/main/kotlin/com/tencent/devops/common/auth/utils/RbacAuthUtils.kt
> bug: 权限迁移策略对比优化 #9066

- src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/pojo/code/git/GitEvent.kt
- src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/pojo/code/git/GitPushEvent.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitPushTriggerHandler.kt
> feat：优化GIT PUSH事件触发判定逻辑 #8978

- src/backend/ci/core/websocket/api-websocket/src/main/kotlin/com/tencent/devops/websocket/api/UserWebsocketResource.kt
- src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/configuration/WebSocketConfig.kt
> feat: websocket支持desktop路径 #9035

- docker-images/core/ci/dockerfile/backend.bkci.Dockerfile
- docker-images/core/ci/dockerfile/jdk.Dockerfile
> feat: 新增arm64的JDK #9063

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/UpdateStateContainerCmdFinally.kt
bug:当stage配置了fastkill时取消后第二次重试后构建可能异常 #9053
#9053
> bug:当stage配置了fastkill时取消后第二次重试后构建可能异常 #9053

- src/gateway/core/lua/util/tag_util.lua
> feat: 网关强制路由区分codecc #9081

- src/gateway/core/vhosts/devops.console.proxy.conf
- support-files/templates/gateway#core#devops.server.conf
> 第三方构建机容器化环境支持登录调试 #8915

- src/frontend/devops-atomstore/src/views/workList/atom.vue
> feat: store文本溢出、空状态规范落地 issue #8774

- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/pojo/dto/VerifyResourceRecordDTO.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/migrate/MigrateResourceService.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/migrate/MigrateResultService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/dao/AuthVerifyRecordDao.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/AuthVerifyRecordService.kt
> bug:权限迁移策略对比查询流水线优化 #9130

- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/config/RbacAuthConfiguration.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/RbacPermissionResourceValidateService.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/RbacPermissionService.kt
- src/backend/ci/core/log/biz-log-sample/src/main/kotlin/com/tencent/devops/log/service/impl/RbacLogPermissionService.kt
> bug: 流水线组A的执行者,查看组A下流水线的日志提示无权限 #9122

- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/RbacPermissionApplyService.kt
> 修复 “点击项目流水线组的添加/移出,再点击去申请没有关联选择用户组”问题 #9115

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStartUpService.kt
> bug: 权限迁移子流水线跨项目调用优化 #9086

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityHistoryService.kt
bug: 重试流水线后回写git的MR评论没有更新 #9073
> bug: 重试流水线后回写git的MR评论没有更新 #9073

- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/atom/AtomEnv.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/atom/PipelineAtom.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomEnvServiceImpl.kt
- src/backend/ci/core/worker/worker-api-sdk/src/main/kotlin/com/tencent/devops/worker/common/api/atom/AtomArchiveResourceApi.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/atom/AtomArchiveSDKApi.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
> pref:拉取插件包时制品库网关增加缓存 #9111

- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/common/StoreVersion.kt
pref:模板编辑页针对大模板校验提速 #9118
#9118
> pref:模板编辑页针对大模板校验提速 #9118

- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/LogStatusService.kt
> bug: 修复日志状态同时写入状态出现的死锁问题 #9102

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildDetailService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/detail/BaseBuildDetailService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/BaseBuildRecordService.kt
- src/backend/ci/core/websocket/biz-websocket/src/main/kotlin/com/tencent/devops/websocket/utils/PageUtils.kt
> bug: 人工审核插件刷新变量替换推送问题 #9129 去掉detail内容推送

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/utils/code/svn/SvnUtils.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/code/CodeSvnRepositoryService.kt
> bug: svn保存代码库校验用户名密码接口调用错误 #9132

- helm-charts/core/ci/base/values.yaml
- helm-charts/core/ci/templates/init/init.plugin.yaml
> feat: 部署时默认不再部署插件 #9154

- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/config/MetricsConfig.kt
- support-files/templates/#etc#ci#application-metrics.yml
> pref:调整metrics查询数量限制 #9124

- src/frontend/devops-quality/src/views/create_rules.vue
> feat: 蓝盾国际化优化 #8975

- src/gateway/core/nginx.conf
- src/gateway/core/vhosts/devops.static.conf
> feat: 修复安全漏洞 #9181

- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/migrate/MigrateV0PolicyService.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/test/resources/v0/expected/group_web_policy_custom.json
- src/backend/ci/core/auth/biz-auth-rbac/src/test/resources/v0/group_web_policy_custom.json
> 对接RBAC权限优化 #9149

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/PipelineBuildRecordService.kt
> bugfix：steam流水线折叠页面不显示耗时 #9162

- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/migrate/RbacPermissionMigrateService.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/IndexService.kt
> perf: 日志行号计算逻辑优化 #9191 减少redis锁频率

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/TaskBuildRecordService.kt
> bug: 新详情页矩阵内显示自定义前端异常 #9201

- helm-charts/core/ci/templates/artifactory/statefulset.yaml
- helm-charts/core/ci/templates/auth/deployment.yaml
- helm-charts/core/ci/templates/dispatch/deployment.yaml
- helm-charts/core/ci/templates/dispatchDocker/deployment.yaml
- helm-charts/core/ci/templates/dispatchKubernetes/deployment.yaml
- helm-charts/core/ci/templates/environment/deployment.yaml
- helm-charts/core/ci/templates/image/deployment.yaml
- helm-charts/core/ci/templates/log/deployment.yaml
- helm-charts/core/ci/templates/metrics/deployment.yaml
- helm-charts/core/ci/templates/misc/deployment.yaml
- helm-charts/core/ci/templates/monitoring/deployment.yaml
- helm-charts/core/ci/templates/notify/deployment.yaml
- helm-charts/core/ci/templates/openapi/deployment.yaml
- helm-charts/core/ci/templates/plugin/deployment.yaml
- helm-charts/core/ci/templates/process/deployment.yaml
- helm-charts/core/ci/templates/project/deployment.yaml
- helm-charts/core/ci/templates/quality/deployment.yaml
- helm-charts/core/ci/templates/repository/deployment.yaml
- helm-charts/core/ci/templates/store/deployment.yaml
- helm-charts/core/ci/templates/stream/deployment.yaml
- helm-charts/core/ci/templates/ticket/deployment.yaml
> feat: 调整滚动发布的速度 #9167

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/Constants.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildTaskService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineTaskService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/TaskBuildRecordService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineBuildExtServiceImpl.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineContextService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/MutexControl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/CheckConditionalSkipContainerCmd.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/StartActionTaskContainerCmd.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/CheckConditionalSkipStageCmd.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineRetryFacadeService.kt
> 增加job.retry_task_id标识当前被重试的任务ID #9173

- .github/workflows/sql.yml
- support-files/sql/2003_v2.x/2020_ci_process-update_v2.0_mysql.sql
> bug: 插件暂停时遇到重复的继续执行请求导致Job反复启动 #9113

- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/RbacPermissionResourceGroupService.kt
> bug: 权限默认组名支持国际化 #9254

- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/dispatcher/agent/ThirdPartyAgentDispatcher.kt
- src/backend/ci/core/environment/api-environment/src/main/kotlin/com/tencent/devops/environment/pojo/thirdPartyAgent/ThirdPartyAgent.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/dao/EnvDao.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdPartyAgent/ThirdPartyAgentMgrService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/ContainerBuildRecordService.kt
Reverts TencentBlueKing/bk-ci#9258
> Revert "bug:JOB 勾选显示资源别名也无法使用 #9255"

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/ContainerBuildRecordService.kt
> bug:JOB 勾选显示资源别名也无法使用 #9255

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/engine/common/BuildTimeCostUtils.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/BaseBuildRecordService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/ContainerBuildRecordService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/PipelineBuildRecordService.kt
> bug: 构建详情页耗时数据兜底 #9236

- helm-charts/core/ci/local_chart/kubernetes-management/templates/deployment.yaml
- helm-charts/core/ci/templates/artifactory/statefulset.yaml
- helm-charts/core/ci/templates/auth/deployment.yaml
- helm-charts/core/ci/templates/dispatch/deployment.yaml
- helm-charts/core/ci/templates/dispatchDocker/deployment.yaml
- helm-charts/core/ci/templates/dispatchKubernetes/deployment.yaml
- helm-charts/core/ci/templates/environment/deployment.yaml
- helm-charts/core/ci/templates/image/deployment.yaml
- helm-charts/core/ci/templates/log/deployment.yaml
- helm-charts/core/ci/templates/metrics/deployment.yaml
- helm-charts/core/ci/templates/misc/deployment.yaml
- helm-charts/core/ci/templates/monitoring/deployment.yaml
- helm-charts/core/ci/templates/notify/deployment.yaml
- helm-charts/core/ci/templates/openapi/deployment.yaml
- helm-charts/core/ci/templates/plugin/deployment.yaml
- helm-charts/core/ci/templates/process/deployment.yaml
- helm-charts/core/ci/templates/project/deployment.yaml
- helm-charts/core/ci/templates/quality/deployment.yaml
- helm-charts/core/ci/templates/repository/deployment.yaml
- helm-charts/core/ci/templates/store/deployment.yaml
- helm-charts/core/ci/templates/stream/deployment.yaml
- helm-charts/core/ci/templates/ticket/deployment.yaml
- helm-charts/core/ci/templates/websocket/statefulset.yaml
> feat: 容器化部署等待依赖底层 #9283

- src/backend/ci/core/plugin/biz-plugin/build.gradle.kts
> 缩减plugin微服务的子模块数量 #9231

- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/JerseyConfig.kt
> feat: Jersey扫描从@RestResource改为@Path #9291

- src/frontend/devops-pipeline/src/components/pipelineList/PipelineTableView.vue
> feat: 【rbac】流水线列表执行按钮权限校验问题 #9296

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/constant/ProcessMessageCode.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/label/PipelineGroupDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/label/PipelineLabelDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/label/PipelineGroupService.kt
- support-files/i18n/process/message_en_US.properties
- support-files/i18n/process/message_zh_CN.properties
> pref:优化标签组/标签重名时的报错提示 #9312

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/CredentialUtils.kt
> bug: 插件入参在开启PAC后支持凭据替换 #9310

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/JsonUtil.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/BaseBuildRecordService.kt
bug:构建详情页接口返回数据过滤掉了插件值为空字符串的参数 #9315
#9315
> bug:构建详情页接口返回数据过滤掉了插件值为空字符串的参数 #9315

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/MarketAtomEnvInfoDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/MarketAtomCommonService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomCommonServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomEnvServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/utils/BkInitProjectCacheUtil.kt
pref:插件环境信息查询接口性能优化 #9322
#9322
> pref:插件环境信息查询接口性能优化 #9322

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/ManualReviewUserTask.vue
- src/frontend/devops-pipeline/src/utils/customRules.js
- src/frontend/devops-pipeline/src/utils/validDictionary.js
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
> feat：人工审核插件支持审核提醒 #8998

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
> bug: 模板实例化携带设置时参数不全 #9331

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeSvnScmImpl.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/utils/code/svn/SvnUtils.kt
> bug: 定时触发插件触发异常 #9237

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/config/MeasureConfig.kt
> 缩减process微服务的子模块数量 #9307

- docker-images/core/ci/dockerfile/backend.bkci.Dockerfile
> feat: 修复macos的jdk #9362

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwBuildResourceV4.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwBuildResourceV4Impl.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/ContainerBuildRecordService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchBuildLessDockerStartupTaskAtom.kt
>  bug: 构建触发待审核长时间占用QUEUE_COUNT #8275

- helm-charts/core/ci/templates/init/init.bkrepo.yaml
> feat: 在bkrepo模式下默认启动bkrepo入口 #9377

- src/frontend/common-lib/docs.ts
- src/frontend/devops-manage/src/components/user-group/components/children/permission-manage/group-aside.vue
- src/frontend/devops-nav/src/components/Header/index.vue
- src/frontend/devops-nav/src/components/User/index.vue
> fix: 蓝盾v2.0.0问题修复 #9343

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomArchiveServiceImpl.kt
bug:选择插件历史版本修复升级后再取消版本校验优化 #9380
#9380
> bug:选择插件历史版本修复升级后再取消版本校验优化 #9380

- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/api/migrate/OpAuthMigrateResource.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/config/RbacAuthConfiguration.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/AuthResourceService.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/RbacPermissionResourceGroupService.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/migrate/MigratePermissionHandoverService.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/migrate/MigrateResourceService.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/migrate/MigrateV0PolicyService.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/migrate/MigrateV3PolicyService.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/migrate/RbacPermissionMigrateService.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/test/kotlin/com/tencent/devops/auth/service/migrate/AbMigratePolicyServiceTest.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/test/kotlin/com/tencent/devops/auth/service/migrate/MigrateV0PolicyServiceTest.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/test/kotlin/com/tencent/devops/auth/service/migrate/MigrateV3PolicyServiceTest.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/dao/AuthResourceDao.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/OpAuthMigrateResourceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/PermissionMigrateService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/PermissionResourceGroupService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/sample/SamplePermissionMigrateService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/sample/SamplePermissionResourceGroupService.kt
- src/backend/ci/core/common/common-auth/common-auth-api/src/main/kotlin/com/tencent/devops/common/auth/api/pojo/PermissionHandoverDTO.kt
- src/backend/ci/core/ticket/biz-ticket/src/main/kotlin/com/tencent/devops/ticket/dao/CertDao.kt
- src/backend/ci/core/ticket/biz-ticket/src/main/kotlin/com/tencent/devops/ticket/resources/ServiceTicketAuthResourceImpl.kt
- src/backend/ci/core/ticket/biz-ticket/src/main/kotlin/com/tencent/devops/ticket/service/AuthCertService.kt
- src/backend/ci/core/ticket/biz-ticket/src/main/kotlin/com/tencent/devops/ticket/service/CertService.kt
- src/backend/ci/core/ticket/biz-ticket/src/main/kotlin/com/tencent/devops/ticket/service/CertServiceImpl.kt
> 迁移新版权限中心优化 #9306

- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/migrate/MigratePermissionHandoverService.kt
> bug:修复权限迁移bug #9400

- src/backend/ci/core/artifactory/api-artifactory/src/main/kotlin/com/tencent/devops/artifactory/pojo/ArchiveAtomRequest.kt
- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/store/service/impl/ArchiveAtomServiceImpl.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/atom/ServiceMarketAtomArchiveResource.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/atom/AtomPkgInfoUpdateRequest.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/atom/ServiceMarketAtomArchiveResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/MarketAtomArchiveService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomArchiveServiceImpl.kt
bug:开源版插件包重新上传时也需重新解析国际化信息 #9326
#9326
> bug:开源版插件包重新上传时也需重新解析国际化信息 #9326

- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/cron/AuthCronManager.kt
> bug: 权限分组和描述都是英文的 #9420

- src/frontend/devops-permission/src/views/my-permission/user-group/group-aside.vue
- src/frontend/devops-permission/src/views/my-permission/user-group/index.vue
> feat：权限入口优化 #9390

- src/frontend/devops-pipeline/package.json
- src/frontend/devops-stream/package.json
feature: 日志组件跳转功能兼容 firefox 浏览器 issue #9465
> feature: 日志组件跳转功能兼容 firefox 浏览器 issue #9465

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwPipelineResourceV4.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwPipelineResourceV4Impl.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServicePipelineResource.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineInfoDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServicePipelineResourceImpl.kt
> 新增v4_user_pipeline_paging_search_by_name接口分页查询根据流水线名称搜索 #9466

- src/frontend/devops-manage/src/router/index.ts
- src/frontend/devops-manage/src/views/manage/group/group-entry.vue
> feat: 独立用户管理页面，支持云研发控制台可以嵌入 #9448

- src/backend/ci/buildSrc/src/main/kotlin/plugins/task-license-report.gradle.kts
> feat: weCheckLicense先创建release文件夹 #9474

- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/api/user/UserAuthApplyResource.kt
- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/annotation/BkInterfaceI18n.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/WebAutoConfiguration.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/interceptor/BkWriterInterceptor.kt
- src/backend/ci/core/store/api-store-image/src/main/kotlin/com/tencent/devops/store/api/image/user/UserImageProjectResource.kt
- src/backend/ci/core/store/api-store-image/src/main/kotlin/com/tencent/devops/store/api/image/user/UserImageReleaseResource.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/atom/UserAtomResource.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/atom/UserMarketAtomResource.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/common/UserStoreMemberResource.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/template/UserTemplateResource.kt
- src/backend/ci/core/store/biz-store-image-sample/src/main/kotlin/com/tencent/devops/store/service/image/impl/SampleImageInitService.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/resources/image/user/UserImageProjectResourceImpl.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/resources/image/user/UserImageReleaseResourceImpl.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageProjectService.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageReleaseService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/atom/ServiceMarketAtomResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/atom/UserAtomResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/atom/UserMarketAtomResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/common/UserStoreMemberResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/template/UserTemplateResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/AtomService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/MarketAtomService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/StoreMemberService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/StoreProjectService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/impl/StoreMemberServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/impl/StoreProjectServiceImpl.kt
bug:接口返回对象缓存在内存时做国际化切换可能导致接口返回对象的国际化值不符合预期 #9445
#9445
> bug:接口返回对象缓存在内存时做国际化切换可能导致接口返回对象的国际化值不符合预期 #9445

- src/frontend/devops-pipeline/src/store/modules/atom/actions.js
feature: 修改日志请求地址 & 支持 devx 跳转路径 #9495
> feature: 修改日志请求地址 & 支持 devx 跳转路径 #9495

- src/frontend/devops-pipeline/package.json
- src/frontend/devops-stream/package.json
> 日志组件文件名错误 #9502

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleCheckService.kt
feat: 研发商店插件的质量红线指标支持占位符 #9506
> feat: 研发商店插件的质量红线指标支持占位符 #9506

- src/backend/ci/core/worker/worker-api-sdk/src/main/kotlin/com/tencent/devops/worker/common/api/ticket/CredentialResourceApi.kt
> bug: 共享凭据不需要依赖插件敏感接口权限校验 #9398

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/task/ManualReviewTaskAtom.kt
> feat: 人工审核插件参数支持变量 #9373

- src/backend/ci/core/common/common-archive/src/main/kotlin/com/tencent/devops/common/archive/client/BkRepoClient.kt
- src/backend/ci/core/common/common-archive/src/main/kotlin/com/tencent/devops/common/archive/constant/ArchiveConstants.kt
- src/backend/ci/core/common/common-archive/src/main/kotlin/com/tencent/devops/common/archive/pojo/defender/ApkDefenderRequest.kt
- src/backend/ci/core/common/common-archive/src/main/kotlin/com/tencent/devops/common/archive/pojo/defender/ApkDefenderTasks.kt
- src/backend/ci/core/common/common-archive/src/main/kotlin/com/tencent/devops/common/archive/pojo/defender/ScanTask.kt
- src/backend/ci/core/common/common-redis/src/main/kotlin/com/tencent/devops/common/redis/RedisOperation.kt
> feat: bkrepo客户端新增apk加固接口 #9423

- src/gateway/core/backend.conf
> feat: user类接口传递网关token #9482

- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageProjectService.kt
- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/service/image/ImageService.kt
- src/backend/ci/core/store/biz-store-image/src/test/kotlin/com/tencent/devops/store/service/atom/action/StoreDecorateFactoryTest.kt
- src/backend/ci/core/store/biz-store-sample/src/main/kotlin/com/tencent/devops/store/service/common/action/impl/SampleFirstStoreHostDecorateImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/AtomDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/template/StoreTemplateDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomPropServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/OpAtomServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/action/StoreDecorate.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/action/StoreDecorateFactory.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/action/impl/AbstractStoreDecorateImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/action/impl/AbstractStoreHostDecorateImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/action/impl/FirstStoreDataDecorateImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/action/impl/FirstStorePropsDecorateImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/impl/StoreIndexManageServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/template/impl/MarketTemplateServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/template/impl/OpTemplateServiceImpl.kt
pref:静态资源文件的url地址域名支持适配特定环境 #9504
#9504
> pref:静态资源文件的url地址域名支持适配特定环境 #9504

- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/store/service/impl/ArchiveAtomServiceImpl.kt
bug:增加开源版插件的task.json的packagePath字段的非空校验 #9509
#9509
> bug:增加开源版插件的task.json的packagePath字段的非空校验 #9509

- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/api/migrate/OpAuthMigrateResource.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/migrate/MigratePermissionHandoverService.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/migrate/RbacPermissionMigrateService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/dao/AuthResourceGroupDao.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/OpAuthMigrateResourceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/PermissionMigrateService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/sample/SamplePermissionMigrateService.kt
- src/backend/ci/core/common/common-auth/common-auth-api/src/main/kotlin/com/tencent/devops/common/auth/api/pojo/MigrateProjectConditionDTO.kt
> feat：fit-sec线权限升级支持 #9521

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomEnvServiceImpl.kt
bugfix：查看研发商店的模版时，若插件可见范围符合要求，不应该提示项目xxx不允许使用插件xxx #9531
> bugfix：查看研发商店的模版时，若插件可见范围符合要求，不应该提示项目xxx不允许使用插件xxx #9531

- src/frontend/devops-pipeline/src/components/PipelineHeader/DetailHeader.vue
> bugfix: 流水线执行重复调用权限校验接口 #9554

- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/EventCacheService.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/p4/P4ChangeTriggerHandler.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/p4/P4ShelveTriggerHandler.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/pojo/EventRepositoryCache.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/test/kotlin/com/tencent/devops/common/webhook/service/code/matcher/P4WebHookMatcherTest.kt
> feat：build_msg需要根据事件触发场景细化 #8831

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildSubPipelineResourceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/ProjectDao.kt
> bug: 获取子流水线执行状态接口不需要做权限校验 #9552

- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/service/ServiceProjectOrganizationResource.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/StaffInfo.kt
- src/backend/ci/core/project/biz-project-sample/src/main/kotlin/com/tencent/devops/project/service/SampleProjectOrganizationServiceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/ServiceProjectOrganizationResourceImpl.kt
> feat: 新增获取部门员工信息接口 #9570

- src/frontend/devops-pipeline/src/views/PipelineList/PipelineGroupAside.vue
> feat: 流水线组侧边栏支持调整宽度 #9559

- src/backend/ci/core/common/common-redis/build.gradle.kts
- src/backend/ci/core/common/common-redis/src/main/kotlin/com/tencent/devops/common/redis/RedisLock.kt
- src/backend/ci/core/common/common-redis/src/main/kotlin/com/tencent/devops/common/redis/RedisOperation.kt
- src/backend/ci/core/common/common-test/src/main/kotlin/com/tencent/devops/common/test/BkCiAbstractTest.kt
> feat: redis分布式锁改造 #9499

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/CodeGithubWebHookTrigger.vue
> feat: github触发器事件补充 #9372

- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/ProjectTagService.kt
> [bugfix] 默认prod集群router-tag判断有误 #9615

- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/api/service/ServiceMonitorSpaceResource.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/config/RbacAuthConfiguration.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/migrate/MigrateResourceService.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/migrate/RbacPermissionMigrateService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/ServiceMonitorSpaceResourceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/PermissionMigrateService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/sample/SamplePermissionMigrateService.kt
> 提供监控迁移service接口 #9592

- src/backend/ci/core/log/biz-log-sample/src/main/kotlin/com/tencent/devops/log/service/impl/V3LogPermissionService.kt
> feat: log的redisKey独立化 #9599

- src/backend/ci/core/common/common-redis/src/main/kotlin/com/tencent/devops/common/redis/RedisAutoConfiguration.kt
- src/backend/ci/core/common/common-redis/src/main/kotlin/com/tencent/devops/common/redis/RedisOperation.kt
- src/backend/ci/core/common/common-redis/src/main/kotlin/com/tencent/devops/common/redis/split/RedisSplitProperties.kt
- src/backend/ci/core/process/biz-base/src/test/kotlin/com/tencent/devops/process/engine/service/BuildVariableServiceTest.kt
- src/backend/ci/core/process/biz-base/src/test/kotlin/com/tencent/devops/process/engine/service/rule/PipelineRuleServiceTest.kt
- src/backend/ci/core/process/biz-engine/src/test/kotlin/com/tencent/devops/process/engine/control/MutexControlTest.kt
- src/backend/ci/core/stream/biz-stream/src/test/kotlin/com/tencent/devops/stream/trigger/actions/EventActionFactoryTest.kt
> feat: redis库拆分 #9621

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/PipelineRecentUseDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineRecentUseService.kt
> feat: 最近使用流水线组新增删除逻辑 #9627

- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/ServiceAutoConfiguration.kt
- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/prometheus/UndertowThreadMetrics.kt
> feat: undertow加上线程池监控 #9631

- helm-charts/core/ci/templates/init/init.iam-rbac.yaml
> bug: 删除T_AUTH_IAM_CALLBACK表中experience资源 #9656

- src/frontend/devops-permission/src/views/applyPermission/apply-permission.vue
> feat：申请权限时搜索项目问题优化 #9556

- src/frontend/devops-pipeline/src/components/atomFormField/RemoteCurlUrl/index.vue
> feat：远程触发的 url http 协议，和当前环境支持的http协议对齐 #9540

- src/backend/ci/core/common/common-archive/src/main/kotlin/com/tencent/devops/common/archive/client/DirectBkRepoClient.kt
> feat: iOS重签名部分功能优化 #9537

- src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/common/log/constant/Constants.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/lucene/LuceneClient.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/impl/LogServiceESImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/impl/LogServiceLuceneImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/impl/StreamLogPermissionService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Constants.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/logger/LoggerService.kt
> pref: 构建日志模块增加服务端压缩请求 #9650

- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/common/BusinessConfigRequest.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/common/enums/BusinessEnum.kt
- src/backend/ci/core/store/biz-store-image-sample/src/main/kotlin/com/tencent/devops/store/service/image/impl/SampleImageInitService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/common/BusinessConfigDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/BusinessConfigService.kt
> pref:添加商店配置项优化 #9600

- src/backend/ci/core/common/common-db-sharding/src/main/kotlin/com/tencent/devops/common/db/config/BkShardingMQConfiguration.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/WebAutoConfiguration.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/runner/BkServiceInstanceApplicationRunner.kt
> pref:微服务的主机IP列表队列配置自动删除 #9663

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/InitializeMatrixGroupStageCmd.kt
> feat: dispatch 支持上下文占位，动态赋值 #6460

- src/gateway/core/lua/router_srv.lua
> feat: 将dispatch-docker和dispatch-kubernetes统一为dispatch #9658

- src/frontend/devops-pipeline/src/components/pipelineSetting/NotifySetting.vue
- src/frontend/devops-pipeline/src/components/pipelineSetting/settingBase/index.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
> feat: 流水线运行完毕通知方式增加语音 #9647

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/IScm.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/ScmOauthFactory.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeGitScmImpl.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/git/api/GitApi.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/config/GitConfig.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/OPRepositoryResource.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/OPRepositoryResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/OPRepositoryService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/IScmOauthService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/IScmService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/ScmOauthService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/ScmService.kt
> feat: 工蜂webhook请求支持路由到灰度 #9678

- src/gateway/core/lua/util/loadbalance_util.lua
- support-files/templates/gateway#core#lua#init.lua
> feat: 容器化特殊域名处理 #9681

- src/backend/ci/core/store/biz-store-image/src/main/kotlin/com/tencent/devops/store/dao/image/ImageCommonDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/AtomCommonDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/common/StoreBuildInfoDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/template/TemplateCommonDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/common/impl/StorePipelineServiceImpl.kt
pref:支持刷新研发商店多个组件内置打包流水线 #9677
#9677
> pref:支持刷新研发商店多个组件内置打包流水线 #9677

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserPipelineResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineListFacadeService.kt
> Bug fix #9711 #9712

- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/ResourceService.kt
- src/backend/ci/core/common/common-auth/common-auth-api/src/main/kotlin/com/tencent/devops/common/auth/callback/SearchInstanceInfo.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/ProjectDao.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/AuthProjectService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/ProjectService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
> feat：修复iam回调蓝盾获取项目慢问题 #9708 

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineListFacadeService.kt
> bug：版本体验选择流水线列表搜不到目标流水线问题修复 #9711

- helm-charts/core/ci/base/default_env.yaml
- scripts/bkenv.properties
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/ProjectVO.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/util/ProjectUtils.kt
> bug：项目列表上的操作入口未加权限控制 #9720

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/op/OpPipelineRepoRefResource.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineModelTaskDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/op/OpPipelineRepoRefResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/RepoPipelineRefService.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/UserRepositoryResource.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/dao/RepoPipelineRefDao.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/UserRepositoryResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepoPipelineService.kt
> 【PAC】feat：新增代码库详情页 #8118

- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/resources/ServiceLogPrintResourceImpl.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/impl/LogServiceESImpl.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserBuildResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/pipeline/BuildRecordInfo.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/pipeline/ModelRecord.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/pipeline/TemplateInfo.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/record/BuildRecordModelDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/PipelineBuildRecordService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserBuildResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> feat：构建详情页面增加源模版版本信息与耗时优化 #9700

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/template/TemplateDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/template/service/TemplateService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/template/TemplateInstanceCronService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
> feat: 耗时展示优化 #9505 

- helm-charts/core/ci/templates/gateway/deployment.yaml
- src/gateway/core/nginx.conf
> feat: 优化网关内核参数 #9706

- helm-charts/core/ci/templates/init/init.iam-rbac.yaml
- helm-charts/core/ci/templates/init/init.iam.yaml
> pref: 优化rbac权限二进制部署脚本 #9769

- src/frontend/devops-stream/src/utils/index.js
- src/frontend/devops-stream/src/views/pipeline/build-list.vue
> stream 限制调用历史列表接口频率 #9782

- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwBuildResourceV3Impl.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwPipelineResourceV3Impl.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwBuildResourceV4Impl.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwPipelineResourceV4Impl.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/utils/ApigwParamUtil.kt
> feat: 限制拉取history的数量为100 #9755

- src/gateway/core/lua/util/consul_util.lua
- support-files/templates/gateway#core#lua#init.lua
> feat: 修改apiserver获取nodes的调用方式 #9764

- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/RbacPermissionResourceService.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/op/OPProjectResource.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/open/OpenProjectResource.kt
- src/backend/ci/core/project/biz-project-sample/src/main/kotlin/com/tencent/devops/project/service/SimpleProjectServiceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/ProjectDao.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/OPProjectResourceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/OpenProjectResourceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/ProjectService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
> feat：增加项目服务op操作接口 #9753

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/utils/ModelUtils.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/template/UserTemplateAtomResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/template/UserTemplateAtomResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineAtomStatisticsService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineAtomService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateAtomService.kt
> feat:根据模板ID获取模板下插件属性数据 #9823

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityMetadataService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/dao/atom/AtomDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/resources/atom/BuildAtomResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
> bug:修复支持插件使用分支开发存在的问题 #9815

- src/gateway/core/lua/util/tag_util.lua
> feat: 网关强制路由支持query #9807

- src/frontend/devops-codelib/src/components/CodeLibDetail/index.vue
- src/frontend/devops-codelib/src/components/CodeLibTable/index.vue
- src/frontend/devops-codelib/src/components/empty-table-status.vue
- src/frontend/devops-codelib/src/config/index.js
- src/frontend/devops-codelib/src/views/Index.vue
bug：切换项目访问代码库服务提示代码库不存在问题fix #9761
> bug：切换项目访问代码库服务提示代码库不存在问题fix

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserBuildParametersResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserScmResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/Constants.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/utils/PipelineUtils.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServicePipelineResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserBuildParametersResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/plugin/trigger/element/TimerTriggerElementBizPlugin.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/ParamFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineListFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
> feat: 重构前端保存传入的无用数据 #6074

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/CodeGitWebHookTriggerElement.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/CodeGitlabWebHookTriggerElement.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/CodeTGitWebHookTriggerElement.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/utils/RepositoryConfigUtils.kt
- src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/enums/WebhookI18nConstants.kt
- src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/pojo/code/git/GitReviewEvent.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitReviewTriggerHandler.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/matcher/P4WebHookMatcher.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/dao/PipelineTriggerEventDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/RepoPipelineRefService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/webhook/PipelineBuildWebhookService.kt
- support-files/i18n/process/message_en_US.properties
- support-files/i18n/process/message_zh_CN.properties
- support-files/i18n/repository/message_en_US.properties
- support-files/i18n/repository/message_zh_CN.properties
> bug: 代码库触发事件类型错误 #9784

- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/dao/ProjectBuildSummaryDao.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/ProjectBuildSummaryService.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/impl/MetricsDataReportServiceImpl.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/impl/ProjectBuildSummaryServiceImpl.kt
- support-files/sql/1001_ci_metrics_ddl_mysql.sql
> feat：流水线运营数据统计 #9735

- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/api/migrate/OpAuthMigrateResource.kt
- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/api/service/ServiceResourceMemberResource.kt
- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/pojo/dto/PermissionHandoverDTO.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/config/RbacAuthConfiguration.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/AuthResourceService.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/RbacPermissionProjectService.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/RbacPermissionResourceMemberService.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/migrate/MigratePermissionHandoverService.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/migrate/RbacPermissionMigrateService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/dao/AuthResourceDao.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/OpAuthMigrateResourceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/service/ServiceResourceMemberResourceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/PermissionMigrateService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/PermissionResourceMemberService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/sample/SamplePermissionMigrateService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/sample/SamplePermissionResourceMemberService.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwAuthProjectResourceV4.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwAuthProjectResourceV4Impl.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwProjectResourceV4Impl.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/constant/ProjectMessageCode.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/ProjectCreateUserInfo.kt
> feat：权限相关功能优化 #9878

- src/gateway/core/lua/auth/auth_gray.lua
- src/gateway/core/lua/router_srv.lua
- src/gateway/core/lua/util/tag_util.lua
- src/gateway/core/vhosts/devops.static.conf
- support-files/templates/gateway#core#lua#init.lua
> feat: 区分ci和codecc的默认tag #9895

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/factory/BkDiskLruFileCacheFactory.kt
> pref:为创建文件磁盘缓存对象增加重试机制 #9892

- src/backend/ci/buildSrc/src/main/kotlin/constants/Versions.kt
- src/backend/ci/core/common/common-auth/common-auth-api/src/main/kotlin/com/tencent/devops/common/auth/utils/AuthCacheKeyUtil.kt
- src/backend/ci/core/common/common-auth/common-auth-rbac/src/main/kotlin/com/tencent/devops/common/auth/api/RbacAuthPermissionApi.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/permission/RbacEnvironmentPermissionService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/permission/RbacPipelinePermissionService.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/permission/RbacQualityPermissionServiceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/permission/RbacRepositoryPermissionService.kt
- src/backend/ci/core/ticket/biz-ticket/src/main/kotlin/com/tencent/devops/ticket/service/permission/RbacCertPermissionService.kt
- src/backend/ci/core/ticket/biz-ticket/src/main/kotlin/com/tencent/devops/ticket/service/permission/RbacCredentialPermissionService.kt
> feat: 权限鉴权增加本地缓存 #9903

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/constant/ProcessMessageCode.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/interceptor/InterceptData.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/interceptor/TimerTriggerScmChangeInterceptor.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineBuildService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
- support-files/i18n/process/message_en_US.properties
- support-files/i18n/process/message_zh_CN.properties
> bug: [源码未更新时不触发]功能影响后续流水线重试 #9855

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
bug:当模板中插件*.latest对应的当前版本是测试中状态时，保存模板报错 #9936
> bug:当模板中插件*.latest对应的当前版本是测试中状态时，保存模板报错 #9936

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineContainerService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/InitializeMatrixGroupStageCmd.kt
> bugfix: 开启了新表达式矩阵变量没有替换 #9914

- helm-charts/core/ci/base/default_env.yaml
- scripts/bkenv.properties
- support-files/templates/#etc#ci#application-assembly.yml
- support-files/templates/#etc#ci#application-misc.yml
- support-files/templates/#etc#ci#application-process.yml
> feat: 将清理任务的参数暴露出来 #9955

- src/backend/ci/buildSrc/src/main/kotlin/utils/DatabaseUtil.kt
pref:增加对分区表的表结构进行校验的gradle插件 #9931
> pref:增加对分区表的表结构进行校验的gradle插件 #9931

- src/backend/ci/build.gradle.kts
- src/backend/ci/core/openapi/api-openapi/build.gradle.kts
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildDetailService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/detail/BaseBuildDetailService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/detail/TaskBuildDetailService.kt
> stage-1排队时取消或者超时显示异常 #8361

- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/api/migrate/OpAuthMigrateResource.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/config/RbacAuthConfiguration.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/AuthResourceService.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/RbacPermissionResourceMemberService.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/migrate/MigrateV0PolicyService.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/migrate/RbacPermissionMigrateService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/dao/AuthResourceDao.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/OpAuthMigrateResourceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/PermissionMigrateService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/PermissionResourceMemberService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/sample/SamplePermissionMigrateService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/sample/SamplePermissionResourceMemberService.kt
> bug: rbac权限支持按照项目自动续期 #9992

- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/dao/QualityNotifyGroupDao.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/dao/v2/QualityRuleDao.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/QualityNotifyGroupService.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleService.kt
> bug: 质量红线和质量红线组更新接口需要带项目ID #9989

- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/PermissionGradeManagerService.kt
- src/backend/ci/core/auth/biz-auth-rbac/src/main/kotlin/com/tencent/devops/auth/service/migrate/MigrateV0PolicyService.kt
> feat：用户组添加成员优化 #9909

- docs/overview/db/devops_ci_dispatch.md
- docs/overview/db/devops_ci_project.md
> 数据库文档更新 1.0.1

- src/frontend/devops-nav/src/store/actions.ts
- src/frontend/devops-nav/src/views/ProjectManage.vue
- src/frontend/locale/nav/en-US.json
- src/frontend/locale/nav/zh-CN.json
> feat：项目列表，启用中和已停用项目分开展示 #9781

- src/frontend/devops-codelib/src/components/CodeLibDetail/ResetAuthDialog.vue
- src/frontend/devops-codelib/src/components/CodeLibTable/index.vue
- src/frontend/devops-codelib/src/views/Index.vue
bug: 重置Oauth授权,提示请求的资源不存在 #9960
> bug: 重置Oauth授权,提示请求的资源不存在 #9960 

- src/frontend/devops-codelib/src/components/CodeLibDetail/index.vue
- src/frontend/devops-codelib/src/components/CodeLibTable/index.vue
> feat：流水线插件关联的代码库增加删除和授权方式限制 #9870

- helm-charts/core/ci/templates/init/init.bkrepo.yaml
> feat: 初始化bkrepo可以修改httpSchema #10056

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/IosUtils.kt
> feat: 新增ipa的scheme获取 #10051

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/record/PipelineRecordModelService.kt
bug: 新构建详情页质量红线插件渲染问题修复 #10029
> bug: 新构建详情页质量红线插件渲染问题修复 #10029

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeSvnScmImpl.kt
> feat: svn webhook接口切换 #9302

- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/code/CodeTGitRepositoryService.kt
> bug: 优化工蜂接口异常提示 #9794

- src/frontend/devops-codelib/src/config/index.js
> feat: svn webhook接口切换

- src/frontend/devops-pipeline/src/components/BuildHistoryTable/index.vue
- src/frontend/devops-pipeline/src/mixins/pipelineConstMixin.js
> feat: 流水线构建历史表格，拖拽表格列宽记忆功能 #10065

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/env/AgentEnv.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/SensitiveValueService.kt
> feat：非活跃项目自动停用 #10087

- src/backend/ci/core/common/common-db-sharding/src/main/kotlin/com/tencent/devops/common/db/service/ShardingRoutingRuleManageService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsShardingRoutingRuleServiceImpl.kt
pref:redis存储db分片规则优化 #10081
#10081
> pref:redis存储db分片规则优化 #10081

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/RepoPipelineRefService.kt
> bug: 删除流水线时，代码库关联关系未删除 #10111

- src/backend/ci/core/common/common-event/src/main/kotlin/com/tencent/devops/common/event/dispatcher/pipeline/mq/MQ.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/op/OPProjectResource.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/mq/ProjectEnableStatusBroadCastEvent.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/config/ProjectMQConfiguration.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/listener/ProjectEventListener.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/OPProjectResourceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
> feat: 项目启用停用广播通知 #10080

- scripts/packager-ci.sh
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/SampleAtomReleaseServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/SampleAtomServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/SampleMarketAtomServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/configuration/SampleStoreServiceConfig.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/StoreFileService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/SampleStoreFileServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/SampleStoreI18nMessageServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreCommonServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreI18nMessageServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreLogoServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/image/service/ImageReleaseService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/image/service/ImageService.kt
抽象类设置了@service之类spring托管bean有关的注解与抽象类实现类设置了@ConditionalOnMissingBean注解时影响开源部署
> bug: store服务抽象类注解优化 #10116

- .github/workflows/release.yml
> feat: 公共构建机支持持久化构建容器调度 #9269

- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/dao/slave/SlaveGatewayDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildTaskDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineTaskService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/plugin/trigger/dao/PipelineTimerDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineRetryFacadeService.kt
fix: 流水线设置的变量重试一次就会叠加一次变量值 #6058
bug: 并发Job运行时进行重试和跳过出现异常] #10103
> 重试或跳过相关逻辑优化

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/event/CallBackData.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/CallBackControl.kt
> feat：蓝盾回调时序可能和时间buildNo号顺序不一致，希望回调报文可以返回buildNo #10017

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/NormalAtomV2.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/PreviewAtom.vue
- src/frontend/devops-pipeline/src/components/atomFormField/Accordion/index.vue
> perf: 研发商店插件UI分组逻辑优化 #10086

- src/frontend/devops-environment/src/components/envTabs/nodeTab.vue
- src/frontend/devops-environment/src/store/actions.js
- src/frontend/devops-environment/src/views/create_env.vue
- src/frontend/devops-environment/src/views/node_list.vue
- src/frontend/devops-stream/src/components/setting/agent-pool-card.vue
- src/frontend/devops-stream/src/components/setting/node-select-mixin.js
- src/frontend/devops-stream/src/http/setting.js
- src/frontend/devops-stream/src/views/setting/agent-pools/add-agent.vue
- src/frontend/devops-stream/src/views/setting/agent-pools/agent-list.vue
> pref: 环境管理部分代码优化 #10157

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/record/PipelineRecordModelService.kt
bug：当流水线job中手动跳过的任务前有质量红线任务时会导致构建详情页渲染出错 #10166
> bug：当流水线job中手动跳过的任务前有质量红线任务时会导致构建详情页渲染出错 #10166

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/CallBackControl.kt
> feat：支持回调被封禁通知 #10018 

- src/frontend/devops-codelib/src/components/CodeLibDetail/trigger-event.vue
> bug: 代码库-触发事件流水线名称改成流水线ID搜索 #10114

- src/frontend/devops-stream/src/views/pipeline/build-list.vue
> bug: stream 流水线下，刷新页面加载了全量的列表 #10152

- .github/workflows/publishMavenJar4CI.yml
> bug: 发布到maven仓库会出现多个staging repository #10192

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeSvnScmImpl.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/svn/api/SVNApi.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/svn/api/SVNOauthApi.kt
> feat: 工蜂svn webhook查询接口增加分页参数 #10189

- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionApplyService.kt
> bug: 修复申请权限跳转特殊符号转义问题 #10188

- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/ContainerContent.vue
- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/ContainerEnvNode.vue
- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/index.vue
- src/frontend/devops-pipeline/src/components/Pipeline.vue
- src/frontend/devops-pipeline/src/components/atomFormField/EnumInput/index.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
> feat: 私有构建机支持项目内复用互斥 #10082

- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/cron/ThirdPartyAgentHeartBeatJob.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/NodeService.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdpartyagent/ImportService.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdpartyagent/ThirdPartyAgentMgrService.kt
bug: 环境管理节点列表ws推送导致的列表刷新，用户行为添加的参数未带上 #10205
1 节点列表的count字段，在有搜索条件时 返回带上搜索条件的数据总数
2 去掉除agent启动之外的ws消息推送
> bug: 环境管理节点列表ws推送导致的列表刷新，用户行为添加的参数未带上 #10205

- src/backend/ci/core/environment/api-environment/src/main/kotlin/com/tencent/devops/environment/api/UserNodeResource.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/dao/NodeDao.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/resources/UserNodeResourceImpl.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/NodeService.kt
> feat：环境管理-节点支持按照关键字搜索 #10208

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/AbstractBuildResourceApi.kt
> bug：文件下载异常提示信息优化 #10202

- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/constant/ProjectMessageCode.kt
- src/backend/ci/core/project/biz-project-sample/src/main/kotlin/com/tencent/devops/project/service/SimpleProjectServiceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
feat：创建/编辑项目的 openapi ，增加组织架构必填限制 #10209
> feat：创建/编辑项目的 openapi ，增加组织架构必填限制 #10209

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineInfoFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
> bug: 流水线编辑接口不需要修改权限资源 #10218

- helm-charts/core/ci/templates/artifactory/statefulset.yaml
- helm-charts/core/ci/templates/auth/deployment.yaml
- helm-charts/core/ci/templates/dispatch/deployment.yaml
- helm-charts/core/ci/templates/environment/deployment.yaml
- helm-charts/core/ci/templates/log/deployment.yaml
- helm-charts/core/ci/templates/metrics/deployment.yaml
- helm-charts/core/ci/templates/misc/deployment.yaml
- helm-charts/core/ci/templates/notify/deployment.yaml
- helm-charts/core/ci/templates/openapi/deployment.yaml
- helm-charts/core/ci/templates/process/deployment.yaml
- helm-charts/core/ci/templates/project/deployment.yaml
- helm-charts/core/ci/templates/quality/deployment.yaml
- helm-charts/core/ci/templates/repository/deployment.yaml
- helm-charts/core/ci/templates/store/deployment.yaml
- helm-charts/core/ci/templates/stream/deployment.yaml
- helm-charts/core/ci/templates/ticket/deployment.yaml
> feat: 提高滚动发布的速度 #10236

- src/frontend/devops-permission/src/views/applyPermission/apply-permission.vue
- src/frontend/devops-permission/src/views/applyPermission/group-search.vue
- src/frontend/devops-permission/src/views/applyPermission/group-tab.vue
- src/frontend/devops-permission/src/views/applyPermission/search-select.vue
> feat：申请权限页面优化 #10145

- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/service/BuildLogPrintService.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/pipeline/record/BuildRecordTask.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/record/BuildRecordContainerDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/record/BuildRecordStageDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/record/BuildRecordTaskDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/PipelineBuildRecordService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildStartControl.kt
> bug: 新构建详情页插件渲染问题修复 #9185 时间刷新异常修复

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
> bug: 新构建详情页插件渲染问题修复 #9185 补充回滚改动

- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/TriggerTransfer.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/enums/OperationLogType.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/label/PipelineViewGroupDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServicePipelineResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineSettingResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineInfoFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineVersionFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/view/PipelineViewGroupService.kt
- src/backend/ci/core/process/biz-process/src/test/kotlin/com/tencent/devops/process/service/view/PipelineViewGroupServiceTest.kt
- support-files/i18n/process/message_en_US.properties
- support-files/i18n/process/message_zh_CN.properties
> feat：流水线版本管理机制 #8161 

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/TaskBuildRecordService.kt
> feat：流水线执行历史列表增加「执行耗时」字段 #10251

- src/frontend/devops-atomstore/src/views/workList/status.vue
> feat: pipeline as code issue #8125

- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/dao/LogStatusDao.kt
> [PAC] code互转对api用户的影响 #9813

- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/WebAutoConfiguration.kt
> feat: 压缩http返回json串 #10323

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/exception/ErrorCodeException.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/extend/ModelCheckPlugin.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/atom/ElementCheckResult.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/atom/PipelineCheckFailedReason.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildSubPipelineResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/constant/ProcessMessageCode.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/app/StartBuildContext.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/PipelineVarUtil.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/atom/plugin/IElementBizPluginService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/atom/plugin/MarketBuildAtomElementBizPlugin.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/atom/plugin/MarketBuildLessAtomElementBizPlugin.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/atom/plugin/SubPipelineCallElementBizPlugin.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/extend/DefaultModelCheckPlugin.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/plugin/ElementBizPlugin.kt
- src/backend/ci/core/process/biz-base/src/test/kotlin/com/tencent/devops/process/engine/extend/DefaultModelCheckPluginTest.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildSubPipelineResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/template/ServicePTemplateResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/plugin/trigger/element/TimerTriggerElementBizPlugin.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineElementBizPluginService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStartUpService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/webhook/WebHookTriggerElementBizPlugin.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/github/GithubOAuthService.kt
- support-files/i18n/process/message_en_US.properties
- support-files/i18n/process/message_zh_CN.properties
> feat：保存流水线时校验引用到的子流水线权限 #10259

- src/gateway/core/lua/util/tag_util.lua
> feat: 网关默认tag不写死 #10334

- src/gateway/core/error/error.json.handler.conf
- src/gateway/core/lua/util/cookie_util.lua
> feat: 网关在auth_request时可以处理302的异常跳转 #10295

- src/backend/ci/core/artifactory/api-artifactory/src/main/kotlin/com/tencent/devops/artifactory/api/user/UserBkRepoStaticResource.kt
- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/resources/UserBkRepoStaticResourceImpl.kt
- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/store/service/impl/ArchiveStorePkgServiceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/UserDao.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/common/ServiceStoreResource.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/dao/StoreProjectRelDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/resources/ServiceStoreResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/StoreComponentManageService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/StoreProjectService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreArchiveServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreComponentManageServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreComponentQueryServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreProjectServiceImpl.kt
> pref：研发商店通用化接口封装 #10123

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/websocket/push/DetailWebsocketPush.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/websocket/push/RecordWebsocketPush.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/websocket/push/StatusWebsocketPush.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/StoreWebsocketPush.kt
> bug: [社区]Bean初始化顺序导致插件上架失败[v2.1.0+] #10357

- .github/workflows/frontend.yml
- src/frontend/devops-pipeline/src/components/PipelineHeader/MoreActions.vue
> bug: bug: [社区]上架失败&流水线执行页面白屏问题[v2.1.0+] issue #10357

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwBuildResourceV3.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwBuildResourceV4.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/app/StartBuildContext.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/code/WebhookInfo.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/Constants.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineBuildService.kt
> feat：openapi 触发流水线运行时，支持传入触发材料 #10302

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildTaskService.kt
> bug: 子流水线插件执行超时，但是没有把子流水线停掉 #10331

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserPipelineTriggerEventResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/trigger/PipelineTriggerReasonStatistics.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineTriggerEventResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/dao/PipelineTriggerEventDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/trigger/PipelineTriggerEventAspect.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/trigger/PipelineTriggerEventService.kt
> feat：代码库触发事件结果展示优化 #10307

- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/atom/AtomEnvRequest.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/AtomBusHandleService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/CommonAtomBusHandleHandleServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/GolangAtomBusHandleHandleServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/JavaAtomBusHandleHandleServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/MarketAtomEnvServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/NodeJsAtomBusHandleHandleServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/PythonAtomBusHandleHandleServiceImpl.kt
perf: 研发商店插件运行支持通过task.json中的execution.target字段指定运行参数 #10072
> perf: 研发商店插件运行支持通过task.json中的execution.target字段指定运行参数 #10072

- .github/workflows/frontend.yml
- src/frontend/devops-manage/src/components/project-form.vue
- src/frontend/devops-manage/src/views/manage/project/show-project.vue
- src/frontend/devops-nav/src/index.html
> bug: 社区版simple权限中心前端应该隐藏最大授权范围 #10040 

- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/permission/ProjectPermissionServiceImpl.kt
bug：开源社区，项目管理界面 开源版权限需放开 #10382 release-2.0
> bug：开源社区，项目管理界面 开源版权限需放开 #10382 release-2.0

- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/creator/ModelCommon.kt
- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/creator/ModelContainer.kt
- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/creator/ModelElement.kt
- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/ContainerTransfer.kt
- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/ElementTransfer.kt
- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/utils/ModelCreateUtil.kt
- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v2/models/job/Job.kt
- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v2/utils/StreamDispatchUtils.kt
- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v3/models/job/Job.kt
- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v3/models/job/PreJob.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/Model.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/VMBuildContainer.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/Element.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/ElementAdditionalOptions.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/BuildTask.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/BuildVariables.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/PipelineVersionUtils.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/extend/DefaultModelCheckPlugin.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/task/ManualReviewTaskAtom.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchVMStartupTaskAtom.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/InitializeMatrixGroupStageCmd.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineVersionFacadeService.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Runner.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/ITask.kt
> feat：流水线版本管理机制 #8161 env功能字段迁移

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/ElementAdditionalOptions.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/compatibility/v2/V2BuildParametersCompatibilityTransformer.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/extend/DefaultModelCheckPlugin.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/BuildVariableService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> feat：流水线版本管理机制 #8161 兼容问题修复

- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/TriggerTransfer.kt
> feat：工蜂MR触发器支持设置监听的action TencentBlueKing#8949 兼容PAC YML转换

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineBuildService.kt
> feat：流水线版本管理机制 #8161 修复传参问题

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/event/CallBackData.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/pipeline/ModelDetail.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildDetailService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/CallBackControl.kt
> feat：流水线版本管理机制 #8161 流水线回调增加调试标识

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/Container.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/NormalContainer.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/TriggerContainer.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/VMBuildContainer.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/engine/common/VMUtils.kt
- src/backend/ci/core/process/api-process/src/test/kotlin/com/tencent/devops/process/utils/VMUtilsTest.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
> feat：流水线版本管理机制 #8161 默认补充job id

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserPipelineResource.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineInfoDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineListFacadeService.kt
> feat: 回收站支持流水线名词搜索 #10408

- .github/workflows/frontend.yml
- .github/workflows/release.yml
- src/backend/codecc/core/common/common-client/common-client-base/src/main/kotlin/com/tencent/devops/common/client/Client.kt
- src/backend/codecc/core/common/common-client/common-client-base/src/main/kotlin/com/tencent/devops/common/client/discovery/DiscoveryUtils.kt
- src/backend/codecc/core/common/common-client/common-client-consul/src/main/kotlin/com/tencent/devops/common/client/discovery/ConsulDiscoveryUtils.kt
- src/backend/codecc/core/defect/biz-defect-migration/src/main/kotlin/com/tencent/bk/codecc/defect/service/impl/PipelineScmServiceImpl.kt
- src/backend/codecc/core/defect/biz-defect/src/main/kotlin/com/tencent/bk/codecc/defect/service/PipelineScmService.kt
> bug: 修复release-1.8编译报错 #10445

- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/dao/DispatchJobMetricsDao.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
feat：获取job执行最大并发/项目活跃用户度量数据 #10232
> feat：获取job执行最大并发/项目活跃用户度量数据 #10232

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/open/OpenPipelineTaskResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/open/BuildStatusInfo.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/open/OpenPipelineTaskResourceImpl.kt
> 增加open接口查询任务状态 #8195

- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/utils/CommonUtils.kt
pref:获取db集群名称方法支持db集群列表实现可配置化 #10372
#10372
> pref:获取db集群名称方法支持db集群列表实现可配置化 #10372

- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/op/OPProjectResource.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/ProjectDao.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/OPProjectResourceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/OpProjectService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/ProjectTagService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsOpProjectServiceImpl.kt
> bug: 修复CodeCC平台灰度标签设置不正确 #10434

- src/frontend/devops-codelib/src/components/AtomContent/CodeGitWebHookTrigger.vue
- src/frontend/devops-codelib/src/store/actions.js
- src/frontend/devops-pipeline/src/components/AtomFormComponent/BranchParameterArray/index.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/CodeGitWebHookTrigger.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/CodeGithubWebHookTrigger.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/CodeSvnWebHookTrigger.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/CodeWebHookTrigger.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/TimerTrigger.vue
- src/frontend/devops-pipeline/src/components/atomFormField/Accordion/index.vue
- src/frontend/devops-pipeline/src/components/atomFormField/AtomCheckbox/index.vue
> feat：工蜂MR触发器支持设置监听的action #8949

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/archive/BuildArchiveGetTask.kt
> feat：拉取构件支持流水线调试模式 #10291

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/control/ControlUtils.kt
- src/backend/ci/core/process/biz-base/src/test/kotlin/com/tencent/devops/process/engine/control/ControlUtilsTest.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/CheckConditionalSkipContainerCmd.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/StartActionTaskContainerCmd.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/CheckConditionalSkipStageCmd.kt
> feat: 支持蓝盾新表达式运行条件 #10467

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/ContainerBuildRecordService.kt
> bug: 新详情页显示问题修复 #10395

- src/frontend/devops-pipeline/src/components/PipelineEditTabs/components/children/param-value-option.vue
> feat: pac ui编辑流水线 issue #8125

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/pipeline/PipelineYamlVo.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineInfoFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineVersionFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/yaml/PipelineYamlRepositoryService.kt
> feat：定时触发器支持指定代码库和分支 #10300 修复code方式创建流水线定时触发检测失败

- README.md
- README_EN.md
> 蓝盾DevOps体系下孵化项目迁移事项 #8042

- docs/overview/db/devops_ci_dispatch.md
- docs/overview/db/devops_ci_environment.md
- docs/overview/db/devops_ci_log.md
- docs/overview/db/devops_ci_process.md
- docs/overview/db/devops_ci_store.md
> 数据库文档更新 1.0.2

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/app/AppPipelineBuildResourceImpl.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/service/ServiceUserResource.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/UserDao.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/ServiceUserResourceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/UserCacheService.kt
> feat: 根据组织ID拉取用户列表 #10513

- src/frontend/devops-pipeline/src/components/PipelineEditTabs/ShowVariable.vue
- src/frontend/devops-pipeline/src/components/PipelineEditTabs/components/children/param-group.vue
- src/frontend/devops-pipeline/src/components/PipelineEditTabs/components/pipeline-param.vue
- src/frontend/devops-pipeline/src/components/PipelineHeader/EditHeader.vue
- src/frontend/devops-pipeline/src/components/pipelineSetting/settingBase/index.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
> feat：流水线变量支持手动拖拽调整顺序 issue #10458

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/pipeline/DeployPipelineResult.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineVersionFacadeService.kt
> feat：流水线版本管理机制 #8161 发布时返回yaml信息

- src/frontend/devops-pipeline/src/components/PipelineDetailTabs/VersionSelector.vue
- src/frontend/devops-pipeline/src/components/PipelineHeader/HistoryHeader.vue
- src/frontend/devops-pipeline/src/components/PipelineHeader/ReleasePipelineSideSlider.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
bug: [必须修复]新流水线开启pac后， 不刷新页面， 这条流水线再保存，还是要选 要不要 开启pac issue #8125
> bug: [必须修复]新流水线开启pac后， 不刷新页面， 这条流水线再保存，还是要选 要不要 开启pac issue #8125

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/constant/PipelineBuildParamKey.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/webhook/TriggerBuildParamUtils.kt
- support-files/i18n/process/message_en_US.properties
- support-files/i18n/process/message_zh_CN.properties
> feat：流水线备注支持 上下文方式 设置和引用 #10459

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/StageControl.kt
> bug: 前序取消状态导致finally stage结束异常 #10533

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
> 【PAC】feat：开启PAC模式的代码库支持自动同步代码库YAML变更到蓝盾 #8130 开启PAC 插件input增加旧变量

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineVersionFacadeService.kt
> bug: 新详情页的部分展示问题 #10557

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
> bug: 新详情页的部分展示问题 #10557 修复setting更新依赖yaml互转问题

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildEndControl.kt
> feat：流水线版本管理机制 #8161 修复流水线排队超时,没有发送结束通知

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineVersionFacadeService.kt
> bug: 新详情页的部分展示问题 #10557 修复setting未关联的兼容修复

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServicePipelineResource.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildMonitorControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/notify/PipelineBuildNotifyListener.kt
> fix:流水线删除后，执行中的任务没终止 #8483

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/control/lock/PipelineReleaseLock.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/scm/ScmProxyService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineVersionFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/webhook/PipelineBuildWebhookService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/yaml/PipelineYamlFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/yaml/actions/internal/PipelineYamlManualAction.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/yaml/git/service/PacGitApiService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/yaml/git/service/TGitApiService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsOpProjectServiceImpl.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/scm/ServiceScmOauthResource.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/scm/ServiceScmOauthResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/IScmOauthService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/ScmOauthService.kt
> feat：流水线版本管理机制 #8161 解决发布的并发问题

- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/TriggerTransfer.kt
- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v3/models/on/MrRule.kt
- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v3/models/on/PushRule.kt
- src/backend/ci/core/common/common-pipeline-yaml/src/main/resources/schema/V3_0/ci.json
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/scm/ScmProxyService.kt
> feat：Git事件触发器自定义触发条件支持通过 Code 方式定义 #10497

- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/TriggerTransfer.kt
- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v3/models/on/PreTriggerOnV3.kt
- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v3/models/on/TriggerOn.kt
- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v3/utils/ScriptYmlUtils.kt
- src/backend/ci/core/common/common-pipeline-yaml/src/main/resources/schema/V3_0/ci.json
> feat：P4触发器支持 Code 编写 #10551

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildSubPipelineResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceSubPipelineResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserSubPipelineInfoResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserSubPipelineInfoResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildSubPipelineResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceSubPipelineResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStartUpService.kt
> feat：子流水线调用插件参数传递方式优化 #9943

- src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/pojo/code/svn/SvnCommitEvent.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/svn/SvnCommitTriggerHandler.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/plugin/svn/service/TriggerSvnService.kt
> feat: SVN事件触发的路径匹配规则增加兜底逻辑 #10510

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/app/StartBuildContext.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineContainerService.kt
> bug: 新详情页的部分展示问题 #10557 修复矩阵重试的数据问题

- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/ContainerTransfer.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildSummaryDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineListFacadeService.kt
> feat：流水线列表最近执行展示内容优化 #10600

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildSubPipelineResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildSubPipelineResourceImpl.kt
> feat：支持在父流水线中查看异步执行的子流水线的状态 #10260

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceSubPipelineResource.kt
> feat：支持在父流水线中查看异步执行的子流水线的状态 #10260 修改QueryParam

- src/frontend/devops-pipeline/src/components/atomFormField/EnumInput/index.vue
- src/frontend/devops-pipeline/src/components/atomFormField/Selector/index.vue
- src/frontend/devops-pipeline/src/components/atomFormField/atomFieldMixin.js
> 用户流水线启动变量设置为只读之后，再将流水线另存为模板，这个时候模板再进行实例化，就会出现变量值不能修改的问题 #10626

- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/CacheProjectInfoService.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/impl/ProjectBuildSummaryServiceImpl.kt
> bug: 禁用项目不应该统计用户数 #10634

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/dao/StoreProjectRelDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreProjectServiceImpl.kt
修复更新组件关联初始化项目信息时未删除关联的调试项目信息 #10621
> 修复更新组件关联初始化项目信息时未删除关联的调试项目信息 #10621

- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/common/OpStoreComponentResource.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/common/ServiceStoreComponentResource.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/common/UserStoreComponentQueryResource.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/common/MyStoreComponent.kt
bug:研发商店通用接口国际化配置调整 #10640
#10640
> bug:研发商店通用接口国际化配置调整 #10640

- helm-charts/core/ci/templates/init/init.iam-rbac.yaml
- helm-charts/core/ci/templates/init/init.iam.yaml
> feat: 修复iam初始化脚本 #10658

- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/TransferMapper.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/constant/OpenAPIMessageCode.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/aspect/ApiAspect.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineTransferYamlService.kt
> feat: openapi 访问无权限时新增文案 #10638

- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v3/models/image/PoolType.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildSummaryDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineStageService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> feat：流水线版本管理机制 #8161 调试记录加入执行计数

- src/frontend/devops-pipeline/index.html
- src/frontend/devops-pipeline/src/views/template/edit.vue
- src/frontend/devops-pipeline/src/views/template/instance_create.vue
> 流水线模板管理编辑和实例管理优化 #10626

- src/frontend/devops-pipeline/src/components/ExecDetail/Artifactory.vue
> 归档构件的制品页,显示有误,路径不完整,缺少文件大小 #10667

- src/frontend/devops-pipeline/src/components/pipelineList/PipelineTableView.vue
- src/frontend/devops-pipeline/src/views/PipelineList/PipelineManageList.vue
> bug: 回收站搜索不可用 #8440

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/setting/PipelineSubscriptionType.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/PipelineSettingDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/notify/command/impl/BluekingNotifySendCmd.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/notify/command/impl/NotifySendCmd.kt
- support-files/i18n/notify/template_en_US.yaml
- support-files/i18n/notify/template_zh_CN.yaml
> feat：流水线版本管理机制 #8161 企业微信组通知类型兼容

- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitIssueTriggerHandler.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/external/ExternalScmResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/external/ExternalScmResourceImpl.kt
> bug: 忽略工蜂webhook测试请求 #10666

- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/GitScmService.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/scm/ServiceTGitResource.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/scm/ServiceTGitResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/tgit/ITGitService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/tgit/TGitService.kt
> bug: 合作版工蜂force push触发流水线失败 #10680

- src/backend/ci/core/misc/biz-plugin/src/main/kotlin/com/tencent/devops/plugin/service/git/CodeWebhookService.kt
> feat: github check run应该支持GONGFENGSCAN渠道的流水线 #10704

- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitMrTriggerHandler.kt
> bug: stream 流水线MR触发时分支变量值有误 #10707

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/SampleAtomReleaseServiceImpl.kt
bug:开源版插件升级版本未刷新LATEST_TEST_FLAG标识状态 #10701
> bug:开源版插件升级版本未刷新LATEST_TEST_FLAG标识状态 #10701

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildStageDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineStageService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/StageControl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/CheckPauseReviewStageCmd.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/UpdateStateForStageCmdFinally.kt
bug:有时候取消final stage后，构建未彻底结束 #10619
#10619
> bug:有时候取消final stage后，构建未彻底结束 #10619

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/record/PipelineRecordModelService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/CheckPauseReviewStageCmd.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/AtomPropServiceImpl.kt
bug:无编译环境构建机执行带审核插件的矩阵job，带占位符的审核人未替换成真实审核人 #10599
> bug:无编译环境构建机执行带审核插件的矩阵job，带占位符的审核人未替换成真实审核人 #10599

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineContainerService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/detail/BaseBuildDetailService.kt
> bug:无编译环境构建机执行带审核插件的矩阵job问题 #10599

- src/frontend/devops-atomstore/src/views/workList/image.vue
> 研发商店-工作台-容器镜像,验证失败时的状态icon错位 #10696

- src/frontend/devops-nav/src/store/modules/platform-config.js
- src/frontend/devops-nav/src/views/Home.vue
> feat: 全局配置title/footer/logo/favicon/产品名称 #10678

- src/frontend/devops-codelib/src/components/CodeLibDetail/trigger.vue
- src/frontend/devops-nav/src/views/App.vue
- src/frontend/devops-nav/src/views/Home.vue
- src/frontend/devops-pipeline/src/components/AtomSelector/index.vue
> fix: bk-ci-v3.3.0 测试问题修复 #10678

- support-files/templates/#etc#ci#application-assembly.yml
- support-files/templates/#etc#ci#application-process.yml
> feat: 蓝鲸7.2版本的改动 #10558

- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/creator/ModelCreate.kt
- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/creator/ModelElement.kt
> [stream] 优化触发流程，减少触发时长 #10753

- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/stream/service/CentralizedStramPermissionServiceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/stream/service/GithubStreamPermissionServiceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/stream/service/GitlabStreamPermissionServiceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/stream/service/StreamPermissionProjectServiceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/stream/service/StreamPermissionServiceImpl.kt
> [stream]新增获取组成员 #10711

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/Container.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/NormalContainer.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/TriggerContainer.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/VMBuildContainer.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineContainerService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/CheckConditionalSkipContainerCmd.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/ICommand.kt
> bugfix: 触发时前端手动跳过的矩阵依然运行 #10751

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/Container.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/NormalContainer.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/TriggerContainer.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/VMBuildContainer.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineContainerService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/CheckConditionalSkipContainerCmd.kt
> Revert "bugfix: 触发时前端手动跳过的矩阵依然运行 #10751"

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/utils/MatrixContextUtils.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/enums/VariableType.kt
- src/backend/ci/core/process/biz-process/src/test/kotlin/com/tencent/devops/process/util/MatrixYamlCheckUtilsTest.kt
> bugfix: 修复矩阵code校验时存在的并发问题 #10771

- src/frontend/devops-pipeline/src/utils/pipelineConst.js
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
> feat：构建历史列表支持展示构建信息字段 #10724

- src/gateway/core/lua/cors_filter.lua
> feat: 蓝盾网关信任安全域名的cors-header #10767

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwRepositoryResourceV4.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwRepositoryResourceV4Impl.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/ServiceRepositoryPacResource.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/ServiceRepositoryPacResourceImpl.kt
> feat：【openapi】关联代码库到蓝盾的api支持开启 PAC #10770

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildDao.kt
> bugfix: 构建历史接口的调试记录查询问题 #10814

- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/AuthDeptServiceImpl.kt
- src/backend/ci/core/common/common-auth/common-auth-api/src/main/kotlin/com/tencent/devops/common/auth/api/pojo/EsbBaseReq.kt
- src/backend/ci/core/common/common-auth/common-auth-api/src/main/kotlin/com/tencent/devops/common/auth/service/IamEsbService.kt
- src/backend/ci/core/notify/biz-notify/src/main/kotlin/com/tencent/devops/notify/blueking/sdk/CMSApi.kt
- src/backend/ci/core/notify/biz-notify/src/main/kotlin/com/tencent/devops/notify/blueking/sdk/pojo/ApiReq.kt
> feat: bk-apigw接口认证方式调整 #10802

- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/JerseySwaggerConfig.kt
- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/swagger/BkJaxrsAnnotationScanner.kt
> feat: 修复swagger的扫包方式 #10806

- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/BuildParams.vue
- src/frontend/devops-pipeline/src/components/FileParamInput/index.vue
- src/frontend/devops-pipeline/src/components/FileUpload/index.vue
- src/frontend/devops-pipeline/src/components/PipelineEditTabs/components/children/param-value-option.vue
- src/frontend/devops-pipeline/src/components/pipelineParamsForm.vue
- src/frontend/devops-pipeline/src/views/subpages/preview.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
> bug: 文件类型变量问题修复 #10822

- src/frontend/devops-pipeline/src/components/pipelineSetting/NotifySetting.vue
> feat：流水线通知方式未生效时的交互优化 #10615

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/CodeGitWebHookTrigger.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/CodeGithubWebHookTrigger.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/CodeGitlabWebHookTrigger.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/CodeSvnWebHookTrigger.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/TimerTrigger.vue
- src/frontend/devops-pipeline/src/components/atomFormField/ConditionalInputSelector/index.vue
- src/frontend/devops-pipeline/src/components/atomFormField/RouteTips/index.vue
- src/frontend/devops-pipeline/src/components/atomFormField/VuexTextarea/index.vue
> Issue 10827

- src/frontend/devops-pipeline/src/components/BuildHistoryTable/index.vue
- src/frontend/devops-pipeline/src/store/modules/pipelines/pipelinesGroup.js
- src/frontend/devops-pipeline/src/views/PipelineList/PatchManageList.vue
- src/frontend/devops-pipeline/src/views/PipelineList/PipelineManageList.vue
> pref：流水线执行历史表格优化 #10769

- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionResourceGroupSyncService.kt
> feat：支持管理员查看项目成员 #9620

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineSettingVersionService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineSettingFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateSettingService.kt
> feat：流水线模板设置优化 #10857

- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/atom/UserAtomResource.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/resources/UserAtomResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/AtomPropService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/AtomPropServiceImpl.kt
feat：Code 方式创建的流水线，变量面板-输出变量未获取到问题优化 #10755
> feat：Code 方式创建的流水线，变量面板-输出变量未获取到问题优化 #10755

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
> feat：流水线版本管理机制 #8161 修复模板常量由常量变成变量,流水线常量也应该变成变量

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildEndControl.kt
> bug: 修正取消正在运行中构建可能产生的慢逻辑 #10874

- src/backend/ci/core/quality/api-quality/src/main/kotlin/com/tencent/devops/quality/api/v2/AppQualityRuleResource.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/resources/v2/AppQualityRuleResourceImpl.kt
> feat: quality新增matchRuleList的app接口 #10610

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/Constants.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/PipelineVarUtil.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineBuildService.kt
> feat：支持管理员查看项目成员 #9620 新增变量BK_CI_AUTHORIZER

- src/backend/ci/core/environment/api-environment/src/main/kotlin/com/tencent/devops/environment/constant/EnvironmentMessageCode.kt
- support-files/i18n/environment/message_en_US.properties
- support-files/i18n/environment/message_zh_CN.properties
> perf: 环境管理添加部分错误码 #10788

- docs/overview/db/devops_ci_auth.md
> 数据库文档更新 1.0.4

- helm-charts/core/ci/templates/artifactory/statefulset.yaml
- helm-charts/core/ci/templates/auth/deployment.yaml
- helm-charts/core/ci/templates/dispatch/deployment.yaml
- helm-charts/core/ci/templates/environment/deployment.yaml
- helm-charts/core/ci/templates/log/deployment.yaml
- helm-charts/core/ci/templates/metrics/deployment.yaml
- helm-charts/core/ci/templates/misc/deployment.yaml
- helm-charts/core/ci/templates/notify/deployment.yaml
- helm-charts/core/ci/templates/openapi/deployment.yaml
- helm-charts/core/ci/templates/process/deployment.yaml
- helm-charts/core/ci/templates/project/deployment.yaml
- helm-charts/core/ci/templates/quality/deployment.yaml
- helm-charts/core/ci/templates/repository/deployment.yaml
- helm-charts/core/ci/templates/store/deployment.yaml
- helm-charts/core/ci/templates/stream/deployment.yaml
- helm-charts/core/ci/templates/ticket/deployment.yaml
- helm-charts/core/ci/templates/turbo/deployment.yaml
- helm-charts/core/ci/templates/websocket/statefulset.yaml
> feat: 新启动的POD需要热身 #10887

- src/backend/ci/buildSrc/src/main/kotlin/plugins/task-docker-build.gradle.kts
> feat: 把docker build插件的config ns配置给去掉 #10926

- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/api/user/UserAuthResourceGroupResource.kt
- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/api/user/UserAuthResourceMemberResource.kt
- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/pojo/dto/ProjectMembersQueryConditionDTO.kt
- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/pojo/request/ProjectMembersQueryConditionReq.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/cron/AuthCronSyncGroupAndMember.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/dao/AuthAuthorizationDao.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/dao/AuthResourceGroupDao.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/dao/AuthResourceGroupMemberDao.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionResourceGroupSyncService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionResourceMemberService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/sample/service/SamplePermissionResourceMemberService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/UserAuthResourceGroupResourceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/UserAuthResourceMemberResourceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/PermissionResourceMemberService.kt
- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/DateTimeUtil.kt
feat：项目成员支持按照过期时间/用户组名称搜索 #10892
> feat：项目成员支持按照过期时间/用户组名称搜索 #10892

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/pipeline/PipelineResourceVersion.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/setting/PipelineVersionSimple.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineResourceVersionDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryVersionService.kt
> feat：草稿版本UI展示 #9861 控制版本返回值

- src/frontend/common-lib/docs.ts
- src/frontend/devops-nav/src/components/Header/index.vue
- src/frontend/devops-nav/src/components/User/index.vue
- src/frontend/locale/index.js
- src/frontend/locale/nav/en-US.json
- src/frontend/locale/nav/zh-CN.json
feat: 产品的顶栏下拉框样式和内容统一规范 #10939
> feat: 产品的顶栏下拉框样式和内容统一规范 #10939

- src/frontend/devops-stream/src/components/setting/add-pool.vue
> fix：stream新建环境名称正则错误修复 #10939

- src/frontend/devops-pipeline/src/views/CreatePipeline.vue
- src/frontend/locale/pipeline/zh-CN.json
bug:上架流水线模板到研发商店，但是新建流水线的时候在“研发商店”Tab搜不出来 #10865
> bug:上架流水线模板到研发商店，但是新建流水线的时候在“研发商店”Tab搜不出来 #10865

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineContainerService.kt
> bug: 新构建详情页的失败重试展示问题 #10735

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/MarketAtomEnvServiceImpl.kt
bug:查插件环境信息接口未正确处理插件测试分支版本号情况 #10924
#10924
> bug:查插件环境信息接口未正确处理插件测试分支版本号情况 #10924

- src/backend/ci/core/dispatch/api-dispatch/src/main/kotlin/com/tencent/devops/dispatch/constants/Constants.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/env/AgentEnv.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
pref:公共构建机插件缓存区路径和变量调整优化 #10844
> pref:公共构建机插件缓存区路径和变量调整优化 #10844

- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/permission/ProjectPermissionServiceImpl.kt
> issue: 修复sample鉴权下查project全表的问题 #10941

- src/frontend/bk-permission/src/components/children/permission-manage/group-aside.vue
> fix: bk-permission 项目成员管理 #9620

- src/frontend/devops-manage/src/views/manage/permission/permission-manage.vue
- src/frontend/devops-nav/package.json
- src/frontend/devops-nav/src/components/Header/index.vue
- src/frontend/devops-nav/src/components/SystemLog/index.vue
- src/frontend/devops-nav/src/store/actions.ts
- src/frontend/locale/nav/en-US.json
- src/frontend/locale/nav/zh-CN.json
> feat：支持查看版本日志 #10938

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/record/BuildRecordModelDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/PipelineBuildRecordService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/listener/pipeline/MQPipelineUpdateListener.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> feat：推荐版本号优化 #10958 修改更新逻辑

- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/BuildOauthResource.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/BuildOauthResourceImpl.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/github/GithubOAuthService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/GitOauthService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/IGitOauthService.kt
> feat: 增加获取工蜂和github oauth url的build接口 #10826

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/CodeGitWebHookTriggerElement.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/CodeTGitWebHookTriggerElement.kt
- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/git/api/GitApi.kt
- src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/enums/WebhookI18nConstants.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/filter/ThirdFilter.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitMrTriggerHandler.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitPushTriggerHandler.kt
- support-files/i18n/process/message_en_US.properties
- support-files/i18n/process/message_zh_CN.properties
- support-files/i18n/repository/message_en_US.properties
- support-files/i18n/repository/message_zh_CN.properties
> feat：MR 事件触发器支持 WIP #10683 补充触发器配置详情信息,增加自定义触发控制相关文案

- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/LinuxOsDockerImage.vue
> feat：第三方构建机支持使用 dcoker 运行构建任务 #9820

- src/frontend/devops-pipeline/src/components/PipelineHeader/EditHeader.vue
- src/frontend/devops-pipeline/src/components/PipelineVersionsForm.vue
- src/frontend/devops-pipeline/src/store/modules/pipelines/build.js
- src/frontend/devops-pipeline/src/views/subpages/preview.vue
- src/frontend/devops-pipeline/src/views/template/edit.vue
> feat：当策略为「锁定构建号」时，执行界面可以修改当前值 #11089

- src/frontend/bk-permission/package.json
- src/frontend/bk-permission/src/components/children/permission-manage/group-aside.vue
- src/frontend/devops-manage/src/components/user-group/components/children/permission-manage/group-aside.vue
- src/frontend/devops-manage/src/http/api.ts
- src/frontend/devops-permission/src/components/itsm-group-detail.vue
- src/frontend/devops-permission/src/views/applyPermission/group-detail.vue
> feat：同步并分表存储资源组权限数据 #10964 

- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/OpPermissionFacadeResourceImpl.kt
> feat：同步并分表存储资源组权限数据 #10964

- src/frontend/devops-pipeline/src/components/PipelineEditTabs/NotifyTab.vue
- src/frontend/devops-pipeline/src/components/pipelineSetting/NotifySetting.vue
- src/frontend/devops-pipeline/src/store/modules/pipelines/pipelines.js
> feat：社区版流水线完成通知，支持通知组 #10976

- src/frontend/devops-pipeline/src/store/modules/common/jobOptionConfigMixin.js
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
feat：Job 互斥组排队时，队列长度支持最长到 50 #10975
> feat：Job 互斥组排队时，队列长度支持最长到 50 #10975

- src/frontend/devops-pipeline/src/components/pipelineList/PipelineTableView.vue
> feat：流水线列表，增加标签展示 #11054

- src/frontend/devops-pipeline/src/components/PipelineHeader/DetailHeader.vue
feat：通过子流水线调用触发的执行，支持重试 #11015
> feat：通过子流水线调用触发的执行，支持重试 #11015

- src/frontend/devops-manage/src/views/manage/project/show-project.vue
- src/frontend/devops-pipeline/src/components/PipelineDetailTabs/TriggerEventChildren.vue
> feat：触发事件重放操作权限控制 #11052

- src/backend/ci/core/artifactory/api-artifactory/src/main/kotlin/com/tencent/devops/artifactory/api/ServiceArchiveComponentPkgResource.kt
- src/backend/ci/core/artifactory/api-artifactory/src/main/kotlin/com/tencent/devops/artifactory/api/UserArchiveComponentPkgResource.kt
- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/store/resources/ServiceArchiveComponentPkgResourceImpl.kt
- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/store/resources/UserArchiveComponentPkgResourceImpl.kt
- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/store/service/ArchiveStorePkgService.kt
- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/store/service/impl/ArchiveStorePkgServiceImpl.kt
- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/store/service/impl/ArchiveStorePkgToBkRepoServiceImpl.kt
- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/store/service/impl/ArchiveStorePkgToLocalServiceImpl.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/common/ServiceStoreArchiveResource.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/common/QueryComponentPkgEnvInfoParam.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/resources/ServiceStoreArchiveResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/StoreReleaseSpecBusService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreComponentManageServiceImpl.kt
> bug:研发商店组件包文件上传下载优化 #11115

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServiceBuildResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/app/AppPipelineBuildResourceImpl.kt
> feat：推荐版本号优化 #10958 增加app端兼容

- src/frontend/common-lib/docs.ts
- src/frontend/devops-codelib/src/views/Index.vue
- src/frontend/devops-nav/src/index.ts
- src/frontend/devops-nav/src/views/UnDeploy.vue
- src/frontend/devops-pipeline/src/main.js
- src/frontend/locale/index.js
> feat: 文档跳转路径优化 #10612

- src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/pojo/code/github/GithubPullRequestEvent.kt
> bug: 修复github pull request id越界 #11146

- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
> feat：最大可授权范围更改无效修复 #11153

- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/dao/AuthOauth2ClientDetailsDao.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/dao/AuthResourceGroupApplyDao.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/config/RbacMQConfiguration.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/listener/SyncGroupAndMemberListener.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionResourceGroupSyncService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/sample/service/SamplePermissionResourceGroupSyncService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/PermissionResourceGroupSyncService.kt
> feat：同步用户组逻辑优化 #11122

- src/frontend/devops-pipeline/src/views/list/atomManage.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
> perf:优化插件管理菜单默认插件查询 #11142

- src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/utils/CommonUtils.kt
> bug:根据Profile获取集群名称优化 #11137

- src/frontend/devops-pipeline/src/components/PipelineDetailTabs/TriggerEvent.vue
- src/frontend/devops-pipeline/src/components/template/templateTable.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
> feat：流水线触发历史支持按照触发结果搜索 #11006

- helm-charts/core/ci/local_chart/kubernetes-management/templates/kubernetes-manager-configmap.yaml
- helm-charts/core/ci/templates/configmap/stream-configmap.yaml
> feat: 调整helm的镜像使其支持配置imageRegistry #11171

- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/code/CodeGitRepositoryService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/code/CodeGithubRepositoryService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/code/CodeGitlabRepositoryService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/code/CodeTGitRepositoryService.kt
> bug: 修复代码库开启PAC时,git_project_id字段为空 #11167

- CHANGELOG/en/CHANGELOG-2.0.md
- CHANGELOG/en/CHANGELOG-2.1.md
- CHANGELOG/en/CHANGELOG-3.0.md
- CHANGELOG/genBundledVersionLog.py
- CHANGELOG/zh_CN/CHANGELOG-2.0.md
- CHANGELOG/zh_CN/CHANGELOG-2.1.md
- CHANGELOG/zh_CN/CHANGELOG-3.0.md
- CHANGELOG/zh_CN/CHANGELOG-3.1.md
> perf: 版本日志日期调整为二级标题 #11162

- src/frontend/devops-environment/src/components/envTabs/nodeTab.vue
- src/frontend/devops-environment/src/views/env_detail.vue
> feat：环境支持资源级别的权限管理入口 #11074

- src/frontend/devops-pipeline/src/components/template/extMenu.vue
- src/frontend/devops-pipeline/src/components/template/templateTable.vue
> bug: 模板列表-模板的删除按钮会被遮挡 #11056

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwPipelineVersionResourceV4.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwPipelineVersionResourceV4Impl.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServicePipelineVersionResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServicePipelineVersionResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineInfoFacadeService.kt
> feat：推荐版本号优化 #10958 增加版本管理api接口

- helm-charts/core/ci/base/values.yaml
- support-files/templates/#etc#ci#common.yml
> feat: 修复开源版启动问题 #11202

- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/builds/MetricsUserService.kt
> feat：流水线/Job并发和排队数据落地 #10997

- src/frontend/devops-manage/src/components/project-form.vue
> fix: 独立部署-项目管理隐藏最大授权范围 #10576

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/RemoteAtom.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
> feat: 流水线插件开发自定义UI希望可以获取到container 的 jobid 属性 #11197

- src/frontend/bk-permission/package.json
- src/frontend/bk-permission/src/components/children/permission-manage/group-aside.vue
- src/frontend/devops-manage/src/components/user-group/components/children/permission-manage/group-aside.vue
> bug: 权限管理用户组添加人员模板同步数据 #11217

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/utils/ModelUtils.kt
> bug: finally stage执行时点击跳过，失败的job状态会卡在执行中 #11143

- src/backend/ci/core/artifactory/api-artifactory/src/main/kotlin/com/tencent/devops/artifactory/api/service/ServiceBkRepoResource.kt
- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/api/sync/OpAuthResourceGroupSyncResource.kt
- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/pojo/enum/MemberType.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/cron/AuthCronSyncGroupAndMember.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/dao/AuthResourceGroupMemberDao.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/config/RbacAuthConfiguration.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionResourceGroupService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionResourceGroupSyncService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionResourceMemberService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/sample/service/SamplePermissionResourceGroupSyncService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/op/OpAuthResourceGroupSyncResourceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/PermissionResourceGroupSyncService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/lock/CronSyncGroupMembersExpiredTimeLock.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/lock/GroupAndPermissionsByGroupCodeCreateLock.kt
- src/backend/ci/core/common/common-archive/src/main/kotlin/com/tencent/devops/common/archive/client/BkRepoClient.kt
- src/backend/ci/core/common/common-archive/src/main/kotlin/com/tencent/devops/common/archive/pojo/BKRepoProjectUpdateRequest.kt
- src/backend/ci/core/common/common-archive/src/main/kotlin/com/tencent/devops/common/archive/pojo/ProjectMetadata.kt
- src/backend/ci/core/project/biz-project-sample/src/main/kotlin/com/tencent/devops/project/service/SimpleProjectExtService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/ProjectExtService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectExtServiceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
> feat：获取项目下用户组成员优化 #11221

- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/impl/JavaAtomRunConditionHandleServiceImpl.kt
bug:同一个job下不同语言的java插件生成启动命令时可能会以为系统变量冲突 #11229
> bug:同一个job下不同语言的java插件生成启动命令时可能会因为系统变量冲突 #11229

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/CallBackControl.kt
> [bugfix] okhttp3 Response 不主动关闭会有潜在的内存泄露问题 #11234

- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/filter/ThirdFilter.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitMrTriggerHandler.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitPushTriggerHandler.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/pojo/ThirdFilterBody.kt
> feat: 触发器的自定义触发控制回调增加事件类型 #11196

- src/backend/ci/core/ticket/api-ticket/src/main/kotlin/com/tencent/devops/ticket/pojo/CredentialWithPermission.kt
- src/backend/ci/core/ticket/biz-ticket/src/main/kotlin/com/tencent/devops/ticket/service/CredentialServiceImpl.kt
> feat：我的凭证列表展示创建和更新信息 #11023

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/TemplateInstanceCreateRequest.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/setting/PipelineSetting.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserPipelineGroupResource.kt
- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/template/OptionalTemplate.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/label/PipelineGroupService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineGroupResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineInfoFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineVersionFacadeService.kt
> feat：创建流水线时支持设置标签 #11055

- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/constant/ProjectConstant.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/constant/ProjectMessageCode.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/ProjectDiffVO.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/ProjectProperties.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/ProjectApprovalService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/util/ProjectUtils.kt
- support-files/i18n/project/message_en_US.properties
- support-files/i18n/project/message_zh_CN.properties
> feat：项目设置支持管理员配置项目下流水线的命名规范 #11057

- CHANGELOG/README_en.md
- CHANGELOG/en/CHANGELOG-3.1.md
- CHANGELOG/genBundledVersionLog.py
> bug: 版本日志根据配置控制弹框 #11260

- src/frontend/devops-nav/src/components/SystemLog/index.vue
- src/frontend/devops-nav/src/store/actions.ts
- src/frontend/devops-nav/src/utils/request.ts
> fix: 版本日志切换环境弹框弹出问题修复 #10938

- src/frontend/devops-stream/src/components/setting/agent-detail/basic-information.vue
- src/frontend/devops-stream/src/http/setting.js
- src/frontend/locale/stream/en-US.json
- src/frontend/locale/stream/zh-CN.json
> fix: 构建机的最大并发数设置需要支持设置docker构建的最大并发数 #9820

- src/frontend/bk-permission/package.json
- src/frontend/bk-permission/src/components/children/permission-manage/group-aside.vue
- src/frontend/devops-manage/src/components/user-group/components/children/permission-manage/group-aside.vue
- src/frontend/devops-pipeline/src/views/subpages/ExecDetail.vue
> bug: 权限管理-权限续期数据同步 #11271

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
> bug: 流水线另存为模版,模版名字与流水线名字一样，会报"流水线名称已被使用" #11264

- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
> fix: 执行前暂停的插件弹窗问题处理 #11296

- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/api/service/ServiceMonitorSpaceResource.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/dao/AuthMonitorSpaceDao.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionAuthMonitorSpaceService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/sample/service/SampleAuthMonitorSpaceService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/service/ServiceMonitorSpaceResourceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/AuthMonitorSpaceService.kt
- src/backend/ci/core/common/common-auth/common-auth-api/src/main/kotlin/com/tencent/devops/common/auth/api/pojo/ProjectConditionDTO.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/ProjectByConditionDTO.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/ProjectDao.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
> pref：查询项目接口优化 #11276

- src/backend/ci/build.gradle.kts
> feat: 升级undertow版本解决内存泄漏问题 #11300

- docker-images/core/ci/dockerfile/gateway.Dockerfile
- docker-images/core/ci/dockerfile/openresty.Dockerfile
> feat: 升级openresty到1.19 #11295

- src/backend/ci/buildSrc/src/main/kotlin/constants/Versions.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/cascade/CascadeParam.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/cascade/RepoRefCascadeParam.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/utils/CascadePropertyUtils.kt
> feat：Git分支/Tag和Svn分支/Tag类型的变量优化 #10774

- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitPushTriggerHandler.kt
> bug: GIT触发器单独监听[新增分支]不生效 #11338

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/template/TemplateInstanceUpdate.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineVersionResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineInfoFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
> bug: 模板推荐版本号重置当前值不生效问题 #11350

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/pojo/ErrorType.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/HeartbeatControl.kt
- src/backend/ci/core/worker/worker-agent/src/test/kotlin/com/tencent/devops/worker/common/exception/TaskExecuteExceptionDecoratorTest.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/exception/TaskExecuteExceptionDecorator.kt
bug：插件执行失败时的错误码类型归属错误问题优化 #11294
> bug：插件执行失败时的错误码类型归属错误问题优化 #11294

- src/backend/ci/core/common/common-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/CodeCCAutoConfiguration.kt
- src/backend/ci/core/common/common-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/CodeccApi.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineModelTaskDao.kt
优化流水线项目下已安装插件关联流水线查询
更新插件质量指标数据获取接口
> pref：优化流水线项目下已安装插件关联流水线查询 #11307

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/ProjectCacheService.kt
> bug: 修复流水线事件重放报500错误 #11333 -- 调整projectCache过期时间为5分钟

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServicePipelineViewResource.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServicePipelineViewResourceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
feat：新增service接口用于获取流水线组下流水线 #11383
> feat：新增service接口用于获取流水线组下流水线 #11383

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/AtomPropServiceImpl.kt
bug：多环境情况下流水线编辑页面插件logo缓存优化 #11380
> bug：多环境情况下流水线编辑页面插件logo缓存优化 #11380

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineInfoFacadeService.kt
bug：更新模板实例导致 流水线模型丢失父模板ID问题 #11309
> bug：更新模板实例导致 流水线模型丢失父模板ID问题 #11309

- src/frontend/devops-codelib/package.json
> bug: 修复v3.0版本打helm chart包时报错 #11391

- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/resources/thirdpartyagent/BuildAgentThirdPartyAgentResourceImpl.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdpartyagent/ThirdPartyAgentMgrService.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/utils/ThirdPartyAgentHeartbeatUtils.kt
> feat: 删除老的心跳key #11430

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/pipeline/ProjectBuildId.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStartUpService.kt
> feat：子流水线插件支持输出触发的子流水线 build_num #11373

- .github/workflows/agent.yml
- .github/workflows/backend.yml
- .github/workflows/frontend.yml
- .github/workflows/release.yml
- helm-charts/core/ci/base/values.yaml
- helm-charts/core/ci/local_chart/kubernetes-management/templates/_helpers.tpl
- helm-charts/core/ci/local_chart/kubernetes-management/templates/init/init.sql.yaml
- helm-charts/core/ci/local_chart/kubernetes-management/templates/kubernetes-manager-configmap.yaml
- helm-charts/core/ci/templates/init/init.iam-rbac.yaml
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/ApiAccessTokenService.kt
- support-files/templates/#etc#ci#common.yml
> feat: 需要修复的chart包问题 #11105

- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/ContainerEnvNode.vue
> feat: 构建资源锁定支持使用只读变量 #11425

- src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/p4/api/P4Api.kt
> bug: 修复p4变更文件太多时导致repository服务OOM #11457

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineAtomStatisticsService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/MarketAtomStatisticServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/dao/StoreStatisticTotalDao.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreTotalStatisticServiceImpl.kt
bug:插件关联的流水线数量在流水线并发保存时可能计算出错 #11419
> bug:插件关联的流水线数量在流水线并发保存时可能计算出错 #11419

- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/ModelTransfer.kt
- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/pojo/ModelTransferInput.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineInfoDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineTransferYamlService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineInfoFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineVersionFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/yaml/PipelineYamlRepositoryService.kt
> feat: Code禁用流水线切换到使用新方式 #11420

- src/frontend/devops-stream/src/components/ui-form/mixins.js
> fix: 【Stream】selector组件下拉选项列表通过接口获取，数据为空 #11375

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/time/BuildTimestampType.kt
- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/utils/TPACommonUtil.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwBuildResourceV3.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwBuildResourceV3Impl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/AgentReuseMutexCmd.kt
> feat：第三方构建机Job并发排队耗时归属优化 #10745

- src/backend/ci/core/misc/biz-plugin/src/main/kotlin/com/tencent/devops/plugin/service/ScmCheckService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/SubPipelineTaskService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineCheckService.kt
> bug: MR事件触发回写检查异常 #11456

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineVersionFacadeService.kt
> bug: 通过api保存的新版本可能覆盖旧版本 #11418 发送事件问题

- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/controller/BuildAgentBuildResourceImpl.kt
> feat: environment的redis迁移 #11464

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/enums/PlatformEnum.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/cascade/BuildCascadeProps.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/app/AppPipelineBuildResourceImpl.kt
> feat: APP的manualStartupInfo新增url处理 #11475

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/pipeline/PipelineResourceVersion.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineResourceVersionDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineBuildService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStartUpService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/webhook/PipelineBuildWebhookService.kt
> bug: 流水线版本管理与触发的并发问题 #11490

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> bug: 流水线版本管理与触发的并发问题 #11490 去掉多余的拦截

- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/resources/BuildFileResourceImpl.kt
- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/resources/UserFileResourceImpl.kt
- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/resources/UserReportStorageResourceImpl.kt
- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/service/impl/DiskArchiveFileServiceImpl.kt
- src/backend/ci/core/common/common-archive/src/main/kotlin/com/tencent/devops/common/archive/util/PathUtil.kt
bug：文件通用下载接口的文件路径参数校验加强 #11501
> bug：文件通用下载接口的文件路径参数校验加强 #11501

- src/backend/ci/buildSrc/src/main/kotlin/plugins/task-sharding-db-table-check.gradle.kts
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> pref:流水线构建重试时增加时间限制 #11478

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/ReflectUtil.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/market/MarketBuildAtomElement.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/market/MarketBuildLessAtomElement.kt
- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/dao/process/ProcessDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineAtomReplaceCronService.kt
bug: 当被替换插件参数发生变化时，插件替换工具不一定能兼容 #11486
> bug: 当被替换插件参数发生变化时，插件替换工具不一定能兼容 #11486

- src/gateway/core/lua/util/loadbalance_util.lua
- src/gateway/core/lua/util/tag_util.lua
> feat: 将tag的缓存有效期从5s改为60s #11508

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/StageBuildRecordService.kt
> pref: 新详情页接口的stage审核状态与日志行数计算优化 #11507

- src/frontend/devops-pipeline/src/components/PipelineEditTabs/components/pipeline-param.vue
> feat：流水线变量面板，上下滚动时固定顶部操作区域 #11378

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/op/OpScmWebhookResource.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineWebhookDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/op/OpScmWebhookResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineWebhookService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineWebhookUpgradeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/trigger/WebhookTriggerService.kt
> bug: 修复T_PIPELINE_WEBHOOK表中PROJECT_NAME字段异常的值 #11449

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserPipelineResource.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/PipelineSettingDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineInfoDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineResourceImpl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineListFacadeService.kt
> feat：项目级别的变量语法风格设置增加风险提示和风险确认 #11407

- src/frontend/devops-pipeline/src/components/AtomFormComponent/SubParameter/index.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/atomMixin.js
> bug: 流水线插件参数字段长度限制为1024字符问题修复 #11520

- README_EN.md
- docs/overview/architecture.md
1. 对英文 Readme 文件进行修订与润色。
2. 删除了 overview/architecture.md 中重复的标点符号。
> docs: 对英文 Readme 文件进行修订与润色。TencentBlueKing#11531

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/webhook/PipelineBuildWebhookService.kt
> bug: webhook触发指定流水线版本号异常 #11535

- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/NodeService.kt
> bug: 导入构建机时listNew接口会因构建机过多而报错 #11553

- src/frontend/devops-pipeline/src/components/ExecPipeline.vue
- src/frontend/devops-pipeline/src/store/modules/atom/actions.js
> bug: 模板实例化的流水线审核记录状态不正确 #11527

- src/frontend/package.json
- src/frontend/pnpm-lock.yaml
> feat: pnpm 10 不兼容问题 #11560

- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/user/UserProjectServiceResource.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/service/ServiceVO.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/UserProjectServiceResourceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/ServiceManageService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/UserProjectServiceService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsUserProjectServiceServiceImpl.kt
> pref: 蓝盾服务首页支持定制化跳转 #11510

- src/backend/ci/core/project/biz-project-sample/src/main/kotlin/com/tencent/devops/project/service/SampleUserProjectServiceServiceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsUserProjectServiceServiceImpl.kt
> pref:完善获取服务跳转地址权限校验 #11567

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/SubPipelineTaskService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineElementBizPluginService.kt
> bug: 子流水线循环检查时，解析子流水线参数时，项目ID可能为空字符串 #11528

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/BuildFormProperty.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/BuildParameters.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/compatibility/v2/V2BuildParametersCompatibilityTransformer.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> feat：文件类型变量上传的文件支持版本管理 #11467 增加存储字段

- src/backend/ci/core/common/common-event/src/main/kotlin/com/tencent/devops/common/stream/config/event/ExtendInitEvent.kt
- src/backend/ci/core/common/common-event/src/main/kotlin/com/tencent/devops/common/stream/customizer/BkProducerMessageHandlerCustomizer.kt
> feat: 让mq在程序启动的时候正常初始化 #11584

- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsUserProjectServiceServiceImpl.kt
> feat: 重构代码库服务代码结构 #9952 修复平台服务状态

- src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/log/configuration/LogPrinterConfiguration.kt
> bug: 高峰期引擎打印的服务内的构建日志触发熔断 #11589

- src/backend/ci/core/environment/api-environment/src/main/kotlin/com/tencent/devops/environment/api/thirdpartyagent/ServiceThirdPartyAgentResource.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/resources/thirdpartyagent/ServiceThirdPartyAgentResourceImpl.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/NodeService.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdpartyagent/ThirdPartyAgentMgrService.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/environment/ApigwEnvironmentAgentResourceV4Impl.kt
> feat: node_third_part_detail 接口获取正确的节点数据 #11607

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/Watcher.kt
- src/backend/ci/core/common/common-util/src/main/kotlin/com/tencent/devops/common/util/LoopUtil.kt
- src/backend/ci/core/common/common-util/src/test/kotlin/com/tencent/devops/common/util/LoopUtilTest.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/cron/ThirdPartyAgentHeartBeatJob.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/dao/thirdpartyagent/ThirdPartyAgentDao.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/NodeService.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdpartyagent/AgentUpgradeJob.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdpartyagent/ThirdPartAgentService.kt
轮训升级agent逻辑优化：
1、对单批次最大可升级数量进行硬限制500，防止配置失当导致故障
2、优化原来全量加载在线构建机的逻辑，改为按id增量查询，匹配至单次可升级最大数量即退出循环，减少全量加载构建机记录带来的内存压力
> 优化环境管理构建机Agent的定时维护任务 #11579

- src/frontend/devops-pipeline/package.json
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
- src/frontend/pnpm-lock.yaml
bug: 编辑模板流水线，matchRuleList接口参数丢失问题 #11613
> bug: 编辑模板流水线，matchRuleList接口参数丢失问题 #11613

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/PipelineSettingVersionDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineInfoDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
> bug: 回收站恢复的流水线名字会多一串数字需要优化 #11632

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwProjectResourceV4.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwProjectResourceV4Impl.kt
- src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/service/ServiceProjectResource.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/ProjectDao.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/ServiceProjectResourceImpl.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/ProjectService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
> feat: project_list 接口增加product_id过滤条件 #11610

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/pipeline/SubPipelineStartUpInfo.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStartUpService.kt
> feat：子流水线调用插件入参类型为文本框时，前端应该为textarea组件 #11605

- src/backend/ci/buildSrc/src/main/kotlin/constants/Versions.kt
> feat: 重构代码库服务代码结构 #9952 devops-scm升级到1.0.1

- src/backend/ci/core/worker/worker-api-sdk/src/main/kotlin/com/tencent/devops/worker/common/api/atom/AtomArchiveResourceApi.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/atom/AtomArchiveSDKApi.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
pref:下载处于测试中状态的插件的执行包不从制品库缓存获取 #11615
> pref:下载处于测试中状态的插件的执行包不从制品库缓存获取 #11615

- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/NodeService.kt
> bug: 环境管理搜索CMDB节点返回为空 #11645

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/dao/MarketStoreQueryDao.kt
> bug: 修复商店首页隐藏应用查询 #11648

- src/frontend/devops-pipeline/src/components/AtomFormComponent/SubParameter/index.vue
- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/ContainerContent.vue
- src/frontend/devops-pipeline/src/components/PipelineTemplatePreview.vue
- src/frontend/locale/pipeline/en-US.json
- src/frontend/locale/pipeline/zh-CN.json
> feat：执行时显示具体资源支持通过Code设置 #11588

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/trigger/scm/WebhookGrayCompareService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/yaml/PipelineYamlFileManager.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepositoryService.kt
> feat: 重构代码库服务代码结构 #9952 修复流水线发布指定分支时创建pr异常

- src/backend/ci/buildSrc/src/main/kotlin/constants/Versions.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/trigger/scm/PipelineWebHookEventListener.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/trigger/scm/WebhookGrayCompareService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/trigger/scm/WebhookManager.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/trigger/scm/WebhookTriggerMatcher.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/trigger/scm/converter/GitTagHookConverter.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/trigger/scm/rule/PullRequestHookRule.kt
- support-files/i18n/process/message_en_US.properties
- support-files/i18n/process/message_zh_CN.properties
> feat: 重构代码库服务代码结构 #9952 修复触发问题

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/Element.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/quality/QualityGateInElement.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/quality/QualityGateOutElement.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/detail/TaskBuildDetailService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/TaskBuildRecordService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineContextService.kt
> feat：运行中重试的展示优化 #10483

- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwAtomResourceV4.kt
- src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwAtomResourceV4Impl.kt
- src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/atom/ServiceAtomResource.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/resources/ServiceAtomResourceImpl.kt
> feat：新增部分openapi #11655

- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/GitActionCommon.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/tgit/TGitIssueActionGit.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/tgit/TGitNoteActionGit.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/tgit/TGitReviewActionGit.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/parsers/PipelineDelete.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/parsers/triggerMatch/TriggerBuilder.kt
> feat: 参照push触发增加stream跨库触发分支删除场景触发参数。 #11634

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/PublishersDataServiceImpl.kt
修复发布者信息同步分层根据组织名称获取ID时可能出现同名组织导致ID设置错误
> bua: 修复发布者信息同步分层根据组织名称获取ID时可能出现同名组织导致ID设置错误 #11643

- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionResourceMemberService.kt
- src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwAuthValidateResourceV4.kt
> pref:用户组加人接口优化 #11678

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/JsonUtil.kt
- src/backend/ci/core/common/common-util/src/main/kotlin/com/tencent/devops/common/util/ThreadPoolUtil.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/trigger/scm/WebhookGrayCompareService.kt
> bug: 接口参数中出现is开头的变量序列化异常 #11689

- src/backend/ci/core/common/common-util/src/main/kotlin/com/tencent/devops/common/util/ThreadPoolUtil.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/trigger/scm/WebhookGrayCompareService.kt
> feat: 重构代码库服务代码结构 #9952 修复webhook线程池创建

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineBuildExtServiceImpl.kt
> bug: step简写版上下文失效 #11688

- src/frontend/devops-pipeline/src/components/PipelineEditTabs/components/children/key-options.vue
> bug:修复变量类型为复选框时一键复制不能点击问题 #11705

- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/pojo/request/GroupMemberHandoverConditionReq.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/config/RbacAuthConfiguration.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionManageFacadeServiceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/migrate/MigratePermissionHandoverService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/PermissionAuthorizationServiceImpl.kt
> pref：批量交接接口优化 #11725

- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/pojo/RepoCondition.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/pojo/github/GithubToken.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/dao/RepositoryCodeGitDao.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/dao/RepositoryGithubDao.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepositoryOauthService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepositoryPacService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/code/CodeGithubRepositoryService.kt
> feat: 重构代码库服务代码结构 #9952 修复GITHUB授权问题

- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/pojo/credential/AuthRepository.kt
- src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/pojo/credential/CredentialIdAuthCred.kt
- src/backend/ci/core/repository/biz-base-scm/src/main/kotlin/com/tencent/devops/repository/service/ScmApiManager.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepositoryCheckService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepositoryWebhookService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/hub/AbstractScmApiService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/hub/ScmProviderAuthFactory.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/hub/ScmProviderRepositoryFactory.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/hub/ScmWebhookApiService.kt
> perf: 优化代码源webhook解析流程 #11694

- src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/enums/code/github/GithubCreateRefType.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/github/GithubCreateTriggerHandler.kt
> feat: Github事件触发支持分支过滤 #11682

- src/frontend/devops-pipeline/src/components/AtomFormComponent/SubParameter/index.vue
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/NormalAtomV2.vue
- src/frontend/devops-pipeline/src/components/PipelineEditTabs/components/pipeline-param.vue
- src/frontend/devops-pipeline/src/components/PipelineHeader/DetailHeader.vue
> bug: 子流水线调用插件-删除参数导致参数值变为默认值问题修复 #11709

- src/backend/ci/core/common/common-util/src/main/kotlin/com/tencent/devops/common/util/ThreadPoolUtil.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/trigger/scm/WebhookGrayCompareService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/OpAtomServiceImpl.kt
> bug: ThreadPoolUtil的submitAction方法会不断创建线程池 #11702

- src/frontend/common-lib/docs.js
- src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomOption.vue
- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/JobOption.vue
- src/frontend/devops-pipeline/src/components/StagePropertyPanel/StageControl.vue
- src/frontend/devops-pipeline/src/store/modules/common/jobOptionConfigMixin.js
- src/frontend/devops-pipeline/src/store/modules/common/optionConfigMixin.js
> feat: 增加表达式使用文档指引 #11723

- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/VariableTransfer.kt
- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v3/models/Variable.kt
- src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v3/parsers/template/YamlObjects.kt
- src/backend/ci/core/common/common-pipeline-yaml/src/main/resources/schema/V3_0/ci.json
> feat：变量分组支持 Code 定义 #11698

- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepositoryOauthService.kt
> bug: OAUTH授权界面无需校验平台管理权限 #11748

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/view/PipelineViewService.kt
> bug：复制流水线页面，所属动态流水线组的逻辑有误 #11734

- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsShardingRoutingRuleServiceImpl.kt
> pref:db分片规则保存更新优化 #11732

- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/LinuxOsDockerImage.vue
- src/frontend/devops-pipeline/src/views/template/instance_create.vue
> bug: 流水线模板实例化的时候复选框的默认值没有自动填上 #11761

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/CallBackControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/TimerScheduleMeasureService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/OPRepositoryService.kt
> feat：定时触发器支持设置启动变量 #10617 移除度量Tag

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/StageControl.kt
> bug：被依赖的Job单步重试成功后未执行后续Job 问题 fix #11412

- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/dao/thirdpartyagent/ThirdPartyAgentDao.kt
- src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdpartyagent/ThirdPartyAgentMgrService.kt
- src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/common/log/utils/BuildLogPrinter.kt
> hotfix:获取项目下第三方构建机列表API增加返回主机名称 #11673

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/plugin/trigger/timer/SchedulerManager.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/plugin/trigger/timer/listener/PipelineTimerChangerListener.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/plugin/trigger/timer/quartz/PipelineQuartzService.kt
> bug: 修复当项目ID含有_时，定时任务不触发 #11800

- src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/log/api/OpLogResource.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/cron/DataCleanJob.kt
- src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/resources/OpLogResourceImpl.kt
> perf: 日志模块数据清理未支持跨集群 #11814

- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/store/service/impl/ArchiveStorePkgServiceImpl.kt
- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/dao/process/ProcessDao.kt
- src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/service/process/ProcessDataClearService.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsShardingRoutingRuleServiceImpl.kt
> pref:db分片规则保存优化 #11811

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildRetryService.kt
> bug: 运行中重试时,重试插件的stage状态必须为运行中 #11802

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/plugin/trigger/element/TimerTriggerElementBizPlugin.kt
> bug: 定时触发任务无法正常移除 #11833

- src/frontend/devops-pipeline/src/components/CheckAtomDialog.vue
- src/frontend/devops-pipeline/src/components/ExecPipeline.vue
- src/frontend/devops-pipeline/src/components/StageReviewPanel/index.vue
- src/frontend/devops-pipeline/src/views/subpages/ExecDetail.vue
> feat：stage审核/人工审核通知连接增加定位 #11704

- src/frontend/devops-pipeline/src/components/ArtifactDownloadButton.vue
> bug：流水线制品下载限制10Gb问题修复 #11793

- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionApplyService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionManageFacadeServiceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/migrate/AbMigratePolicyService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/migrate/MigrateResultService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/AuthDeptServiceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/DefaultDeptServiceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/DeptService.kt
> pref：用户管理接口优化 #11816

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/BuildFormProperty.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/compatibility/v2/V2BuildParametersCompatibilityTransformer.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/ParamFacadeService.kt
feat：流水线参数在执行预览界面的展示支持联动 #11438
> feat：流水线参数在执行预览界面的展示支持联动 #11438

- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/api/service/ServiceAuthApplyResource.kt
- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/api/service/ServiceResourceGroupResource.kt
- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/pojo/ApplyJoinGroupSimpleInfo.kt
- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/pojo/AuthGroupConfigAction.kt
- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/pojo/vo/AuthApplyRedirectInfoVo.kt
- src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/pojo/vo/AuthRedirectGroupInfoVo.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/dao/AuthResourceGroupDao.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/config/RbacAuthConfiguration.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacCommonService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionApplyService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionAuthMonitorSpaceService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionResourceGroupService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/sample/service/SamplePermissionResourceGroupService.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/service/ServiceAuthApplyResourceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/service/ServiceResourceGroupResourceImpl.kt
- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/PermissionResourceGroupService.kt
> pref：无权限跳转申请优化 #11769

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/BuildFormProperty.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> feat: 子流水线插件支持传递推荐版本号变量 #11684

- src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/pojo/code/svn/SvnCommitEvent.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/filter/ProjectNameFilter.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/CodeWebhookTriggerHandler.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/svn/SvnCommitTriggerHandler.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/matcher/AbstractScmWebhookMatcher.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/matcher/ScmWebhookMatcher.kt
- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/test/kotlin/com/tencent/devops/common/webhook/service/code/filter/ProjectNameFilterTest.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineWebhookDao.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineWebhookService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/plugin/svn/service/TriggerSvnService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/trigger/WebhookTriggerService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/trigger/scm/WebhookGrayCompareService.kt
> bug: 触发时兼容工蜂SVN仓库名 #11799

- src/frontend/devops-pipeline/src/components/PipelineEditTabs/components/children/env-item.vue
- src/frontend/devops-pipeline/src/components/PipelineEditTabs/components/system-var.vue
> feat：系统内置上下文展示，缺少/job/step级别的变量 #10845

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/OpAtomServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/utils/StoreFileAnalysisUtil.kt
> bug: 插件unzip的时候要去掉根目录 #11825

- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/dao/MarketStoreQueryDao.kt
bug:研发商店还未发布处于测试中的组件查询无需按可见范围过滤 #11863
> bug:研发商店还未发布处于测试中的组件查询无需按可见范围过滤 #11863

- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/yaml/PipelineYamlFileManager.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/yaml/PipelineYamlViewService.kt
> bug: PAC模式下流水线删除后，流水线组还存在需要优化 #11742

- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/ContainerContent.vue
> feat: 希望mac公共构建机Xcode版本选择框可以填写变量来控制 #11855

- src/frontend/devops-pipeline/src/components/AtomFormComponent/SubParameter/index.vue
> feat: 子流水线调用插件在子流水线开启了PAC场景下支持指定分支 #11768

- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/service/ServiceLocaleResource.kt
- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/ServiceLocaleResourceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreCommonServiceImpl.kt
> pref:研发商店组件版本号规范调整 #11780

- src/frontend/devops-pipeline/src/components/PipelineEditTabs/components/children/param-group.vue
> pref：支持变量分组按字母排序 #11590

- src/frontend/devops-pipeline/src/components/PipelineHeader/MoreActions.vue
> bug: 流水线拥有者,无法导出流水线 #11959

- src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/aop/UserApiPermissionAspect.kt
> bug: 用户态接口增加项目访问权限校验 #11971

- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/builds/MetricsEventService.kt
> feat: 新增流水线监控事件 #11874

- .github/workflows/publishMavenJar4CI.yml
- src/backend/ci/buildSrc/src/main/kotlin/plugins/nexusPublishing.gradle.kts
- src/backend/ci/buildSrc/src/main/kotlin/plugins/task-deploy-to-maven.gradle.kts
- src/backend/ci/buildSrc/src/main/kotlin/utils/MavenUtil.kt
> bug: publish-plugin插件不支持Nexus Pro 3 #11944

- src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/OkhttpUtils.kt
- src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/impl/NodeJsAtomRunConditionHandleServiceImpl.kt
> pref：插件运行时包文件下载超时时间优化 #11954

- src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/store/service/impl/ArchiveStorePkgToBkRepoServiceImpl.kt
> pref:获取制品库文件下载链接接口优化 #11999

- src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/ContainerContent.vue
> bug: mac公共构建机无法选择xcode16版本配置 #11980

- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/impl/MetricsDataReportServiceImpl.kt
pref:调整metrics服务数据上报接口分布式锁超时时间 #12005
> pref:调整metrics服务数据上报接口分布式锁超时时间 #12005

- src/frontend/devops-environment/src/views/node/group_aside.vue
- src/frontend/devops-environment/src/views/node/list_table.vue
- src/frontend/devops-manage/src/components/project-form.vue
- src/frontend/devops-permission/src/views/applyPermission/apply-permission.vue
> feat：第三方构建机节点支持标签管理 #11881

- src/frontend/devops-pipeline/src/components/PipelineHeader/MoreActions.vue
- src/frontend/devops-pipeline/src/views/PipelineList/ArchiveDialog.vue
- src/frontend/devops-pipeline/src/views/PipelineList/DeleteArchivedDialog.vue
- src/frontend/devops-pipeline/src/views/subpages/History.vue
> perf：已归档的流水线查看页面，导出和删除操作不可用 #12006

- src/backend/ci/core/common/common-event/src/main/kotlin/com/tencent/devops/common/event/pojo/measure/BuildEndMetricsBroadCastEvent.kt
- src/backend/ci/core/common/common-event/src/main/kotlin/com/tencent/devops/common/event/pojo/measure/IMeasureEvent.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/listener/BuildEndMetricsDataReportListener.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/MetricsDataReportService.kt
- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/impl/MetricsDataReportServiceImpl.kt
pref:metrics构建数据上报接口在构建并发量大时可能出现线程阻塞情况 #12043
> pref:metrics构建数据上报接口在构建并发量大时可能出现线程阻塞情况 #12043

- src/backend/ci/core/misc/biz-plugin/src/main/kotlin/com/tencent/devops/plugin/service/git/CodeWebhookService.kt
> feat: GIT触发区分MR合并前后的检查 #11966

- src/frontend/devops-environment/src/views/node/node_list.vue
> feat：导入第三方构建机时支持自动切换启动用户 #11945

- .github/workflows/publishMavenJar4CI.yml
- src/backend/ci/build.gradle.kts
- src/backend/ci/buildSrc/build.gradle.kts
- src/backend/ci/buildSrc/src/main/kotlin/plugins/task-deploy-to-maven.gradle.kts
- src/backend/ci/buildSrc/src/main/kotlin/utils/MavenUtil.kt
>  feat: Maven仓库发布从oss迁移到central #11817  -- 迁移到release-3.0

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/scm/ScmProxyService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/plugin/trigger/element/TimerTriggerElementBizPlugin.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStartUpService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> feat: 定时触发器支持绑定TGIT代码库 #12073

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/quality/QualityGateInElement.kt
- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/quality/QualityGateOutElement.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildQualityService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/utils/QualityUtils.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/quality/QualityGateInTaskAtom.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/quality/QualityGateOutTaskAtom.kt
- src/backend/ci/core/quality/api-quality/src/main/kotlin/com/tencent/devops/quality/api/v2/pojo/request/BuildCheckParams.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleCheckService.kt
> feat: 质量红线指标仅检查所在控制点 #12137

- src/backend/ci/core/quality/api-quality/src/main/kotlin/com/tencent/devops/quality/api/v2/pojo/request/IndicatorCreate.kt
- src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityIndicatorService.kt
feat: 自定义bash质量红线指标支持prompt提示信息 #12162
> feat: 自定义bash质量红线指标支持prompt提示信息

- src/frontend/devops-environment/src/views/node/index.vue
- src/frontend/devops-environment/src/views/node/list_table.vue
> feat: 自定义bash质量红线指标支持prompt提示信息 #12162

- src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionResourceService.kt
> bug: PAC 流水线修改名称后，权限中心资源未释放 #12078

- src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/builds/MetricsEventService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/TaskAtomService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/listener/run/PipelineTaskPauseListener.kt
> bug: 流水线事件上报处理异常数据 #12210

- src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/GitScmService.kt
- src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/docker/utils/DispatchDockerCommonUtils.kt
- src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/utils/DispatchCommonUtils.kt
- src/backend/ci/core/misc/biz-image/src/main/kotlin/com/tencent/devops/image/utils/CommonUtils.kt
- src/backend/ci/core/misc/biz-plugin/src/main/kotlin/com/tencent/devops/plugin/service/ScmCheckService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/CodeService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/scm/ScmProxyService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/plugin/svn/service/TriggerSvnService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepoCredentialService.kt
- src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepoFileService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/image/service/ImageReleaseService.kt
- src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/util/CommonCredentialUtils.kt
> chore: 升级bcprov-jdk15on到 1.78.1 #11888

- src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/setting/PipelineModelVersion.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineResourceDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineResourceVersionDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/MarketAtomServiceImpl.kt
- src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StorePipelineServiceImpl.kt
pref: 插件代码库被删除时，查询插件详情信息逻辑优化 #12206
> pref: 插件代码库被删除时，查询插件详情信息逻辑优化 #12206

- src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/ManualTriggerElement.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> feat：手动触发支持配置默认的「构建信息」 #12215

- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildDao.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/BaseBuildRecordService.kt
- src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildCancelControl.kt
- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildStartControl.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
- src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildRetryService.kt
> bug: 调试构建生成model时逻辑优化 #12283

- src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/InitializeMatrixGroupStageCmd.kt
> bug: 矩阵兼容record #12279

- src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
> bug: service态获取项目列表接口返回增加是否拥有项目管理员权限 #12289
